### ISSUE TITLE
Rstudio Crashes: devtools::document() or devtools::check()

### ISSUE THREAD

**Issue by paternogbc** [r-lib/devtools#1586]
I have managed to capture the log files from Rstudio regarding the previous issue (#1563)
Also I checked both functions (check and document) on R console outside Rstudio and they work just fine.

Let me know if I can provide any additional information.

**rsession-paterno:**
> 01 Aug 2017 11:57:47 [rsession-paterno] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1238
04 Aug 2017 19:56:25 [rsession-paterno] WARNING Process supervisor did not terminate within 1 second; LOGGED FROM: void {anonymous}::rCleanup(bool) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1098
16 Aug 2017 01:46:21 [rsession-paterno] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1238

**rdesktop.log**
> 03 Aug 2017 10:33:07 [rdesktop] ERROR system error 104 (Connection reset by peer); OCCURRED AT: void rstudio::core::http::AsyncClient<SocketService>::handleReadStatusLine(const rstudio_boost::system::error_code&) [with SocketService = rstudio_boost::asio::basic_stream_socket<rstudio_boost::asio::local::stream_protocol>] /home/ubuntu/rstudio/src/cpp/core/include/core/http/AsyncClient.hpp:363; LOGGED FROM: void rstudio::desktop::NetworkReply::onError(const rstudio::core::Error&) /home/ubuntu/rstudio/src/cpp/desktop/DesktopNetworkReply.cpp:288

**Comment by hadley** [comment]
@kevinushey any ideas?

**Comment by kevinushey** [comment]
@paternogbc can you replicate the crash outside of RStudio (e.g. in RGui.exe or similar)?

**Comment by paternogbc** [comment]
Hi @kevinushey ,

I am running LINUX but there is no crash outside Rstudio. When using R outside Rstudio, `devtools` functions works just fine. I am not sure if that was what you asked. I can also try to install and do some testing in a virtual machine with Windows or other Linux distributions.

Let me know how I can help.

**Comment by jimhester** [comment]
I am not sure of the cause of this, but it would be useful to know if it occurs only with the CRAN version of devtools, or with the development version. Also if does this crash occur when developing any package or only specific packages?

**Comment by micdonato** [comment]
I am having the same problem. 

Whenever I run `devtools::document()` or `devtools::check()` RStudio crashes.

Nothing seems to be saved in the logs.

The only thing I get is the "bomb" message ("R session aborted, fatal error, yadda yadda").

If I run check from the RStudio panel I get the following error, but I can't identify what I am missing.

```
==> devtools::document(roclets=c('rd', 'collate', 'namespace'))


 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 4: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 5: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 6: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 7: loadNamespace(package, ...)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch(loadNamespace(package, ...), error = function(e) e)
12: requireNamespace(dep_name, quietly = TRUE)
13: check_dep_version(package, version)
14: pkgload::check_suggested(package = package, version = version,     compare = compare, path = path)
15: check_suggested("roxygen2")
16: devtools::document(roclets = c("rd", "collate", "namespace"))
17: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
18: suppressPackageStartupMessages({    oldLC <- Sys.getlocale(category = "LC_COLLATE")    Sys.setlocale(category = "LC_COLLATE", locale = "C")    on.exit(Sys.setlocale(category = "LC_COLLATE", locale = oldLC))    devtools::document(roclets = c("rd", "collate", "namespace"))})
An irrecoverable exception occurred. R is aborting now ...

Exited with status 11.
```

`roxygen2` is installed
`devtools` is installed from github

**Comment by jimhester** [comment]
We would need more information to determine the case, particularly what package you are trying to develop.
