### ISSUE TITLE
Revisit type to ensure binaries are installed if they are available.

### ISSUE THREAD

**Issue by jimhester** [r-lib/devtools#1605]
There seem to be some cases (maybe when installing dependencies from Remotes?) where packages are being compiled when there are binaries available.

**Comment by Pawamoy** [comment]
I'm interested in this as well.

It seems that a *lot* of the packages I install with `install_version` are being compiled on my local machine every time, and it takes a long time. But maybe this is normal behavior? If it is, then is there a way to install a specific version using binary, not sources?

**Comment by jimhester** [comment]
No, CRAN does not keep binaries of old versions, only the latest one.

**Comment by Pawamoy** [comment]
OK, thanks :crying_cat_face:
