### ISSUE TITLE
use inst/WORDLIST 

### ISSUE THREAD

**Issue by tbates** [r-lib/devtools#1645]
The spelling is helpful, but not being able to have a private spelling list makes it unhelpful too :-)

`spelling::update_wordlist()` allows the user to create a file of private words from the package, and curate the file in a text editor.

It would be very helpful if devtools used this list... apologies

packageVersion("devtools")
[1] ‘1.13.3’

**Comment by hadley** [comment]
Would you like to do a PR?

**Comment by jimhester** [comment]
It might make sense to provide some infrastructure around the (undocumented) whitelisting for CRANs spell checking as well http://dirk.eddelbuettel.com/blog/2017/08/10/

**Comment by tbates** [comment]
At a first glance, it appears a solution is for devtools to use [spelling](https://github.com/ropensci/spelling) instead of `hunspell`.

Then switch to calling `spell_check_package(".")` to just inherit spelling's smart parsing and also any inst/WORDLIST file contained in the package.

**Comment by hadley** [comment]
It already does?

**Comment by tbates** [comment]
not sure if it does or not.

Using the latest github `devtools::release()` with `check=TRUE`, I'm not now seeing any spell checking done, and introducing typos doesn't give a type list (I have a WORDLIST in the package).

Also, not sure the process is functioning correctly, as after I OK that I have done a win build, I get this error about finding package root:

    Have you checked on win-builder (with `check_win_devel()`)?
    # 1: Yeah
    Error: Could not find package root.

This is with

    packageVersion("devtools")
   [1] ‘1.13.3.9000’

**Comment by jimhester** [comment]
The spell check in release was removed in https://github.com/hadley/devtools/commit/2fc8895ddbfe4dad277d429c1cd8c253885f6806, not sure if that was intentional or not. I am guessing not because the argument is still there...

**Comment by tbates** [comment]
thanks @jimhester! spell_check working nicely with WORDLIST, and great to break out spell_check from release - much quicker iterating to a successful outcome
