### ISSUE TITLE
RStudio add-in to run single test

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1650]
* Should work with files in `R/` or in `tests/testthat`
* Needs to run in separate session and `load_all()` code

**Comment by krlmlr** [comment]
Can that add-in output to the "Build" pane?

**Comment by krlmlr** [comment]
Also, there's brushthat: https://github.com/krlmlr/brushthat. Runs all tests by default, but can be extended to run single tests.

**Comment by krlmlr** [comment]
I think testthis pretty much fits the description of the original issue (minus the separate session), CC @s-fleck.

**Comment by s-fleck** [comment]
@krlmlr I think the ability to run in the build pane does not yet exists. I was looking for that when I started working on testthis, but also couldn't find anything :(
