### ISSUE TITLE
Add option to generate .zenodo.json file from DESCRIPTION

### ISSUE THREAD

**Issue by ha0ye** [r-lib/devtools#1673]
For folks using Zenodo to archive package releases, a ".zenodo.json" file helps to make sure that the citation is correct (rather than what is auto-populated from GitHub).

Seems like this could be straightforward to do, by adding an optional flag to generate the file when using `devtools::document()`.

I believe this might be the [JSON schema](https://zenodo.org/schemas/records/record-v1.0.0.json).

**Comment by jimhester** [comment]
If people are interested in this feature we would review a PR for it, but are not going to develop it ourselves.

**Comment by ha0ye** [comment]
If I find myself with some free time (hah!) over the next few months, I might take a crack at a PR, but it might be slow going given that I don't have any experience in the constructing JSON files.
