### ISSUE TITLE
Put `check()` results in `pkg.Rcheck`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/devtools#1680]
Instead of the temporary directory `rcmdcheck` uses.

**Comment by jennybc** [comment]
Also related: the *RStudio > Build > Check* workflow. Results in that case are extra vulnerable to deletion, because (quoting @hadley)

> RStudio build pane which runs R in a new session, and the default location is a session specific temporary directory which is deleted when that process ends

**Comment by jimhester** [comment]
Ok this should now work as it does with CRAN devtools, sorry for the trouble!
