### ISSUE TITLE
Installing IRKernel on silo'd environment (SCCM)

### ISSUE THREAD

**Issue by Swarje** [r-lib/devtools#1694]
Program Dep Versions:
R 3.3.1
Anaconda 4.0

My network has no Internet access and I'm trying to automate installation on fresh windows 2012 R2 machines. I am copying the following to the node via cmd or powershell
- The unzipped IRKernel-master folder named IRkernel
- A repository containing all of my dependencies
- My r script which follows

```
packageDeps <- c('Rcpp', 'repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest', 'roxygen2','testthat')
install.packages(packageDeps, repos="file:///C:\\temp\\portable_jupyteR")

devtools::install_local("C:\\temp\\IRkernel")
IRkernel::installspec(user = FALSE)
```
and I get "Installation Failed: Cannot open the connection."

If I use load_all instead of install_local It does not error, However, after opening Jupyter notebook and loading the kernel it will die repeatedly. 

I am hoping somebody can tell me I'm totally missing something blatantly obvious. 
and I apologize if this ends up not being a bug.

**Comment by jimhester** [comment]
It is hard to say, but you might try using `devtools::install()`, or alternatively eschewing devtools altogether and installing the package locally with `install.packages("C:\\temp\\IRkernel", repos = NULL)`
