### ISSUE TITLE
Installing from private github repo fails in docker build

### ISSUE THREAD

**Issue by 1beb** [r-lib/devtools#1707]
I'm trying to install from a private repository on github, using the following: 

```
install_github("user/repo", auth_token = readLines("token.txt")) # token.txt exists and is correct
```

And I'm getting this: 

```
Installation failed: length(user) == 1 is not TRUE
```

I'm using a clean version of rocker/hadleyverse to build on so I expect that versions would be fairly recent. Any thoughts?

**Comment by jimhester** [comment]
The results of `traceback()` after the failure would be useful to help debug this

**Comment by 1beb** [comment]
This is run inside of a circleci build using: 

```
Rscript -e 'devtools::install_github(...)'
```
I can certainly try to run it again, although I don't know how to get a traceback when using `Rscript -e` at the console.

**Comment by jimhester** [comment]
You can do so by setting a custom error handler, `options(error = function() traceback(3))`

e.g.

```shell
> Rscript -e 'f <- function() stop("hi"); options(error = function() traceback(3)); f()'
Error in f() : hi
2: stop("hi")
1: f()
```
