### ISSUE TITLE
add devtools check for vignette title (VignetteIndexEntry)?

### ISSUE THREAD

**Issue by jrosen48** [r-lib/devtools#1710]
I sometimes forget to change the vignette title (in the VignetteIndexEntry field - I do change the title field) for my vignettes, so the title defaults to "Vignette Title" (i.e., in [this package on CRAN](https://cran.r-project.org/web/packages/tidyLPA/)). Would it be reasonable to add a devtools check to make sure the title is not this default title?

**Comment by jimhester** [comment]
This is actually [**extremely common**](https://github.com/search?utf8=%E2%9C%93&q=user%3Acran+%22Vignette+Title%22+extension%3ARmd&type=Code) even for published packages on CRAN, yes this seems like a very good idea.

**Comment by jrosen48** [comment]
I'll confess that that package on CRAN (above) is mine! Would you be willing to consider a PR for this? I may take some coaching up on it but would be very interested in trying to dive in.

**Comment by jrosen48** [comment]
(if you think this is an idea worth moving forward)

**Comment by jimhester** [comment]
Yes definitely open a PR!

**Comment by jennybc** [comment]
I already did this once. Did this check go missing?

https://github.com/r-lib/devtools/pull/1043

**Comment by jimhester** [comment]
Oh yes, it is still there, so it should have caught this before you submitted @jrosen48 (assuming you did so with `devtools::release()`).

**Comment by jrosen48** [comment]
Grr, I just missed this (didn't pay enough attention).
