### ISSUE TITLE
Add CRAN-RELEASE to .Rbuildignore

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1711]
In case you have to resubmit

**Comment by jimhester** [comment]
Maybe we should have a check in `release()` for this? Ideally if you are resubmitting you should remove CRAN-RELEASE prior to submission?

I ran into this as well; accidently submitting a package with CRAN-RELEASE in the tarball.

**Comment by hadley** [comment]
Yeah, although for a resubmission, I often don't run the full `release()` cycle
