### ISSUE TITLE
Unknown, possibly mis-spelled, fields in DESCRIPTION:  'Remotes'

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1717]
Hi, 
I am using the development version of `devtools` and running `R CMD check` on my `DESCRIPTION` file (attached below) gives me the following `NOTES`:
```
NOTE
   Maintainer: 'Indrajeet Patil <patilindrajeet.science@gmail.com>'
   
   Unknown, possibly mis-spelled, fields in DESCRIPTION:
     'Remotes'
```
I have added `remotes` to `Suggests`, but I get the same error. How can I get rid of these `NOTES`?

P.S. Here is my `DESCRIPTION` file:
```
Package: ggstatsplot
Version: 0.0.1
Type: Package
Title: ggplot2 Based Plots with Statistical Details
Authors@R: person(given = "Indrajeet", 
  family = "Patil", 
  email = "patilindrajeet.science@gmail.com", 
  role = c("aut", "cre"))
Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
Description: Extension of `ggplot2`, ggstatsplot creates graphics with details from statistical tests 
  included in the plots themselves. It is targeted primarily at behavioral sciences community to provide a 
  one-line code to generate information-rich plots.
License: GPL-2 | file LICENSE
Depends: R (>= 3.1.0)
Encoding: UTF-8
LazyData: true
BugReports: https://github.com/IndrajeetPatil/ggstatsplot/issues
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.0.1.9000
VignetteBuilder: knitr
Imports: 
  car (>= 2.1-6),
  coin (>= 1.2-2),
  datasets,
  devtools (>= 1.13.4),
  dplyr (>= 0.7.4),
  effsize (>= 0.7.1),
  ggExtra,
  ggrepel (>= 0.7.0),
  ggplot2 (>= 2.2.1),
  grid (>= 3.4.1),
  jmv (>= 0.8.0),
  MASS (>= 7.3-47),
  plyr (>= 1.8.4),
  rlang (>= 0.1.6),
  sfsmisc (>= 1.1-1),
  sjstats (>= 0.14.0),
  stats (>= 3.4.1),
  WRS2 (>= 0.9-2)
Remotes: 
  github::daattali/ggExtra
Suggests: 
    datasets,
    grDevices (>= 3.4.1),
    gtable (>= 0.2.0),
    knitr,
    remotes (>= 1.1.1),
    RColorBrewer (>= 1.1-2),
    testthat (>= 2.0.0),
    rmarkdown
```

**Comment by jennybc** [comment]
You can only have the `Remotes` field in DESCRIPTION while you are in a development state.

Exactly how are you running R CMD check? If you run with `--as-cran`, I would expect this error, because you can't submit a package to CRAN with this field.

**Comment by jennybc** [comment]
Also, this has nothing to do with the remotes R package, so you should remove that addition from Suggests, in any case.

**Comment by IndrajeetPatil** [comment]
@jennybc Thanks! Yes, I ran it with `--as-cran`. 
If I can't use `Remotes` field when I submit to CRAN, then how can I add development version of a package in dependencies? 
Should I just add `ggExtra (>= 0.7.1.9000)` to `Imports` and then remove `Remotes` field? 

Cool, I'll remove `remotes` package from `Suggests`.

**Comment by jennybc** [comment]
Nothing on CRAN can depend on a non-CRAN, i.e. development, version of another package.

So, yes, ggExtra should appear in Imports but with a minimum version that is actually available on CRAN.

Yes, you must remove the `Remotes` field from your DESCRIPTION.

**Comment by IndrajeetPatil** [comment]
Gotcha! Perfect, thanks. Will implement this.

**Comment by jimhester** [comment]
Thanks for saying what I would have said for me Jenny :)
