### ISSUE TITLE
check_win_xxx() need manual = FALSE arg

### ISSUE THREAD

**Issue by krlmlr** [r-lib/devtools#1720]
to pass on to `build()` for DBI. Should this be fixed here or elsewhere?

**Comment by jimhester** [comment]
You can use `check_win_devel(args = '--no-manual')`

**Comment by krlmlr** [comment]
I need to omit `--no-manual`, but can't because `pkgbuild::build()` is called with the default setting of `manual = FALSE`. I have a patch ready.

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/devtools/commit/2f7bc84fc8f0a1392d6b9644b65d67a226c5208b
