### ISSUE TITLE
devtools::document fails with shared object not found

### ISSUE THREAD

**Issue by kimyen** [r-lib/devtools#1721]
In my `.onLoad` function, I include:
```
library.dynam.unload(<someLibrary>, file.path(libname, pkgname))
...
library.dynam(<someLibrary>, pkgname, libname, local=FALSE)
```
And in `.onUnload`:
```
library.dynam.unload( <someLibrary>, libpath )
```

`R CMD install`, `Build & Reload` works. However, `devtools::document()` fails with error:
```
Updating <myPkg> documentation
Loading <myPkg>
Error in library.dynam("<someLibrary>", pkgname, libname, local = FALSE) : 
  shared object ‘<someLibrary>.so’ not found
Calls: suppressPackageStartupMessages ... load_all -> run_pkg_hook -> <Anonymous> -> library.dynam
Execution halted

Exited with status 1.
```
The stack trace shows that the error occurs at 
```
library.dynam(...)
```
in my `.onLoad` function.

I would like to figure out why this happens, and if there is anything I can do to fix this. Any help would be greatly appreciated.

**Comment by kimyen** [comment]
This may be helpful. I printed the value of `file.path(libname, pkgname)`. While running `Build & Load`, it prints:
```
"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/PythonEmbedInR"
```
and while running `devtools::document`, it prints:
```
"/Users/kimyentruong/Documents/PythonEmbedInR"
```

**Comment by jimhester** [comment]
I would suggest you call `roxygen2::rogyxenise()` manually, the approach you are using is not one we have resources to support.

**Comment by kimyen** [comment]
@jimhester Thank you for your response. I tried what you suggested and the problem persists. I will open another Jira on `roxygen2` repo. I think creating document (where calling `devtools::document()` or `roxygen2::roxygenise()` requires reading the `.R` file, and not requires loading the entire package. While in my package, loading the package requires loading the dynamic library, this will fail for call to load hook from the source code directory. And calling these functions from the installed directory would not include the source code (`.R` files).
