### ISSUE TITLE
check_win_xxx(): offer an email argument?

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#1723]
I like how the `rhub::check_[on|for]_*()` functions have an email argument. Useful when you're doing checks on a package, but you are not the official maintainer.

Right now I edit DESCRIPTION by hand just before using `check_win_xxx()`, then restore it when I'm done. In theory. But it's easy to forget.

**Comment by jimhester** [comment]
Yes I agree, I was actually the person who recommended this for the `rhub::check_()`functions for the very same reason!

**Comment by jimhester** [comment]
This is actually a bit tricky to do unless we switch devtools to using desc.
