### ISSUE TITLE
install_github doesn't check SHA1 for remote dependencies when using private repo

### ISSUE THREAD

**Issue by carlganz** [r-lib/devtools#1731]
Issue: `install_github` will perform unnecessary reinstallations of dependencies from github when the package is in a private repo

Steps to reproduce:

1. Create package in private github repo
2. Make package depend on remote package on github (which is public)
3. `install_github` the package in the private repo using your auth token
4. repeat step 3, and the remote dependency will be reinstalled despite having the same SHA1 as before

Thanks for the extremely useful package.

**Comment by jimhester** [comment]
I think this was related to the git2r SSL v1 issue, it should be fixed by upgrading to a newer version of git2r.
