### ISSUE TITLE
Difference between install_github and loading function locally

### ISSUE THREAD

**Issue by cbail** [r-lib/devtools#1733]
Hi:
Thanks for the great package, all. I am having a strange issue loading this repo that I created with install_github:

https://github.com/cbail/textnets

One of the functions within this package, called "create_textnet," is throwing an error message when installed and loaded from install_github, but when I cut and paste the function into any R session it runs. Here is the function:

https://github.com/cbail/textnets/blob/master/R/create_textnet.R

The error message is a dplyr-related issue (I had left out a pipe in a previous edit). Strangely, once I added it back in I somehow created this weird "syncing" issue.

Thank you in advance for your help.

**Comment by jimhester** [comment]
This is not a devtools issue. In your NAMESPACE file you are exporting only functions which match `[[:alpha:]]+`, but your function has a `_` in it, which is not matched by that regular expression, so the function is not exported.

https://github.com/cbail/textnets/blob/46705ae19cb44cc2fe58dc88b577e31e5b864666/NAMESPACE#L1

**Comment by cbail** [comment]
Thank you very much- and sorry that I couldn't figure this out on my own!
