### ISSUE TITLE
install_github fails to install certain packages in R 3.4.4

### ISSUE THREAD

**Issue by jefshe** [r-lib/devtools#1734]
I recently upgraded my version of R to 3.4.4 and am now getting errors while trying to install an R package from github. This previously did not occur in 3.4.3:
STR:

1.  Run `devtools::install_github('timelyportfolio/d3vennR')`

This gives the following error:

```
* installing *source* package ‘d3vennR’ ...
Warning in .write_description(db, file.path(outDir, "DESCRIPTION")) :
  Unknown encoding with non-ASCII data: converting to ASCII
Error in iconv(x[ind], "latin1", "ASCII", sub = "byte") :
  object 'ind' not found
ERROR: installing package DESCRIPTION failed for package ‘d3vennR’
* removing ‘/usr/lib/opencpu/library/d3vennR’
```

sessionInfo:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

other attached packages:
[1] devtools_1.11.1
```

**Comment by jefshe** [comment]
Sorry this is a bug in the R source code.

in the .write_description function, `ind` is undefined:
https://github.com/wch/r-source/blame/tags/R-3-4-4/src/library/tools/R/utils.R#L1769

**Comment by lcgodoy** [comment]
Did you solve this problem ? I'm having the same issue

**Comment by jefshe** [comment]
My solution was just to downgrade my version of R. I raised the issue with the R developers and it has now been fixed
