### ISSUE TITLE
`devtools::document` is not calling Rcpp::compileAttributes 

### ISSUE THREAD

**Issue by vspinu** [r-lib/devtools#1739]
Previously  `RcppExports` were updated on `document` (and maybe `install`; not sure). With `devtools  1.13.5.9000` I no longer see this happening. Is this intended?

**Comment by jimhester** [comment]
Could you provide more details, this is working as intended on my machine.

**Comment by vspinu** [comment]
I am seeing it on a repo which is not public yet, but I could make it available. Whatever I do RcppExports is not automatically created, with neither `install`, `load_all`, or `document.

I can reproduce it partially with `lubridate` with which RcppExports are only added if compilation is invoked: 

```sh
tmp$ git clone https://github.com/tidyverse/lubridate.git
tmp$ cd lubridate/
lubridate$ R-devel
> devtools::install(".")
> quit()
lubridate$ rm -rf src/RcppExports.cpp R/RcppExports.R 
lubridate$ R-devel 
> devtools::document(".")
Updating lubridate documentation
Updating collate directive in  /home/vspinu/tmp/lubridate/DESCRIPTION 
Loading lubridate
> quit("no")
lubridate$ ll src/ | grep Exports
-rw-rw-r-- 1 vspinu 1.5M Mar 21 21:42 RcppExports.o
lubridate$ ll R/ | grep Exports
lubridate$ 
```

What kind of hints `document` uses? I should be able to debug this myself if I knew in which package the logic lies. There is not a single mention of `RcppAttributes` in the entire repo.


This is outside R-studio btw, with:

```R
R Under development (unstable) (2018-02-17 r74265) -- "Unsuffered Consequences"
```

It might have something to do with the fact that the repo in question doesn't have `Collate:` derective in the `DESCRIPTION`. 

With lubridate, if I delete all object files, trigger `document`, at the end of the re-compilation I see:

```R
Adding files missing in collate: RcppExports.R
```

**Comment by jimhester** [comment]
The code is in https://github.com/r-lib/pkgbuild/blob/master/R/rcpp-attributes.R, also it does not run when running `document()` it runs when compiling the dll e.g. `pkgbuild::compile_dll()` which is called when running `devtools::load_all()` or during package installation.

`devtools::document()` does call `load_all()`, however if none of your source files are newer than the shared library the code will not be compiled (and no attributes will be compiled).

If you want to explicitly compile them yourself you can do so with `pkgbuild:::compile_rcpp_attributes()` or `Rcpp::compileAttributes()`.

**Comment by vspinu** [comment]
Ok. I have figure this out. It was the [`install_min`](https://github.com/r-lib/pkgbuild/blob/master/R/compile-dll.R#L35) which was running the preclean and deleting my RcppAttributes. I had `rm src/RcppExports.cpp R/RcppExports.R` in my ./cleanup. Well. Now I know :/

I think it would make more sense to first `preclean` and then compileAttributes, no?

> If you want to explicitly compile them yourself you can do so with 

Sure, but in my mind RcppAttributes is more about documentation rather than compilation. Just like `@export` are parsed by `document` and NAMESPACE is updated, I do expect `// [[Rcpp::export]]` to be parsed and relevant files added regardless of whether compilation is triggered or not.

**Comment by jimhester** [comment]
Removing RcppExports in `cleanup` is not a good idea, `cleanup` is run by `R CMD build` when creating a source package, so your source will ship without RcppExports and not actually work if you try to install it with `R CMD INSTALL`.
