### ISSUE TITLE
Multisession loading problems when using future

### ISSUE THREAD

**Issue by gzagatti** [r-lib/devtools#1741]
I am developing a package and I use `load_all` from `devtools` to streamline the development framework and `testthat` for tests. However, this workflow fails when testing functions that create parallel sessions as is the case with `future`. 

When using the `multisession` parallelization planning in the `future` package, `future` will try to load all the packages present in the master session. The problem is that when starting a new session, R will not be able to load the package under development since it has not been installed. What is the best approach for that? Does `devtools` implement something like`pip install -e .`, which is to install a package in editable mode?

I have engaged in a very fruitful discussion [here](https://github.com/HenrikBengtsson/future/issues/206#issuecomment-373249972) which might have to clarify the problem.

**Comment by jimhester** [comment]
You can use `devtools::install()`, perhaps with conjunction with `devtools::dev_mode()` to use a development library.

**Comment by gzagatti** [comment]
Thanks, using `devtools::install_local()` solves the issue. I can install the package every time I’m testing a particular function that expects it to be installed and I can thus develop efficiently. Also I didn’t know about `devtools::dev_mode()`. I have yet to try it out.
