### ISSUE TITLE
GITHUB_PAT messages are a bit noisy

### ISSUE THREAD

**Issue by kevinushey** [r-lib/devtools#1752]
When installing a package from GitHub when `GITHUB_PAT` is set, the message:

```
Using GitHub PAT from envvar GITHUB_PAT
```

gets printed once for each package install from GitHub (for the case where requesting a package install might trigger installation of remotes). Any chance this could be suppressed, or only printed once, or similar?

**Comment by jimhester** [comment]
I think we can probably turn it off by default definitely.
