### ISSUE TITLE
Add reminder to update pkgdown website in release()

### ISSUE THREAD

**Issue by maelle** [r-lib/devtools#1753]
Cf https://github.com/r-lib/pkgdown/issues/624

Thanks ☺

**Comment by hadley** [comment]
Want to do a PR??

**Comment by maelle** [comment]
Could I make a PR for this and #1754 at the same time? 👼

**Comment by jimhester** [comment]
@maelle You can do two separate ones definitely! Put them on two different git branches to keep them straight

**Comment by maelle** [comment]
Cool if both are welcome, will prepare them next week and separately. ☺

**Comment by maelle** [comment]
I'll work on the other PR once I know how this one should look like (adding a reminder for codemeta.json should be quite similar 😀 )

**Comment by jimhester** [comment]
I just realized when reviewing this is we already had a question in release for this

https://github.com/r-lib/devtools/blob/ab568e954252a95f2279281784480afd117e63fa/R/release.r#L115

Although it seems to have a typo...

**Comment by maelle** [comment]
Oh cool! Then I'll close this and my PR 😀
