### ISSUE TITLE
Add reminder to update codemeta.json to release()?

### ISSUE THREAD

**Issue by maelle** [r-lib/devtools#1754]
Maybe out-of-scope feature request. 😺 

Similar to #1753 could there be a reminder in `release()` when there's a codemeta.json in the root of the package folder? 

[Codemeta](https://codemeta.github.io/) provide minimal metadata schemas for science software and code, in JSON-LD. They can be created via [codemetar](https://github.com/ropensci/codemetar)`::write_codemeta()`

**Comment by jimhester** [comment]
My main hesitation with this is the vast majority of packages are _not_ going to have this. But as you mentioned I guess this reminder would only occur if a `codemeta.json` file is in the package; so it is probably fine.

**Comment by maelle** [comment]
Just a few code lines that I promise to maintain when needed 😉

**Comment by jimhester** [comment]
So just realized we have a mechanism for package authors to add custom release check questions by defining `release_questions` function in their package environment. I think this may be the best way to handle this. We could have `codemetar::write_codemeta()` issue a message to add this prompt to the package source the first time it is run on a package. e.g.

```r
message(
  "* Include the following code somewhere in your package\n",
  '  release_questions <- function() "Have you updated codemeta.json with codemetar::write_codemeta()?"')
```
Then this question will be automatically picked up and included in the release questions for the package.

**Comment by maelle** [comment]
Oh nice! Are there some docs so that I might stop bothering you? I'm wondering how to add _several_ questions 👼

**Comment by jimhester** [comment]
No there are no docs, but you can have the function return a character vector of questions to ask.

```r
release_questions <- function() {
  c("Have you xyz",
     "Have you 123")
}
```

**Comment by maelle** [comment]
Fantastic, thanks!
