### ISSUE TITLE
HK admin: Enable option to easily delete registrations

### ISSUE THREAD

**Issue by MichaelM27** [r-lib/devtools#1760]
Webpage concerned: https://www.healthkit.com/a/hk/data/registrations

Current situation: HK admin user can add new registered bodies, but cannot remove the entry once created.

Desired situation: Allow HK admin user to delete/disable registration bodies for situations where an error is made (i.e. added to the wrong country/profession).

**Comment by jimhester** [comment]
I think this issue has been opened in the wrong repository, this is for the devtools R package.
