### ISSUE TITLE
as.package("base") produces Error: Can't find 'base'

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/devtools#1761]
# Issue
In devtools 1.13.5, `?devtools::parse_ns_file` says:

> Argument 'pkg': package description, can be path or package name. See as.package for more information

but when trying to pass a package _name_, you get:
```r
> devtools::parse_ns_file("utils")
Error: Can't find 'utils'.
```

# Troubleshooting

This is because  the above calls `as.package("utils")` which in turn passes the package name as argument `path` to `package_file()`, i.e.
```r
> devtools::package_file(path = "utils")
Error: Can't find 'utils'.
```

OTH, the following doesn't work either, but for a different reason:
```r
> devtools::package_file("utils")
Error: Could not find package root.
```

EDIT 2018-04-10: Sorry, my example was confusing since I used `base`; it's a package without a `NAMESPACE` file.

**Comment by HenrikBengtsson** [comment]
Sorry, my example was confusing since I used base; it's a package without a NAMESPACE file. I've edited my original post to use `utils` instead.

**Comment by jimhester** [comment]
`parse_ns_file` is removed in the devel version of devtools and moved to pkgload, which only supports a path to a package, or within a package.

```
parse_ns_file             package:pkgload              R Documentation

Parses the NAMESPACE file for a package

Description:

     Parses the NAMESPACE file for a package

Usage:

     parse_ns_file(path = ".")

Arguments:

    path: Path to a package, or within a package.
```

**Comment by HenrikBengtsson** [comment]
Ok. thxs
