### ISSUE TITLE
Do something about README.Rmd --> README.md

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#1762]
Currently README.md can grow stale because nothing one does in the normal course of development will cause it to be re-rendered.

We've discussed that it should be probably rendered via `devtools::document()`.

pkgdown is also relevant, but [it was recently decided](https://github.com/r-lib/pkgdown/commit/20872cb2b8d6d58410927df051560458fb06d4f1) that it's confusing for `pkgdown::build_site()` to modify files outside of `docs/`.

Also connected to vignette development workflows, which are up in the air:
https://github.com/r-lib/devtools/issues?utf8=✓&q=is%3Aissue+is%3Aopen+vignette

**Comment by hadley** [comment]
Rebuilding README.md (+ improved vignette workflow) should also involve installing development package to a temporary library.
