### ISSUE TITLE
R CMD check shows incoming CRAN feasibility

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1767]
```R

❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: ‘Hadley Wickham <hadley@rstudio.com>’
  
  Version contains large components (0.4.1.9000)

```

Isn't this supposed to be disabled?

**Comment by jimhester** [comment]
The remote checks are disabled, but in newer R versions the other checks still happen. See https://github.com/r-lib/devtools/blob/13ee56b9bb43dd2cb2e3b364bcba2c49ef350fac/R/check.r#L207-L214 and #1271
