### ISSUE TITLE
Illegal characters found in URL in curl call within dev_package_deps()

### ISSUE THREAD

**Issue by ms609** [r-lib/devtools#1769]
Running 
 >    devtools::dev_package_deps(dependencies = NA)

generates the error
 >    Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
 >  Illegal characters found in URL

I noticed this occurring in Travis CI builds, e.g. [here](https://travis-ci.org/ms609/hyoliths/builds/367214602), and replicated it on my local Windows 10 PC using R 3.4.4 and devtools 1.13.5.

**Comment by jimhester** [comment]
You seem to be missing a comma in between your `Remotes: ` fields.

https://github.com/ms609/hyoliths/blob/05e0e37827e974fe61f9220a4201e34707ec1a6e/DESCRIPTION#L18-L19

**Comment by ms609** [comment]
Thank you for spotting this.  A lot of frustration for the sake of a comma!

**Comment by Serenthia** [comment]
Should this perhaps be caught in the R CMD check (ie. a check for \n characters in Remotes)?  I ask as I've just been caught out by the same!

**Comment by jimhester** [comment]
@Serenthia this results in a more informative error in the devel version of devtools, but it is not yet release to CRAN.
