### ISSUE TITLE
Current devtools fails if run against git2r prior to 0.21.0.9002

### ISSUE THREAD

**Issue by gwarnes-mdsol** [r-lib/devtools#1771]
since it uses `git2r::repository_head` instead of `git2r::head`.

Perhaps it would be a good idea to bump version number to the [appropriate line](https://github.com/r-lib/devtools/blob/970dc3920804ae2f02154e24d9be765d4a2a1895/DESCRIPTION#L28
) in DESCRIPTION to alert the user at install-time, from
```
    git2r (>= 0.11.0),
```
to
```
    git2r (>= 0.21.0.9002),
```

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/devtools/commit/61c0c41a7875385b4d4732a921be21c345c5e080
