### ISSUE TITLE
encoding warning confusion with test()

### ISSUE THREAD

**Issue by plantarum** [r-lib/devtools#1776]
I'm not using `encoding` directives anywhere in my package, either in DESCRIPTION, .Rd files or vignettes. However, when I run my tests (via `devtools::test`), I get the warning:

>Warning message:
>`encoding` is deprecated; all files now assumed to be UTF-8 

According to the [R Extensions Manual](https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file), `Encoding` isn't actually deprecated, and even if it were I'm not using it. What is the intention of this warning? Have I done something  that needs attention?

**Comment by jimhester** [comment]
This is actually referring to the `encoding = ` parameter to `testthat::test_dir()`, rather than the `Encoding:` field in the `DESCRIPTION` file. We should remove the encoding argument at https://github.com/r-lib/devtools/blob/ab568e954252a95f2279281784480afd117e63fa/R/test.r#L70

**Comment by jimhester** [comment]
But as  workaround you should be able to add `Encoding: UTF-8` to your DESCRIPTION and that should make this warning go away.
