### ISSUE TITLE
Deleting Remotes field from DESCRIPTION in release() and build()

### ISSUE THREAD

**Issue by bgctw** [r-lib/devtools#1778]
When submitting to CRAN, the Remotes field has to be deleted from DESCRIPTION.
`release()`  already warns if such a field is present.

I suggest that `release` should  ask and delete the field temporarily before building the package. After the built for CRAN the original DESCRIPTION should be restored.
An option in `build` would be also appreciated.

**Comment by gaborcsardi** [comment]
> I suggest that release should ask and delete the field temporarily before building the package. After the built for CRAN the original DESCRIPTION should be restored.

I am not sure what is the use case here, but usually you add `Remotes` if the CRAN version is not good enough for you. And when you submit to CRAN, the CRAN version must be good enough for you, meaning that it is time to remove `Remotes` permanently.

**Comment by bgctw** [comment]
My use case: I migrated some parts of larger package REddyProc to its own package REddyProcNCDF. The latter lists the former in the DEPENDS field and also used the Remotes field. In the latter package I want always use the most recent version of the former.  I could  make sure myself, that I update the dependencies during development, but I thought, this was the purpose of the `Remotes` field.

I would like to use,

- On cran, the most recent cran version of the dependency 
- while on non-cran (development), the most recent github version of the dependency.

What would be the recommended procedure?

**Comment by jimhester** [comment]
You should remove the Remotes field when submitting, then add it back, we are not going to do this automatically because it should be a conscious choice.
