### ISSUE TITLE
devtools::install(".") fails with cygwin1.dll problem

### ISSUE THREAD

**Issue by surmann** [r-lib/devtools#1781]
My environment:

- Windows 7
- R 3.5.0
- Rtools35
- devtools    * 1.13.5.9000 2018-05-14 Github (hadley/devtools@13ee56b)

I try to install the cloned local package ropensci/git2r@91a169d4. It works with `R CMD INSTALL .` but it fails with `devtools::install(".")` with the following error message:

          0 [main] make (3748) c:\Rtools\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x612A5410/0xD65410.
    This problem is probably due to using incompatible versions of the cygwin DLL.
    Search for cygwin1.dll using the Windows Start->Find/Search facility
    and delete all but the most recent version.  The most recent version *should*
    reside in x:\cygwin\bin, where 'x' is the drive on which you have
    installed the cygwin distribution.  Rebooting is also suggested if you
    are unable to find another cygwin DLL.
          0 [main] make 7432 fork: child -1 - forked process 3748 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
    make: fork: Resource temporarily unavailable
    ERROR: compilation failed for package 'git2r'

I have no cygwin installation. The search for cygwin1.dll returns 3 matches, but the paths are not listed in the windows `PATH` system variable.

Do you have any suggestions what's my mistake?

**Comment by jimhester** [comment]
Yes, you have `C:\Program Files\ConEmu\ConEmu` in your PATH, so that `cygwin1.dll` is being used instead of the one from R.

**Comment by surmann** [comment]
I know. There are two reasons to argue the converse:
- The `PATH` variable does not look in subdirectories. `wsl` as a subdirectory of ConEmu is not browsed.
- On my other system with a similar (Win 10 instead of Win 7) installation, everything works fine.

If there are no ideas, how to tackle this problem, let me know.

**Comment by jimhester** [comment]
If you are still looking for help I would suggest posting on community.rstudio.com, I don't think this is a devtools specific issue.
