### ISSUE TITLE
install_version() fails with reload argument

### ISSUE THREAD

**Issue by amstilp** [r-lib/devtools#1783]
Passing the `reload` argument to `install_version` fails. I would expect to be able to do this because the help for `reload` says that the `...` extra arguments are passed to `install`, which has the `reload` argument.

 It looks like `reload` is then being passed to `download.file`, which doesn't accept the `reload` argument. Sadly, if I don't include the `reload` argument, I get a segfault when specific packages are reloaded after install. (In my case, the `curl` package is the culprit.)

Here's an example:

```
install_version("argparser", version="0.4", repos="http://cran.rstudio.com/", type="source", dependencies=FALSE, reload=FALSE)
```

And the error message:
```
Installing package into ‘/tmp/tmp_library’
(as ‘lib’ is unspecified)
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  unused argument (reload = FALSE)
```

Here is `sessionInfo()`:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/local/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.5

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    withr_2.1.2    memoise_1.1.0  digest_0.6.14 
```

**Comment by jimhester** [comment]
It mentions `...` is passed to `install.packages()` not `devtools::install()`, so this is working as intended.

**Comment by jayMcoder** [comment]
So basically devtools call the download.file function of R util package with additional parameters passed to install_version -> This restricts use of install parameters defined by devtools::install
```
R utils package download.file
download.file(url, destfile, method, quiet = FALSE, mode = "w",
              cacheOK = TRUE,
              extra = getOption("download.file.extra"), ...)
```

**Comment by jimhester** [comment]
The documentation is already fixed in the devel version of devtools.
