### ISSUE TITLE
How do I install a library from github to a specified location and keep the source in another

### ISSUE THREAD

**Issue by statquant** [r-lib/devtools#1784]
Hello I'd like to use `install_*` (`install_github` if possible as the package is not on cran) to install a package.
Because I need to be able to track things I need to a be able to 

- specify a directory where things are installed (this I can set the env var R_USER_LIBS)
- keep the source in another **this I am not sure**

Essentially like `destdir` and `lib`  in `base::install.package`
`install.packages(pkgs='devtools', destdir='/tmp/spran_sources', lib='/tmp/spran_library', dependencies=TRUE, repos='http://cran.us.r-project.org')`

The docs refers to `with_libpaths` but it is deprecated

**Comment by jimhester** [comment]
I think you should just clone the repository yourself, then install it with `devtools::install()`.

This workflow is not something we plan to support in devtools.

Also note devtools tracks the git SHA when it installs the package, you can retrieve it (after installing with `install_github()`) with `packageDescription("xyz")$RemoteSha`.

**Comment by statquant** [comment]
Many thanks @jimhester I discovered `versions` and it gives me what I want as it is simply doing `install.packages` pointing to the microsoft snapshot of cran.

**Comment by statquant** [comment]
Many thanks @jimhester for the prompt reply
