### ISSUE TITLE
In RStudio, automatically update help file after document()

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1785]
This may require that RStudio report what help file is currently open so we can figure out which file to rebuild.

**Comment by jimhester** [comment]
I think this would require something like `rstudioapi::getHelpContext()`, which does not exist and doesn't look like there is any tooling for tracking which file is open. It would also have to disambiguate between viewing a help file and doing other things in that pane, like files and plots.

**Comment by hadley** [comment]
@kevinushey how hard would it to be add something to rstudioapi to tell us what help file is currently open?

(@jimhester since we're already shimming `?`, couldn't we track the last help file loaded?)

**Comment by kevinushey** [comment]
Can you give me a full run-through of the workflow you're imaging here? Would you also need the ability to programmatically refresh the Help pane? What information do you need from the Help pane (e.g. is just the URL being viewed sufficient)?

**Comment by jimhester** [comment]
I think the workflow would be something like

`devtools::load_all()`

`?xyz` 

Where xyz is a fun of the pkg under development, this (as it does now) would open xyz in the help pane.

***user makes changes in roxygen comment in source file***

`devtools::document()`

***magic which doesn't currently exist***

The open help pane of xyz is updated with the changes.

I think we would need to determine if a help page from the current pkg is currently being viewed (probably the URL is sufficient for this) and to refresh the page if so (maybe we could just issue a new call to `help()` the help page topic for this).

**Comment by hadley** [comment]
I just realised another challenge — `devtools::document()` is usually run in another process

**Comment by kevinushey** [comment]
Maybe it would be sufficient for RStudio to just always refresh the Help pane after a Build pane action completes successfully?

**Comment by hadley** [comment]
But `document()` can't call rstudioapi, because it's not run from RStudio (usually)

**Comment by kevinushey** [comment]
I think the intention would be that `devtools::document()`s run in the current session would use `rstudioapi` to refresh the Help pane, but RStudio would just refresh the Help pane by default for things that happen in the Build pane.

**Comment by hadley** [comment]
I’m closing this give the challenges of cross process communication and the relatively small utility and that we haven’t made any progress on it in the last two years.
