### ISSUE TITLE
devtools::test() fails when code in test_that doesn't have expectations, devtools::check() is ok

### ISSUE THREAD

**Issue by GeoBosh** [r-lib/devtools#1789]
On the following code 
```
test_that("aha", {
    # expect_equal(2+2, 4)
    theta <- 0.7
})
```
`devtools::test()` fails and reports something like:
```
> devtools::test()
   ...
Error in x[[method]](...) : attempt to apply non-function
== Results =========================================
Duration: 1.5 s
OK:       2
Failed:   4
Warnings: 0
Skipped:  1
 >
```
At the same time  `devtools::check()` is ok with this. It seems that it is the absence of expectations in the code that triggers the error (uncommenting the commented out line removes the problem). 
This is on Windows with the latest versions of  `devtools` and `testthat` from `CRAN`. 

I am reporting this on `devtools` since running the `test_that` command directly is ok.

**Comment by jimhester** [comment]
So this is actually a testthat issue, https://github.com/r-lib/testthat/issues/700 and is fixed in the devel version of testthat (not yet on CRAN).

**Comment by jimhester** [comment]
A workaround is to ensure all of your test files have a `context()` line before any tests.
