### ISSUE TITLE
Is remotes still one of the "diaspora" packages?

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#1790]
The devtools README suggests that remotes is the "diaspora" package slated to host functionality around "Installing packages".

https://github.com/r-lib/devtools/blame/aa72670ceba41614fc2be129a4d1b171d381378a/README.md#L105

I suspect this information is not current/complete and it's encouraging people to prefer remotes over devtools for tasks such as ... `remotes::install_github()` vs. `devtools::install_github()`. It would be good to clarify the current and future status of remotes vis-a-vis devtools.

cc @mine-cetinkaya-rundel

**Comment by jimhester** [comment]
The original plan was to use remotes, but because getting the other diaspora packages on CRAN as drawn out so long now the current plan is to skip remotes and go straight to pkgman and friends I think.

**Comment by jennybc** [comment]
So is there any reason to have remotes in one's `.Rprofile` now? Is there any function there that we like better for any reason than its counterpart in some other package, mainly devtools, I suppose?

It's all a bit foggy now, but I think `remotes::install_github()` was, at some point, the reason I put remotes in `.Rprofile` and I placed it after devtools, so masking it. If I want cutting edge r-lib, should I revert this?

**Comment by jimhester** [comment]
The main benefit to remotes vs devtools is remotes has no dependencies, so for local use I would recommend using devtools or pkgman stuff if you are feeling adventurous.

**Comment by gaborcsardi** [comment]
> pkgman stuff if you are feeling adventurous.

please don't use pkgman yet

**Comment by jennybc** [comment]
OK I am going to revert to devtools for my non-`utils::install.packages()` package installation needs. And will speak up if I notice something that was good about remotes that should be brought into devtools or pkgman.
