### ISSUE TITLE
error after calling load_all: "functionName" not resolved from current namespace

### ISSUE THREAD

**Issue by epurdom** [r-lib/devtools#1791]
Hello,
I am getting an error in running code after using `load_all` for my package. Specifically, if I reload my package (which has C code to compile, via `Rcpp`), C code from another package no longer works. I get the error:
```
Error in .C(Cname, t(data), as.integer(k), d, n, nn.index = integer(n *  : 
  "get_KNN_kd" not resolved from current namespace (FNN)
```
I've seen posts online about this error being related to whether the argument `PACKAGE=` option was set in the `.C` call of the package [here](http://r.789695.n4.nabble.com/question-re-error-message-package-error-quot-functionName-quot-not-resolved-from-current-namespace-td4663892.html). And the package `FNN` (which is not mine) does not appear to set this argument; but for the record, neither does my package, since this doesn't seem to be set by the `.Call` created automatically by Rcpp, which I am using.

However, given that it only happens when I call `load_all`, I'm wondering if it is really that issue or if its something about how `load_all` unloads dll. I do get the warning after running `load_all`:

```
unloadNamespace("clusterExperiment") not successful, probably because another loaded package depends on it.Forcing unload. If you encounter problems, please restart R.
```

I always get this error, and perhaps the problem with the C code is an example of the problems due to unloading. But if so, it basically means that I can't use `load_all` for my package development, since this is a problem that I'm hitting in my vignette, so I'm hoping not! 

Here is the full code that reproduces it on my machine (Mac OSX, R 3.5.0, Bioconductor 3.7)

First clone my current (master) branch from github (so can have directory with code with which to call `load_all`):

```
git clone https://github.com/epurdom/clusterExperiment.git
cd clusterExperiment
R
```

Then within R install the release version of my package from Bioconductor via biocLite:
```
#install clusterExperiment from bioconductor:
source("https://bioconductor.org/biocLite.R")
biocLite("clusterExperiment")
```

Then the following code seems to create the error (note that there has been no change to the C code between the two different versions of my package used here):

```
packageVersion("clusterExperiment")
#[1] ‘2.0.2’
packageVersion("scran")
#[1] ‘1.8.1’
packageVersion("FNN")
#[1] ‘1.1’
library(clusterExperiment)
library(scran)
#following code from `scran` package calls a function from package FNN 
#it works here
buildSNNGraph(matrix(rnorm(100),ncol=10), k = 2, d = NA, transposed = FALSE)
#now load my github version
library(devtools)
load_all()
packageVersion("clusterExperiment")
#[1] ‘2.1.3’
#now fails after load_all
buildSNNGraph(matrix(rnorm(100),ncol=10), k = 2, d = NA, transposed = FALSE)
```

Thank you for your assistance,
Elizabeth Purdom
@drisso

**Comment by jimhester** [comment]
I don't think this is a devtools / pkgload issue. The clusterExperiment package does not seem to be able to be unloaded by R.

e.g.

``` r
loadNamespace("clusterExperiment")
#> Warning: namespace 'bigmemory' is not available and has been replaced
#> by .GlobalEnv when processing object ''

#> Warning: namespace 'bigmemory' is not available and has been replaced
#> by .GlobalEnv when processing object ''
#> <environment: namespace:clusterExperiment>
unloadNamespace("clusterExperiment")
#> Warning: namespace 'bigmemory' is not available and has been replaced
#> by .GlobalEnv when processing object ''

#> Warning: namespace 'bigmemory' is not available and has been replaced
#> by .GlobalEnv when processing object ''
"clusterExperiment" %in% loadedNamespaces()
#> [1] TRUE
```

Created on 2018-07-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Contrast this with a package which is able to be unloaded.

``` r
loadNamespace("fs")
#> <environment: namespace:fs>
unloadNamespace("fs")
"fs" %in% loadedNamespaces()
#> [1] FALSE
```
