### ISSUE TITLE
Evaluate where get_path() and friends belong

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#1796]
Is devtools still the forever home for `get_path()`, `set_path(path)`, and `add_path(path, after = Inf)`? I came across these in a disambiguation prompt when seeking help on `fs::path()`. The latter two definitely feel more like withr functions now.

**Comment by jimhester** [comment]
withr has `with_path()`, so you can get the same behavior as `add_path(after = Inf)` with `withr::with_path(path, action = "suffix")`.

It doesn't seem like these functions are used by [any packages on CRAN](https://github.com/search?l=R&q=user%3Acran+set_path+OR+get_path+OR+add_path&type=Code) (including devtools) so maybe we should just remove them entirely?

**Comment by jennybc** [comment]
I can convince myself either way, but The Great Devtools Breakup certainly feels like a good time to clean out the proverbial closet.
