### ISSUE TITLE
under test(), cannot detach the package being tested

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/devtools#1797]
Within a package named "packagefileprob", which defines and exports a function `bar`, in tests/test-detach.R, I have
```
context('whatever')

test_that('some tests where I detach my package', {
  detach(package:packagefileprob, unload = TRUE, force = TRUE)
  expect_error(bar())
  expect_silent(packagefileprob::bar())
  library(packagefileprob)
})

library(clipr)

test_that('some tests where I detach a different package', {
  detach(package:clipr, unload = TRUE, force = TRUE)
  expect_error(dr_clipr())
  expect_error(clipr::dr_clipr(), NA)
  library(packagefileprob)
})

```

From the command line the `test_that` call runs silently, as expected. It also works if I run `testthat::test_dir("tests/testthat")`. But if I run `devtools::test()`, I get:

```
test-detach.R:6: failure: some tests where I detach my package
`bar()` did not throw an error.
```

This matters if I want to write tests that ensure my package works when called without being attached.

The second testthat chunk works fine. Only the package being tested cannot be detached.

`detach()` seems to fail silently. The `unload` and `force` arguments don't make a difference.

**Comment by jimhester** [comment]
If you want to do this then you will need to do it without testthat in a separate test file.

**Comment by jonathanbratt** [comment]
@hughjonesd 
I found myself wanting to write the same sort of test you refer to. It seems to work if I detach the current package in the base environment and run the call to be tested there. Something like:

```
test_that("package routine can be called using ::, without the package being attached")
expect_silent(
    local({
        library(my_package)
        detach("package:my_package")
        my_package::my_function()
        library(my_package)
    },
    envir=baseenv()) 
)
```
