### ISSUE TITLE
library(pkg) does not find loaded development dependency

### ISSUE THREAD

**Issue by renozao** [r-lib/devtools#1798]
Assuming `pkgA` depends on `pkgB`, and that one wants to test/use in `pkgA` development changes made in `pkgB`. One does not necessarily own `pkgA` and just load it with `library`.

The following used to work fine and as expected, that is that the installed version of `pkgA` would load and use the pre-loaded development version of `pkgB`:
```R
library(devtools)
load_all("path/to/pkgB/src")
library(pkgA)
```

Now I am getting this error:
```
package ‘pkgB’ required by ‘pkgA’ could not be found
```

My setup is:
```
Session info --------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.423)           
 language en_ZA:en                    
 collate  en_ZA.UTF-8                 
 tz       Europe/Athens               
 date     2018-06-06   

devtools version:
devtools                 * 1.13.5     2018-02-18 CRAN (R 3.4.3)
```

**Comment by jimhester** [comment]
You need to install pkgB to use it from pkgA, you cannot just use `load_all()`, which does not actually install the package.

Likely previously you had some version of pkgB installed.

In general it is best to use `devtools::install("pkgB")` in this situation rather than `load_all()`

**Comment by renozao** [comment]
@jimhester I am definite that the installed `pkgA` was loading the loaded development version of `pkgB`. I have been using this feature many many times: I could see that `pkgA` was using the modified version of the functions in `pkgB` I was busy with.
This behaviour would happen even if there was an installed version of `pkgB`: `pkgA` would not try to load `pkgB` from the library, if it was already loaded by `load_all`.

Currently, not only the loaded `pkgB` dev package is not used, but neither is found its installed "old" version. 
I am aware and indeed experienced things that go wrong when using `load_all` for dependencies, but this was in relatively specific and rare situations, e.g., with dependencies with compiled libraries in parallel computations or intricate S4 methods and classes.

**Comment by jimhester** [comment]
Yes, but previously you had an installed version of `pkgB` on your system, now you do not.

Nothing has changed in this regard on the CRAN version of devtools for probably 2 years, so this is not due to a change in devtools.
