### ISSUE TITLE
install_github() can fail if installation runs an executable script

### ISSUE THREAD

**Issue by wch** [r-lib/devtools#1799]
On R installations that have `options(unzip = "internal")`, installation of packages can fail.

For example, these will fail on Linux and Mac:

```R
# Most installations have options(unzip = "/usr/bin/unzip"), but we'll set it to
# internal for this example.
options(unzip = "internal")

devtools::install_github("r-lib/fs")

devtools::install_github("rstudio/httpuv@v1.4.3")
```

The error looks like this:

```
(cd libuv \
	&& touch aclocal.m4 \
	&& touch -r aclocal.m4 configure Makefile.in \
&& CC="gcc" CFLAGS="-g -O2  -fpic -fvisibility=hidden" AR="ar" RANLIB="ranlib" LDFLAGS="-L/usr/local/lib" ./configure --quiet)
/bin/bash: line 3: ./configure: Permission denied
Makevars:32: recipe for target 'libuv/Makefile' failed
make: *** [libuv/Makefile] Error 126
ERROR: compilation failed for package ‘fs’
```

The problem is that the internal `unzip` does not preserve execute permissions.

Most installations of R default to `/usr/bin/unzip`, but some do not. With httpuv, we heard about this issue from a few people who had their own builds of R. On rstudio.cloud and rsp.rstudioservices.com, the default for unzip is `internal`, so installation of these packages from GitHub fails. The error is pretty cryptic so we went through a bunch of rounds of communication, asking if there were NFS issues, limits on sudo permissions, or weird filesystems that were used for the temp dir. But it turned out to just be just due to the internal unzip.

@jimhester and I discussed changing `install_github` to download a .tar.gz instead of .zip. Assuming the internal untar preserves execute permissions, this would solve the problem with `install_github()`. However, it wouldn't solve the problem with .zip files in general.

**Comment by gaborcsardi** [comment]
That's  (partially)  because `install_github()` does not call `R CMD build` on the package.  If you use `local = FALSE` (which should be the default imo), then  `R  CMD build` fixed the permission of  `configure`:

```
* checking for file ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpPDEoK4/devtools9153552faec1/rstudio-httpuv-a868452/DESCRIPTION’ ... OK
* preparing ‘httpuv’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘httpuv_1.4.3.tar.gz’
Warning: file 'httpuv/src/libuv/configure' did not have execute permissions: corrected
```

It still fails, because `install-sh`  is  not executable, either:
```
make --directory=libuv \
		HAVE_DTRACE=0
make[1]: ./install-sh: Permission denied
```
but this can be fixed from `configure`, I think.

**Comment by gaborcsardi** [comment]
Btw., also, an explicit `local = FALSE` is not ideal, because it is not passed to the installed dependencies, so if `httpuv` is  installed  as  a dependency, it will still fail. The ideal solution would be to change the default for all `install_*` functions (but not for `install()`) to `local = FALSE`.

**Comment by gaborcsardi** [comment]
> I don't think it should be the default.

Why?

**Comment by jimhester** [comment]
Building the package first is much slower in some cases, particularly large packages with a lot of data

**Comment by gaborcsardi** [comment]
Even with  `R --no-resave-data  --no-build-vignettes` ?

**Comment by jimhester** [comment]
You still have to copy, archive and recompress the archive, then decompress them again to actually install the package
