### ISSUE TITLE
installing devtools in R 3.4.3

### ISSUE THREAD

**Issue by Gioparra91** [r-lib/devtools#1800]
Hi guys, sorry i'm a n00b and I can't install devtools.
I get this:
"ERROR: dependency ‘igraph’ is not available for package ‘lintr’
* removing ‘/Users/giovanni/Desktop/AI_ML_DL_DataScience/anaconda3/envs/ML_AI/lib/R/library/lintr’
Warning in install.packages :
  installation of package ‘lintr’ had non-zero exit status
* installing *source* package ‘IRdisplay’ ...
** package ‘IRdisplay’ successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (IRdisplay)
ERROR: dependency ‘git2r’ is not available for package ‘devtools’
* removing ‘/Users/giovanni/Desktop/AI_ML_DL_DataScience/anaconda3/envs/ML_AI/lib/R/library/devtools’
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status"

Thanks

**Comment by jimhester** [comment]
It looks like you have having issues installing igraph and git2r. You would need to post more of the installation log to know more.

Also this is unlikely due to devtools code, I would recommend you post this on https://community.rstudio.com/ with the full installation log.
