### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle)

### ISSUE THREAD

**Issue by SrinivasTammana** [r-lib/devtools#1802]
Hi All,

I am trying to authenticate LinkedIn using below command. but getting error. can any one provide solution or suggestions ?
Command:
in.auth <- inOAuth(app_name, consumer_key, consumer_secret)
Error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

**Comment by jimhester** [comment]
This does not seem related to devtools, perhaps you want to post it on community.rstudio.com?
