### ISSUE TITLE
Installation failed: formal argument "dependencies" matched by multiple actual arguments

### ISSUE THREAD

**Issue by Dripdrop12** [r-lib/devtools#1805]
I'm getting this error when running:

```
install_cran("rintrojs", dependencies = TRUE, force = TRUE)
install_cran("js", dependencies = TRUE)
```
Is `dependencies` set underneath the `install_cran` call? 

The docs say `...` passes its args to `install_packages`. However, when I check `?install_packages` I get "No documentation for ‘install_packages’ in specified packages and libraries."

Many of the other `install_` variants in `devtools` pass their arguments on to `install`, which uses the standard from `install.packages` for their `dependencies` argument. Is that the intention for `install_cran`?

Here is my session info:

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.5

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    withr_2.1.2    yaml_2.1.19    memoise_1.1.0  digest_0.6.15
```

**Comment by jimhester** [comment]
Thanks, reproduced and now fixed

**Comment by Dripdrop12** [comment]
Thanks @jimhester!
