### ISSUE TITLE
New to R - trouble installing package from github

### ISSUE THREAD

**Issue by JamesSteeleII** [r-lib/devtools#1807]
Hi all, 

I'm very new to using R and have been installing some packages to use that I think will be useful for the research I work on. I recently tried to install the following - https://github.com/lucymcgowan/sgpvalue 

And end up with the following in the console that suggests it did not install correctly... 

> > devtools::install_github("LucyMcGowan/sgpvalue")
> Downloading GitHub repo LucyMcGowan/sgpvalue@master
> from URL https://api.github.com/repos/LucyMcGowan/sgpvalue/zipball/master
> Installing sgpvalue
> Installing 1 package: purrr
> Installing package into ‘\\uka-file1/redirectedfolders$/jamessteele/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> Warning: dependencies ‘methods’, ‘utils’, ‘grDevices’, ‘tools’ are not available
> also installing the dependencies ‘assertthat’, ‘utf8’, ‘cli’, ‘crayon’, ‘pillar’, ‘magrittr’, ‘rlang’, ‘tibble’
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/assertthat_0.2.0.zip'
> Content type 'application/zip' length 53556 bytes (52 KB)
> downloaded 52 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/utf8_1.1.4.zip'
> Content type 'application/zip' length 214517 bytes (209 KB)
> downloaded 209 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/cli_1.0.0.zip'
> Content type 'application/zip' length 329289 bytes (321 KB)
> downloaded 321 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/crayon_1.3.4.zip'
> Content type 'application/zip' length 749818 bytes (732 KB)
> downloaded 732 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/pillar_1.2.3.zip'
> Content type 'application/zip' length 146605 bytes (143 KB)
> downloaded 143 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/magrittr_1.5.zip'
> Content type 'application/zip' length 155487 bytes (151 KB)
> downloaded 151 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/rlang_0.2.1.zip'
> Content type 'application/zip' length 822368 bytes (803 KB)
> downloaded 803 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/tibble_1.4.2.zip'
> Content type 'application/zip' length 243565 bytes (237 KB)
> downloaded 237 KB
> 
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/purrr_0.2.5.zip'
> Content type 'application/zip' length 288976 bytes (282 KB)
> downloaded 282 KB
> 
> package ‘assertthat’ successfully unpacked and MD5 sums checked
> package ‘utf8’ successfully unpacked and MD5 sums checked
> package ‘cli’ successfully unpacked and MD5 sums checked
> package ‘crayon’ successfully unpacked and MD5 sums checked
> package ‘pillar’ successfully unpacked and MD5 sums checked
> package ‘magrittr’ successfully unpacked and MD5 sums checked
> package ‘rlang’ successfully unpacked and MD5 sums checked
> package ‘tibble’ successfully unpacked and MD5 sums checked
> package ‘purrr’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\jamessteele\AppData\Local\Temp\RtmpMBJztJ\downloaded_packages
> "//uka-file1/redirectedfolders$/jamessteele/Documents/R/R-3.5.0/bin/x64/R" --no-site-file --no-environ --no-save  \
>   --no-restore --quiet CMD INSTALL  \
>   "C:/Users/jamessteele/AppData/Local/Temp/RtmpMBJztJ/devtools32444ab27600/LucyMcGowan-sgpvalue-354298b"  \
>   --library="\\uka-file1/redirectedfolders$/jamessteele/Documents/R/win-library/3.5" --install-tests 
> 
> '\\uka-file1\redirectedfolders$\jamessteele\Documents\R\R-3.5.0' is not recognized as an internal or external command,
> operable program or batch file.
> In R CMD INSTALL
> Installation failed: Command failed (1)

`

I'm unsure how to address this - is anyone able to offer some help?

Thanks in advance,

James

**Comment by jimhester** [comment]
It looks like your library is set to a network drive, but the path is not correct (the `\uka-file1\` should be `//uka-file1`. I would suggest you set your library to a location on your physical drive with `.libPaths()`.

It also looks like your R distribution is installed on a network drive, generally I would not recommend this setup as there are cases where R has problems with network drives.

I would try re-installing R on a local drive and if you are still running into problems try posting the issue on community.rstudio.com

As this is not a devtools specific issue I am going to close it.
