### ISSUE TITLE
Export, credit or something else - github_remote, remote_download.github_remote, & source_pkg

### ISSUE THREAD

**Issue by Dripdrop12** [r-lib/devtools#1808]
I'm using some internal `devtools` functions to download R packages from Github and build Windows binaries for `RInno` installations:

```
    if (length(req_deps) > 0) {
      cat("Downloading remotes... \n - ")
      cat(remotes, sep = "\n - ")

      github_remotes <- lapply(remotes, devtools:::github_remote, username = auth_user,
                        auth_token = auth_token, host = "https://api.github.com")

      zip_files <- lapply(github_remotes, devtools:::remote_download.github_remote)

      decompressed_pkgs <- lapply(zip_files, function(x) {
        gsub("[\\/]+", "/", devtools:::source_pkg(x))
      })
```
https://github.com/ficonsulting/RInno/blob/93d876454bb665e8ba681cf0e1a23a100ac947a9/R/download_packages.R#L72-L83

It looks like there are three options to avoid CRAN NOTEs:

1. Export these internal methods
2. Copy them and credit the authors of `devtools`
3. Find another way to do the same thing w/o `devtools`

Which route would you prefer to take? Thanks!

**Comment by jimhester** [comment]
We will not be exporting these functions, so I would suggest you either copy the implementations (with attribution) or find a way to do this without devtools.
