### ISSUE TITLE
devtools::build_vignettes and rstudio build->install and restart

### ISSUE THREAD

**Issue by wolski** [r-lib/devtools#1809]
Hello,

There is a difference between devtools and the rstudio behaviour although although I configured the package build in rstudio to use devtools.

When building vignettes with devtools::build_vignettes they end up in inst/doc
and also the package index is updated so that they are visible in the package documentation.

When building vignettes with rstudio -> install and restart, the vignettes are build but the html and pdf version do remain in the vignettes folder and do not show up in the package documentation.

These are my rstudio build settings.

![rstudiosettings](https://user-images.githubusercontent.com/1926513/42209617-6846e18e-7eaf-11e8-8853-c2de3623846e.jpg)

I am wondering if this is something to be expected.

I wish you a great day.
Best regards

**Comment by jimhester** [comment]
It is expected, we are planning to re-think how devtools builds vignettes https://github.com/r-lib/devtools/issues/1578.
