### ISSUE TITLE
add method for releasing to package repositories other than CRAN

### ISSUE THREAD

**Issue by ntdef** [r-lib/devtools#1817]
Currently, the URL that `devtools::release` submits to is hardcoded to point to CRAN in `release.r`. It would be awesome if that url could be configurable or a more custom method was available to submit to other repositories (e.g. internal repositories).

Along with this issue, I've provided PR #1816 as a possible solution.

**Comment by hadley** [comment]
Our recent experience is that it's not a great idea for us to add functions that we never use because they inevitably bitrot, and we have no idea how to fix them. So I think this is a good idea, but unfortunately devtools is just not the right package for it.
