### ISSUE TITLE
Bug in Remotes: GitHub in DESCRIPTION

### ISSUE THREAD

**Issue by TKoscik** [r-lib/devtools#1820]
I have set up a package on GitHub to require another package I have on GitHub, using the "Remotes" section in the DESCRIPTION file, but the dependency only is acknowledged and installed if "Imports:" is present even though there are no other dependencies. Not sure if this is the desired behaviour or not.

**Comment by jimhester** [comment]
This behavior is already changed in the devel version of devtools https://github.com/r-lib/devtools/commit/1ce84b04568ff7846c3da754f28e7e22a23c8737#diff-e7118181d76027ea30ccf5babc54f550
