### ISSUE TITLE
load_all() Fails with Trailing Slash

### ISSUE THREAD

**Issue by billdenney** [r-lib/devtools#1821]
When attempting to use `load_all` with a directory name with a trailing forward slash (on Windows), it fails, but it succeeds when the trailing slash is removed:

``` r
> devtools::load_all(pkg="c:/git/pknca/")
Error: Can't find 'c:\git\pknca\'.
> devtools::load_all(pkg="c:/git/pknca")
Loading PKNCA
```

If important, devtools was not a loaded package when this was called (i.e. I'd not called `library(devtools)`).

**Comment by jimhester** [comment]
Paths ending with `/` and those which do not are not equivalent on windows. See https://bugs.r-project.org/bugzilla/show_bug.cgi?id=14721

Anyway I am pretty sure this is already fixed in pkgload; which devtools will use in the next version.

Could you verify

```r
install.packages("pkgload")
pkgload::load_all("C:/git/pknca/")
```

**Comment by billdenney** [comment]
Wow, that's a horrible bug in base R.  Thanks for letting me know about it.

It's not on the CRAN version of pkgload:
``` r
> install.packages("pkgload")
Installing package into ‘C:/Users/Bill Denney/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/pkgload_1.0.0.zip'
Content type 'application/zip' length 101899 bytes (99 KB)
downloaded 99 KB

package ‘pkgload’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Bill Denney\AppData\Local\Temp\RtmpKIwds9\downloaded_packages
> devtools::load_all("c:/git/pknca/")
Error: Can't find 'c:\git\pknca\'.
> devtools::load_all("c:/git/pknca")
Loading PKNCA
> 
```

I also installed the GitHub version of `pkgload`, and got the same result.
