### ISSUE TITLE
Convert to use fs

### ISSUE THREAD

**Issue by jimhester** [r-lib/devtools#1826]

**Comment by malcolmbarrett** [comment]
@jimhester do you want help on this one? Just flipping through issues, and this seems straightforward, if a bit tedious

**Comment by jimhester** [comment]
Sure!

**Comment by malcolmbarrett** [comment]
Cool, I'll prep a PR soon. Do you want an fs vs base linter like usethis has?

**Comment by jimhester** [comment]
no, I think we are ok, we aren't doing as much active development and interacting with the file system in devtools so I think it would be overkill
