### ISSUE TITLE
Installing R package from GitHub Enterprise

### ISSUE THREAD

**Issue by crossxwill** [r-lib/devtools#1831]
I'm trying to install a private R package from my company's GitHub Enterprise. I referred to the instructions in #688 and #892. 

The process appears to be:
1. Create a personal access token inside your company's instance of GitHub Enterprise
2. Create a GITHUB_PAT variable inside your .Renviron file
3. Set the host to the GitHub Enterprise API

I'm surprised to see that `install_github` still calls out to raw.githubusercontent.com (even though I specified a host that points to my company's GitHub Enterprise).
```r
> library(devtools)
> Sys.getenv('GITHUB_PAT')
[1] "{nonsense alpha-numeric-chars}"
> install_github('{username}/{privateRpackage}', host='{companyGitHubEnterpriseURL}/api/v3/')
Using GitHub PAT from envvar GITHUB_PAT
Installation failed: Failed to connect to raw.githubusercontent.com port 443: Timed out
> 
```

When I ran debug, I found that `devtools:::remote_package_name.github_remote` calls out (hard-coded) to https://raw.githubusercontent.com.

```r
function (remote, url = "https://raw.githubusercontent.com", 
    ...) 
{
    tmp <- tempfile()
    path <- paste(c(remote$username, remote$repo, remote$ref, 
        remote$subdir, "DESCRIPTION"), collapse = "/")
    if (!is.null(remote$auth_token)) {
        auth <- httr::authenticate(user = remote$auth_token, 
            password = "x-oauth-basic", type = "basic")
    }
    else {
        auth <- NULL
    }
    req <- httr::GET(url, path = path, httr::write_disk(path = tmp), 
        auth)
    if (httr::status_code(req) >= 400) {
        return(NA_character_)
    }
    read_dcf(tmp)$Package
}
<environment: namespace:devtools>
```

Is there a reason that `url` is hard-coded?

```r
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.6

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.3 R6_2.2.2       tools_3.4.3    withr_2.1.2    curl_3.2       yaml_2.1.19    memoise_1.1.0  git2r_0.23.0   digest_0.6.15 
```

**Comment by jimhester** [comment]
Thanks, should now be fixed, please try the devel version of devtools and let me know if it works for you.

**Comment by crossxwill** [comment]
@jimhester - thank you. Unfortunately, my company won't allow me to install non-CRAN packages. I'll assume it's fixed and wait for the next CRAN release. Thank you. Do you know approximately when is the next CRAN release?

**Comment by jimhester** [comment]
It is on the master branch, the commit is linked above.

I do not know when the next CRAN release will be, maybe in the next month or so.
