### ISSUE TITLE
document() is not dev-mode aware

### ISSUE THREAD

**Issue by anhqle** [r-lib/devtools#1838]
I'm contributing to the `tibble` package and has set up a dev-mode folder to install `tibble`'s dependencies.

However, `document()` doesn't seem use the packages installed in the dev-mode folder. For example, I have `pillar 1.3.0` in my `dev_mode` folder, called `R-tibble`:

```
d> packageVersion("pillar")
[1] ‘1.3.0.9000’

d> .libPaths()
[1] "/Users/anh/R-tibble"                                           
[2] "/Users/anh/Rlibs"                                              
[3] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library"
```

However, `document()` complains that `namespace ‘pillar’ 1.2.1 is already loaded, but >= 1.2.3.9002 is required`.

```
d> devtools::document()
Updating tibble documentation
Loading tibble
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘pillar’ 1.2.1 is already loaded, but >= 1.2.3.9002 is required
In addition: Warning message:
Version of roxygen2 last used with this package is 6.0.1.9000.  You only have version 6.0.1 
``` 

Is this a bug or I'm using dev_mode incorrectly?

**Comment by jimhester** [comment]
What version of devtools and roxygen are you using? Please try with the development versions if you have not done so.

**Comment by anhqle** [comment]
I could no longer reproduce this error because I nuked my R package folders and switched `packrat` for development.

Thanks a lot for your prompt reply! I'll close this issue for now and will re-open if I run into it again. Sorry for opening an unhelpful issue :(
