### ISSUE TITLE
add_desc_package does not like special char in DESCRIPTION file

### ISSUE THREAD

**Issue by gbouzill** [r-lib/devtools#1839]
Hello,

When trying to use "use_vignette" function, I had the following error: 
`Error in nchar(text) : invalid multibyte string, element 1`

It seems related to special characters (é) in the DESCRIPTION file due to the call of "add_desc_package" and then "write_dcf".

I don't know if it's important but UTF-8 encoding field is present in the DESCRIPTION file.

Thank you !

**Comment by jimhester** [comment]
Could you try this with `usethis::use_vignette()`? and if the problem still occurs open an issue at https://github.com/r-lib/usethis
