### ISSUE TITLE
authentication token is not passed down to graphql queries and github_user

### ISSUE THREAD

**Issue by renozao** [r-lib/devtools#1842]
Arguments `pat` and `host` are currently not passed down to calls to `github_GET` and `github_POST`, when querying the DESCRIPTON, sha and user.
This breaks access to private repositories.
I believe that this happened with the switch to graphql queries.

@jimhester the function github_user introduced in 7270c20 also needs to get those arguments for private repos access.

**Comment by tbates** [comment]
This seems to be a show stopper for the dev version of `devtools`

```Splus
devtools::release()
Error in stop(github_error(req)) : 
  This endpoint requires you to be authenticated. (401)

```

**Comment by jimhester** [comment]
I reverted the graphql commits, so this should now be fixed.
