### ISSUE TITLE
catching commented examples and vignette build time problems in R CMD CHECK

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1846]
My package has now been rejected a couple of times by CRAN for issues that are currently not captured by `devtools` and I think it will be great if future releases of `devtools` can catch these:

1. Vignette build-time: 
```
Check time in seconds: 1086 > 10 min
vignette outputs ... [13m]

Please reduce to less than 10 minutes for all checks/examples/vignette 
(maybe by using smaller data sets).
```

2. Commented examples in unexported functions
```
We also see:
Examples for unexported function "untable" in untable.Rd.

Please either add ggstatsplot::: to the function calls in the examples, 
omit these examples or export these functions.

Please also do not comment out examples.
```

Or maybe there is already a way to do this and I didn't do it? I usually do the following before submission:
```
devtools::check(check_version = TRUE, document = TRUE)
devtools::check_win_devel()
devtools::check_dep_version()
devtools::check_failures()
```

**Comment by jimhester** [comment]
There is nothing we can do about the build-time, it is dependent on how fast the vignettes run on the CRAN build machines, they must take less time locally and on win-builder.

The commented examples check is not part of `R CMD check` as far as I can tell, it was just found manually by the CRAN maintainers, so I don't think there is much we can do about this either.

**Comment by IndrajeetPatil** [comment]
sigh, I see.

From Twitter (I think it was @leeper's tweet), I had learned that CRAN no longer allows don't run examples-
```
#'@examples
#'\dontrun{
#'}
```
So I feel like they might have made changes to `R CMD CHECK` to catch all instances where either examples have been commented out or examples are included for functions not exported from the package.

**Comment by jimhester** [comment]
No, there is no code in the R sources `R CMD check` for this, you can look yourself https://github.com/wch/r-source/search?q=%22unexported+function%22&unscoped_q=%22unexported+function%22.

CRAN does allow dontrun, but it is only appropriate if the code cannot be run by either users or automated checks out of the box. If the code could be run by users interactively you should use `\donttest{}`. Please see Uwe's response at https://stat.ethz.ch/pipermail/r-package-devel/2018q2/002812.html for details.

**Comment by IndrajeetPatil** [comment]
Ah, I see. Okay, I will just manually check for these errors. Doesn't seem to be a way around it.
