### ISSUE TITLE
cannot install `devtools` on 3.5.1

### ISSUE THREAD

**Issue by Xinzhu-Fang** [r-lib/devtools#1847]
I was trying to install `devtools` in Rstudio in the rocker/rstudio image, which runs version 3.5.1, by calling `install.packages('devtools',dependencies = T)`. The installation failed with a bunch of errors yelling for missing dependencies such as `git2r`. So I called `install.packages('git2r',dependencies = T)`, which failed agian with error yelling for missing dependency `zlib`. So I called `install.packages('zlib',dependencies = T)`, which failed with `Warning in install.packages :
  package ‘zlib’ is not available (for R version 3.5.1)`

**Comment by jimhester** [comment]
Please read the full error message more closely, git2r should have given you an error saying something similar to

```r
   The zlib library that is required to build
   git2r was not found.

   Please install:
     zlib1g-dev (package on e.g. Debian and Ubuntu)
     zlib-devel (package on e.g. Fedora, CentOS and RHEL)
   and try again.
```

So you need to use the package manager for your linux distribution to install the appropriate system libraries for git2r installation to succeed.

In any case this is not an issue with devtools.

**Comment by Xinzhu-Fang** [comment]
thanks
