### ISSUE TITLE
reload(".") does not load "."

### ISSUE THREAD

**Issue by heavywatal** [r-lib/devtools#1848]
The behavior of `reload(".")` is a little surprising to me. After unloading `"."`, it tries to load a package with the same name from somewhere in`.libPaths()`. It applies to any case where a path is passed as `pkg` argument. I guess many users expect the package in the given path is loaded by this function even if they know `load_all()` is a more preferable way to reload a package under development.

https://github.com/r-lib/devtools/blob/5bbcac458f7c874e465229c01f07d4ff229d3dfc/R/reload.r#L25-L33

**Comment by hadley** [comment]
I think this is a documentation problem since `reload()` is unrelated to `load_all()`.
