### ISSUE TITLE
save_all helper?

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1850]
```R
  if (rstudioapi::hasFun("documentSaveAll")) {
    rstudioapi::documentSaveAll()
  }
```

Is repeated in a lot of places. If it was extracted out, you could also imagine adding implementations for other editors.

**Comment by AmundsenJunior** [comment]
I'm considering two ways of implementing this. First option is to place a `save_all()` function into `R/utils.R`. I'm not sure that this is the best location, if we are anticipating expanding with impls for other editors. In that case, it makes more sense to me to create `R/save-all.R`, and export the function from that file.

**Comment by jimhester** [comment]
I think we should put it in `R/save-all.R` with an eye towards expanding the functionality to other editors in the future. Although doing so would likely require a package to communicate with them ala rstudioapi.

**Comment by AmundsenJunior** [comment]
@jimhester created PR for save-all.R
