### ISSUE TITLE
Enhancement: colour check "Errors"

### ISSUE THREAD

**Issue by layik** [r-lib/devtools#1856]
Using version `1.13.6`

If there is an "Error" in `devtools::check()` seems it is left with the rest of the output, but for warnings color is set. I could not spot where in this file I should send a PR but would be great if someone could change the error colour so it can be spotted easier.

https://github.com/r-lib/devtools/blob/master/R/check.r

Thanks

**Comment by jimhester** [comment]
@layik if you would like to see what the output will look like in upcoming releases of devtools you can use `rcmdcheck::rcmdcheck()`.

**Comment by layik** [comment]
Thanks @jimhester & @gaborcsardi noted.
