### ISSUE TITLE
install_bioc() references the (outdated) svn repository

### ISSUE THREAD

**Issue by mtmorgan** [r-lib/devtools#1858]
In the SOURCE TARBALL ON CRAN `install_bioc` is
```
> devtools::install_bioc
function (repo, mirror = getOption("BioC_svn", "https://hedgehog.fhcrc.org/bioconductor"), 
    ..., quiet = FALSE) 
```
referencing the svn repository. I don't know where this comes from; it seems that the code on github was updated by https://github.com/r-lib/devtools/commit/fa7f7740403e2b865fda4cad9a15dfc09d5a02cb#diff-acdca8b4c069a3805b6e8c3aaca69f6c much earlier than the 1.13.6 version?

**Comment by mtmorgan** [comment]
I don't really know what that means; is `devtools::install_bioc()` no longer supported? If so, please mark it as such?

**Comment by jimhester** [comment]
We plan to have a devtools 2.0.0 release based off the master branch of devtools in the next couple of weeks ~ 1 month, so this should be fixed on CRAN soon.

**Comment by jimhester** [comment]
remotes 2.0.0 has now been released to CRAN, with the updated bioc code, devtools will be submitted in the very near future (using remotes) as well.
