### ISSUE TITLE
check() fails on Windows if check_dir has spaces

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/devtools#1864]
And probably also for other special characters that would need escaping. This is because `R CMD check` re-parses the arguments.

A fix will be implemented in rcmdcheck, by changing the working  directory and omitting the `--output` option. Then I'll submit a PR here to adapt `devtools::check()` to the new rcmdcheck argument.

**Comment by jimhester** [comment]
Is there a reason we can't use `shQuote()`? Or you just think changing the working directory is more robust?

**Comment by gaborcsardi** [comment]
Maybe there is a way to quote it, but I did not manage to get it working. It is possible that we would  need to quote and pass `windows_verbatim_args` down to processx.

So yeah, changing the working directory is much simpler.
