### ISSUE TITLE
vignette build fails with devtools::build but not with devtools::build_vignette

### ISSUE THREAD

**Issue by wolski** [r-lib/devtools#1867]
Not sure if this is an issue related to devtools however, when building the vignettes for the first time (empty inst/doc directory) with devtools::build()

It fails with:

```
** building package indices
** installing vignettes
   ‘Grp2Analysis.Rmd’ using ‘UTF-8’ 
Error in eval(x, envir = envir) : object 'child_docs' not found
Warning in readLines(if (is.character(input2)) { :
  cannot open file './child_docs': No such file or directory
Quitting from lines 390-391 (./child_docs) 
Error in readLines(if (is.character(input2)) { : 
  cannot open the connection
ERROR: installing vignettes failed
* removing ‘/tmp/RtmpsSoEaT/Rinst302f232b112b/SRMService’
      -----------------------------------
ERROR: package installation failed
```

While when building it with devtools::build_vignettes() all is well.
re-running devtools::build after build_vignettes succeeds.

The source code of the package and the failing vignette can be found here:
<https://github.com/protViz/SRMService/blob/master/vignettes/Grp2Analysis.Rmd>

Thank you. 

PS. Love using devtools

**Comment by jimhester** [comment]
I am almost 100% sure this is an issue with your package rather than an issue with devtools.

Likely the path to `child_docs` is not being constructed as you expect.

Try something like

```r
system.file("ParametrizedReportsChild", child_docs, package = "SRMService")
```

I unfortunately cannot reproduce the error on my machine, I get an error when building a different vignette.

```
Quitting from lines 109-124 (Run_Tidy_MSqRob_Analysis.Rmd)
Error: processing vignette 'Run_Tidy_MSqRob_Analysis.Rmd' failed with diagnostics:
Error: `x` is not a matrix object
```

Also I needed to make the following changes to correctly install all dependencies for the package

```diff
diff --git a/DESCRIPTION b/DESCRIPTION
index 7d3bbec..08ba6a9 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -68,6 +68,13 @@ Collate:
     'zzz.R'
 Suggests:
     testthat,
+    ggplot2,
     knitr,
-    rmarkdown
+    readxl,
+    rmarkdown,
+    MSqRob
+Remotes:
+    protViz/bibliospec,
+    statOmics/MSqRob
+BiocViews:
 VignetteBuilder: knitr
```

**Comment by wolski** [comment]
Dear Jim,
Thank you a lot. That indeed solves the problem. Have a great Day.
regards

Witek

**Comment by wolski** [comment]
Dear Jim,

I did some further testing.

I implemented that change and 
child_docs <- system.file("ParametrizedReportsChild",child_docs,package = "SRMService")
updated the DESCRIPTION

but executing
```
devtools::clean_vignettes()
devtools::build()
```
Is still crashing with:

```
Error in eval(x, envir = envir) : object 'child_docs' not found
Warning in readLines(if (is.character(input2)) { :
  cannot open file './child_docs': No such file or directory
Quitting from lines 387-388 (./child_docs) 
Error in readLines(if (is.character(input2)) { : 
  cannot open the connection
ERROR: installing vignettes failed
```

while 

```
devtools::clean_vignettes()
devtools::build_vignettes()
devtools::build()
```

builds with no problem.

I did test it on two systems.
Microsoft R Open 3.5.1
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2018 Microsoft Corporation

And:

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

Both systems have exactly the same behavior.

Kind regards
Witek

**Comment by jimhester** [comment]
This is not a devtools issue. You should not need to build your vignettes before building the package. The way you are specifying the child documents is wrong, I unfortunately do not have the time to figure out how.

I would suggest if you need further help with your vignettes to post the issue at community.rstudio.com
