### ISSUE TITLE
use_data() is not deprecated

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1871]
I think it should be, in favour of `usethis::use_data()`

**Comment by jimhester** [comment]
So I agree it should be, the comments explain why it is not formally deprecated

https://github.com/r-lib/devtools/blob/75e1dbe6faf0b9abfe9cbfa57d036e537a983daf/R/infrastructure.R#L87-L95

I guess conflicted then complains about this function, which is why you have opened the issue...

**Comment by hadley** [comment]
Oh I didn't notice it is a straightforward alias; conflicted should be eliminating the conflict a different way 😬

**Comment by hadley** [comment]
Now in https://github.com/r-lib/conflicted/issues/25

**Comment by hadley** [comment]
Oh the problem is that `use_data()` isn't re-exported, as you have:

```R
use_data <- usethis::use_data
```

This copies `usethis::use_data()` at package build time.
