### ISSUE TITLE
check_cran deprecation

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/devtools#1872]
This is wrong imo:  https://github.com/r-lib/devtools/blob/62970aa7783a721089fc71ab5a090ece0614b146/R/check-cran.R#L12

revdepcheck package,  maybe?  But that's not on CRAN.... :(

**Comment by jimhester** [comment]
Yes, it should be revdepcheck sorry, it not being on CRAN is fine, people can install from GH if they need it.
