### ISSUE TITLE
Nicer check output

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/devtools#1874]
This is not urgent, especially the build part, but maybe we can consolidate the title rules.

This  is with devtools:
<img width="762" alt="screen shot 2018-09-19 at 1 06 35 pm" src="https://user-images.githubusercontent.com/660288/45752406-400d2480-bc0d-11e8-80de-dd0d20f91427.png">

This  is with  rcmdcheck:
<img width="762" alt="screen shot 2018-09-19 at 1 07 20 pm" src="https://user-images.githubusercontent.com/660288/45752416-469b9c00-bc0d-11e8-99cc-18db104a289d.png">

**Comment by jimhester** [comment]
So we should only need changes to pkgbuild (https://github.com/r-lib/pkgbuild/pull/47). No changes to rcmdcheck needed thankfully.
