### ISSUE TITLE
Mac 10.13.6 returns "Could not find build tools necessary to build..." even with command line tools installed and built

### ISSUE THREAD

**Issue by jiaqitony** [r-lib/devtools#1879]
```
> devtools::install_github("RGLab/Rtsne.multicore")
Downloading GitHub repo RGLab/Rtsne.multicore@master
from URL https://api.github.com/repos/RGLab/Rtsne.multicore/zipball/master
Installation failed: Could not find build tools necessary to build Rtsne.multicore
```

I have installed command line tools and built them. All are up to date as well.

**Comment by jiaqitony** [comment]
This is my path: 
/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
and the veirsion of devtool is 1.13.6

**Comment by jimhester** [comment]
And what does `R CMD config CXX11` run in the terminal give you?

**Comment by jiaqitony** [comment]
clang++

**Comment by jimhester** [comment]
And what does `which clang++` give you?

**Comment by jiaqitony** [comment]
/usr/bin/clang++

**Comment by jimhester** [comment]
Are you running this within RStudio or from the command line?

**Comment by jiaqitony** [comment]
I am running this within RStudio.

**Comment by jimhester** [comment]
What does `getOption("buildtools.check", NULL)` return? and what version of RStudio?

**Comment by jiaqitony** [comment]
```function (action) 
{
    if (identical(.Platform$pkgType, "mac.binary.mavericks")) {
        .Call("rs_canBuildCpp")
    }
    else {
        if (!.Call("rs_canBuildCpp")) {
            .rs.installBuildTools(action)
            FALSE
        }
        else {
            TRUE
        }
    }
}
<environment: 0x105997220>```
version: 1.1.456

**Comment by jiaqitony** [comment]
```
function (action) 
{
    if (identical(.Platform$pkgType, "mac.binary.mavericks")) {
        .Call("rs_canBuildCpp")
    }
    else {
        if (!.Call("rs_canBuildCpp")) {
            .rs.installBuildTools(action)
            FALSE
        }
        else {
            TRUE
        }
    }
}
<environment: 0x105997220>
```
version: 1.1.456

**Comment by jimhester** [comment]
And what happens when you try to run the function? e.g. 

```r
getOption("buildtools.check", NULL)("Building R package from source")
```

**Comment by jimhester** [comment]
This must be a bug in RStudio's detection then, I am not sure what is going wrong. @kevinushey any thoughts?

**Comment by kevinushey** [comment]
Are you a macOS user? Did you recently update to Mojave? If so, to install packages from source you'll need to reinstall command line tools and also install a special package that ensure C / C++ standard library headers get reinstalled at `/usr/include`.

```
installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```

This was documented in the Xcode 10 release notes: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes, but it's definitely an annoying change (if this is indeed the issue you're having)

**Comment by kevinushey** [comment]
You can also try running `/usr/bin/clang++ --version` from the command line; you should be prompted if you do need to install command line tools.

**Comment by jiaqitony** [comment]
I am still on High Sierra.
This is what is returned.
```
Apple LLVM version 10.0.0 (clang-1000.10.43.1)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jimhester** [comment]
I don't believe this is a devtools specific issue, I would suggest if you continue to have problems you post on the [community site](http://community.rstudio.com) or in the [RStudio IDE issue tracker](https://github.com/rstudio/rstudio/issues)

**Comment by EDYAC** [comment]
options(buildtools.check = function(action) TRUE)
this seem to fix it?
