### ISSUE TITLE
produce a `NOTE` when vignette build time exceeds 10 minutes

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1881]
If vignette build time exceeds 10 minutes, `CRAN` maintainers add `--no-vignettes` flag to the daily checks (https://cran.r-project.org/web/checks/check_results_ggstatsplot.html). 

I think it will be a good idea for `devtools` to produce a `NOTE` when this happens because the package is either going to be rejected or going to have this flag, none of which is anticipated by a newcomer.

**Comment by jimhester** [comment]
We have no way to know how long a vignette is going to take to build on CRANs machines, which are under very different load and specifications than your local machine.
