### ISSUE TITLE
`devtools::build_vignettes()` creates extra folders

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1882]
I am using the development version of `devtools` and when I ran-
```
devtools::build_vignettes(dependencies = FALSE,
                          upgrade = FALSE,
                          install = FALSE)
```
it produced two new folders (called `Meta` and `doc`) and also added them to `.Rbuildignore` and `.gitignore`. 

I was a bit confused by this because this is the first time that this command behaved this way, so I am guessing this is a new feature. 

Just wanted to understand: Why is it creating these new folders?

**Comment by jimhester** [comment]
https://github.com/r-lib/devtools/pull/1824
