### ISSUE TITLE
introducing function to check web only vignettes

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#1886]
I have a data visualization package and, as much as I wish to write detailed vignettes with a lot of plots, I constantly run into the issue of package size being bigger than 5MB, which is something `CRAN` doesn't really like.

Of late, one solution I have found is to write vignettes in a subdirectory and host them on the `pkgdown` website articles (e.g., https://github.com/IndrajeetPatil/ggstatsplot/tree/master/vignettes/web_only). But the risk is that the code in this subdirectory is not checked by `devtools` and so some mistakes can slip through.

Is there any possibility to have a function that can also check these vignettes in such a subdirectory?

**Comment by jimhester** [comment]
Possibly, but the vignette checking code is part of `R CMD check`, which is part of base R and difficult to extend. I think the problem can be at least partially solved by running pkgdown locally or setting up travis to update the pkgdown site on each commit.
