### ISSUE TITLE
spelling: allow use of WORDLIST if found

### ISSUE THREAD

**Issue by tbates** [r-lib/devtools#1889]
`devtools` initially used the `spelling` package, which takes advantage of a WORDLIST file if one is found in `inst/`

`hunspell` (the current spelling support) doesn't, and its equivalent mechanism (`ignore`) defaults to an empty vector.

_OBTAINED_: As a result, `devtools:: release` can't use a package-specific dictionary, and catches a big list of false positives each time (or to it simply being turned off by setting to `NULL`).

_DESIRED_: Allow `release()` and `spell_check()` to detect the presence of `inst/WORDLIST` and use it (i.e., read in, parse into a vector of words, and pass to `ignore=`) unless `ignore = NULL`.

https://github.com/r-lib/devtools/issues/1645

**Comment by jimhester** [comment]
The devel version of devtools does use the spelling package, you seem to be using the CRAN version of devtools.

https://github.com/r-lib/devtools/blob/95ba7657d7da116d08e900a5b5078f3a47d038a5/R/spell-check.R#L19

**Comment by tbates** [comment]
OK: so going forward we can use `spelling::spell_check_package` (if `devtools::spell_check` just calls it. Makes sense.
Sorry for the false alarm,
t

PS: I see the Rd for `spell_check` still refers to hunspell
> Other languages require installation of a custom dictionary, see the hunspell vignette

PPS: I guess y'all have made the cost/benefit analysis, but backward-incompatible changes in devtools make it hard to keep up with: When the dev version gets in a non-functional state, one can't fall back on the CRAN version as dependent packages may compile on either devtools dev OR devtools CRAN, but not both as the changes break functions that depend on devtools... 

e.g. Since the June CRAN release, the dev version dropped the `spell` parameter from release.
