### ISSUE TITLE
should `build_win` use `manual = TRUE`?

### ISSUE THREAD

**Issue by topepo** [r-lib/devtools#1890]
`generics` has some `\Sexpr` in the man files but the `build_win` process came up with the note: 

> Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.

**Comment by gaborcsardi** [comment]
`check_win()` should probably call build with `manual  = TRUE` here:
https://github.com/r-lib/devtools/blob/95ba7657d7da116d08e900a5b5078f3a47d038a5/R/check-win.R#L60

**Comment by jimhester** [comment]
The devel version of devtools passes `...` to `pkgbuild::build()`, so you just need to specify `manual = TRUE` in this case.

I am not really sure we should necessarily change the default as building the manual requires a LaTeX installation, which not everyone will have.

**Comment by gaborcsardi** [comment]
AFAIK only if the package has  `\Sexpr`, in which case you do need latex. For `manual = FALSE` it just omits the `--no-manual` flag, and `R CMD build` decides  automatically:
```
❯ R  CMD build --help
Usage: R CMD build [options] pkgdirs

Build R packages from package sources in the directories specified by
‘pkgdirs’

Options:
  -h, --help		print short help message and exit
[...]
  --no-manual           do not build the PDF manual even if \Sexprs are present
```

**Comment by gaborcsardi** [comment]
Thanks!
