### ISSUE TITLE
Can devtools::check() fail on errors?

### ISSUE THREAD

**Issue by akubisch** [r-lib/devtools#1894]
Hi!
We're developing some R packages using gitlab and gitlab CI. Now it would be very useful if the pipeline could fail in case check() detects errors - unfortunately this seems not possible, yet - or am I maybe missing some setting? For devtools::test() I can set the reporter to "fail", so at least I can use unit tests in the CI process. check(), however, always returns "Job succeeded", independent of the number of errors.

I would appreciate any help in further improving our development processes :-)

Thanks a lot in advance!

**Comment by jimhester** [comment]
Yes, this is already implemented, see the `error_on` argument in the devel version.

**Comment by akubisch** [comment]
Great, thank you! Now I need to find out why github does not inform me about updates...
