### ISSUE TITLE
install_github("repository", build_vignettes = TRUE)

### ISSUE THREAD

**Issue by lindbrook** [r-lib/devtools#1896]
With devtools 2.0.0, `devtools::install_github("repository", build_vignettes = TRUE)` no longer builds the vignettes. 

`devtools::install("repository", build_vignettes = TRUE)` does build the vignettes.

I've tried using `remove.packages("package")` first and by using `remotes::install_github("repository", build_vignettes = TRUE)`. Same results.  

Has the syntax changed?

After downgrading to devtools 1.13.6, `devtools::install_github("repository", build_vignettes = TRUE)` does builds the vignettes.

**Comment by jimhester** [comment]
Yes, remove `--no-build-vignettes` from the `build_opts` to build the vignettes. e.g.

```r
devtools::install_github("foo/bar", build_opts = c("--no-resave-data", "--no-manual"))
```

**Comment by DanielEWeeks** [comment]
For my vignette to build, I had to add the 'build_vignettes = TRUE' option

`install_github("foo/bar", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)`

**Comment by ferroao** [comment]
the build_ops works in windows, and the build_vignettes works in linux.
