### ISSUE TITLE
github_auth() uses httr::authenticate() wrongly

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/devtools#1902]
It seems the order of `token` and `"x-oauth-basic"` should be opposite.

https://github.com/r-lib/devtools/blob/7575090e51f94739a70b9280c49aecb7a4131d65/R/github.R#L5

But are these functions in `github.R` no longer used? If so, please close this issue.

**Comment by jimhester** [comment]
They are not used now except for in `source_gist()`, but actually the way the GitHub API works if you are using basic authentication with a Oauth token the token can be in either the username or the password https://developer.github.com/v3/auth/#via-oauth-tokens, so this is actually working as intended.

**Comment by yutannihilation** [comment]
> a Oauth token the token can be in either the username or the password

Oh, wow! I don't think it's documented, but I confirmed `"x-oauth-basic"` is a special password that let us use the token as the username... Thanks.
