### ISSUE TITLE
install_bitbucket compatible with subdir

### ISSUE THREAD

**Issue by paulmartins** [r-lib/devtools#1904]
I seemed to have an issue with the latest version of devtools 2.0.0
I used to be able to install my package from the github repo like this

`devtools::install_bitbucket(repo = "username/repo"
                                          ,auth_user = "my_git_user" 
                                          ,password = "my_git_password" 
                                          ,ref = "my_branch"
                                          ,subdir = "PathTo/Package1")`

It recently failed with this kind of error

`cannot open URL 'https://my_git_user:my_git_pwd@api.bitbucket.org/2.0/repositories/username/repo/src/my_branch/PathTo/Package1DESCRIPTION'`

It looks to me that a `/` is missing at the end of the url, between the package name and the DESCRIPTION. I could not find a publicly available repository where the packages are located in subdirectories otherwise I would have checked the `subdir` still works. 

Any advice on whether what I am doing is right would be much appreciated :)

Thanks,
Paul

**Comment by jimhester** [comment]
This was previously reported and is fixed by https://github.com/r-lib/remotes/issues/220
