### ISSUE TITLE
could 'install_deps()' work within project sub-directory?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/devtools#1905]
E.g.

``` r
> devtools::install_deps()
Warning in read.dcf(path) :
  cannot open compressed file '/Users/kevin/r/pkg/Rcpp/inst/unitTests/DESCRIPTION', probable reason 'No such file or directory'
Error in read.dcf(path) : cannot open the connection
```

I was briefly working in the `inst/unitTests` folder for Rcpp; discovered I was missing some development dependencies, and was hoping an `install_deps()` would do the trick. It'd be nice if this function looked upwards for a package root + associated `DESCRIPTION` file.

**Comment by jimhester** [comment]
This is how it used to work when `install_deps()` was in devtools, but the functions in remotes don't do this so we no longer have this functionality.

One way to get it back is to use `devtools::package_file()`, e.g.

`devtools::install_deps(devtools::package_file())`

**Comment by kevinushey** [comment]
Do you think `devtools` / `remotes` should do this? Could they use `rprojroot::find_package_root_file()` as a default? Or should I just learn to live with the change in behavior?
