### ISSUE TITLE
Intermittently ignoring GITHUB_PAT?

### ISSUE THREAD

**Issue by mhines-usgs** [r-lib/devtools#1906]
I am seeing intermittent failures during Travis builds with this error message:

```
1.16s$ Rscript -e 'devtools::install_github("usgs-r/gsplot@v0.8.1")'
Error: HTTP error 403.
  API rate limit exceeded for 35.192.187.174. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
  Rate limit remaining: 0/60
  Rate limit reset at: 2018-10-26 17:02:34 UTC
  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Add `GITHUB_PAT` to your travis settings as an encrypted variable.
Execution halted
The command "Rscript -e 'devtools::install_github("usgs-r/gsplot@v0.8.1")'" failed and exited with 1 during .
```
Full log here: https://travis-ci.org/USGS-R/repgen/builds/446760948?utm_source=github_status&utm_medium=notification

I do have a GITHUB_PAT token associated with this job, and randomly it works fine and prints the line ~ 900
```
Setting environment variables from repository settings
$ export GITHUB_PAT=[secure]
```
Am I doing something wrong that could randomly trigger this? 

per the failed log, mentioning @jeroen and @jimhester

**Comment by jimhester** [comment]
This is fixed by https://github.com/r-lib/remotes/commit/c0aa8682b55936e3f28f1dbae2b5e983341ff3d4, we plan to have a release of remotes today to fix this.
