### ISSUE TITLE
devtools check new behavior with folder and archive not cleaned?

### ISSUE THREAD

**Issue by BenoitLondon** [r-lib/devtools#1908]
Whenn running ctrl+shift+e (check package) in rstudio using devtools::check it creates a folder pkgname.Rcheck and pkgname_version.tar.gz in the upper directory.
If I change some code to alter the check it looks like it uses the old code inside the folder or the archive.

How do I disable this folder creation or at least clean it on fail and success?
There is a Rstudio  option in tools/global options/Packages `cleanup output after successful R CMD check` but it looks like it does not work and it definitely does not clean on failure...

So my workflow used to be 1)run check 2)fix problems and loop but now I have to manually delete this folder and archive to make it work otherwsie it uses old code

Any solution please?

**Comment by jimhester** [comment]
This is fixed by https://github.com/r-lib/rcmdcheck/pull/84, you can install the development version of rcmdcheck to fix this or wait until a new version is released on CRAN (which should be soon).

cc @gaborcsardi

**Comment by BenoitLondon** [comment]
thanks!
