### ISSUE TITLE
check() and build() hang if DESCRIPTION file is malformed

### ISSUE THREAD

**Issue by ms609** [r-lib/devtools#1913]
I'm running devtools 2.0.1 on R3.5.1, Windows 10.

When I run `check()` or `build()`, R hangs at 
```
    v  checking for file 'C:\path\to\package/DESCRIPTION' ... 
```

The terminal looks "busy", but never progresses.  This occurs whether I run the function from the console, or from within RStudio.

When I run `R CMD check` in the Windows Command Prompt, I receive an error message and `CMD check` completes:

```
C:\Research\R>R CMD check Quartet
* using log directory 'C:/Research/R/Quartet.Rcheck'
* using R version 3.5.1 (2018-07-02)
* using platform: i386-w64-mingw32 (32-bit)
* using session charset: ISO8859-1
* checking for file 'Quartet/DESCRIPTION' ... ERROR
Required fields missing or empty:
  'Author' 'Maintainer'
* DONE

Status: 1 ERROR
```
The problem with the [description file](https://raw.githubusercontent.com/ms609/SlowQuartet/f75d0bf89359581b343f9a9e1868dc06dd8fc08f/DESCRIPTION) turns out to be that I'd `Suggests:`ed a package, rtqdist, that is not available on CRAN, without specifying a path to the package under the `Remotes:` field.  

I would expect devtools to report this as an error (as happened using `R CMD check` once I'd added a dummy `Author:` and `Maintainer:` field to the DESCRIPTION file, rather than hanging.

**Comment by jimhester** [comment]
Please try installing the development version of rcmdcheck and see if that fixes your issue.

https://github.com/r-lib/rcmdcheck

**Comment by ms609** [comment]
This seems to have done the job, thank you.

**Comment by ms609** [comment]
Correction: this seems to have fixed the issue with

**Comment by ms609** [comment]
It initially looked as though this had resolved the issue, but I believe I was mistaken -- I've been making other changes to the package and, when this caused `check` to compile the package, and assumed that the issue had been fixed.  But now that the C code is compiling again, `check` gets as far as 
```
    v  checking for file 'C:\path\to\package/DESCRIPTION' ... 
```
and then gets stuck again.

**Comment by ms609** [comment]
Digging into this further, it seems that the issue relates to file copying or access issues.  My package contained a `data-raw` folder, listed in `.Rbuildignore`, but containing many thousand files.  Now that I've deleted the folder, `check()` still sticks for a long time after `checking for file ... DESCRIPTION`, but does eventually proceed to

```
-  preparing 'Quartet': (1m 35.8s)
```

Presumably this "preparing" stage was previously taking upwards of 30 minutes, leading me to interpret the process as hanging.  

Would it be desirable / possible to display the `- preparing 'PACKAGENAME':` message sooner, rather than waiting until it was complete?  This would give users an indication as to why the process appears to have stalled.
