### ISSUE TITLE
Failed to connect to api.github.com

### ISSUE THREAD

**Issue by PatBall1** [r-lib/devtools#1915]
I am unable to use `devtools::install_github()` to install packages.
Every time I try I receive the following error. I've tried with firewall turned off. Please help!
```
> devtools::install_github("dkahle/ggmap")
Error in curl::curl_fetch_memory(url, handle = h) : 
  Failed to connect to api.github.com port 80: Timed out
```

**Comment by briholt100** [comment]
did you find a cause and fix for this?

**Comment by PatBall1** [comment]
Yes, thanks. The problems was that I didn't have curl properly set up in my path. It worked fine once I had corrected this.

**Comment by anitasgiraldo** [comment]
How did you properly set  up the path ? I am having the same problem but don't know how to fix it.

**Comment by PatBall1** [comment]
> How did you properly set up the path ? I am having the same problem but don't know how to fix it.

Please see the link below. Good luck!
https://develop.zendesk.com/hc/en-us/articles/360001068567-Installing-and-using-cURL#install

**Comment by Maiae** [comment]
There seems to be an issue with `curl` and `api.github.com` specifically.
My workaround was to change the `host` argument in `devtools::install_github` like the example below:

``` r
devtools::install_github("snowflakedb/dplyr-snowflakedb", host = "https://api.github.com")
```

**Comment by jjzmajic** [comment]
@Maiae 's solution did not work for me, but what I realized is even though I was behind a corporate proxy, and I had `export HTTP(S)_PROXY=xyz` set, R did not understand it when it was capitalized. So what you want do is add `export http(s)_proxy=xyz` to your `.basrc` or wherever, source it, and then start `R`. Things should work with no issues after that.

**Comment by ArPharazon** [comment]
I had the same issue on windows behind corp proxy.  
Resolved by setting the **http_proxy** and **https_proxy** environment variables.

**Comment by haseebmahmud** [comment]
> I had the same issue on windows behind corp proxy.
> Resolved by setting the **http_proxy** and **https_proxy** environment variables.

Could you please explain what did you do in detail?

**Comment by jjzmajic** [comment]
> > I had the same issue on windows behind corp proxy.
> > Resolved by setting the **http_proxy** and **https_proxy** environment variables.
> 
> Could you please explain what did you do in detail?

On Linux you would just put `export http_proxy=xyz` and `export https_proxy=xyz` (all lowercase) in yor shell startup file like your `.bashrc` and then `source ~/.bashrc` from your shell (there is no need for this step to be repeated as it will be automatically sourced on login. 

On windows follow this guide https://www.tenforums.com/tutorials/121664-set-new-user-system-environment-variables-windows.html#option1. A GUI makes everything unnecessarily complicated.
