### ISSUE TITLE
no min version for ‘rhub’ >= * must be installed for this functionality.

### ISSUE THREAD

**Issue by tbates** [r-lib/devtools#1916]
if the user hasn't installed the rhub package, the question they are given is not well-formed. Guessing this should be 

    ‘rhub’ >= 1.01 must be installed for this functionality.

or similar?
Instead the user sees

    ‘rhub’ >= * must be installed for this functionality.

**Comment by juliasilge** [comment]
I'll take this one! Is `1.01` the correct version requirement?
