### ISSUE TITLE
build_vignettes() output at wrong file directory

### ISSUE THREAD

**Issue by strengejacke** [r-lib/devtools#1918]
When I use `devtools::build_vignettes()`, the directory `docs` in `inst` is removed, but the new directory `docs` is located in the root directory of the package (insted of inside `inst`). When re-building the package, vignettes are not available.

**Comment by jimhester** [comment]
This is the expected behavior, please see https://github.com/r-lib/devtools/pull/1824 for a discussion of why the change was made.
