### ISSUE TITLE
devtools::check() gives error on missing License field, but License field is not missing

### ISSUE THREAD

**Issue by rsetienne** [r-lib/devtools#1920]
When running devtools::check(), I get

E checking for file 'secsse/DESCRIPTION'Required field missing or empty:
'License'

However. the License field is present in the description file (GPL-3).

**Comment by jimhester** [comment]
Sorry I cannot reproduce this, please provide an example package.

**Comment by HughParsonage** [comment]
I can reproduce this, though perhaps an RStudio issue?

1. Create a package in RStudio with a broken License field.
2. Click `Check` in the Build tab.
3. Fix the License field.
4. Run `Check` again. The error persists.

**Comment by jimhester** [comment]
Please be sure to update the rcmdcheck package, there is a known bug in v1.3.1 and earlier versions that causes old tarballs to be used when run as RStudio does.
