### ISSUE TITLE
load_all() no longer works with package objects (as created by as.package)

### ISSUE THREAD

**Issue by kevinushey** [r-lib/devtools#1923]
``` r
setwd(tempdir())
usethis::create_package("test")
#> ✔ Setting active project to '/private/var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T/Rtmp7dXsc3/test'
#> ✔ Creating 'R/'
#> ✔ Creating 'man/'
#> ✔ Writing 'DESCRIPTION'
#> ✔ Writing 'NAMESPACE'
pkg <- devtools::as.package("test")
devtools::load_all(pkg)
#> Error in path.expand(path): invalid 'path' argument
```

<sup>Created on 2018-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

AFAIK this worked with devtools 1.13.6.

**Comment by jimhester** [comment]
Is there a reason you need this?

**Comment by kevinushey** [comment]
It's a pattern we were using in the IDE:

https://github.com/rstudio/rstudio/pull/3876

It made it easier to (only using devtools) load a package when given the path to a test file living within that package.

**Comment by hack-r** [comment]
I noticed this as well. It's useful.

**Comment by kevinushey** [comment]
Thanks!
