### ISSUE TITLE
check_win*() wants to remove vignettes-folder

### ISSUE THREAD

**Issue by strengejacke** [r-lib/devtools#1924]
I guess this one is related to https://github.com/r-lib/devtools/issues/1918 and https://github.com/r-lib/devtools/pull/1824, however, this behaviour is somewhat annoying.

I have vignettes with long computational time to build (Bayesian models), and CRAN policies ask to keep running-time for tests and vignette building short. So I build the vignettes locally and use a switch in the knitr-option that prevents re-building the vignettes on CRAN after submission - so CRAN takes the compiled vignettes from `inst/doc`.

However, this directory is removed each time I run `build_vignettes()` or `check_win*()`. 

My question is, could _removing_ the folder be optional, and not the only and default option? For me, using devtools is now useless to some extent, unfortunately.

**Comment by jimhester** [comment]
The folder is only removed if you build the vignettes, during the check.

e.g. build your package into a tarball with `pkgbuild::build()` then use that built package as the input to `check_win*()`.

**Comment by strengejacke** [comment]
Ok, I will try this. I was a confused because there's now a two-step-action required when using `devtools::check_win*()` (not on a source tarball) for packages, first to decide if you really want to check and second if the folder should be removed.
