### ISSUE TITLE
devtools::build errors

### ISSUE THREAD

**Issue by wolski** [r-lib/devtools#1925]
Hello,

I observe the following error:

```
r> devtools::build()
Building the package will delete...
  'C:/Users/wolski/prog/RmarkdownVignetteProblem/inst/doc'
Are you sure?

1: Yes
2: No

Selection: 2
Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  no("wd") || is_string(wd) is not TRUE
> 
```

To reproduce it one can use the following minimal package (no dependencies) on:

https://github.com/wolski/RmarkdownVignetteProblem

System: Windows 10 all updates installed.

R version 3.5.1 (2018-07-02) -- "Feather Spray"
> packageVersion("devtools")
[1] ‘2.0.1’

best regards
Witek

**Comment by jimhester** [comment]
Sorry I cannot reproduce this error, please make sure you have updated versions of devtools and all its dependencies.
