### ISSUE TITLE
[bug] new devtools install fails on package with rcpp

### ISSUE THREAD

**Issue by BenoitLondon** [r-lib/devtools#1928]
if I run R CMD INSTALL. on my package it works fine
if I run devtools::install() it says 

> devtools::install()
Error: Could not find tools necessary to compile a package

if I run devtools::install(quick = TRUE)` it says 

>   devtools::install(quick = TRUE)
   Running /usr/lib64/R/bin/R CMD INSTALL /XXXXX --install-tests --no-docs \
  --no-multiarch --no-demo 
    installing to library ‘/usr/lib64/R/library’
    installing *source* package ‘XXXXX’ ...
    libs
    make: the '-j' option requires a positive integer argument

**Comment by BenoitLondon** [comment]
Ok I had MAKE='make -j' in my .Renviron file which works fine with R base commands but apparently devtols commands conflict with the -j
setting MAKE='make' in the .Renviron file make devtools::install work. So the question is how to tell R to compile in parallel without bugging devtools?

**Comment by jimhester** [comment]
The proper way to pass arguments to make is using [MAKEFLAGS](https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/The-Make-Macro-MAKEFLAGS.html), e.g.

`MAKEFLAGS=-j8`

**Comment by BenoitLondon** [comment]
ah thank you Jim :)

**Comment by BenoitLondon** [comment]
sorry for the newbie question again but should it be in .Renviron or Makevars?
Also I think I went for the MAKE solution because it was not getting picked 

see this [post](https://community.rstudio.com/t/is-there-a-way-to-enable-multithreading-while-installing-compiling-packages/5519)

**Comment by BenoitLondon** [comment]
ok in the .Renviron it works thanks! :)
