### ISSUE TITLE
Passing `build` arguments to `install`

### ISSUE THREAD

**Issue by cdeterman** [r-lib/devtools#1932]
Is there a way to pass `build` arguments to `install`?  I am working with a package that I want to customize the build prior to using `install`.  I'm not noticing anything in the docs and it appears that in the [code](https://github.com/r-lib/devtools/blob/master/R/install.R#L65) the `build_opts` is never able to be added to from the `install` command.

**Comment by jimhester** [comment]
In that case maybe you are better off using `pkgbuild::build()` to build the package and passing the built tarball to `remotes::install_local()` or `callr::rcmd("INSTALL")` directly.
