### ISSUE TITLE
`devtools::document()` causing DLL failure on Travis CI, but working locally

### ISSUE THREAD

**Issue by ms609** [r-lib/devtools#1940]
`devtools::document()` is currently causing my Travis testing environment to fail.

https://travis-ci.org/ms609/TreeSearch/jobs/464846191
```
    > devtools::document()
    Updating TreeSearch documentation
    Writing NAMESPACE
    Loading TreeSearch
    Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
      must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
    Calls: <Anonymous> ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo
    Execution halted
```

If I run `document()` locally and upload all generated files, the build runs okay.  I'm struggling to diagnose this, and would welcome any thoughts -- could this issue be caused by `devtools`?

**Comment by krlmlr** [comment]
This looks related to https://github.com/klutometis/roxygen/issues/822.

**Comment by krlmlr** [comment]
This should now work better with the development version of {pkgload}. Can you confirm?

**Comment by ms609** [comment]
Sorry for the delayed response. I've tried [today](https://travis-ci.org/ms609/TreeSearch/jobs/544183030), using `r_github_packages` to direct Travis to load r-lib/devtools and r-lib/pkgload.  

`devtools::document()` no longer triggers an error, but instead throws a warning:
```
Warning message:
Failed to load at least one DLL: must specify DLL via a “DLLInfo” object. See getLoadedDLLs() 
```

The warning does not stop Travis returning a success.

**Comment by jimhester** [comment]
You need to have a working shared library before trying to document, as roxygen loads the package in order to document it. So call `pkgload::load_all()` or another mechanism to compile the package before running `devtools::document()`.

**Comment by randy3k** [comment]
A current master of roxygen should fix this issue. https://github.com/r-lib/roxygen2/issues/822#issuecomment-533183162

Before a new release is made, I am using the following workaround
```
pkgbuild::compile_dll()
devtools::check()
```
