### ISSUE TITLE
devtools::install_github crashed R tough find_rtools() returned TRUE

### ISSUE THREAD

**Issue by KoichiHashikawa** [r-lib/devtools#1942]
Let me reopened issue originally posted by @luckygoh

In my case, find_devtools() gave TRUE, but whenever I tried devtools::install_github, it started installing other already installed packages such as Rcpp and crashed R.

It only happened to my when I used windows computer, but not with my Mac PC.
______________________________________________________________________
the workaround seems like not working for me. or there is something i did wrong.

I used the code below as mentioned by previously and get a `TRUE`.

but the error still occurs.

`
> find_rtools()
[1] TRUE
> devtools::install_github("sneumann/xcms")
Downloading GitHub repo sneumann/xcms@master
from URL https://api.github.com/repos/sneumann/xcms/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.5)
#Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing xcms
"C:/PROGRA~ 1/R/R-35~ 1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/UM/AppData/Local/Temp/Rtmp2LXJjL/devtools26081b46695c/sneumann-xcms-f1eecf6"  \
  --library="C:/Users/UM/Documents/R/win-library/3.5" --install-tests
*installing *source* package 'xcms' ...
** libs
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'xcms'
*removing 'C:/Users/UMSBIOTECH/Documents/R/win-library/3.5/xcms'
*restoring previous 'C:/Users/UMSBIOTECH/Documents/R/win-library/3.5/xcms'
In R CMD INSTALL
Installation failed: Command failed (1)
`

_Originally posted by @luckygoh in https://github.com/r-lib/devtools/issues/1852#issuecomment-418025187_

**Comment by jimhester** [comment]
You can put the build tools on your path explicitly with

`pkgbuild::with_build_tools(devtools::install_github("sneumann/xcms"))`
