### ISSUE TITLE
run_examples Disregards R Library Paths

### ISSUE THREAD

**Issue by DarioS** [r-lib/devtools#1945]
The documentation of `pkg` explains
> ... can be path or package name.

I input the name of a package I already installed but there is an error.

```r
> run_examples("ClassifyR")
Error: Can't find 'C:\Users\Dario\Documents\ClassifyR'
```

It doesn't seem to check the paths which are shown by `.libPaths()` to locate the package I specified. It would be useful to do for packages which are already successfully installed in a library but one of the documentation examples stops working because one of the package's dependencies has been updated and now causes a problem for the example.

Providing the absolute path to the R package works, as expected (although there are two successive greater than or equal to signs in the message about roxygen2 version).

```r
> run_examples("C:/Program Files/R/R-3.5.1/library/ClassifyR")
‘roxygen2’ >= >= 6.1.0 must be installed for this functionality.
Would you like to install it?
```

**Comment by jimhester** [comment]
This is misleading documentation, it can be a package object or a path, but not a name of an installed package. 

You can use `run_examples(inst("ClassifyR"))` to run the examples from a installed package.
