### ISSUE TITLE
check() deletes inst/doc

### ISSUE THREAD

**Issue by rvlenth** [r-lib/devtools#1946]
I enabled devtools in RStudio, then ran a package check. My package has a needed CSS file saved in `inst/doc`, but that directory is deleted by `devtools::check()`. That is really irritating...

Note: I actually tested this to make sure: Noted that `inst/doc` was present, ran `check()`, and saw it disappear.

**Comment by rvlenth** [comment]
Update: I found out what happens... It uses `pkgbuild::build()`, which has code that deletes `inst/doc`; if in interactive mode, it asks for confirmation. But RStudio's plug-in isn't interactive.

So I guess this is really an issue for **pkgbuild**, not **devtools**. I still think this is pretty nasty. Is it really necessary to delete the whole `inst/doc` directory? I'm really feeling like I can't trust **devtools** anymore.

**Comment by jimhester** [comment]
Please see https://github.com/r-lib/pkgbuild/issues/58 for discussion.
