### ISSUE TITLE
`Remotes:` in DESCRIPTION and `remotes:install_github()` not building vignettes

### ISSUE THREAD

**Issue by stefanocoretta** [r-lib/devtools#1947]
This is related to #1578. I have a remote dependency specified with `Remotes:` in the DESCRIPTION file of one of my packages, but when this package is installed, the vignettes of the remote dependency are not installed (the dependency installs fine).

Is there a workaround?

**Comment by jimhester** [comment]
I think now using `devtools::install_github(build_vignettes = TRUE)` should be passed down to dependencies. If not please open an issue in the [remotes repository](https://github.com/r-lib/remotes/issues).
