### ISSUE TITLE
Failure "fs" and "usethis" dependencies when installing devtools in macOS Mojave 10.14.2

### ISSUE THREAD

**Issue by NicolaGiordano** [r-lib/devtools#1950]
I have been trying to install some R packages that I can run in Jupiter in my Mac laptop but I often come across a **non-zero exit** status

This is the error I get when I operate from R within the Terminal shell:

`install.packages('devtools')`
`also installing the dependencies ‘fs’, ‘usethis'`
`* installing *source* package ‘fs’ ...`
`** package ‘fs’ successfully unpacked and MD5 sums checked`
`** libs`

`configure: error: in /private/var/folders/93/h0b_40jx1yl2f6_vsv8vrb1r0000gn/T/RtmpOraT36/R.INSTALL162215199f03/fs/src/libuv': configure: error: C compiler cannot create executables`
`See 'config.log' for more details make: *** [Makevars:32: libuv/Makefile] Error 77`
`ERROR: compilation failed for package ‘fs’`
`* removing ‘/anaconda3/lib/R/library/fs’`
`ERROR: dependency ‘fs’ is not available for package ‘usethis’`
`* removing ‘/anaconda3/lib/R/library/usethis’`
`ERROR: dependency ‘usethis’ is not available for package ‘devtools’`
`* removing ‘/anaconda3/lib/R/library/devtools’`

`The downloaded source packages are in ‘/private/var/folders/93/h0b_40jx1yl2f6_vsv8vrb1r0000gn/T/Rtmp9rFCVe/downloaded_packages’
Updating HTML index of packages in '.Library'`
`Making 'packages.html' ... done
Warning messages:
1: In install.packages("devtools") :
  installation of package ‘fs’ had non-zero exit status
2: In install.packages("devtools") :
  installation of package ‘usethis’ had non-zero exit status
3: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status`

=========

I was wondering if the issue relates to a C compiler and that's where I get lost... how do I configure my machine to install devtools? Thank you for your support

**Comment by jimhester** [comment]
This is an issue with anaconda, not with devtools. I would suggest you raise an issue with their help resources (https://www.anaconda.com/community/)

In general you will run into fewer installation issues by avoiding use of anaconda for R packages.
