### ISSUE TITLE
devtools::install_github("repo/xyz") does not install vignettes

### ISSUE THREAD

**Issue by mkarikom** [r-lib/devtools#1954]
What is the recommended way to install packages from github so that vignette(package = 'xyz') returns the vignettes for package xyz?

**Comment by jimhester** [comment]
By default all `install_github()` functions have `--no-build-vignettes` in the `build_opts` argument, because many packages take a long time to build the vignettes. If you want to build the vignettes simply remove this option, e.g.

```r
install_github("foo/bar", build_opts = c("--no-resave-data", "--no-manual"))
```

**Comment by jennybc** [comment]
Related to #2016

**Comment by jimhester** [comment]
remotes 2.1.0 re-added the `build_vignettes` argument, so `install_github("foo/bar", build_vignettes = TRUE)` will build vignettes when installing.

devtools also now uses ellipsis, so specifying invalid (or removed) arguments will now result in an error rather than being silently ignored.
