### ISSUE TITLE
Relative path breaks durting check() but not in test()

### ISSUE THREAD

**Issue by Fazendaaa** [r-lib/devtools#1957]
Hi,

My package, as the title of this issue says, breaks the testthat testing when running `check()` but it works just fine when running `test()`. The use of relative paths is to fetch pictures stored in the `extdata/` folder of the package to run against some tests, I think that the problem is really this because of the following line that is printed when running the check call:

```
R CMD check results
1 error  | 0 warnings | 1 note 
checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  [REMOVED LINES]
  7: get_reader(file)(file)
```

Unfortunately, I cannot share the code here due to some concerns about its content. Is there any way that I could debug this by myself trying to find how to fix this? Or allow printing a `getwd()` call inside the function that calls this file -- right now this approach is not working, maybe the output is silent and I don't know how to enable a "debug mode".

Thank you guys for this awesome package :)

**Comment by jimhester** [comment]
Use `system.file()` to access the content and it should work in both cases.

**Comment by Fazendaaa** [comment]
Thanks, @jimhester :)
