### ISSUE TITLE
Error when running devtools::release() or devtools::submit_cran()

### ISSUE THREAD

**Issue by jrosen48** [r-lib/devtools#1958]
Hi, when I run `devtools::release()` (or `devtools::submit_cran()`), the following error is returned:

`Submitting file: /var/folders/zn/9_h784cn6t5b2tchsgx4v2p00000gn/T//RtmpXyITUe/tidyLPA_0.2.4.tar.gz
File size: 240.9 Kb
Uploading package & comments
Error in upload_cran(pkg, built_path) : Not Found (HTTP 404).`

The package is available here: [https://github.com/jrosen48/tidyLPA](https://github.com/jrosen48/tidyLPA)

Of course, I did check that I have Internet access--and I'm posting here from the same computer I used to run these commands.

**Comment by jimhester** [comment]
> The package submission system will remain offline until Jan 2nd 2019. 
Reasons being CRAN team vacation and maintenance work.

> Happy holidays and thank you for your understanding.

https://cran.r-project.org/submit.html
