### ISSUE TITLE
devtools::check_rhub() failed in loadNamespace() for 'rjags'

### ISSUE THREAD

**Issue by LuZhangstat** [r-lib/devtools#1962]
Hi all,

I am using **devtools** to release an R package, and I got the following error report when running `devtools::check_rhub()`
<img width="603" alt="screen shot 2019-01-14 at 11 58 47 pm" src="https://user-images.githubusercontent.com/23649581/51166491-817aad00-1858-11e9-905b-fe2f2a125d6a.png">
The path of the file _00install.out_ does not exist on my laptop, so I checked the online r-hub builder and found the error messages about loading package **rjags**:
<img width="738" alt="screen shot 2019-01-15 at 12 03 30 am" src="https://user-images.githubusercontent.com/23649581/51166676-2e552a00-1859-11e9-8472-5f2d6dcc4f5e.png">
Since **rjags** is an interface to the JAGS MCMC library, the functions in **rjags** will call the JAGS MCMC library, which I think is not available on **CRAN**. Would you like to give me some suggestions so that I can pass the check_rhub test? Thanks a lot!

Best regards,

Lu

**Comment by jimhester** [comment]
If your package requires additional system libraries it is going to fail on CRAN in the same ways as it does on rhub. In any case this is not a devtools issue, so I will close this. 

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by LuZhangstat** [comment]
Sounds good. Thanks.
