### ISSUE TITLE
package ‘devtools’ is not available (for R version 3.5.2) 

### ISSUE THREAD

**Issue by gohaku** [r-lib/devtools#1963]
Hello,Sir
I am tring to install devtools on R version 3.5.2,
 "install.packages("devtools")".
And I am getting an error,package ‘devtools’ is not available (for R version 3.5.2
I tried to install devtools on Rstudio again, but I get an error when input
 library(devtools)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : Loaded the namespace ‘processx’ 3.2.0, but the required is >= 3.2.1

**Comment by NoodleGt** [comment]
You have to update `processx` package. That will fix the problem.

**Comment by gohaku** [comment]
> 
> 
> You have to update `processx` package. That will fix the problem.
thank you,the problem was fixed.

**Comment by slhck** [comment]
Note that I got this error while upgrading a set of packages from a lockfile via `packrat::restore()`:

```
...
Replacing callr (upgrade 3.1.1 to 3.2.0) ... Error: Command failed (1)

Failed to run system command:

        '/usr/lib/R/bin/R' --vanilla CMD INSTALL '/tmp/Rtmp6iCiAN/callr' --library='/home/bestnet/best-net-data-analysis/data-analyze/rscript/packrat/lib/x86_64-pc-linux-gnu/3.5.1' --ins
tall-tests --no-docs --no-multiarch --no-demo

The command failed with output:
* installing *source* package ‘callr’ ...
** package ‘callr’ successfully unpacked and MD5 sums checked
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘processx’ 3.2.1 is being loaded, but >= 3.3.0 is required
ERROR: lazy loading failed for package ‘callr’
* removing ‘/home/bestnet/best-net-data-analysis/data-analyze/rscript/packrat/lib/x86_64-pc-linux-gnu/3.5.1/callr’
In addition: Warning message:
In packrat::restore() :
  The most recent snapshot was generated using R version 3.5.3
Execution halted
```

I think it was solved by manually loading an R shell and running `install.packages("processx")`, then continuing the `packrat::restore()` operation.
