### ISSUE TITLE
install_github from a private repo in Docker throws 404

### ISSUE THREAD

**Issue by Fazendaaa** [r-lib/devtools#1964]
I'm running the following command inside my Dockerfile:
```Docker
RUN R -e "devtools::install_github('myOrg/myRepo')
```

And this throws the following:
```shell
  Not Found

  Rate limit remaining: 57/60
  Rate limit reset at: 2019-01-16 14:18:59 UTC

  
Execution halted
```

Not allowing me to add the desired package.

I've noticed that I can install it just fine this package in my machine but if I run R in sudo mode, I throws that same error. I noticed that after noticing that my Docker is in the sudo group; is there any relation between this? And if so, how do I fix it?

Thanks in advance :)

**Comment by jimhester** [comment]
If the repo is private you need to setup a GITHUB_PAT environment variable in the docker container to access it.

**Comment by Fazendaaa** [comment]
It works just fine, thanks :)
