### ISSUE TITLE
Should test()/check() warn if missing developer dependencies?

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1970]
And hint to use `install_dev_deps()`

**Comment by jimhester** [comment]
Maybe `load_all()` as well, I had to make this same suggestion to many people as well.

**Comment by hadley** [comment]
Maybe we should have a pkg_sitrep() too?

**Comment by jennybc** [comment]
This came up in today's group meeting and concluded with what I now see @Hadley had already said: we need a sitrep-type of function that reports readiness for package development, in general and with respect to the current package/project.

Does this belong in devtools or usethis? I suspect devtools? Once it exists, it is conceivable that `usethis::create_from_github()` should call this if the newly created project is a package.

**Comment by jimhester** [comment]
Ok I added a new function `pkg_sitrep()`. This is how it looks now if you have all the detectable problems. 

I think we should have people run `devtools::pkg_sitrep()` as the first thing they do when starting working on a package during the dev day.

![Screen Shot 2019-09-04 at 1 13 43 PM](https://user-images.githubusercontent.com/205275/64276416-ec771200-cf15-11e9-89ba-73e4237c2f6e.png)

**Comment by jennybc** [comment]
Looks awesome (based on glimpse above)!

What you think of calling it `dev_sitrep()`?

**Comment by jimhester** [comment]
I am fine with it, I called it `pkg_siterep()` only because @hadley mentioned that name in https://github.com/r-lib/devtools/issues/1970#issuecomment-455904628. But `dev_sitrep()` is probably better.

**Comment by jennybc** [comment]
`pkg_sitrep()` feels like it might be reporting on a specific package (probably the "current one", if well-defined) whereas `dev_sitrep()` somehow feels more related to "am I ready for package development?"
