### ISSUE TITLE
devtools::release seems to handle "NOT_CRAN" in vignettes differently since version 2.0

### ISSUE THREAD

**Issue by paul-buerkner** [r-lib/devtools#1973]
The computations in the vignettes of my brms package (https://github.com/paul-buerkner/brms) take a long time and so I avoid recomputing them on CRAN via the "NOT_CRAN" environment variable. Specifically, I add 

```
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
```

to the YAML header of my rmarkdown vignettes. This works as expected.

However, with the release of devtools 2.0, it seems as if `devtools::release(check = FALSE)` seems to be not building the vignettes either so that they are shown unevaluated on CRAN (https://cran.r-project.org/web/packages/brms/index.html). My question is how to convince the new ` devtools::release` to build the vignettes locally and submit them to CRAN, while using the "NOT_CRAN" environment variable.

Thanks in advance for you help.

**Comment by jimhester** [comment]
The environment variable is not going to be set unless you do so explicitly when calling `devtools::release()`, so something like the following should do what you want.

```r
withr::with_envvar(c("NOT_CRAN" = "true"),
  devtools::release()
)
```

**Comment by paul-buerkner** [comment]
That seems to work perfectly! Thank you!
