### ISSUE TITLE
fail to run install_github

### ISSUE THREAD

**Issue by wangt-biotime** [r-lib/devtools#1975]
Hello, 
when I install packages by install_github(" "), the error showed: 

> devtools::install_github("sheffien/IRangeKernels")
Downloading GitHub repo sheffien/IRangeKernels@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/sheffien/IRangeKernels/tarball/master'

> devtools::install_github("hadley/ggplot2")
Downloading GitHub repo hadley/ggplot2@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/hadley/ggplot2/tarball/master'

any packages were failed by the way. Do you know how to solve this problem. 
Thankyou 
WT

**Comment by jimhester** [comment]
What does `remotes:::download_method()` and `capabilities()` return? Also what version of R are you using?

**Comment by wangt-biotime** [comment]
It return:
> remotes:::download_method()
[1] "auto"
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua    http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE

**Comment by ewingzhang** [comment]
I have the same issue now.

**Comment by jimhester** [comment]
I don't know what the issue is, but I don't believe it is really something we can fix in devtools, rather it is a system configuration problem.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
