### ISSUE TITLE
devtools::release() does not look at additional CRAN check results

### ISSUE THREAD

**Issue by coatless** [r-lib/devtools#1976]
During an update with a recent package, I received:

```
── Details of the CRAN check results for <PKG> ──────────────────────────
✔ All clear for <PKG>!
──────────────────────────
Have you fixed all existing problems at 
https://cran.rstudio.com/web/checks/check_results_<PKG>.html
 shown above?
```

However, the check page is missing the new `memtests` routines that Ripley added to CRAN. Thus, the "All clear for `<PKG>`!" is a bit misleading. 

Anyway this check could scan for "additional issues" via 

```r
issues = tools::CRAN_check_issues()
```

**Comment by jimhester** [comment]
devtools uses the foghorn package to parse the check issues, so I think this issue is better opened there https://github.com/fmichonneau/foghorn/issues

**Comment by coatless** [comment]
Thanks @jimhester, opened a ticket at: fmichonneau/foghorn#33

**Comment by fmichonneau** [comment]
@jimhester, a new version of foghorn that includes the fix for this is on CRAN now. Would you like me to submit a PR here to update the minimum required version?

**Comment by jimhester** [comment]
@fmichonneau thank you for updating the package and for letting me know!
