### ISSUE TITLE
devtools::install_deps() needs remotes > 2.0.2

### ISSUE THREAD

**Issue by bastistician** [r-lib/devtools#1979]
The default `upgrade` argument of `devtools::install_deps()` and `devtools::install_dev_deps()`
https://github.com/r-lib/devtools/blob/55f982c6f7a9bef22c659954318a824381d9fdab/R/install.R#L113
has been changed in https://github.com/r-lib/devtools/commit/55f982c6f7a9bef22c659954318a824381d9fdab to accommodate the development version of **remotes**.

However, this changed also needs to increase the minimum required version of **remotes** in the DESCRIPTION of **devtools** to `remotes > 2.0.2`.

Using in-development **devtools**`::install_deps()` with released **remotes** 2.0.2 fails with
```
Error in match.arg(upgrade, c("ask", "always", "never")) : 
  'arg' must be of length 1
```
because at some point, **remotes** 2.0.2 calls
```r
match.arg(upgrade, c("ask", "always", "never"))
```

**Comment by itcarroll** [comment]
I think this bug has now made it in to the released devtools 2.0.2 and is causing the Travis r environment builds to fail.

[Exhibit A.](https://travis-ci.org/NCEAS/codyn/jobs/517549224)

**Comment by bastistician** [comment]
Sounds good! Thanks for linking the new bug report. My report from over two months ago unfortunately remained unnoticed until the recent CRAN release. A quick change in the devtools-devel DESCRIPTION to force `remotes (> 2.0.2)` would probably have prevented this "hell".

**Comment by itcarroll** [comment]
@bastistician Do you get why they closed this? I don't see any indication that the DESCRIPTION has been updated to reflect devtool's dependency on remotes >= 2.0.3.

**Comment by bastistician** [comment]
@itcarroll: I have no idea why this issue has been closed with no apparent fix. Time will tell. Maybe this has been fixed in some local devtools repository awaiting sync with the GitHub remote.
