### ISSUE TITLE
Error in Lazy database

### ISSUE THREAD

**Issue by Kota-R** [r-lib/devtools#1980]
I am using R version 3.5.2. When I try to run following commands 
`devtools::install_github("r-lib/devtools")`
`library(devtools)`

However, then I got following errors: 

`Error: package or namespace load failed for ‘devtools’ in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/devtools/R/devtools.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1` 

I have tried to restart R studio but it did not work.

**Comment by jimhester** [comment]
You will need to restart R, then re-install devtools.

**Comment by Kota-R** [comment]
Thanks jimhester. However, it did not work when I tried it before.

**Comment by hadley** [comment]
If `has_devel()` doesn't return an error, you are good to go.

**Comment by MikeJohnPage** [comment]
I had the same issues as above: (i) needing to restart R to install devtools, (ii) getting no returned output when calling `has_devel()`.

Regarding (ii) I think the devtools documentation and R packages book could do with an update (unless I am missing something) to clarify that a blank output after calling `has_devel()` does not indicate an error. This is not clear in the R packages book:

> ... This will print out some code which I use to help diagnose problems. If everything is ok, it will return TRUE. Otherwise, it will throw an error and you’ll need to investigate what the problem is.

and the documentation, which declares nothing about blank output:

> has_devel returns TRUE or FALSE.

**Comment by evgeny-vlasov** [comment]
> 
>  has_devel returns TRUE or FALSE.

I've got 
`Your system is ready to build packages!`
Good enough for me but still, unexpected output.
