### ISSUE TITLE
Incomplete package loading for collate files containing UTF-8 characters and missing Encoding in DESCRIPTION

### ISSUE THREAD

**Issue by akaever** [r-lib/devtools#1981]
When using `devtools::load_all` and in case of some UTF-8 characters within the collate files but missing `Encoding: UTF-8` in the DESCRIPTION, devtools loads parts of the files (until UTF-8 characters) and does not stop. There is just an indirect warning:

> Warning in readLines(con, warn = FALSE, n = n, ok = ok, skipNul = skipNul) :
>   invalid input found on input connection 'test.R'

Most likely, `Encoding ASCII` is assumed and `pkgload:::read_lines_enc` reads incomplete files. In case the UTF-8 character is found within a roxygen function documentation (or comment), no incomplete code is evaluated and no error is thrown.

The following code from `pkgload:::read_lines_enc` reads files until the first UTF-8 character:
```
file_encoding <- "ASCII"
con <- file("test.R", encoding = file_encoding)
lines <- readLines(con, warn = FALSE, n = -1L, ok = TRUE, skipNul = FALSE)
Encoding(lines) <- "UTF-8"
```
The following replacement reads all lines and seems to be more robust: 
```
lines <- readLines("test.R", warn = FALSE, n = -1L, ok = TRUE, skipNul = FALSE)
Encoding(lines) <- "UTF-8"
```

**Comment by jimhester** [comment]
If your DESCRIPTION has UTF-8 characters but not `Encoding: UTF-8`, then it is an invalid file.
