### ISSUE TITLE
devtools::check() "could not find bar" despite @importFrom foo bar

### ISSUE THREAD

**Issue by mkarikom** [r-lib/devtools#1982]
Here is the output from devtools::check()
```
Quitting from lines 200-204 (my_vignette.Rmd) 
   Error: processing vignette 'my_vignette.Rmd' failed with diagnostics:
   could not find function "E<-"
   Execution halted
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error

```
Lines 200-204 call multiple functions from my package which depend on igraph, thus I have the following line in the function code:
`@importFrom igraph graph.data.frame get.edge.ids E `

As we can see, igraph::E is among the imported functions and as a sanity check, its also in my automatically generated (via devtools::document) package NAMESPACE:
`importFrom(igraph,E)
`

Also, building this vignette via pkgdown::build_site() produces the following error:

`Error in E(network) <- `*vtmp*` : could not find function "E<-"`

However, running my_vignette.Rmd chunk by chunk produces no errors.  So my functions must be importing igraph::E() successfully, just not when the vignette is built?

What could be going on here?

**Comment by jennybc** [comment]
`E` and `E<-` (the assignment form) are two different functions.

https://github.com/cran/igraph/blob/88642b96a3ba8576df72405008c8f5ffea6cefba/NAMESPACE#L106

versus

https://github.com/cran/igraph/blob/88642b96a3ba8576df72405008c8f5ffea6cefba/NAMESPACE#L96

Are you sure you are importing both?

**Comment by mkarikom** [comment]
> `E` and `E<-` (the assignment form) are two different functions.
> 
> https://github.com/cran/igraph/blob/88642b96a3ba8576df72405008c8f5ffea6cefba/NAMESPACE#L106
> 
> versus
> 
> https://github.com/cran/igraph/blob/88642b96a3ba8576df72405008c8f5ffea6cefba/NAMESPACE#L96
> 
> Are you sure you are importing both?

Hello @jennybc, thanks for the heads up.  I didn't notice that E<- was actually a separate function.   it's It's working after adding E<- to @importFrom igraph.
