### ISSUE TITLE
devtools and usethis

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#1985]
I'm starting the revision of R Packages.

The relationship of devtools to usethis is a bit awkward. devtools re-exports lots of functions, but also does not re-export many others. I'm adding an early "whole game" chapter that shows the creation of a small toy package. And I can't close the deal without attaching usethis and using it directly.

I think we need to get off this fence:

  1. Admit package devs will probably need to attach both devtools and usethis.
  2. Re-export more usethis stuff from devtools.

If we choose 1., we need to clarify language like this (from v2.0.0 blog post but also the README & pkgdown site):

> devtools will remain the primary package developers will interact with when writing R packages; it will just rely on these other packages internally for most of the functionality.
>
> Generally, you should not need to worry about these different packages, because devtools installs them all automatically. You will need to care, however, if you’re filing a bug because reporting it at the correct place will lead to a speedier resolution.

Honestly, I think we have to do 1. because 2. feels unsustainable / extreme. Would we ever put usethis in Depends 🤔?

Do we have a pithy principle that governs whether devtools will import and re-export a usethis function vs not?

cc @hadley

**Comment by hadley** [comment]
I think devtools is primarily about _doing_ stuff where as usethis is about _creating_ stuff; or maybe usethis is simplifies things that you do once (like creating a file), whereas devtools automates things that you do multiple times (like running all tests).

**Comment by jimhester** [comment]
devtools already _does_ attach usethis when you attach devtools. The functions that previously existed in devtools are re-exported in devtools only to provide deprecation messages.

``` r
library(devtools)
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS  10.14.2
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] usethis_1.4.0.9000  devtools_2.0.1.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.0         knitr_1.21         magrittr_1.5      
#>  [4] pkgload_1.0.2      R6_2.3.0           rlang_0.3.1       
#>  [7] stringr_1.3.1      highr_0.7          tools_3.5.1       
#> [10] pkgbuild_1.0.2     xfun_0.4           sessioninfo_1.1.1 
#> [13] cli_1.0.1.9000     withr_2.1.2        remotes_2.0.2.9000
#> [16] htmltools_0.3.6    yaml_2.2.0         rprojroot_1.3-2   
#> [19] digest_0.6.18      assertthat_0.2.0   crayon_1.3.4      
#> [22] processx_3.2.1     callr_3.1.1.9000   fs_1.2.6          
#> [25] ps_1.3.0.9000      testthat_2.0.1     glue_1.3.0.9000   
#> [28] memoise_1.1.0      evaluate_0.12      rmarkdown_1.10    
#> [31] stringi_1.2.4      compiler_3.5.1     desc_1.2.0        
#> [34] backports_1.1.3    prettyunits_1.0.2
```

<sup>Created on 2019-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment]
And yes the plan is to eventually remove the re-exported functions completely and put usethis in depends.

**Comment by jennybc** [comment]
> devtools already _does_ attach usethis when you attach devtools

AHA! I didn't delve deeply enough to see this and attributed some of my local phenomena to the fact that I always have usethis attached (at least in interactive sessions). OK thanks I think I know how to talk/write about this now.
