### ISSUE TITLE
Weird installation error if installing to a different lib that is not on the lib path

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/devtools#1987]
For this you need the dev version (or just a different version, really) of usethis in a regular library, and then install usethis and devtools to another library.  E.g.

```r
dir.create(lib1 <- tempfile())
pak::pkg_install("r-lib/usethis", ask = FALSE, lib = lib1)
.libPaths(c(lib1, .libPaths()))

library(usethis)
dir.create(lib2 <- tempfile())
install.packages(c("devtools", "usethis"), lib = lib2)
```

```
** testing if installed package can be loaded
Error: package or namespace load failed for 'devtools':
 .onAttach failed in attachNamespace() for 'devtools', details:
  call: value[[3L]](cond)
  error: Package 'usethis' version 1.4.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace 'usethis' is imported by 'devtools' so cannot be unloaded

Error: loading failed
Execution halted
ERROR: loading failed
```

Is there a reason why devtools can't simply just depend on usethis?

**Comment by jimhester** [comment]
> Is there a reason why devtools can't simply just depend on usethis?

Yes, we wanted the `use_*()` functions to be depreciated in devtools, but still attach usethis to the search path, so new functions or those called with `devtools::` would work without a deprecation message. The problem with just using `Depends` is the devtools functions then come before the usethis functions in the search path, so you get deprecation messages when calling the unqualified name.

**Comment by gaborcsardi** [comment]
I think a workaround is to check where the imported package is coming from, that's in the namespace info, see `getNapespaceInfo()`, and add a  `lib.loc` arg to the `library()` call, to make sure the same package is attached.
