### ISSUE TITLE
`run_examples()` attempts to run code inside of `\dontrun{}` block

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/devtools#1990]
The current version of devtools attempts to run code inside of `\dontrun{}` for working examples when calling `run_examples()`. Is there a way to disable this behavior? It appears that this was brought up in issue #118 but I'm a bit confused as to how this was resolved.

**Comment by jimhester** [comment]
`devtools::run_examples(run = FALSE)` should do it.

**Comment by mjsteinbaugh** [comment]
Nice. Thanks @jimhester
