### ISSUE TITLE
Binary Version on CRAN

### ISSUE THREAD

**Issue by muschellij2** [r-lib/devtools#1991]
Any idea why the OSX binary on CRAN is still 1.13.6?  I can install from source, but run times were causing some issues.
https://cran.r-project.org/web/packages/devtools/index.html
<img width="851" alt="screen shot 2019-02-15 at 2 32 12 pm" src="https://user-images.githubusercontent.com/1075118/52879912-815b1f00-312e-11e9-8222-842d34d25b0c.png">

**Comment by muschellij2** [comment]
Looks like devtools OSX has ERRORs: 
https://cran.r-project.org/web/checks/check_results_devtools.html

https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/devtools-00check.html
https://www.r-project.org/nosvn/R.check/r-oldrel-osx-x86_64/devtools-00check.html

**Comment by jennybc** [comment]
This is because the CRAN macOS machine either has no Pandoc or has a rather ancient Pandoc.

**Comment by jimhester** [comment]
the devtools version on CRAN is now current (2.1.0)
