### ISSUE TITLE
Deprecate release()

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#1992]
In favour of `usethis::use_release_issue()`, at least when it's obvious that GitHub is being used.

**Comment by jimhester** [comment]
@jennybc I know you still use `release()`, do you have strong opinions one way or the other on this?

**Comment by jennybc** [comment]
I **am** rather attached to `release()`. I like being confronted with all of these programmatic checks vs. a checklist where I can sort of fudge things or get lazy about re-visiting them after a change ("oh this small change couldn't possibly break anything"). I use both. I have pretty regular examples where `release()` catches something.

**Comment by hadley** [comment]
In that case I retract my request for deprecation, and instead request that we prominently advertise `use_release_issue()` from the help, and maybe from the command line.
