### ISSUE TITLE
"I agree" is not a good option

### ISSUE THREAD

**Issue by barryrowlingson** [r-lib/devtools#1993]
Running a `release` and I see:
```
Were Git checks successful?
1: Nope
2: Uhhhh... Maybe?
3: I agree

```

Option 3, "I agree", is not clearly meaning "yes" or "no" here. I'm not sure which of these actually means "yes"....

**Comment by mattmalin** [comment]
It does seem out of place with all the other "yes"es to be used in a standard yes/no question:
https://github.com/r-lib/devtools/blob/8e1818cea8db5c7f55bd7f94482416ae9fadfcf5/R/release.R#L191

maybe it could be replaced with an "Indeed" or "of course" or similar?
