### ISSUE TITLE
Error find_rtools() : could not find function Mac OSMojave R 3.5.2

### ISSUE THREAD

**Issue by sormehyazdi** [r-lib/devtools#1995]
First tried 

`
install.packages(devtools)
find_rtools()
`
Installing the "devtools" package seems to have worked, but after find_rtools, I get:

`Error in find_rtools() : could not find function "find_rtools"`

So then I tried:
`
> install.packages("pkgbuild") 
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/pkgbuild_1.0.2.tgz'
Content type 'application/x-gzip' length 126355 bytes (123 KB)
==================================================
downloaded 123 KB

The downloaded binary packages are in
	/var/folders/3w/f6l8_wr90yvbg0d6r98qwnsm0000gn/T//RtmpbCzeLa/downloaded_packages
> library(devtools)
> devtools::install_github("r-lib/pkgbuild")
Downloading GitHub repo r-lib/pkgbuild@master
✔  checking for file ‘/private/var/folders/3w/f6l8_wr90yvbg0d6r98qwnsm0000gn/T/RtmpbCzeLa/remotes4eed51235efd/r-lib-pkgbuild-6e4ebdf/DESCRIPTION’ ...
─  preparing ‘pkgbuild’:
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pkgbuild_1.0.2.9000.tar.gz’
   
* installing *source* package ‘pkgbuild’ ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (pkgbuild)
> library(pkgbuild)
Error in value[[3L]](cond) : 
  Package ‘pkgbuild’ version 1.0.2 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘pkgbuild’ is imported by ‘devtools’ so cannot be unloaded
> find_rtools()
Error in find_rtools() : could not find function "find_rtools"
`

So then I tried

`
> assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), "devtools")
Error in bindingIsLocked(x, ns) : no binding for "version_info"
> library(pkgbuild)
Error in value[[3L]](cond) : 
  Package ‘pkgbuild’ version 1.0.2 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘pkgbuild’ is imported by ‘devtools’ so cannot be unloaded
> library("pkgbuild", lib.loc="/Library/Frameworks/R.framework/Versions/3.5/Resources/library")
Error in value[[3L]](cond) : 
  Package ‘pkgbuild’ version 1.0.2 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘pkgbuild’ is imported by ‘devtools’ so cannot be unloaded
> find_rtools()
Error in find_rtools() : could not find function "find_rtools"
`

And I'm not sure why I can't load "pkgbuild" or why it should be unloaded, and I still don't know why find_rtools() isn't working. 

Your time and help would be really appreciated!

**Comment by PrasanthV454** [comment]
Facing the same problem here

**Comment by PrasanthV454** [comment]
I reinstalled rtools 

`library(pkgbuild)
library(devtools)
find_rtools()`

Successfully yielded TRUE

**Comment by jennybc** [comment]
This has already been reported and fixed in the dev version of devtools.

https://github.com/r-lib/devtools/issues/1909
