### ISSUE TITLE
curl::curl_fetch_memory(url, handle = h) : Could not resolve host: api.github.com

### ISSUE THREAD

**Issue by irinasm** [r-lib/devtools#1996]
I have the following problem downloading package from github:
>  devtools::install_github('walkerke/tigris') Error in
> curl::curl_fetch_memory(url, handle = h) :    Could not resolve host:
> api.github.com

I was able to do this successfully last night, but then I had some other issues downloading some shapefiles from census. Meanwhile downloading package from github did work. So here is what I did:

1.I unchecked Use IE library/proxy for HTTP and I tried to create a new .renviron file with proxy. that did not solve the problem with census. 
2.I re-checked IE proxy setting, and I deleted the .renviron file that I created (going back to how it was). Now I started having problem with github (resolving host). 
3.I removed CURL and HTTR. I reinstalled them. That did not help 
4.I deleted CURL and HTTR folder libraries manually and reinstalled them. that did not help.
5.I had R and R studio completely uninstalled, deleted folders and then installed. However I still get that error

> "curl::curl_fetch_memory(url, handle = h) : Could not resolve host: api.github.com".

I am just trying to get refresh everything I can, to get to the point I was last night when I could do successfully

> devtools::install_github('walkerke/tigris')

without errors resolving host. What else can I do?

Thank you for your help!

**Comment by jimhester** [comment]
Uses this is just the case that your internet connection has gone down and once that is resolved it will be fixed. I don't believe there is any bug in devtools to fix, so I will close this issue.

If you continue to experience issues try asking for help at <https://community.rstudio.com>, you will likely receive a prompter response then here.
