### ISSUE TITLE
ability to install source-only packages without Rtools etc.

### ISSUE THREAD

**Issue by bbolker** [r-lib/devtools#200]
As a wishlist item for devtools, I wonder if it would be feasible to allow `install_github` to work successfully on Windows (or any OS, although Windows is the hardest) _without_ development tools (Rtools) installed, for a binary-less package [i.e. ones without any need for compilers/Makefiles/etc.] ... what makes me think this is possible is that (IIRC) `install.packages(...,type="source")` works fine on devel-tools-lacking Windows systems ... A Windows-using colleague reports that `install_github(...)` does _not_ successfully install a binary-less package on a machine without Rtools, although I admit I haven't tried it myself (access to a Windows development/test environment is a minor nuisance, although not impossible).

I apologize if this has been covered elsewhere (a quick search through the Issues list and a quick google for "install_github Rtools source" didn't turn anything up)

I haven't dug into the source  yet to see what the problem might be  -- if this seems like a good idea, I could try to generate a patch ...

(Related: https://github.com/hadley/devtools/issues/173 )

**Comment by cmclean3** [comment]
Hi all

Trying to install a package from Github on a strongly locked down work pc. 

I had Rtools installed (by using an administrator's password) but when the package tries to open Rtools to build during the install process, the pc security blocks it from being open as its an unauthorized application.

Is there any way to install a package from github without requiring Rtools to be installed?

Alternatively is it possible to create a package archive file (.zip or .tar.gz) from a github package on another open computer? Then i would copy to the locked computer and install manually.

thanks

**Comment by jimhester** [comment]
@cmclean3 If the package has a `src/` directory it contains compiled code and needs Rtools in order to compile the code.

You can build a binary package from a separate computer with

```R
git clone repo.git
cd repo
R CMD build .
R CMD INSTALL --build pkg*tar.gz
```

This will produce a `foo.zip` package with the compiled code that can be installed on the other computer with `Rscript -e "install.packages('foo.zip', repos = NULL)"`.

See http://www.hep.by/gnu/r-patched/r-exts/R-exts_20.html for more information.

**Comment by cmclean3** [comment]
that's great, will attempt tonight at home - thanks Jim

**Comment by cmclean3** [comment]
@jimhester so i was able to clone the repo and change directory, however after i enter R CMD build i get the error:

bash: R: command not found

Searching the web for a solution but no luck yet. Is this something you have come across before?

**Comment by jimhester** [comment]
Doesn't look like R is installed, or if it is installed it is not on your path.

Note if you want to use an R package on a windows machine the binary package needs to be built on windows as well.
