### ISSUE TITLE
maybe document() should render README.md and README.html

### ISSUE THREAD

**Issue by rcorty** [r-lib/devtools#2007]
https://github.com/r-lib/devtools/issues/1762 was closed based on commit https://github.com/r-lib/devtools/commit/c509f1e07ad500ea5c76c92f8c372bd4cef0fc8c

But I don't believe that commit put the building of README.md and README.html into the standard workflow of building a package (which includes `document()`), it simply made available the `build_readme()` function.

**Comment by jennybc** [comment]
The question of rendering README has come up before and I'd agree that, yeah, it never been fully resolved, from a workflow point of view.

`build_readme()` is helpful, but it's still not wired into anything automatic, like `document()`.

Related issue:

  * #1762 Do something about README.Rmd --> README.md

**Comment by jimhester** [comment]
I would definitely not want document to render the readme, I at least usually have fairly heavy examples in my readme and run document many many times throughout the day. I generally only build the readme when I make a change to the text or am nearing a release.

**Comment by jimhester** [comment]
I think having the readme as a separate function is fine, but perhaps we should include it in the release issue or similar?
