### ISSUE TITLE
callLoadDataset: Cannot tokenize lines longer than 999

### ISSUE THREAD

**Issue by mustansarsaeed** [r-lib/devtools#2009]
Hi,
I am trying to build graphs based on results files generated in OMNet++ but while loading data set, it shows error:
```
> require("omnetpp")
> loadDataset("WLH_updated.sca")
```
**Error:**

> callLoadDataset: Cannot tokenize lines longer than 999

**Comment by jimhester** [comment]
Hi, I cannot believe this is an issue with devtools, if you still need help open an issue with a link to the package in question at <https://community.rstudio.com>.
