### ISSUE TITLE
devtools installs master branch

### ISSUE THREAD

**Issue by Nelson-Gon** [r-lib/devtools#2013]
I'm trying to install "my" package using `devtools::install_github("https://github.com/Nelson-Gon/manymodelr@develop")`. However, both `devtools` and `remotes` install from the master branch. I've looked at some options like manually specifying the branch that have all failed.  Is this a known issue?

**Comment by Nelson-Gon** [comment]
This solved it but would be great to know why the above failed to work.
`remotes::install_github("https://github.com/Nelson-Gon/manymodelr",ref = "develop")`

**Comment by jimhester** [comment]
```r
devtools::install_github("Nelson-Gon/manymodelr@develop")
```

Would work, as would the ref option as you described.

You can also use the url to the branch, e.g.

```r
devtools::install_github("https://github.com/Nelson-Gon/manymodelr/tree/develop")
```
