### ISSUE TITLE
documenting re-exported functions in the manual

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#2018]
This is more of a general question about how to document re-exported function couched in `devtools` settings.

For example, `devtools` re-rexports `session_info` function from the `sessioninfo` package:
https://github.com/r-lib/devtools/blob/f6d0cae9727ebd17b4a8193270bb390dbe5cf0b2/R/session-info.R#L31-L37

And although this function is exported from the package, if one were to simply go by the manual, one would completely miss out on the existence of this function-
https://cran.r-project.org/web/packages/devtools/devtools.pdf

![image](https://user-images.githubusercontent.com/11330453/55578932-0dc49f80-56e5-11e9-88af-4dc20f5cd205.png)

Since a lot of users check out available functions by looking at the manual, I was wondering if there is any way to document re-exported function in the `pdf` manual?

**Comment by IndrajeetPatil** [comment]
@jimhester, @jennybc Any thoughts on this? 

If this is not possible, I will close the issue.

**Comment by jennybc** [comment]
I think it's a good question. This also affects the reference section of the pkgdown site:

https://devtools.r-lib.org/reference/index.html

If we're encouraging folks to think of devtools as the "storefront" for this suite of functions, it feels like we should also have a way of surfacing the functions made available by devtools, via re-export or attach, that come from a separate package.

**Comment by IndrajeetPatil** [comment]
Tagging also @hadley; maybe he has some thoughts on this.

**Comment by hadley** [comment]
We have no control over the manual, and in general, please don't tag me into issues unless it's urgent.
