### ISSUE TITLE
devtools error on Travis CI

### ISSUE THREAD

**Issue by jadahlke** [r-lib/devtools#2020]
As of the April 4th CRAN update to devtools v2.0.2, Travis CI is encountering an error with devtools during its setup phrase when building R packages (the error occurs prior to Travis testing any of the user's R code). I've encountered this issue with two different R packages today that previously passed Travis' tests - neither package's code was changed before running on Travis, I just created new branches from previously passing branches to initiate new builds. I am attaching a screenshot of the error message from Travis' job log - hope it helps! 

![devtools error message from Travis CI](https://user-images.githubusercontent.com/18146391/55768597-1d284d80-5a43-11e9-9477-4242e6c8ee33.png)

**Comment by AAlhendi1707** [comment]
My package is a biocoductor dependent package (R: bioc-devel). it just failed to pass the build few hours ago given the error mentioned above.

`Error in match.arg(upgrade, c("ask", "always", "never")) : 
  'arg' must be of length 1`

see [job log](https://travis-ci.org/AAlhendi1707/countToFPKM/jobs/517585235).

Any suggestions would be greatly appreciated.

**Comment by richelbilderbeek** [comment]
Same [here](https://travis-ci.org/ropensci/babette/jobs/517663224#L1364) on all three of the `r-release`, `r-devel` and macOS builds.

Good luck fixing it :+1:

**Comment by jimhester** [comment]
I am aware of it and will likely have a fix today. In the interim you can install the development version of remotes using `r_github_packages` to fix the issue

```yaml
r_github_packages: r-lib/remotes
```

**Comment by jimhester** [comment]
Sorry, you actually need to install dev remotes prior to the install step, so this should work.

```r
before_install: R -e 'source("https://install-github.me/r-lib/remotes")'
```

**Comment by richelbilderbeek** [comment]
Workaround works under Linux (`r-relase` and `r-devel`), but not on macOS Travis machines. The glass is two-thirds full :+1:

**Comment by jdblischak** [comment]
@nachti I got the same error https://travis-ci.org/jdblischak/workflowr/jobs/517831999#L944

**Comment by trannhatanh89** [comment]
```
before_install: R -e 'source("https://install-github.me/r-lib/remotes")'
``
does not work for me ([log](https://travis-ci.org/trannhatanh89/HPAanalyze/jobs/517848747)). I guess I will wait it out.

**Comment by jimhester** [comment]
remotes 2.0.3 is now on CRAN, which will fix this, no workaround should now be necessary.

**Comment by fabnavarro** [comment]
Same problem here ([log](https://travis-ci.org/fabnavarro/rwavelet/builds/517860907)), but another one appeared after clearing the cache [(log)](https://travis-ci.org/fabnavarro/rwavelet/builds/517976018?utm_medium=notification&utm_source=email)

**Comment by grabear** [comment]
https://github.com/r-lib/remotes/issues/316

**Comment by jennybc** [comment]
I don't think this thread is related to #316. I don't see the same errors in the log.

@fabnavarro The error in your second log is because travis merged a commit from @jimhester faster than expected and I believe your job tried to grab R 3.5.3 before a build of it had arrived in the proper location. That should be sorted now. I'm only answering for him since I suspect he's done for the day.

**Comment by fabnavarro** [comment]
@jennybc the build is passing now, thank you very much for your answer.

**Comment by rkrug** [comment]
I still get this error: https://travis-ci.com/Exp-Micro-Ecol-Hub/emeScheme/builds/107620556

**Comment by stelsemeyer** [comment]
> I still get this error: https://travis-ci.com/Exp-Micro-Ecol-Hub/emeScheme/builds/107620556

This is fixed now by https://github.com/r-lib/remotes/pull/340.

**Comment by stelsemeyer** [comment]
> I still get this error: https://travis-ci.com/Exp-Micro-Ecol-Hub/emeScheme/builds/107620556

@rkrug : This is fixed now by https://github.com/r-lib/remotes/pull/340.
