### ISSUE TITLE
spell_check() not using its argument use_wordlist

### ISSUE THREAD

**Issue by riccardoporreca** [r-lib/devtools#2024]
https://github.com/r-lib/devtools/blob/ab6c878d9ec3657fc08f07fa4389e23374617d01/R/spell-check.R#L14
when calling `spelling::spell_check_package()`
https://github.com/r-lib/devtools/blob/ab6c878d9ec3657fc08f07fa4389e23374617d01/R/spell-check.R#L16

**Comment by jimhester** [comment]
Thanks!
