### ISSUE TITLE
source_gist() breaks on ` (backquote)

### ISSUE THREAD

**Issue by iqis** [r-lib/devtools#2025]
I tried to source a [gist](https://gist.github.com/iqis/926c189da89a32b9702c340c42401c67) with `source_gist()`
```
> source_gist("https://gist.github.com/iqis/926c189da89a32b9702c340c42401c67")
```
Which returns the following error:
```
Sourcing https://gist.githubusercontent.com/iqis/926c189da89a32b9702c340c42401c67/raw/4116d40e09840e3e7822dc5a014ed275b6f16dfe/tree.R
SHA-1 hash of file is 93c56b0352c3867ed21104aab28fc3a0c25b6849
Error in source(temp_file, ...) : 
  invalid multibyte character in parser at line 53
```
On line 53 I wrote 
```
function(x) `if`(x, "    ", "│    "))`
```
which used backquote around `if`.

I'm suspecting that this some how got broke when the file was written as a binary?

https://github.com/r-lib/devtools/blob/ab6c878d9ec3657fc08f07fa4389e23374617d01/R/run-source.R#L39

**Comment by jimhester** [comment]
So I think you had an extra backquote, which was causing the issue when sourcing the file, this would happen locally as well. It looks like you have fixed this in the latest version, so I will close this.
