### ISSUE TITLE
Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by muratdsahin** [r-lib/devtools#2033]
I am trying to download the updated version of simstudy package using devtools. I get the error massage: 

devtools::install_github("kgoldfeld/simstudy")
Downloading GitHub repo kgoldfeld/simstudy@master
Error: Could not find tools necessary to compile a package

Devtools package is up to date (2.0.2). I tried several ways but nothing changes. 
I also tried what Hadley says here:
https://github.com/r-lib/pkgdown/issues/377

Can you pls help me?

**Comment by jimhester** [comment]
You need to install the RTools package to install a compiler toolchain. https://whattheyforgot.org/set-up-an-r-dev-environment.html#windows-system-prep has instructions on what needs to be done.
