### ISSUE TITLE
Vignette runs and knits properly but won't build

### ISSUE THREAD

**Issue by jmgirard** [r-lib/devtools#2034]
This is probably an issue with my package rather than devtools, but I would appreciate some pointers toward fixing it. When I run my vignette .Rmd file, it complets without issue. I can also knit it to R and html files. However, when I try to use `document()` or `build()` or `build_vignette()`, the process seems to get stuck on the vignette and never completes. Ultimately I have to stop the process. Note that two other vignettes in my package build fine.

My package source code is at:
https://github.com/jmgirard/circumplex
The offending vignette is: 
https://github.com/jmgirard/circumplex/blob/master/vignettes/introduction-to-ssm-analysis.Rmd

Any ideas on how to troubleshoot this issue? Thanks in advance!

**Update:** Tried this on another machine and it worked fine. Must be something with my configuration at work.

**Comment by jimhester** [comment]
If you still are stuck on this, this sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
