### ISSUE TITLE
release() reports that dev packages are out of date

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#2036]
`release()` reports that packages installed at a dev version (i.e. are *past* the CRAN version) are "out of date".

``` r
> release()
Warning: DR_DEVTOOLS FOUND PROBLEMS
* R is out of date (3.5.3 vs 3.6.0)
* Devtools or dependencies out of date: git2r, glue, rcmdcheck, rlang
Proceed anyway?
1: Uhhhh... Maybe?
2: For sure
3: I forget

Selection: 3
> packageVersion("glue")
[1] '1.3.1.9000'
> packageVersion("rlang")
[1] '0.3.4.9002'
> packageVersion("git2r")
[1] '0.25.2.9000'
> packageVersion("rcmdcheck")
[1] '1.3.2.9002'
```

It's conceivable that `release()` *should* let you know if you're not installed from the most recent CRAN version. But the current wording is confusing.

**Comment by jimhester** [comment]
I cannot reproduce this, are you sure they are not _actually_ out of date? e.g. there is a more recent SHA in the GitHub repo?

**Comment by jennybc** [comment]
Oh there probably is a more recent SHA.

I think there are 2 issues:

  * Technically, one should probably be checking the release candidate for package X against CRAN versions of its dependencies. But of course we often let that get checked on Travis, AppVeyor, win-builder, and r-hub and don't worry about dev versions in the local library.
  * So the main kind of out-of-date-ness I care about here would be if I was behind CRAN version.

Is it hard to borrow the display of "what you have" vs. "what's current" from remotes, where one could easily which situation it is?

**Comment by jimhester** [comment]
It is possible, but I don't really want to invest much development time in `release()` as I no longer use it. I am happy to accept PRs for it though!

**Comment by jennybc** [comment]
If you close this, I'll survive and will try to remember to come back.

If you leave it open, I'll give it some thought next time I'm working on similar stuff in usethis, such as the `use_release_issue()`.
