### ISSUE TITLE
devtools::test() and changes to RNGkind and sample

### ISSUE THREAD

**Issue by boennecd** [r-lib/devtools#2038]
I may be doing something wrong but it seems like there is an issue with `devtools::test()` and the changes to RNGkind and the `sample` method. I have an example here https://stackoverflow.com/questions/56104176/devtoolstest-rngversion-and-sample-yields-different-results

**Comment by jimhester** [comment]
`devtools::test()` doesn't run the code in `tests/testthat.R`, you need to put the `suppressWarnings(RNGversion("3.5.0"))` call in a testthat helper to get it to run during `devtools::test()`.

**Comment by boennecd** [comment]
Thanks for the reply. There is still a difference between the first and second call to `devtools::test`. See the updated question at SO.

**Comment by jimhester** [comment]
Sorry cannot reproduce this, my suggested fix of setting the seed in the helper worked fine, and repeated calls of `devtools::test()` all pass successfully. See https://github.com/jimhester/testseed for an example repo
