### ISSUE TITLE
Forwarding arguments to rhub::check() from check_rhub()

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/devtools#2041]
Would be nice. `...` is forwarded to `build()` currently. So maybe we can have a new `rhub_check_args` argument.

Alterrnatively, it could just print or document that people should use `rhub::check()` for more flexibility.

**Comment by jimhester** [comment]
We have `build_args` in `devtools::check()` so we should probably do the same in `devtools::check_rhub()` and then forward `...` to `rhub::check()`.

**Comment by gaborcsardi** [comment]
Yeah, I think that would be best. A breaking change though, but people usually use `rhub_check()` interactively, I guess.

**Comment by maelle** [comment]
I'd be happy to make a PR, should I?

**Comment by gaborcsardi** [comment]
@maelle yes, please!

**Comment by jimhester** [comment]
Fixed by 75c8c2321607274d7b4df48a824ef1f1a902e800
