### ISSUE TITLE
When using installl_github and only one outdated dependency exists, the options to update all or none don't appear

### ISSUE THREAD

**Issue by daattali** [r-lib/devtools#2046]
I've noticed this happen a few times, I let it slide initially but because it persists, I'll post a screenshot as proof:

![image](https://user-images.githubusercontent.com/952340/58062180-c0df4000-7b4f-11e9-89d0-b377492e0876.png)

Normally I have an option to update "none" of the above package. 

This is with devtools 2.0.2

**Comment by jimhester** [comment]
You can just use an empty line to cancel in this case, but we should probably still include none as well.

**Comment by jimhester** [comment]
I think this is now fixed actually, if it still occurs with remotes 2.1.0 please open an issue in the remotes repository.
