### ISSUE TITLE
Print stack trace on error in devtools::document() or devtools::check()

### ISSUE THREAD

**Issue by kummerer94** [r-lib/devtools#2048]
I am trying to get a large codebase with many classes and generics set up as a package. This is a tedious task when using S4 classes and the devtools and roxygen2 packages definitely make it easier. Thanks for that.

However, when I am trying to follow the advice on [this page](http://r-pkgs.had.co.nz/check.html), I run into the following issue: I get back an error from `devtools::document()` or `devtools:check()` that is unspecific as to where the error actually happened (which file and which line). All I seem to get is the error message but no stacktrace, no file or line number.

Is there a way to fix this? Is this a limitation of the way R handles things? For me, just the file where the error occurs would be of great help.

Thanks,
Alexander

**Comment by jimhester** [comment]
Use `traceback()` after the error happens to get a stack trace of the calls which lead to the error.

 For more general info on debugging R code see [Chapter 11 of what they forgot to teach you about R](https://whattheyforgot.org/debugging-r-code.html#debugging-your-own-code)
