### ISSUE TITLE
devtools::document error with shared object

### ISSUE THREAD

**Issue by vanderleidebastiani** [r-lib/devtools#2051]
Dear,

I have been using devtools::document() to update .Rd files and NAMESPACE in my package. This package need load a dynamic shared object (specifically a Fortran .f90 file) and have been working accordingly.

To do this I include the .onLoad function and use library.dynam function to inform the dynamic shared object.

.onLoad <- function(lib, pkg) {
	library.dynam("xx_package", pkg, lib)
}

and to inform NAMESPACE via @rawNamespace tag:

@rawNamespace useDynLib(xx_package)

This correct include “useDynLib(xx_package)” in NAMESPACE file. The package can be installed and load.

However, every time that I need update .Rd or NAMESPACE files the function devtools::document() fails.

The following error:

devtools::document()
Updating xx_package documentation
Loading xx_package
Error in library.dynam("xx_package", pkg, lib) : 
  shared object ‘xx_package.so’ not found

To solve this, I need to follow the following steps:
1 - Comment (with #) library.dynam line in .onLoad function
2 - Run devtools::document()
3 - Uncomment library.dynam line in .onLoad function

As I already informed via @rawNamespace tag the existence of dynamic shared object all work accordingly. Could I find a simpler solution to solve this error?

Best, Vanderlei

**Comment by jimhester** [comment]
I think for modern versions of R it should actually work without explicitly calling `library.dynam()` in your `.onLoad()` and just relying on the NAMESPACE file. In general you hardly ever need to call `library.dynam()` yourself.

That being said I do not know if this is true of FORTRAN bindings, in general if you are using FORTRAN you are basically on your own...
