### ISSUE TITLE
Informative error when on `load_all()` failure due to duplicative Rcpp exports

### ISSUE THREAD

**Issue by alexpghayes** [r-lib/devtools#2052]
If you try to `load_all()` when you have two C++ functions with exactly the name, along the lines of

``` cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector timesTwo(NumericVector x) {
  return x * 2;
}

// [[Rcpp::export]]
NumericVector timesTwo(NumericVector x) {
  return x * 2;
}
```

You'll the following error:

![image](https://user-images.githubusercontent.com/15078251/58716346-7307da80-838e-11e9-8fca-23f22e6d4e4e.png)

In the big picture this may not be a huge deal, but I find `src`  and C++ the least pleasant and approachable parts of package development and think informative messages even for these simple cases are super useful for people just getting their feet wet with compiled code.

**Comment by jimhester** [comment]
Unfortunately trying to make llvm or gcc errors more friendly a very large problem and I don't feel it is within the scope of devtools.
