### ISSUE TITLE
`devtools::check` doesn't catch invalid file URIs

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/devtools#2054]
Although I had 0 `NOTE`, `ERROR`, or `WARNING` on my local machine, this is the `NOTE` I am getting with the development version of R (but not on `R 3.6.0`). 

```r
Found the following (possibly) invalid file URIs:
  URI: commits/master
    From: README.md
  URI: /commits/master
    From: README.md
  URI: CONDUCT.md
    From: README.md
```

This is my `.Rbuildignore` for the R package in question-
https://github.com/IndrajeetPatil/ggstatsplot/blob/master/.Rbuildignore

I am guessing this is a new check implemented on `R CMD CHECK`? Maybe worth including in `devtools` as well?

P.S. I am also attaching the full log in case you need to have a look it.
[full_log.txt](https://github.com/r-lib/devtools/files/3250395/full_log.txt)

**Comment by jimhester** [comment]
`devtools::check()` is just a wrapper around `R CMD check`, so to get this check you need to check with R devel, and also use `remote = TRUE`.

**Comment by IndrajeetPatil** [comment]
Got it. But how can I get rid of this `NOTE`? I have no clue what the problem is here.

**Comment by jennybc** [comment]
Replace any internal links in your README with a full URL to GitHub (or perhaps a pkgdown site).

**Comment by IndrajeetPatil** [comment]
That solved it! Thanks. 

I still think `devtools` or `rcmdcheck` should catch this though.

**Comment by jennybc** [comment]
> I still think devtools or rcmdcheck should catch this though.

Like @jimhester said, `check()` is just a wrapper around `R CMD check` at the end of the day and this is a brand new check added by CRAN. This check doesn't exist in the current version of R. You won't see this unless you're checking with r-devel. Assuming you don't want to install r-devel locally, you can check on r-devel remotely with `devtools::check_win_devel()`, on r-hub, or on travis.

**Comment by IndrajeetPatil** [comment]
Ah, got it. Sorry when he said it's a wrapper around `R CMD CHECK`, I somehow converted that to `rcmdcheck` and thought to myself why not implement this check in that package. 

I understand now why this is not possible.

**Comment by IndrajeetPatil** [comment]
I am guessing for the same reason `devtools` also doesn't catch `NOTE` related to invalid **URL**s:

```r
URL: https://cran.r-project.org/web/packages/ggstatsplot/readme/README.html
    From: README.md
    Status: 200
    Message: OK
    CRAN URL not in canonical form
  URL: https://cran.r-project.org/web/packages/ggstatsplot/vignettes/
    From: README.md
    Status: 200
    Message: OK
    CRAN URL not in canonical form
  The canonical URL of the CRAN page for a package is 
    https://CRAN.R-project.org/package=pkgname
```

**Comment by jimhester** [comment]
I you running check with `remote = TRUE`? those checks are only turned on when that is the case.

**Comment by IndrajeetPatil** [comment]
Yes, this is the exact code I am running-
```r
devtools::check(
  run_dont_test = TRUE,
  manual = TRUE,
  remote = TRUE,
  incoming = TRUE,
  force_suggests = TRUE
)
```
