### ISSUE TITLE
devtools::install() tries to install too late version of dependency package

### ISSUE THREAD

**Issue by stela2502** [r-lib/devtools#2055]
My package (BioData) depends on seurat <= 2.3.0. So if I install the package using devtools::install() it always wants to install a newer version of seurat which later on breaks the installation process as the version of seurat is then too new for my package.
I consider this a bug - would it be possible to fix this?

Thank you!

**Comment by jimhester** [comment]
No, not really possible to fix. 

In general depending on `<=` of dependencies is not really supported for R packages due to limitations in base R functions.
