### ISSUE TITLE
Consider throwing an error when build_manual() fails

### ISSUE THREAD

**Issue by jolars** [r-lib/devtools#2056]
Currently, there is no nothing to let you know that something went wrong during compilation of the package manual when `build_manual()` is called. The only difference from a successful call is that the two last lines of output are missing

Successfull call to `build_manual()`:

```r
Hmm ... looks like a package
Creating pdf output from LaTeX ...
Saving output to ‘[some-file-name].pdf’ ...
Done
```

Failing call to `build_manual()`:

```r
Hmm ... looks like a package
Creating pdf output from LaTeX ...
```

May I suggest that, at the very least, the function throws an error saying something went wrong in building the manual.

**Comment by jimhester** [comment]
Do you have an example package where the manual fails to build?

**Comment by jolars** [comment]
Sure, here's an example: <https://github.com/jolars/testr>

**Comment by jimhester** [comment]
Ok we now fail in this case, thanks for opening the issue and making the example package!
