### ISSUE TITLE
Override deletion of inst/doc 

### ISSUE THREAD

**Issue by Nelson-Gon** [r-lib/devtools#2062]
This has been discussed several times before although I thought it wise to "reopen" this issue. The **problem** is that `devtools` deletes vignettes in `inst/doc` yet vignettes stored under the vignettes folder are not correctly built if one installs from github. 

I may be wrong here and would welcome guidance on what the best(current) prcatice is for building vignettes while using devtools. For instance, if I try to install a package of "mine" from github, the default is to delete inst/doc but no vignettes are built yet the vignettes folder exists.

**Example:**

```
devtools::install_github("Nelson-Gon/manymodelr@develop",
                         build_vignettes=T)

```

Previously, one would download and build these vignettes like so. However, now the default is to delete inst/doc hence no vignettes are built.

**Session Info:**

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)
‘devtools’ version 2.0.2

```

Thank you and my apologies of this has already been conclusively discussed. I failed to find a real solution to the issue.

**Comment by Nelson-Gon** [comment]
My apologies, it seems it does in deed build the vignettes now unlike a few days ago.

**Comment by jimhester** [comment]
The `build_vignettes` argument was added back in remotes v2.1.0
