### ISSUE TITLE
release() --> git_checks() should probably report branch

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#2064]
I'm one of those people who still use `release()`.

I nearly just submitted a package to CRAN from a non-`master` branch.

I think the `git_check()` should at least surface this, to make sure it's intentional.

https://github.com/r-lib/devtools/blob/master/R/check-git.R

**Comment by jimhester** [comment]
I submit packages to CRAN on non-master branches pretty often, as I use release branches, but I also no longer use `release()`...

**Comment by jennybc** [comment]
What do you think of revealing branch here? Like ...

```
> devtools:::git_checks()
── Running Git checks for bigrquery ──────────────────────────────────────────────
On branch: weird-feature-branch
Checking uncommitted files... OK
Checking synchronisation with remote branch... OK
──────────────────────────────────────────────────────────────────────────────────
```

**Comment by jimhester** [comment]
Sure, if you want to write a PR I would be happy to include it!
