### ISSUE TITLE
install_github(): bin/tar error

### ISSUE THREAD

**Issue by f527** [r-lib/devtools#2066]
Hello,

On Win10 Enterprise (64-bit), 
R 3.6.0, 
Devtools35: during installation, I instruct Devtools to modify the system PATH and ensure it's at the top of the list.

I'm receiving an error at install_github():

`devtools::install_github("hrbrmstr/msgxtractr")`
`Downloading GitHub repo hrbrmstr/msgxtractr@master`
`/Rtools/bin/tar: Child returned status 127`
`/Rtools/bin/tar: Error is not recoverable: exiting now`
`External tar failed with --force-local, trying without`
`/Rtools/bin/tar: Child returned status 127`
`/Rtools/bin/tar: Error is not recoverable: exiting now`
`External tar failed with --force-local, trying without`
`Error: Failed to install 'msgxtractr' from GitHub:`
`  Does not appear to be an R package (no DESCRIPTION)`
`In addition: Warning messages:`
`1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\<USER>\AppData\Local\Temp\RtmpIXPEtg\file39641a2bbb.tar.gz" -C "C:/Users/<USER>/AppData/Local/Temp/RtmpIXPEtg/remotes396417b329d0"’ returned error code 2`
`2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\<USER>\AppData\Local\Temp\RtmpIXPEtg\file39641a2bbb.tar.gz"' had status 2`

**Comment by kotoroshinoto** [comment]
I am also experiencing errors similar to this.
Trying from R started in windows CMD: https://pastebin.com/SjXKTEgQ
Trying from R terminal in RStudio: https://pastebin.com/yRrE1jCe

**Comment by kotoroshinoto** [comment]
reported to remotes: https://github.com/r-lib/remotes/issues/405

**Comment by jimhester** [comment]
As mentioned this is a duplicate to other issues, generally they are caused by the default download method, so switching to a different one should fix the issue.
