### ISSUE TITLE
Cull options set by devtools

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#2068]
devtools is setting lots of options, many of which I believe are now vestigial, i.e. that job is being handled by usethis:

https://github.com/r-lib/devtools/blob/4e088027e48c831f98f7ddb284d79333dbadce36/R/zzz.R#L49-L58

It would be good to review these and delete any that aren't used by devtools itself.

**Comment by jimhester** [comment]
I am not sure if _any_ of these are used now

**Comment by jennybc** [comment]
usethis will consult some of this, out of a sense of honour for the deprecated. But it's better to set usethis options. Plus that's really to help out _users_ who are setting them intentionally, not a package setting defaults.

I agree. From where I sit, I think they've all fallen out of use.

**Comment by jennybc** [comment]
If devtools still consults a name, should it also honour the equivalent usethis option?

**Comment by jimhester** [comment]
It is only used in `release_email()`, which actually now that I look at it we should just remove, I don't think that function is used by anything, and you no longer need to send an email when you upload a package to CRAN.
