### ISSUE TITLE
Improvement demand on devtools::check

### ISSUE THREAD

**Issue by neonira** [r-lib/devtools#2069]
**CRAN** does not accept packages submitted when version in **DESCRIPTION** file has leading zeros _(e.g. 1.01.004)_. This ends up to be rejected by **CRAN,** and the fix is just to turn 1.01.004 to 1.1.4. 

I wish **devtools::check** to implement such a simple test as it will make all of us avoid this trap and avoid many erroneous submissions on **CRAN**, not currently detected by devtools.

**Comment by jimhester** [comment]
This is checked automatically during `R CMD check`, if you run `devtools::check(incoming = TRUE)` to run the CRAN incoming checks with a suitable version of R.

**Comment by jimhester** [comment]
```
N  checking CRAN incoming feasibility (2.6s)
   Maintainer: ‘Jim Hester <james.f.hester@gmail.com>’

   Version contains leading zeroes (1.01.004)
```
