### ISSUE TITLE
Installation instructions for Mac / Mojave

### ISSUE THREAD

**Issue by DSLituiev** [r-lib/devtools#2070]
It took me sometime to figure out how to install devtools on my Mojave Mac and I wish there were an instruction section in the README.md.

1. Install Xcode patch by typing following in command line:
```open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg```
This is necessary as [Mojave has a different header folder location](https://stackoverflow.com/questions/52702738/stdio-h-not-found-during-r-package-installation)

2. [Install `Omp` library](https://stackoverflow.com/questions/25990296/how-to-include-omp-h-in-os-x) required for `px` package dependency:
```brew install libomp```

3. Install `devtools` per se: `install.packages('devtools')`

Done

**Comment by jimhester** [comment]
1. and 2. may be necessary to install certain source packages with compiled code, but certainly not all of them and devtools can definitely be installed without them.
