### ISSUE TITLE
CRAN release uses latest version not yet available

### ISSUE THREAD

**Issue by TomKellyGenetics** [r-lib/devtools#2071]
I have a minor release for a package ready to upload. I builds without issues on R 3.6.0 on various test environments. At the time of writing, R version 3.6.1 is only available from source but `release` doesn't not seem to check based on system builds. Is it possible to get this updated? (or delayed a few days after a new release to ensure that it is available)

At the moment, a workaround is to "Proceed Anyway" with the current version (I have updated from R 3.5.2). I've mentioned this in the `cran-comments.md` as well.

<img width="607" alt="Screen Shot 2019-07-06 at 9 15 00" src="https://user-images.githubusercontent.com/5493325/60749105-49b31d80-9fd0-11e9-8d7e-decdf688f8b2.png">
<img width="1039" alt="Screen Shot 2019-07-06 at 9 15 30" src="https://user-images.githubusercontent.com/5493325/60749106-49b31d80-9fd0-11e9-80ce-87408d80d11c.png">

**Comment by jennybc** [comment]
This is a situation when I would definitely exercise human judgment and "Proceed anyway". These questions are just meant to be speed bumps to help you pause and reflect.

**Comment by TomKellyGenetics** [comment]
Thanks, that's no problem. I just wasn't sure if this had been considered or it was an edge case due to the timing with new R version.
