### ISSUE TITLE
R 3.6.1 does not allow devtools (on 3.5.1 i used rtools35.exe)

### ISSUE THREAD

**Issue by amit0thesingularity** [r-lib/devtools#2074]
I just upgraded to 3.6.1 on R but after rtools35.exe i am still getting non zero exit for devtools on install. How do I install devtools? I tried going back to R 3.5.1 but i need it on R 3.6.1

**Comment by kalycett** [comment]
I'm having this issue but on R 3.5.1!

I will try updating R, but if it's not working for you on R 3.6.1, I doubt it'll work for me.

**Comment by kalycett** [comment]
Ok - updated R, still could not get it to work but then I noticed R Studio was still running the old version of R. 

I went in to R 3.6.1 (without R Studio) and got it to download fine, no issues.

I went back in to R Studio and told it to specifically use the updated version of R and then restarted. Was able to successfully install the package.

**Comment by j-berg** [comment]
Thought I'd add to this conversion in case someone comes across this flavor of the issue. I was getting the same error with my conda-installed R. I think this came about because I had both R and r-base installed. I uninstalled R and kept r-base and had no issues.
