### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by mezerji1365** [r-lib/devtools#2078]
I try to install a package form GitHub using devtools

library(devtools)
install_github("santosneto/glmBP")
and got an error message:
Downloading GitHub repo santosneto/glmBP@master
from URL https://api.github.com/repos/santosneto/glmBP/zipball/master
Installation failed: Not Found (404)

please help to solve this.

**Comment by jennybc** [comment]
This means you have a typo in the GitHub username or repo name. Because I can't find such a repository:

https://github.com/santosneto/glmBP
