### ISSUE TITLE
has_devel() returns nothing

### ISSUE THREAD

**Issue by programgirl** [r-lib/devtools#2080]
I'm in Windows 10, working in RStudio version 1.2.1335 (Build 1379). I installed the latest stable version of Rtools (Rtools35). Then I installed devtools, roxygen2, testthat, and knitr, so I have the latest versions from CRAN.

I received no warning or error messages upon installing those four R packages.

I then loaded devtools. This is when the apparent problem occurred.

I'm working in the console. has_devel() returns nothing. I get no warning/error messages, but I don't get the expected TRUE either. The console is ready for more input, so something happened.

I have been following the instructions on this page: http://r-pkgs.had.co.nz/intro.html

**Comment by jennybc** [comment]
The existing issues that are tracking this are:

https://github.com/r-lib/devtools/issues/1970

https://github.com/r-lib/pkgbuild/issues/69

BTW, the 2nd edition of R Packages is taking shape at a different URL:

https://r-pkgs.org

**Comment by jmarshallnz** [comment]
Heya,

devtools::has_devel returns true invisibly, so it should be all good :)

See the issue here r-lib/pkgbuild#69 that suggests changing the behaviour. Current code is here:

https://github.com/r-lib/pkgbuild/blob/601439baac0df05b2cbb8774cd6322544954a098/R/build-tools.R#L39

**Comment by programgirl** [comment]
Thank you for the response and advice.
