### ISSUE TITLE
devtools::build_site() generated Note in devtools:check() Non-standard file/directory found at top level

### ISSUE THREAD

**Issue by dachosen1** [r-lib/devtools#2087]
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

devtools version: 2.1.0

The devtools::build_site() function generated a new file in my package directory 'docs'. However, when I performed the devtools::check() function I receive two additional notes that weren't previously there.

Note 1: 
 checking for portable file names ... NOTE
  Found the following non-portable file paths:
    formulaic/docs/articles/Introduction-to-formulaic_files/datatables-css-0.0.0/datatables-crosstalk.css
    formulaic/docs/articles/Introduction-to-formulaic_files/dt-core-1.10.16/css/jquery.dataTables.extra.css
    formulaic/docs/articles/Introduction-to-formulaic_files/dt-core-1.10.16/css/jquery.dataTables.min.css
  
  Tarballs are only required to store paths of up to 100 bytes and cannot
  store those of more than 256 bytes, with restrictions including to 100
  bytes for the final component.
  See section 'Package structure' in the 'Writing R Extensions' manual.

Note 2:
checking top-level files ... NOTE
 Non-standard file/directory found at top level: 'docs' 

I added inst/doc to .gitignore and ^doc$to .Rbuildignore

Package link for reproducibility: https://github.com/dachosen1/formulaic

**Comment by jimhester** [comment]
You seem to be missing an s, you need to add `$docs^` not `^doc$`. `usethis::use_pkgdown()` will add the correct file to the ignore files for you.

**Comment by dachosen1** [comment]
Thank you
