### ISSUE TITLE
report when CRAN submission is closed...

### ISSUE THREAD

**Issue by tbates** [r-lib/devtools#2088]
When CRAN submissions are closed (as they are now) CRAN post a message at 
https://cran.r-project.org/submit.html

Devtools just says, however
> Error in upload_cran(pkg, built_path) : Not Found (HTTP 404).

Be nice to say instead:
> Check here to see if CRAN is up: https://cran.r-project.org/submit.html

**Comment by brooklynbagel** [comment]
Would be glad to look into contributing.

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/devtools/commit/03537c6c6f1f6db2e74874f38d5457708ef69fc6
