### ISSUE TITLE
devtools::test() not reporting failures?

### ISSUE THREAD

**Issue by bbimber** [r-lib/devtools#2090]
I'm trying to use devtools::test() on travisci.  I originally just ran "R CMD check"; however, it seemed that even if my tests failed, this returned a zero exit code.  

Both b/c my tests run long (i.e. it creates a long period with zero output) and b/c of the above I switched to run "R CMD check --no-tests" and "Rscript -e 'res=devtools::test(reporter="summary", filter = 'singleR');df=as.data.frame(res);if(sum(df$failed) > 0 || any(df$error)) {q(status=1)}'", based on an example that was posted.  

When I manually run that devtools::test() command, when a test fails with a code error, as opposed to testthat(), it is not reflected in the results.  Below is part of the output:

Seurat: 1

== Failed ======================================================================
-- 1. Error: (unknown) (@test-singleR.R#6)  ------------------------------------
object of type 'S4' is not subsettable
1: RunSingleR(seuratObj = seuratObj, resultTableFile = results) at C:\Projects\OOSAP/tests/testthat/test-singleR.R:6

My questions are: 1) is there a more standard way to run R tests through travis?  The fact that I cant get non-zero exit codes seems odd, and 2) when tests fail with exceptions, how is that supposed to get reported?  

Thanks.

**Comment by jimhester** [comment]
`usethis::use_travis_ci()` will setup travis CI for you with the recommended settings.

However this sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

You could also try at https://travis-ci.community/c/languages/r

**Comment by bbimber** [comment]
OK, thanks - I will ask there.

I started with use_travis(), and read over the travis/R docs and plugin code.  I'd prefer to use that as much as possible, but I concluded I needed to override parts in order to: 1) use build stages and caching, and 2) Because my tests run long, I needed to wrap R CMD CHECK with "travis_wait 30".
