### ISSUE TITLE
Check that run_examples() documentation correct

### ISSUE THREAD

**Issue by k-doering-NOAA** [r-lib/devtools#2100]
https://github.com/r-lib/devtools/blob/master/R/run-examples.R#L19-L20 . From this documentation, I thought that running `run_examples(run = TRUE)` would mean that any examples enclosed with \dontrun{} would be ignored, but closed issue #1990 (and my own running of examples in an R package) suggests that I should use `run_examples(run = FALSE)`  to not run examples enclosed with \dontrun{}. 

I think the documentation needs to be updated to
```
#' @param run if `FALSE`, code in \code{\\dontrun{}} will be commented
#'   out.
```

**Comment by jimhester** [comment]
I moved an issue to pkgload to track this https://github.com/r-lib/pkgload/issues/107
