### ISSUE TITLE
devtools::install_github("databio/GenomicDistributions") does not work

### ISSUE THREAD

**Issue by DzLGasoline** [r-lib/devtools#2101]
I tried to install an R package "GenomicDistributions" with only provided way by the devs:
`devtools::install_github("databio/GenomicDistributions")`

And it only returns this error message:

`Downloading GitHub repo databio/GenomicDistributions@master`
`sh: /usr/local/bin/gtar: No such file or directory`
`sh: /usr/local/bin/gtar: No such file or directory`
`Error: Failed to install 'GenomicDistributions' from GitHub:`
 ` error in running command`
`In addition: Warning messages:`
`1: In system(cmd) : error in running command`
`2: In utils::untar(tarfile, ...) :`
`  ‘/usr/local/bin/gtar -xf '/tmp/RtmphcCAry/filea6967cdf34f3.tar.gz' -C` `'/tmp/RtmphcCAry/remotesa696220d7d91'’ returned error code 127`

I tried almost everything I could, i.e. running R with sudo... etc.

I installed R through anaconda, and I guess it might be a cause of this problem, but I'm not sure.

My R session information is stated below.
>─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin13.4.0        
 ui       unknown                     
 language (EN)                        
 collate  ko_KR.UTF-8                 
 ctype    ko_KR.UTF-8                 
 tz       Asia/Seoul                  
 date     2019-09-04                  

>─ Packages ───────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
 backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.1)
 callr         3.3.1   2019-07-18 [1] CRAN (R 3.6.1)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.1)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
 curl          4.0     2019-07-22 [1] CRAN (R 3.6.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
 devtools      2.1.0   2019-07-06 [1] CRAN (R 3.6.1)
 digest        0.6.20  2019-07-04 [1] CRAN (R 3.6.1)
 fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.1)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.1)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.1)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
 pkgbuild      1.0.5   2019-08-26 [1] CRAN (R 3.6.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.1)
 processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.1)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.1)
 Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.6.1)
 remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
 rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.1)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
 testthat      2.2.1   2019-07-25 [1] CRAN (R 3.6.1)
 usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.1)

>[1] /Users/spark_2/miniconda3/lib/R/library

I really appreciate any helps or advices. Thank you in advance.

**Comment by jimhester** [comment]
> I installed R through anaconda, and I guess it might be a cause of this problem

Yes that is the problem. If you are using `conda` you need to use `conda` to install all of the packages. See https://whattheyforgot.org/set-up-an-r-dev-environment.html#what-about-conda for our advice.
