### ISSUE TITLE
Error: Failed to install 'HierBasis' from Github: Does not appear to be an R package(no DESCRIPTION)

### ISSUE THREAD

**Issue by RoundNose** [r-lib/devtools#2102]
I tried to install [asadharis/HierBasis](https://github.com/asadharis/HierBasis) but encountered such error.

![error](https://user-images.githubusercontent.com/49848788/64235054-27834080-cf2a-11e9-8eab-89eca451f8b1.jpg)

`Sys.setenv("TAR" = "internal")`  advised in [devtools-Issues #1939 ](https://github.com/r-lib/devtools/issues/1939)  is no use.

The session Information is here.
![session](https://user-images.githubusercontent.com/49848788/64235472-02430200-cf2b-11e9-8fa2-755ffbc70263.jpg)

**Comment by jimhester** [comment]
This is most likely due to your download method, not TAR, I would suggest you open an issue at community.rstudio.com.

As this seems to be a system configuration issue rather than a bug in devtools I am closing this issue.
