### ISSUE TITLE
Error: 'create' is not an exported object from 'namespace:devtools'

### ISSUE THREAD

**Issue by bennlich** [r-lib/devtools#2104]
I installed devtools with `packages.install('devtools')` and it eventually installed without error. I can't seem to use any of its methods though?

```
> devtools::create("atp-analytics")
Error: 'create' is not an exported object from 'namespace:devtools'
```

```
> devtools::use_package()
Error: 'use_package' is not an exported object from 'namespace:devtools'
```
I feel like I must be missing some trivial step...

```
> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo       
```

**Comment by jennybc** [comment]
devtools did drop `create()`, in favour of `usethis::create_package()`.

In an upcoming release, `devtools::create()` will be restored, to support backwards compatibility with older versions of RStudio, But it's still a better idea to call `usethis::create_package()`.

`use_package()` (and all functions in usethis) are made available by devtools, but the function actually lives in usethis. So if you want to call it in a namespace-qualified way, it must be `usethis::use_package()`. Or, after attaching devtools via `library(devtools)`, you can just call `use_package()` directly. But you cannot call it via `devtools::use_package()`.

More about the relationship between devtools and usethis:

  * devtools 2.0.0 release post: <https://www.tidyverse.org/articles/2018/10/devtools-2-0-0/>
  * devtools vs. usethis usage advice in R Packages: <https://r-pkgs.org/setup.html#setup-usage>

**Comment by bennlich** [comment]
Thank you! This is super helpful.

Maybe worth updating the cheatsheet on the homepage?

**Comment by jennybc** [comment]
> Maybe worth updating the cheatsheet on the homepage?

Excellent point! Will you open a new issue about that? Looks like that dates back to January 2015.

**Comment by bennlich** [comment]
Done! https://github.com/r-lib/devtools/issues/2107

**Comment by vojtechhuser** [comment]
I just had the same errror and this helped me

**Comment by JimShady** [comment]
^and me
