### ISSUE TITLE
Lovely README cheatsheet is getting stale

### ISSUE THREAD

**Issue by bennlich** [r-lib/devtools#2107]
The [cheatsheet graphic](https://raw.githubusercontent.com/batpigandme/cheatsheets/1c942c36846559b3e8efbd40d023bc351aeed6ba/pngs/thumbnails/package-development-thumbs.png) linked from the https://github.com/r-lib/devtools/blob/master/README.md is wonderful! But it still references `devtools::create`, which I understand has been replaced by `usethis::create_package()`. Time for an update?

**Comment by hadley** [comment]
Draft update at https://github.com/rstudio/cheatsheets/blob/main/pngs/package-development.png

**Comment by jennybc** [comment]
Closing in favour of #2443, since the main update has now happened.
