### ISSUE TITLE
Error: package or namespace load failed for ‘processx’using termux on android phone

### ISSUE THREAD

**Issue by ZihaoXingstudy** [r-lib/devtools#2114]
Error: package or namespace load failed for ‘processx’:
.onLoad failed in loadNamespace() for 'processx', details:
call: ps::ps_handle()
error: Unknown errorfs_error0NA
Error: loading failed
Execution halted
ERROR: loading failed

removing ‘/usr/local/lib/R/site-library/processx’

**Comment by jimhester** [comment]
This is not a devtools issue, 
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
