### ISSUE TITLE
bug in `check()` or `R CMD CHECK`?

### ISSUE THREAD

**Issue by blueskypie** [r-lib/devtools#2124]
`R CMD CHECK` gives a NOTE on my R package:
> checking R code for possible problems ... NOTE  
  Found the following calls to attach():  
  File ‘wfr/R/rmd.util.r’:  
    attach(rImageFn, name = "rImage", pos = 2)  
  See section ‘Good practice’ in ‘?attach’.

Here is the corresponding "Good Practice" section in [`attach`](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/attach):
> Good Practice  
`attach` has the side effect of altering the search path and this can easily lead to the wrong object of a particular name being found. People do often forget to `detach` databases.

The NOTE is due to the following three consecutive lines of code in a function in my R package:
```r
        attach(rImageFn,name="rImage", pos=2)
        obj1=get("OBJ2",pos = 2)
        detach(name="rImage", pos=2)
```
Seems the concern from the NOTE is that **People do often forget to detach databases**, which is not the case here. So I wonder if `R CMD CHECK` should issue the NOTE **only if** `attach` is not followed by `detach`?

Meanwhile, any suggestion on how to prevent this NOTE?

**Comment by jimhester** [comment]
Don't use `attach()`, just `get()` the object from the environment directly.

**Comment by jimhester** [comment]
In your case you are using attach to read a data file I guess, you could use `load()` rather than `attach()`. But really I think it would be better to rethink how you are saving the data, e.g. use `saveRDS()` rather than `save()`.

**Comment by blueskypie** [comment]
Thanks for the comment! But my R package intends to give the users option to save the working image so that they can reload the image later for their own interests.

Although in this function I only read one object from the working image, i.e. I could just `saveRDS` on that object and later `readRDS`, I still have to save the working image to keep the above-mentioned option, which logically makes saving the object separately redundant.

But regardless, shouldn't the checking on `attach` be followed by a checking on `detach`? and not giving NOTE if `detach` follows `attach`?

**Comment by jimhester** [comment]
This check does not come from devtools, but from `R CMD check` which is outside our control, there isn't anything we can do about it.

If you want to keep the NOTE and try to explain your reasoning to CRAN you are welcome, but I doubt they will be receptive.

**Comment by blueskypie** [comment]
Thanks for the quick reply! `devtools::check()` does give the same NOTE.

**Comment by jimhester** [comment]
`devtools::check()` is just a wrapper around `R CMD check`.

**Comment by blueskypie** [comment]
I see! thanks!
