### ISSUE TITLE
Broken reference links

### ISSUE THREAD

**Issue by bennlich** [r-lib/devtools#2126]
Broken (non-existent) links in the details section at the bottom of this page: https://devtools.r-lib.org/reference/remote-reexports.html

That page is linked to from all of the install_* links at the bottom of https://devtools.r-lib.org/reference/index.html

**Comment by brooklynbagel** [comment]
I'm new to pkgdown but I wouldn't mind taking a look into fixing.

**Comment by jimhester** [comment]
I think part of the issue is cross package pkgdown links only work when the package has the pkgdown site in the URL, I added that to remotes at https://github.com/r-lib/remotes/commit/8d8d545cb6a1725bd943522cb953c5c2755c2cf4

**Comment by hadley** [comment]
Looks good to me now.
