### ISSUE TITLE
Error installing devtools

### ISSUE THREAD

**Issue by fredaas** [r-lib/devtools#2131]
I get the following error after trying to install devtools via `install.packages('devtools', dependecies=TRUE)` on Ubuntu 18.04:
```
ERROR: dependency ‘httr’ is not available for package ‘pkgdown’
* removing ‘/usr/local/lib/R/site-library/pkgdown’
ERROR: dependencies ‘usethis’, ‘covr’, ‘httr’, ‘rversions’ are not available for package ‘devtools’
* removing ‘/usr/local/lib/R/site-library/devtools’
```
I read somewhere that installing the following dependencies should solve the problem:
```
sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
```
And indeed it does.

Is this documented somewhere? If not, it definitely should be.

Edit:

Running on Linux 4.15.0-72-generic, Ubuntu 18.04.3 LTS.

**Comment by tonca** [comment]
Very useful indeed!

**Comment by JairoRotava** [comment]
Same issue here. Thanks for sharing.

**Comment by javadba** [comment]
Is this related?  I got 

ERROR: dependency ‘usethis’ is not available for package ‘devtools’

**Comment by fredaas** [comment]
@javadba Yes, as you can see from my original post.

**Comment by javadba** [comment]
How should this be performed on macOS ?

**Comment by jennybc** [comment]
@javadba I'm skeptical you are having the same problem on macOS. There was a recent problem with the macOS side of CRAN, which could have caused your inability to install usethis. That is fixed at the source now and percolates through the mirrors as they sync up. What **exact error** do you see if you try to install usethis?

**Comment by javadba** [comment]
Thx Jenny!

```
install.packages('devtools')

* installing *source* package ‘gh’ ...
** package ‘gh’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘cli_alert_info’ is not exported by 'namespace:cli'
Execution halted
ERROR: lazy loading failed for package ‘gh’
* removing ‘/usr/local/lib/R/3.6/site-library/gh’
ERROR: dependency ‘gh’ is not available for package ‘usethis’
* removing ‘/usr/local/lib/R/3.6/site-library/usethis’
ERROR: dependency ‘usethis’ is not available for package ‘devtools’
* removing ‘/usr/local/lib/R/3.6/site-library/devtools’

```

**Comment by jennybc** [comment]
```
Error: object ‘cli_alert_info’ is not exported by 'namespace:cli'
```

It looks like maybe you need to update cli? Perhaps devtools (or something else involved above) has an undocumented minimum version requirement re: cli that is not met by the version you currently have installed. In any case, that's what I would try next.

**Comment by javadba** [comment]
Thx that did do the trick.  I actually have a follow-on error but maybe should I create a separate issue?  I feel lost here: a series of issues and wondering if there were some guide i'm missing.

```
> install.packages('ps',verbose=TRUE)
Installing package into ‘/usr/local/lib/R/3.6/site-library’
(as ‘lib’ is unspecified)
system (cmd0): /usr/local/Cellar/r/3.6.1_1/lib/R/bin/R CMD INSTALL
trying URL 'https://cloud.r-project.org/src/contrib/ps_1.3.2.tar.gz'
Content type 'application/x-gzip' length 98761 bytes (96 KB)
==================================================
downloaded 96 KB

foundpkgs: ps, /var/folders/d6/m67jyndd7h754m3810cl3bpm0000gp/T//Rtmp8ikDio/downloaded_packages/ps_1.3.2.tar.gz
files: /var/folders/d6/m67jyndd7h754m3810cl3bpm0000gp/T//Rtmp8ikDio/downloaded_packages/ps_1.3.2.tar.gz
* installing *source* package ‘ps’ ...
** package ‘ps’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/usr/local/opt/llvm/bin/clang -fopenmp -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -Wall px.c -o px
ld: library not found for -lomp
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [px] Error 1
ERROR: compilation failed for package ‘ps’
* removing ‘/usr/local/lib/R/3.6/site-library/ps’
* restoring previous ‘/usr/local/lib/R/3.6/site-library/ps’

The downloaded source packages are in
	‘/private/var/folders/d6/m67jyndd7h754m3810cl3bpm0000gp/T/Rtmp8ikDio/downloaded_packages’
Warning message:
In install.packages("ps", verbose = TRUE) :
  installation of package ‘ps’ had non-zero exit status

```

**Comment by jennybc** [comment]
@javadba You're on macOC, right? I'm not sure why you end up compiling ps from source here, as CRAN has a binary for the most recent release. I would try to sort that out.

But since you are compiling from source ... there's this:
```
/usr/local/opt/llvm/bin/clang -fopenmp -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -Wall px.c -o px
ld: library not found for -lomp
```
ps does not use openmp, so this suggests something is misconfigured on your system. Others have seen this before so you might find this issue helpful https://github.com/r-lib/ps/issues/56

**Comment by javadba** [comment]
I'm not sure where to go here. From  `install.packages('ps')` - which is `R` world it is sent to `ps` project due to a compilation error. Then in `ps` it is pointed back to possible `CRAN` issue.   afa "build from source"  - given I used `install.packages` I did not explicitly choose that approach.

**Comment by jennybc** [comment]
>  From install.packages('ps') - which is R world it is sent to ps project due to a compilation error. Then in ps it is pointed back to possible CRAN issue. afa "build from source" - given I used install.packages I did not explicitly choose that approach.

I don't exactly follow what you mean by some of that, but the bottom line is that I suspect something about your system is mis-configured. When I install ps from macOS, right now, with `install.packages()`, I get a binary from CRAN.

```
> install.packages("ps")
Installing package into '/Users/jenny/Library/R/3.6/library'
(as 'lib' is unspecified)
trying URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.6/ps_1.3.2.tgz'
Content type 'application/x-gzip' length 208566 bytes (203 KB)
==================================================
downloaded 203 KB


The downloaded binary packages are in
	/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T//RtmpzTEvGk/downloaded_packages
```

**Comment by fredaas** [comment]
Why is this closed? Is the dependency issue fixed and/or documented?

**Comment by Jerrywang959** [comment]
Thank you ! It works in my computer. Deepin Linux 15.11

**Comment by fredaas** [comment]
@jimhester Please provide a brief comment on the resolution of the issue before closing. As it stands there is still a dependency issue.

**Comment by jimhester** [comment]
There is not any issue particular to devtools, your system is misconfigured if you are unable to install the dependencies.


If you need help configuring your system to install R packages open an issue at community.rstudio.com

**Comment by thomas-broethaler** [comment]
Thank you very much @fredaas this solved an issue I had with installing packages like plotly and tidyverse. Now they install correctly and as expected without issues.

**Comment by n-a-t-e** [comment]
fyi, on CentOS 7 I had to run:

```
sudo yum groupinstall 'Development Tools' and
sudo yum install gcc gcc-c++ make openssl-devel libxml2-devel
```

to before installing devtools

**Comment by nutle** [comment]
For CentOS7, we also needed

```
sudo yum install -y libcurl-devel
```
on top of @n-a-t-e 's comment

**Comment by JD-Robbs** [comment]
Same issue in Ubuntu 20.04 LTS. 😞 

Did what the OP said, and results in the following:

```
ERROR: dependency ‘usethis’ is not available for package ‘devtools’
* removing ‘/usr/local/lib/R/site-library/devtools’
ERROR: dependencies ‘systemfonts’, ‘textshaping’ are not available for package ‘ragg’
* removing ‘/usr/local/lib/R/site-library/ragg’
ERROR: dependency ‘ragg’ is not available for package ‘pkgdown’
* removing ‘/usr/local/lib/R/site-library/pkgdown’

The downloaded source packages are in
        ‘/tmp/RtmpIb9SoP/downloaded_packages’
Warning messages:
1: In install.packages("devtools", dependencies = TRUE) :
  installation of package ‘gert’ had non-zero exit status
2: In install.packages("devtools", dependencies = TRUE) :
  installation of package ‘systemfonts’ had non-zero exit status
3: In install.packages("devtools", dependencies = TRUE) :
  installation of package ‘usethis’ had non-zero exit status
4: In install.packages("devtools", dependencies = TRUE) :
  installation of package ‘textshaping’ had non-zero exit status
5: In install.packages("devtools", dependencies = TRUE) :
  installation of package ‘devtools’ had non-zero exit status
6: In install.packages("devtools", dependencies = TRUE) :
  installation of package ‘ragg’ had non-zero exit status
7: In install.packages("devtools", dependencies = TRUE) :
  installation of package ‘pkgdown’ had non-zero exit status
````

**Comment by aabiddanda** [comment]
If using brew on Mac OSX, first run `brew install libgit2` and then `install.packages("usethis", verbose=TRUE)`. It worked well for me and solved this issue when installing `devtools`. 

OSX 10.15.7 (Macbook Air)

**Comment by damnms** [comment]
same here on debian 11

**Comment by fredaas** [comment]
> There is not any issue particular to devtools, your system is misconfigured if you are unable to install the dependencies.
> 
> If you need help configuring your system to install R packages open an issue at community.rstudio.com

Exactly. The original post asks that you document this somewhere. If devtools relies on specific packages to be available upon install then that is a package-dependency issue which is the responsibility of the package maintainer to document.

**Comment by rpep** [comment]
I just ran into this. I totally agree with @fredaas. This is nothing to do with the system being misconfigured - if there are OS level dependencies pulled in, they need to be documented, because different OS's will have different packages installed by default (and even flavours - for e.g. 'server' versions ususally have a very barebones setup).

**Comment by jimhester** [comment]
The are documented, in the SystemRequirements fields of the DESCRIPTION files of the given dependency package, just like every other R package.
