### ISSUE TITLE
Installed package could not be loaded

### ISSUE THREAD

**Issue by YPeiLin** [r-lib/devtools#2138]
Hi there, \ 
I build a package on local and I upload to github. After I install successfully and I "load" the package with no error by using library. However, I could not use any functions from my package, could I ask what are some possibilities of such an error? Thanks
> install_github("qlu-lab/PUMAS")
Downloading GitHub repo qlu-lab/PUMAS@master
✔  checking for file ‘/private/var/folders/j9/jxd5sz7x09zb_fjqp_9b7bxc0000gn/T/RtmpA4iWGH/remotes9f6759daad3/qlu-lab-PUMAS-eeb0cac/DESCRIPTION’ ...
─  preparing ‘pumas’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pumas_0.0.tar.gz’
   
* installing *source* package ‘pumas’ ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (pumas)
> library(pumas)
> pumas.main("/working-directory-to-input/T0030_pruned.txt","/working-directory-to-output/T0030_pruned.png","Beta","EAF","SE",766345,TRUE)
Error in pumas.main("/working-directory-to-input/T0030_pruned.txt", "/working-directory-to-output/T0030_pruned.png",  : 
  could not find function "pumas.main"

**Comment by jimhester** [comment]
In order for your functions to be used by users they need to be exported, which you do by putting the special `#' @export` comment above the function (and running `devtools::document()`) for more details please see https://r-pkgs.org/namespace.html#exports
