### ISSUE TITLE
tag ref as instructed by CRAN-RELEASE

### ISSUE THREAD

**Issue by randy3k** [r-lib/devtools#2139]
I have been using the following function to tag ref as instructed by CRAN-RELEASE.
```
This package was submitted to CRAN on 2019-10-26.
Once it is accepted, delete this file and tag the release (commit 18503ae37c).
```

```r
tag_release <- function(pkg = ".") {
    pkg <- devtools:::as.package(pkg)
    release_file <- file.path(pkg$path, "CRAN-RELEASE")
    if (!file.exists(release_file)) {
        cat("CRAN-RELEASE file not found\n")
        return(invisible())
    }
    line <- readLines(release_file)[2]
    match <- regexec("commit ([a-z0-9]+)", line)
    sha <- regmatches(line, match)[[1]][2]
    if (is.na(sha)) {
        cat("Cannot parse CRAN-RELEASE\n")
        return(invisible())
    }
    semver <- paste0("v", pkg$version)
    if (devtools:::yesno(glue::glue("tag {sha} as {semver}"))) {
        return(invisible())
    }
    tag_sha <- gert::git_tag_create(semver, message = semver, ref = sha, repo = pkg$path)
    file.remove(release_file)
    invisible(tag_sha)
}
```

The code has not yet polished for deployment. Yet, I want to check if devtools devs are interested in it before I create a PR.

**Comment by randy3k** [comment]
One potential problem is that the version number in DESCRIPTION may have changed so we might need to hard code that too in CRAN-RELEASE.

**Comment by jimhester** [comment]
I believe `usethis::use_github_release()` tags the commit along with creating the draft GitHub release, isn't that correct @hadley?

**Comment by randy3k** [comment]
Thanks for the ref to usethis. That feature is more ambitious than the goal of this and that one is github specific. However, as usethis has a similar code, should we move the discussion to usethis?

**Comment by randy3k** [comment]
I see there are two major problems of `use_github_release`. 1. It is github specific, 2. It tags the HEAD ref instead of what is said in `CRAN-RELEASE`. To allow actuary tagging, we need to write both version number and sha to the file.

**Comment by jimhester** [comment]
Yes, it would be great to discuss this in usethis, I think that is the right place for this.

**Comment by jimhester** [comment]
Also I agree that `use_github_release()` should use the commit defined in `CRAN-RELEASE`

**Comment by randy3k** [comment]
I think we still need some changes in devtools. For example, we need to store the tagged version number together with the commit sha in `CRAN-RELEASE`.
