### ISSUE TITLE
 Error: Vignette re-building failed.

### ISSUE THREAD

**Issue by hdvinod** [r-lib/devtools#2140]
I have updated some of my R functions and added some functions to my R package generalCorr
It was OK just 3 weeks ago.
I have not touched the vignettes and yet I get the above error
 Error: Vignette re-building failed.  I tried all kinds of things over several days
to fix the problem in vain.  Sorry to bother.  vinod@fordham.edu
Here is a part of the diagnostic:

```
v  checking for file 'C:\Pack\generalCorr/DESCRIPTION' ...
-  preparing 'generalCorr': (813ms)
v  checking DESCRIPTION meta-information ...
-  installing the package to build vignettes (475ms)
E  creating vignettes (10.5s)
   --- re-building 'generalCorr-vignette.pdf.asis' using asis
   Error: processing vignette 'generalCorr-vignette.pdf.asis' failed with diagnostics:
   Failed to set timestamp: generalCorr-vignette.pdf
   --- failed re-building 'generalCorr-vignette.pdf.asis'
   
   --- re-building 'generalCorr-vignette2.pdf.asis' using asis
   Error: processing vignette 'generalCorr-vignette2.pdf.asis' failed with diagnostics:
   Failed to set timestamp: generalCorr-vignette2.pdf
   --- failed re-building 'generalCorr-vignette2.pdf.asis'
   
   --- re-building 'generalCorr-vignette3.pdf.asis' using asis
   Error: processing vignette 'generalCorr-vignette3.pdf.asis' failed with diagnostics:
   Failed to set timestamp: generalCorr-vignette3.pdf
   --- failed re-building 'generalCorr-vignette3.pdf.asis'
   
   SUMMARY: processing the following files failed:
     'generalCorr-vignette.pdf.asis' 'generalCorr-vignette2.pdf.asis'
     'generalCorr-vignette3.pdf.asis'
   
   Error: Vignette re-building failed.
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
Calls: <Anonymous> ... with_envvar -> force -> do.call -> <Anonymous> -> throw
Execution halted

Exited with status 1.
```

<details>
<summary>`sessioninfo::session_info()`</summary>

- Session info ------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2019-10-27                  

- Packages ----------------------------------------------------------------------------
 package      * version date       lib source        
 abind          1.4-5   2016-07-21 [1] CRAN (R 3.6.0)
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports      1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
 boot           1.3-23  2019-07-05 [1] CRAN (R 3.6.1)
 callr          3.3.2   2019-09-22 [1] CRAN (R 3.6.1)
 car            3.0-3   2019-05-27 [1] CRAN (R 3.6.1)
 carData        3.0-2   2018-09-30 [1] CRAN (R 3.6.0)
 cellranger     1.1.0   2016-07-27 [1] CRAN (R 3.6.0)
 cli            1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
 commonmark     1.7     2018-12-01 [1] CRAN (R 3.6.0)
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 cubature       2.0.3   2018-12-18 [1] CRAN (R 3.6.0)
 curl           4.2     2019-09-24 [1] CRAN (R 3.6.1)
 data.table     1.12.6  2019-10-18 [1] CRAN (R 3.6.1)
 desc           1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
 devtools     * 2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
 digest         0.6.22  2019-10-21 [1] CRAN (R 3.6.1)
 dynlm        * 0.3-6   2019-01-06 [1] CRAN (R 3.6.1)
 ellipsis       0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
 forcats        0.4.0   2019-02-17 [1] CRAN (R 3.6.0)
 foreign        0.8-72  2019-08-02 [1] CRAN (R 3.6.1)
 fs             1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
 generalCorr  * 1.1.4   2019-10-27 [1] local         
 glue           1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
 haven          2.1.1   2019-07-04 [1] CRAN (R 3.6.1)
 hms            0.5.1   2019-08-23 [1] CRAN (R 3.6.1)
 lattice      * 0.20-38 2018-11-04 [1] CRAN (R 3.6.1)
 lmtest         0.9-37  2019-04-30 [1] CRAN (R 3.6.1)
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.0)
 Matrix         1.2-17  2019-03-22 [1] CRAN (R 3.6.1)
 MatrixModels   0.4-1   2015-08-22 [1] CRAN (R 3.6.0)
 meboot       * 1.4-7   2016-11-18 [1] CRAN (R 3.6.0)
 memoise        1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
 mnormt         1.5-5   2016-10-15 [1] CRAN (R 3.6.0)
 nlme         * 3.1-141 2019-08-01 [1] CRAN (R 3.6.1)
 np           * 0.60-9  2018-10-25 [1] CRAN (R 3.6.0)
 openxlsx       4.1.0.1 2019-05-28 [1] CRAN (R 3.6.1)
 pillar         1.4.2   2019-06-29 [1] CRAN (R 3.6.1)
 pkgbuild       1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
 pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
 pkgload        1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits    1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
 processx       3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
 ps             1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
 psych        * 1.8.12  2019-01-12 [1] CRAN (R 3.6.0)
 quadprog       1.5-7   2019-05-06 [1] CRAN (R 3.6.0)
 quantreg       5.51    2019-08-07 [1] CRAN (R 3.6.1)
 R6             2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
 Rcpp           1.0.2   2019-07-25 [1] CRAN (R 3.6.1)
 readxl         1.3.1   2019-03-13 [1] CRAN (R 3.6.0)
 remotes        2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
 rio            0.5.16  2018-11-26 [1] CRAN (R 3.6.0)
 rlang          0.4.1   2019-10-24 [1] CRAN (R 3.6.1)
 roxygen2     * 6.1.1   2018-11-07 [1] CRAN (R 3.6.0)
 rprojroot      1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi     0.10    2019-03-19 [1] CRAN (R 3.6.0)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 SparseM        1.77    2017-04-23 [1] CRAN (R 3.6.0)
 stringi        1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
 stringr        1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
 testthat       2.2.1   2019-07-25 [1] CRAN (R 3.6.1)
 tibble         2.1.3   2019-06-06 [1] CRAN (R 3.6.1)
 usethis      * 1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
 vctrs          0.2.0   2019-07-05 [1] CRAN (R 3.6.1)
 withr          2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
 xml2           1.2.2   2019-08-09 [1] CRAN (R 3.6.1)
 xtable       * 1.8-4   2019-04-21 [1] CRAN (R 3.6.0)
 zeallot        0.1.0   2018-01-28 [1] CRAN (R 3.6.0)
 zip            2.0.4   2019-09-01 [1] CRAN (R 3.6.1)
 zoo          * 1.8-6   2019-05-28 [1] CRAN (R 3.6.1)

[1] C:/Program Files/R/R-3.6.1/library

</details>

**Comment by hdvinod** [comment]
There is a bug in check which causes this frustrating problem to occur.
It sometimes goes away if the dates in NEWS and DESCRIPTION files are updated and also if
all vignettes are ordered by name in the vignettes directory.

**Comment by jimhester** [comment]
If I were to guess I would say make sure you don't have files in `inst/doc` that should be in `vignettes`. But I don't really know how the `R.rsp` package works, you may have better success opening an issue in https://github.com/HenrikBengtsson/R.rsp/issues.

However I don't believe this is really a devtools problem, `devtools::check()` is just a thin wrapper around `R CMD check`, and you will likely see the same behavior there.

**Comment by hdvinod** [comment]
Thanks for your reply..
Why should
devtools::check()
be sensitive to the order in which files are present in the vignettes folder

Also  time stamp failure is attributed by check()
 to re-creation of vignettes, whereas it is often due to the wrong date in
the
DESCRIPTION  or NEWS files.  If you are sure that check() is OK, I will
open the issue in the R.rsp  as you suggested.

Thanks and regards,

On Thu, Oct 31, 2019 at 8:37 AM Jim Hester <notifications@github.com> wrote:

> If I were to guess I would say make sure you don't have files in inst/doc
> that should be in vignettes. But I don't really know how the R.rsp
> package works, you may have better success opening an issue in
> https://github.com/HenrikBengtsson/R.rsp/issues
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_HenrikBengtsson_R.rsp_issues&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=jOon43tKLVRpvfeQu95XS9U8pSo3ZLUjmqbU_jNBdQE&m=usnCSoC34xoDLEy8ajA5MCU3Mg5Eh0jR_yT3bHhL7UI&s=Zms09cz2XXsA1kgp6NCfy5q0Q6QkvUSeGrKyPB_FGzM&e=>
> .
>
> However I don't believe this is really a devtools problem,
> devtools::check() is just a thin wrapper around R CMD check, and you will
> likely see the same behavior there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_r-2Dlib_devtools_issues_2140-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAODK6NBL76DBWI3SARBZMTQRLGR3A5CNFSM4JFTDGK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECXTGCI-23issuecomment-2D548352777&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=jOon43tKLVRpvfeQu95XS9U8pSo3ZLUjmqbU_jNBdQE&m=usnCSoC34xoDLEy8ajA5MCU3Mg5Eh0jR_yT3bHhL7UI&s=F12Oa15OX1S3u2dpCj-p8PpnENjEGSkoQ5dy1eWjxEQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAODK6NTPIQPOT6KQKXSWNDQRLGR3ANCNFSM4JFTDGKQ&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=jOon43tKLVRpvfeQu95XS9U8pSo3ZLUjmqbU_jNBdQE&m=usnCSoC34xoDLEy8ajA5MCU3Mg5Eh0jR_yT3bHhL7UI&s=lw5EdgfSTob34Jo3kqP5UMtuAeNvxvnI6AMYxL0V0N4&e=>
> .
>


-- 

Hrishikesh (Rick) D. Vinod
Professor of Economics, Fordham University
E-Mail: Vinod@fordham.edu Tel 718-817-4065,
Secretary 718-817-4048, Fax 718-817-3518
Web page: http://www.fordham.edu/economics/vinod
ResearchGate says my papers have been cited 2837 times in various research
publications.
