### ISSUE TITLE
Strange problem with run_examples -- example code cut off at % symbol

### ISSUE THREAD

**Issue by cdriveraus** [r-lib/devtools#2151]
I tried to create a MWE for this but couldn't reproduce the problem unfortunately.

2 somewhat long code snippets are found at: https://gist.github.com/cdriveraus/37125c2ff1447b5383e6f7b0f9c1dca0

The first contains the actual function code in my package, the second contains the code that run_examples is trying to run (copied from the temp file reported in the error message). 

On line 274 of the 'function code' file, there is a selection using %in% construction, but on line 202 of the run_examples code (which should be the same!) the code is chopped off until the end of the line, beginning at the % symbol. The rd file in my package is correct, the problem happens somewhere during the run_examples process.  *edited to correct rmd to rd*

**Comment by cdriveraus** [comment]
I believe this to be a relatively new issue, but can't say exactly when. Perhaps introduced in the last 2 months.

**Comment by jennybc** [comment]
You might want to look at your package with respect to recent changes in roxygen2:

https://www.tidyverse.org/blog/2019/11/roxygen2-7-0-0/

Specifically:

> `%` (the Rd comment symbol) is now automatically escaped in markdown text. That means if you previously escaped it with `\%`, you’ll need to remove the backslash and take it back to `%`.
>
> If you forget to do this, you’ll see confusing `R CMD check` notes like:
>
> unknown macro '\item'
> unexpected section header '\description'
> unexpected END_OF_INPUT

**Comment by cdriveraus** [comment]
Good pointer, thanks. You're right that it's related, it was a roxygen bug related to % within \dontrun{ blocks, fixed a couple of days ago. I still don't understand why my rd files were fine, but whatever!
