### ISSUE TITLE
Updating with devtools::install() doesn't work

### ISSUE THREAD

**Issue by AshesITR** [r-lib/devtools#2155]
Whenever I try updating using `devtools::install()` - even in a fresh session - I run into the same error ("Cannot remove prior installation of package 'digest'")

Should be reproducible by

1. creating a new package
2. installing an old version of a package, `digest` and `rlang` both "worked" for me
3. usethis::use_package(...)
4. devtools::install()
5. Allow updating
6. Find error and a broken package installation for the package from 2.

I'm on Windows {7,10} / RStudio 1.2.1511 / R 3.6.1 with devtools 2.2.1.

```
> devtools::install()
These packages have more recent versions available.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: digest (0.6.22 -> 0.6.23) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
digest (0.6.22 -> 0.6.23) [CRAN]
Installing 1 packages: digest
Installing package into ‘C:/Users/Alex/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/digest_0.6.23.zip'
Content type 'application/zip' length 249129 bytes (243 KB)
downloaded 243 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘digest’

```

**Comment by jennybc** [comment]
This is a semi-classic Windows problem, where R sometimes partially installs a package and leaves you in this hopeless state. I find that sometimes you just have to delete a borked package manually. Quit all running R sessions, all instances of RStudio, etc. Delete the digest package from your library "by hand", i.e. however you normally delete a directory. Restart R and do a fresh install of the problem package.

**Comment by AshesITR** [comment]
Actually, `install.packages("digest")` in a fresh R Session does the job for me.
Maybe some packages, such as `rlang` and `digest` are loaded via devtools somehow?
I still think it's worth looking into the issue since `install.packages()` doesn't corrupt the package installation.

**Comment by jimhester** [comment]
As mentioned this is a known issue, and `install.packages()` absolutely will happily install broken packages if you try to install packages which are already loaded on windows.
