### ISSUE TITLE
Error occured during installation.

### ISSUE THREAD

**Issue by CHUNGGAK** [r-lib/devtools#2160]
I use R version 3.6.3 and Ubuntu 18 in Oracle Virtual Box.
I installed libcurl4-gnutls-dev, libxml2-dev, libssl-dev.
But error occurred during installation.
Error message is as below.

`install.packages('devtools')`
/usr/lib/R/bin/R: line 8: uname: command not found
/usr/lib/R/bin/R: line 143: exec: sh: not found

**Comment by jimhester** [comment]
This is not an error in devtools, the R script assumes you have these tools installed and on your PATH.

**Comment by CHUNGGAK** [comment]
Thank you for guide to the place where I can find the answer.

**Comment by CHUNGGAK** [comment]
Thank you for guide to the place where I can find the answer.
