### ISSUE TITLE
Set NOT_CRAN=true when running devtools::install_github

### ISSUE THREAD

**Issue by Marlin-Na** [r-lib/devtools#2164]
It seems that currently this is not set with `devtools::install`. Is this behavior intended?

**Comment by jennybc** [comment]
Off the top of my head, I can't think why `NOT_CRAN` is relevant to `devtools::install_github()`. Can you elaborate?

**Comment by Marlin-Na** [comment]
@jennybc I was trying to relay on `NOT_CRAN` environment variable in the `configure` script to differentiate its behaviors between CRAN machine and a installation with `devtools`. More specifically, I need to bundle an external C++ library within the R package. For CRAN, I will run this step manually before submitting so that this do not need to be run on the CRAN machine. For travis CI and installation with `devtools`, the bundling will run at build time.

For my case, I can definitely relay on other mechanisms to differentiate the behavior. But I guess there are other use cases. For example, to have different compiler options with CRAN machine and a `devtools` installation.

**Comment by jimhester** [comment]
I don't think we should be setting `NOT_CRAN` during installations, and in general I don't think you should be changing installation behavior when users install via devtools vs what is done on CRAN.

**Comment by stefanoborini** [comment]
This was already raised by me, and I repeat it's completely wrong to assume that you are always on CRAN. Most usage of devtools is not done on CRAN.
