### ISSUE TITLE
Possible inconsistence with --no-vignettes option

### ISSUE THREAD

**Issue by iago-pssjd** [r-lib/devtools#2165]
I am running `devtools::check(args = c('--as-cran','--no-vignettes'))` to check the package `sjPlot` I've just modified a minor thing, but I get
```
...
-  installing the package to build vignettes
E  creating vignettes (57.7s)
...
   Error: processing vignette 'tab_bayes.Rmd' failed with diagnostics:
   schannel: failed to receive handshake, SSL/TLS connection failed
   --- failed re-building 'tab_bayes.Rmd'
...
   Error: processing vignette 'tab_model_estimates.Rmd' failed with diagnostics:
   there is no package called 'pscl'
   --- failed re-building 'tab_model_estimates.Rmd'
...
   Error: Vignette re-building failed.

Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
Calls: <Anonymous> ... with_envvar -> force -> do.call -> <Anonymous> -> throw

Exited with status 1.
```
where the errors are mainly `there is no package called '...'`.
I understand that with the option `--no-vignettes`, R code in vignettes is not run so I cannot see why these errors are produced.
This issue seems to be related to #1667

**Comment by jimhester** [comment]
The error is happening when building the vignettes during `R CMD build`, before the `R CMD check` happens, so `--no-vignettes` has no effect. To disable vignettes completely you need to pass `build_args = '--no-build-vignettes'` as well.

But I think this is too much to ask people to know, so I have now added a vignette argument to `check()`, which will do both of these things for you.
