### ISSUE TITLE
devtools:test() works, but devtools:check() fail on functions with if(class(x) == "type") conditional.

### ISSUE THREAD

**Issue by andzajan** [r-lib/devtools#2167]
Hi. I and @grlloyd have stumbled across strange behaviour of the `devtools` package using `R-devel (4.0.0)` and the latest `devtools` package.

I am using R command `class` to determine what data structure object belong to. Based on the object type, function is supposed to do different tasks. Small example is shown below or can be accessed from Github repository [devtoolsCheck](https://github.com/andzajan/devtoolsCheck):

```
#' This is example function to demonstrate that devtools:check() can fail.
#'
#' @param object R object
#' @return The class of the object
#' @examples
#' mat <- matrix(1:20, nrow=5, ncol=5)
#' object_class (mat)
#' @export

object_class <- function (object){
    obj_class <- class(object)
    if (obj_class == "matrix"){
        cat ("Object type is matrix!", "\n")
    } else {
        cat ("Object type isn't matrix!", "\n")
    }
}
```
And corresponding `testthat` test looks like this:
```
  
test_that("Object class is returned", {
    mat <- matrix(1:20, nrow=5, ncol=5)
    expect_output(object_class(mat))
})
```

This works fine with `devtools:test()` and `rcmdcheck::rcmdcheck()`, but fails with `devtools:check()` command. Giving error:
```
 --- value of length: 2 type: logical ---
[1]  TRUE FALSE
```
Full Travis report using `r-devel` version:  
[devtools:check() fails](https://travis-ci.org/andzajan/devtoolsCheck/builds/626808086?utm_source=github_status&utm_medium=notification).

The fix is to specifically only to take the first element of `class` command output, `devtools:check()` and Travis will pass. [Travis report with fix](https://travis-ci.org/andzajan/devtoolsCheck/builds/626813214?utm_source=github_status&utm_medium=notification)
```
obj_class <- class(object)[1]
```

But output from a `class` command for `matrix` object is length of 1, why does `devtools:check()` fail?
```
> mat <- matrix(0, ncol=5, nrow =5)
> class(mat)
[1] "matrix"
> length(class(mat))
[1] 1
> 
```
```
> sessionInfo()
R Under development (unstable) (2019-12-10 r77548)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtoolsCheck_0.0.0.91 testthat_2.3.1        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        compiler_4.0.0    git2r_0.26.1      prettyunits_1.0.2 remotes_2.1.0    
 [6] tools_4.0.0       digest_0.6.22     pkgbuild_1.0.6    pkgload_1.0.2     memoise_1.1.0    
[11] rlang_0.4.1       cli_2.0.0         rstudioapi_0.10   xopen_1.0.0       xml2_1.2.2       
[16] withr_2.1.2       stringr_1.4.0     roxygen2_7.0.2    desc_1.2.0        fs_1.3.1         
[21] devtools_2.2.1    rprojroot_1.3-2   glue_1.3.1        R6_2.4.1          processx_3.4.1   
[26] fansi_0.4.0       rcmdcheck_1.3.3   sessioninfo_1.1.1 callr_3.4.0       purrr_0.3.3      
[31] clipr_0.7.0       magrittr_1.5      whisker_0.4       backports_1.1.5   ps_1.3.0         
[36] clisymbols_1.2.0  ellipsis_0.3.0    usethis_1.5.1     assertthat_0.2.1  stringi_1.4.3    
[41] crayon_1.3.4   
```

**Comment by jennybc** [comment]
> But output from a `class` command for `matrix` object is length of 1

This is changing in R 4.0.0

https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html

**Comment by andzajan** [comment]
Hi @jennybc , thank you for a link, very useful.

All examples in my original post are from R 4.0.0. Why these is still different behaviour going on from `devtools:test()` command, and running tests within `devtools:check()`?

**Comment by jennybc** [comment]
I think it's a difference re: env vars.

https://github.com/hadley/r-pkgs/issues/483#issuecomment-564742085

**Comment by jimhester** [comment]
As jenny noted, this is all expected behavior, so I will close this.

**Comment by andzajan** [comment]
Hi @jimhester , I understand that it could be a case of expected behavior in R 4.0.0. But it really isn't as running `class(x)` in the terminal of current R-devel still returns output of length 1. 

`devtools` package should have consistency. `devtools;test()` should fail in the same way as running tests within `devtools:check()` call. 

Similar inconsistency of outputs was reported here as well. https://github.com/r-lib/devtools/issues/2032
