### ISSUE TITLE
build_vignettes=TRUE does not automatically install 'Suggests' dependencies

### ISSUE THREAD

**Issue by Marlin-Na** [r-lib/devtools#2168]
It seems that `devtools(build_vignettes=TRUE)` does not install the `Suggests` packages prior building the vignette.

Version: devtools_2.2.1.9000

Related: https://github.com/symengine/symengine.R/issues/74

**Comment by jimhester** [comment]
This is true, if you use `build_vignettes = TRUE` you also need to use `dependencies = TRUE`.

**Comment by Marlin-Na** [comment]
@jimhester Thanks for letting me know. For your information, I was referring [Development cycle](http://r-pkgs.had.co.nz/vignettes.html) section of the R packages book.

> You can force building with devtools::install_github(build_vignettes = TRUE). This will also install all suggested packages.

Probably should fix there.

**Comment by Marlin-Na** [comment]
Or in my mind, a probably more reasonable solution is to have the default value of `dependencies` argument as `dependencies = if (build_vignettes) TRUE else NA`.

**Comment by jimhester** [comment]
closed by 54b6dd0e
