### ISSUE TITLE
Dots not passed to install.packages

### ISSUE THREAD

**Issue by infotroph** [r-lib/devtools#2169]
This is a new report for attention, but I'm re-reporting the same issue as #2154, which was closed as supposedly fixed but I still see the reported buggy behavior when running the latest devtools (4cbed16a).

I've checked that my versions of remotes (3fd1845e) and ellipsis (77387d25) are up to date as well; am I missing something or was it not in fact fixed?

**Comment by jimhester** [comment]
It was fixed, and I cannot reproduce it, sorry.

**Comment by infotroph** [comment]
Looks like @danarmak [nailed a key point](https://github.com/r-lib/devtools/issues/2154#issuecomment-564014545): apparently this only happens when all deps are up to date:

```
docker run --rm -it -e PASSWORD=foo rocker/tidyverse:devel R

remotes::install_github(
	c("r-lib/devtools", "r-lib/remotes", "r-lib/ellipsis"),
	upgrade = "always")

usethis::create_package("demo")
install.packages("plotrix") # usethis refuses to add an uninstalled dep
usethis::use_package("plotrix")

# fails
devtools::install_deps(Ncpus = 2, upgrade = "always")
# succeeds, nothing to do
devtools::install_deps(upgrade = "always")
# succeeds, nothing to do
remotes::install_deps(upgrade = "always")

remove.packages("plotrix")

# succeeds, reinstalls plotrix
devtools::install_deps(Ncpus = 2, upgrade = "always")

# fails again
devtools::install_deps(Ncpus = 2, upgrade = "always")
```

**Comment by jimhester** [comment]
Sorry, this docker file does not reproduce the error, are you restarting R after you install devel devtools? With the devel version of devtools this is a warning, not an error, as intended.

**Comment by jimhester** [comment]
Hmm, it seems https://github.com/r-lib/devtools/commit/674b3f8711bfd7aca9ebe8951636f852da32a358 was not included in the 2.2.1 release, I will do a new release shortly to include it

**Comment by jimhester** [comment]
CRAN is not currently accepting packages until the 6th of January, so I cannot submit an update of devtools until then.

**Comment by infotroph** [comment]
OK, yes, I can confirm I see a warning not an error when using master, and I admit I wasn't checking carefully for warning vs. error before.

And I understand that y'all added ellipsis to try to mitigate a very real general usage hazard (that arguments unexpectedly swallowed by `...` are insidious and hard to debug). 

But: 

1. It still seems buggy to accept `...` when dependencies need updating but complain about it when they're up to date.

2. I don't think "a warning not an error" resolves the issue here, because the *only purpose* of `...` in this function is to be passed onward for ultimate use by install.packages. If ellipsis can't check that properly, then either ellipsis should skip checking here or `install_deps` should stop claiming to accept `...`. It seems counterproductive to issue warnings against arguments that are used exactly as documented.

**Comment by jimhester** [comment]
If you don't like the behavior you can set `options(devtools.ellipsis_action = rlang::signal)` and you will receive no output.
