### ISSUE TITLE
spell_check doesn't check if spelling is installed

### ISSUE THREAD

**Issue by mikemahoney218** [r-lib/devtools#2172]
When running `devtools::spell_check()` on a computer without `spelling` installed, `spell_check` fails due to the missing namespace:

```
> devtools::spell_check()
Error in loadNamespace(name) : there is no package called ‘spelling’
```

Other functions such as `devtools::check_rhub()` seem to make use of `check_suggested()` in interactive sessions to prompt users to install the package if needed, rather than just failing. Would it make sense for this function to do the same?

**Comment by jimhester** [comment]
Sure, would be happy to review a PR if you are interested!

**Comment by mikemahoney218** [comment]
Threw up #2173 which I'm pretty sure will do the trick -- thanks!
