### ISSUE TITLE
add package commit date to DESCRIPTION file when building/installing package

### ISSUE THREAD

**Issue by dracodoc** [r-lib/devtools#2183]
It's often helpful to provide detailed package version information to user for bug report. Manually assigned version number may not be updated frequently like commit date, thus it can be useful to add the commit date time to package DESCRIPTION file.

Right now devtools will add a "Built date", but that is just the time it installing the package from source. There is remote SHA if installed from github which is helpful but not directly usable as a commit date.

Thus when devtools install a package from github or from local source, it will be helpful to add the commit date to DESCRIPTION file.

**Comment by dracodoc** [comment]
[Previous discussion dated from 2016](https://github.com/r-lib/devtools/issues/1327)

I think a simple solution is to have an option in building package:
- when a build is planed to be a release (somewhat official and worth tagging with build date), add an entry in description file.
- Simply use the last commit message should be enough, like `git2r::last_commit()`, which have the SHA, Date, commit message.
- Another option is to automatically increase the version number in the development part (9000 section) if the version number is using this scheme.

It's easy to write some code to do this by myself, but it will be best to be included in devtools so it can be triggered by the "build package" action in RStudio. I'd also happy to submit a PR for this.

**Comment by dracodoc** [comment]
Assuming current project is the package in developing

```r
library(git2r)
library(data.table)
library(stringr)

# use all to get a data.frame. there is only one record.
desc_dt <- data.table(read.dcf("DESCRIPTION", all = TRUE))
# increase version in 9000 part
bump_version <- function(ver, inc = 1) {
  parts <- str_split(ver, "\\.")[[1]]
  parts[4] <- as.numeric(parts[4]) + inc
  str_c(parts, collapse = ".")
}
desc_dt[1, Version := bump_version(Version)]
desc_dt[1, LastCommit := capture.output(last_commit())]
write.dcf(desc_dt, "DESCRIPTION")

```

**Comment by jimhester** [comment]
I don't think this is necessary. Given a SHA1 and a repository you can look up the commit date.

**Comment by xhdong-umd** [comment]
When the package is not installed with devtools there is no SHA available. My package is provided in github but I also have a drat repo setup to allow user install without devtools (sometimes it can be tricky for new user to install devtools).

Of course this is kind of less common case...
