### ISSUE TITLE
using source_url for private github repo?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-lib/devtools#2185]
Hi

I would like to use source a R file on a Github repo that is private. If it is not private, I can just use `source_url`. But it does not seem to work if private? and it seems the source_url does not have the `auth_token` argument as other functions do?

This seems to be a popular request/question, see: 

- https://stackoverflow.com/questions/52614317/sourcing-r-files-in-a-private-github-folder
- https://stackoverflow.com/questions/12380491/r-sourcing-private-repos-from-github

Thanks!

**Comment by hadley** [comment]
I think this is out of scope for devtools, since we're generally moving away from tools to provide the ability to source files from arbitrary locations. It's a good idea; just not currently a good fit for devtools.
