### ISSUE TITLE
install_github doesn't work after updating R version

### ISSUE THREAD

**Issue by Janlow** [r-lib/devtools#2186]
Hello! 

I have a data package that I can't get to load in R-studio after I updated R to version 3.6.2. The version of R-studio is 1.2.5033. It still works fine on another computer with R version 3.5.1 and R-studio version 1.1.456. I have tried looking around for similar errors and tried some of the solutions but they don't work for me. Anyone have an answer? 

I am both trying to run devtools::install_github("Janlow/Studi") and remotes::install_github("Janlow/Studi") but I get the same error: 

Downloading GitHub repo Janlow/Studi@master
✓  checking for file ‘/private/var/folders/h4/jhv87tl16gq_whzkplxtkyk40000gn/T/RtmpvKpZhE/remotes16e318e42f40/Janlow-Studi-98a16f2/DESCRIPTION’ (514ms)
─  preparing ‘StudiData’: (686ms)
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘StudiData_0.1.0.tar.gz’ (1m 25.4s)
   
* installing *source* package ‘StudiData’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error : 'use_data_raw' is not an exported object from 'namespace:devtools'
Error: unable to load R code in package ‘StudiData’
Execution halted
ERROR: lazy loading failed for package ‘StudiData’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/StudiData’
Error: Failed to install 'StudiData' from GitHub:
  (converted from warning) installation of package ‘/var/folders/h4/jhv87tl16gq_whzkplxtkyk40000gn/T//RtmpvKpZhE/file16e32cda1f84/StudiData_0.1.0.tar.gz’ had non-zero exit status

**Comment by jimhester** [comment]
`use_data_raw()` no longer exists in devtools, it is in the [usethis](https://github.com/r-lib/usethis) package. Change `devtools::use_data_raw()` to `usethis::use_data_raw()` at https://github.com/Janlow/Studi/blob/427003ef943faa70adaba1e433b493eeee24b4af/R/hello.R#L19. But really you shouldn't have this call in your top level `R` files at all I think.
