### ISSUE TITLE
GitHub Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by daynefiler** [r-lib/devtools#2189]
Hi,

I am now getting emails from GitHub every time I reinstall a private repo:

> Hi @daynefiler,
> 
> On February 13th, 2020 at 16:27 (UTC) your personal access token (repo-pat) using libcurl/7.65.3 was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/37485241/tarball/v0.5.0
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team

Seems like `install_github` will need a new access method for private repositories.

**Comment by jimhester** [comment]
You need to update the remotes package.
