### ISSUE TITLE
Error when installing Liger:  dependency 'RANN.L1' is not available for package 'liger'

### ISSUE THREAD

**Issue by happar73** [r-lib/devtools#2190]
Hi Liger team,

I am a newcomer for our package. Thanks for developing such a good package. As our samples have some batch effects and Seurat integration seems not very ideal for our data, therefore we want to use liger. But when I install the liger, I got error: 

Downloading GitHub repo MacoskoLab/liger@master
Skipping 1 packages not available: RANN.L1
√  checking for file 'C:\Users\AppData\Local\Temp\RtmpkDeFI4\remotes96c818ba2ed2\MacoskoLab-liger-ae5f142/DESCRIPTION' ...
-  preparing 'liger':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  installing the package to process help pages
         -----------------------------------
   **ERROR: dependency 'RANN.L1' is not available for package 'liger'**
-  removing 'C:/Users/AppData/Local/Temp/RtmpqcUQod/Rinst163458f7d3e/liger'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'liger' from GitHub:
  **System command error, exit status: 1, stdout + stderr:**
E> * checking for file 'C:\Users\AppData\Local\Temp\RtmpkDeFI4\remotes96c818ba2ed2\MacoskoLab-liger-ae5f142/DESCRIPTION' ... OK
E> * preparing 'liger':
E> * checking DESCRIPTION meta-information ... OK
E> * cleaning src
E> * installing the package to process help pages
E>       -----------------------------------
E> ERROR: dependency 'RANN.L1' is not available for package 'liger'
E> * removing 'C:/Users/AppData/Local/Temp/RtmpqcUQod/Rinst163458f7d3e/liger'
E>       -----------------------------------
E> ERROR: package installation failed

The session Info is below:
> R version 3.6.2 (2019-12-12)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18362)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] devtools_2.2.2 usethis_1.5.1  Seurat_3.1.2  
> 
> loaded via a namespace (and not attached):
>   [1] TH.data_1.0-10      Rtsne_0.15          colorspace_1.4-1    ellipsis_0.3.0     
>   [5] ggridges_0.5.1      rprojroot_1.3-2     fs_1.3.1            rstudioapi_0.11    
>   [9] leiden_0.3.1        listenv_0.8.0       npsurv_0.4-0        remotes_2.1.1      
>  [13] ggrepel_0.8.1       fansi_0.4.1         mvtnorm_1.0-11      codetools_0.2-16   
>  [17] splines_3.6.2       R.methodsS3_1.7.1   mnormt_1.5-5        lsei_1.2-0         
>  [21] TFisher_0.2.0       pkgload_1.0.2       jsonlite_1.6.1      ica_1.0-2          
>  [25] cluster_2.1.0       png_0.1-7           R.oo_1.23.0         uwot_0.1.5         
>  [29] sctransform_0.2.1   compiler_3.6.2      httr_1.4.1          backports_1.1.5    
>  [33] assertthat_0.2.1    Matrix_1.2-18       lazyeval_0.2.2      cli_2.0.1          
>  [37] prettyunits_1.0.2   htmltools_0.4.0     tools_3.6.2         rsvd_1.0.2         
>  [41] igraph_1.2.4.2      gtable_0.3.0        glue_1.3.1          RANN_2.6.1         
>  [45] reshape2_1.4.3      dplyr_0.8.4         rappdirs_0.3.1      Rcpp_1.0.3         
>  [49] Biobase_2.46.0      vctrs_0.2.2         multtest_2.42.0     gdata_2.18.0       
>  [53] ape_5.3             nlme_3.1-143        gbRd_0.4-11         lmtest_0.9-37      
>  [57] stringr_1.4.0       ps_1.3.0            globals_0.12.5      testthat_2.3.1     
>  [61] lifecycle_0.1.0     irlba_2.3.3         gtools_3.8.1        future_1.15.1      
>  [65] MASS_7.3-51.5       zoo_1.8-6           scales_1.1.0        parallel_3.6.2     
>  [69] sandwich_2.5-1      RColorBrewer_1.1-2  curl_4.3            memoise_1.1.0      
>  [73] reticulate_1.14     pbapply_1.4-2       gridExtra_2.3       ggplot2_3.2.1      
>  [77] stringi_1.4.6       desc_1.2.0          mutoss_0.1-12       plotrix_3.7-7      
>  [81] caTools_1.17.1.3    BiocGenerics_0.32.0 pkgbuild_1.0.6      BiocParallel_1.20.1
>  [85] bibtex_0.4.2.2      Rdpack_0.11-1       SDMTools_1.1-221.2  rlang_0.4.4        
>  [89] pkgconfig_2.0.3     bitops_1.0-6        lattice_0.20-38     ROCR_1.0-7         
>  [93] purrr_0.3.3         htmlwidgets_1.5.1   processx_3.4.1      cowplot_1.0.0      
>  [97] tidyselect_1.0.0    RcppAnnoy_0.0.14    plyr_1.8.5          magrittr_1.5       
> [101] R6_2.4.1            gplots_3.0.1.1      multcomp_1.4-11     withr_2.1.2        
> [105] pillar_1.4.3        sn_1.5-4            fitdistrplus_1.0-14 survival_3.1-8     
> [109] tibble_2.1.3        future.apply_1.4.0  tsne_0.1-3          crayon_1.3.4       
> [113] KernSmooth_2.23-16  plotly_4.9.1        grid_3.6.2          data.table_1.12.8  
> [117] callr_3.4.0         metap_1.2           digest_0.6.24       tidyr_1.0.0        
> [121] numDeriv_2016.8-1.1 R.utils_2.9.2       RcppParallel_4.4.4  stats4_3.6.2       
> [125] munsell_0.5.0       viridisLite_0.3.0   sessioninfo_1.1.1  

Can you help me fix it?
Thanks very much!
Yale

**Comment by jimhester** [comment]
I think maybe you should open this in the [liger repository](https://github.com/MacoskoLab/liger)?
