### ISSUE TITLE
option for disabling interactive rhub check

### ISSUE THREAD

**Issue by coatless** [r-lib/devtools#2195]
When I'm checking packages, I sometimes forget to add `interactive = FALSE` to:

```r
devtools::check_rhub()
```

This causes my R console to be taken over with streaming results... 

Thus, would there be any objection if I added a profile variable? e.g.

```r
interactive = getOption("devtools.interactive_check", TRUE)
```

**Comment by jimhester** [comment]
You can always use an interrupt, e.g. `CTRL-C` to cancel the interactive output, the job still continues to run on R-hub in this case.
