### ISSUE TITLE
Text Detection from an Image using R

### ISSUE THREAD

**Issue by maniya900** [r-lib/devtools#2197]
Hello All,
I am trying to read an .PNG image and need to extract the text from that image.
I used tesseract and magick packages but output is weird.Please find the below screenshots and please let me know what should be done to solve it.

NOTE:M rookie in R programming
![image](https://user-images.githubusercontent.com/41445716/76545111-333e5980-64af-11ea-8a29-72e054b9e4dd.png)

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by maniya900** [comment]
Source:
![image](https://user-images.githubusercontent.com/41445716/76545378-ac3db100-64af-11ea-99ea-39bf977c2291.png)

**Comment by maniya900** [comment]
> This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer)

Sure will post there..thanks for your reply
