### ISSUE TITLE
Print which variables are missing/extra in the documentation

### ISSUE THREAD

**Issue by julianbarg** [r-lib/devtools#2198]
When a package which contains a dataset is checked (devtools::check or check button in RStudio), and there is a mismatch between the columns present and columns documented, the console will first print a list of the columns present, and then a list of the columns documented. Obviously, this is very uninformative, especially if the order is different. Instead (or in addition) devtools should provide the specific list of columns that are absent/extra in the documentation. Assuming that devtools just obtains a character vector for both the variables in the dataset, and the variables in the documentation, two calls to %in% would be sufficient to do so.

**Comment by jimhester** [comment]
This is controlled by `R CMD check`, shipped by R core, not devtools, there isn't much we can do unfortunately.
