### ISSUE TITLE
Spell check does not for for two or more languages

### ISSUE THREAD

**Issue by samuel-rosa** [r-lib/devtools#2199]
I have a package in which the documentation in written in English (functions) and a second language (vignettes). These languages are set in the `Language` field of the `DESCRIPTION` file. This is done following the 'Writing R Extensions' manual:

> A `‘Language’` field can be used to indicate if the package documentation is not in English: this should be a comma-separated list of standard (not private use or grandfathered) IETF language tags as currently defined by RFC 5646 (https://tools.ietf.org/html/rfc5646, see also https://en.wikipedia.org/wiki/IETF_language_tag), i.e., use language subtags which in essence are 2-letter ISO 639-1 (https://en.wikipedia.org/wiki/ISO_639-1) or 3-letter ISO 639-3 (https://en.wikipedia.org/wiki/ISO_639-3) language codes.

When running `devtools::spell_check()`, the following error message is issued:

```
> devtools::spell_check()
Error: Dictionary file not found: pt_BR, EN_US.dic
``` 

I haven't found a way around this.

**Comment by jennybc** [comment]
I suspect this issue should be directed towards https://github.com/ropensci/spelling.

**Comment by jimhester** [comment]
Yep, `devtools::spell_check()` is a thin layer over the spelling package, so definitely this should be opened there.
