### ISSUE TITLE
check_win(email = "...") should reset DESCRIPTION once done

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2205]
So you avoid accidentally changing the author

**Comment by jennybc** [comment]
Seems to have come up before in #2152 and was allegedly fixed in #2157?

**Comment by hadley** [comment]
Either it's broken again in `devtools:::check_win()` or I need to update devtools

**Comment by hadley** [comment]
Looks like I just needed to upgrade devtools 😢
