### ISSUE TITLE
submit_cran() errors confirming submission: "argument is of length zero"

### ISSUE THREAD

**Issue by matthewcornell** [r-lib/devtools#2208]
Hi Folks,

Thanks very much for your work.

My issue: When running `submit_cran()` on a package that we have successfully submitted in the past, I now get this error:

> ...
> Uploading package & comments
> Confirming submission
> Error in if (new_url$query$submit == "1") { : argument is of length zero

The line is [here](https://github.com/r-lib/devtools/blob/03537c6c6f1f6db2e74874f38d5457708ef69fc6/R/release.R#L348). My naive guess is that the POST is failing due to something on the CRAN side, but their site lists nothing about not accepting submissions.

Any help would be awesome!

devtools version: 2.0.2

`version` output:

> platform       x86_64-apple-darwin15.6.0   
> arch           x86_64                      
> os             darwin15.6.0                
> system         x86_64, darwin15.6.0        
> status                                     
> major          3                           
> minor          6.0                         
> year           2019                        
> month          04                          
> day            26                          
> svn rev        76424                       
> language       R                           
> version.string R version 3.6.0 (2019-04-26)
> nickname       Planting of a Tree

**Comment by jimhester** [comment]
devtools 2.0.2 is quite a few releases ago, could you update to a more recent version of devtools, or preferably the devel version, which refactors some of this code to produce more actionable errors when CRAN is down?

**Comment by matthewcornell** [comment]
My mistake: I am currently using 2.2.2 . Please: how do I install the dev version?

**Comment by jimhester** [comment]
`remotes::install_dev("devtools")`

**Comment by matthewcornell** [comment]
I believe it worked, though I did get an Error:

![Screen Shot 2020-04-09 at 1 14 58 PM](https://user-images.githubusercontent.com/1034007/78922191-25ef9d00-7a64-11ea-8689-e32a37e5883b.png)

> > devtools::submit_cran()
> Is your email address cornell@umass.edu?
> 1: No
> 2: Nope
> 3: Yup
> 
> Selection: 3
> Building
> pdflatex not found! Not building PDF manual.
> ✓  checking for file ‘/Users/cornell/IdeaProjects/zoltr/DESCRIPTION’ ...
> ─  preparing ‘zoltr’: (472ms)
> ✓  checking DESCRIPTION meta-information ...
> ─  installing the package to build vignettes (349ms)
> ✓  creating vignettes (6.5s)
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘zoltr_0.5.0.tar.gz’
>    Warning: invalid uid value replaced by that for user 'nobody'
>    Warning: invalid gid value replaced by that for user 'nobody'
>    
> Submitting file: /var/folders/zk/3j9j9y1s00q6j0xn7_60v7s9y8f565/T//Rtmp1TiHtb/zoltr_0.5.0.tar.gz
> File size: 50.9 Kb
> Ready to submit zoltr (0.5.0) to CRAN?
> 1: I forget
> 2: No way
> 3: Yeah
> 
> Selection: 3
> Uploading package & comments
> Confirming submission
> Package submission successful.
> Check your email for confirmation link.
> Error in get0(oNam, envir = ns) : 
>   lazy-load database '/Users/cornell/Library/R/3.6/library/usethis/R/usethis.rdb' is corrupt
> In addition: Warning message:
> In get0(oNam, envir = ns) : internal error -3 in R_decompress1
>
