### ISSUE TITLE
installation of package ‘devtools’ had non-zero exit status

### ISSUE THREAD

**Issue by TJrogers86** [r-lib/devtools#2211]
I am trying to install devtool but I keep getting the following warnings:

Warning messages:
1: In install.packages("devtools") :
  installation of package ‘curl’ had non-zero exit status
2: In install.packages("devtools") :
  installation of package ‘openssl’ had non-zero exit status
3: In install.packages("devtools") :
  installation of package ‘httr’ had non-zero exit status
4: In install.packages("devtools") :
  installation of package ‘rversions’ had non-zero exit status
5: In install.packages("devtools") :
  installation of package ‘gh’ had non-zero exit status
6: In install.packages("devtools") :
  installation of package ‘covr’ had non-zero exit status
7: In install.packages("devtools") :
  installation of package ‘usethis’ had non-zero exit status
8: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status

Any advice??

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
