### ISSUE TITLE
[feature request] Create notes/changelog.md from git commits

### ISSUE THREAD

**Issue by mccroweyclinton-EPA** [r-lib/devtools#2212]
I am not sure if this is the right place to post this or even if this is possible in R but I figure I would give it a shot and this seems like the best place to request this.

The concept is simple, Git commit messages can be formatted so that all the relevant information needed to generate changelogs is there. I am requesting a feature that would allow for automatically generating a changelog based off these preformatted git commit messages. An example implementation can be found here

https://medium.com/jobtome-engineering/how-to-generate-changelog-using-conventional-commits-10be40f5826c.

These changelogs can possibly be extended with either rmarkdown or roxygen2 comment tags in another file to make into a useful notes file since notes files are preferred in R packages as opposed to simple changelogs.

Thank you for your consideration.

**Comment by jimhester** [comment]
If you are interested in this maybe consider the [fledge](https://krlmlr.github.io/fledge/articles/fledge.html) package.

We have no plans to add similar functionality to devtools, and generally feel that commit messages and NEWS entries serve different purposes and should be written for different audiences. 

NEWS is intended for users, to describe _what_ has changed. Commit messages are intended for developers to describe _why_ a change occurred.
