### ISSUE TITLE
devtools::test_file not working when file name starts with test_

### ISSUE THREAD

**Issue by maximilianmordig** [r-lib/devtools#2213]
The convention is that the file name starts with `test-`, not `test_`. In the latter case, `test_file` does not work currently.

https://github.com/r-lib/devtools/blob/b166195be72927a003e6937de5c3239881095a9f/R/test.R#L180

In this line, you remove the `test` prefix. On the other hand, in `testthat:::filter_test_scripts`, you remove "test-?" (see https://github.com/r-lib/testthat/blob/de3cff6bb59a957cf4078e127a9ea9a616ca7fea/R/test-files.R#L57).

So a fix would be to replace the quoted line 180  above: `"test" -> "test-?"`

**Comment by hadley** [comment]
This should now be resolved — testthat strips both `test-` and `test_` (https://github.com/r-lib/testthat/blob/snapshot-file/R/context.R#L51-L52) and so does devtools (https://github.com/r-lib/devtools/blob/master/R/active.R#L40-L41).
