### ISSUE TITLE
Addin does not appear when installing package with devtools::install

### ISSUE THREAD

**Issue by Timag** [r-lib/devtools#2214]
I just started a new package and when i tried to install it at work with devtools::install the addin is not listed in the "addins list" in Rstudio.

From what i see it might not only be a problem in my package but is also depend on the installation method i choose:

**devtools::install_github() works:**

```
devtools::install_github("Timag/code2R")
library(code2r)

```

**devtools::install() does not:**

```
remove.packages("code2r")
tmp <- tempfile()
download.file(url = "https://github.com/Timag/code2R/archive/master.zip", destfile = tmp)
unzip(tmp, exdir = "code2r")
devtools::install("code2r/code2r-master")
library(code2r)
```

**Sitenote:**

In the second step, the error:

> Error in eapply(pkgload::ns_env(pkg$package), force, all.names = TRUE) : 
>   cannot open file 'C:/Users/User11/Documents/R/win-library/3.6/code2r/R/code2r.rdb': No such file or directory

might appear which goes away after restarting rstudio. I will inspect that tomorrow.

**Expected output:**

![image](https://user-images.githubusercontent.com/9567384/79892929-9652d280-8403-11ea-88a7-d8f55c7b809c.png)

**Comment by jimhester** [comment]
I don't think this is a bug in devtools.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
