### ISSUE TITLE
If rlang have newer source version for windows, install_github could fail because of locking

### ISSUE THREAD

**Issue by dracodoc** [r-lib/devtools#2223]
I have rlang 0.4.5 binary installed
```r
> install.packages("rlang")
Installing package into ‘D:/Lib/R_user_lib’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.4.5  0.4.6              TRUE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/rlang_0.4.5.zip'
Content type 'application/zip' length 1112530 bytes (1.1 MB)
downloaded 1.1 MB

package ‘rlang’ successfully unpacked and MD5 sums checked
```
while installing a package with `install_github`, I chose to only update CRAN packages, 

```r
> devtools::install_github("ctmm-initiative/ctmmweb")
Downloading GitHub repo ctmm-initiative/ctmmweb@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: rlang (0.4.5 -> 0.4.6) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
2
rlang        (0.4.5 -> 0.4.6   ) [CRAN]
```
then it will ask me 
>   There is a binary version available (and will be installed) but the source version is later:
      binary source
rlang  0.4.5  0.4.6

I chose Not to install from source, then it will download 0.4.5 and try to install it again, even I already have 0.4.5 installed. In the end the package installation will fail.

```r

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/rlang_0.4.5.zip'
Content type 'application/zip' length 1112530 bytes (1.1 MB)
downloaded 1.1 MB
...
package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'ctmmweb' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

```

I cannot pass this failure loop unless I chose to install rlang 0.4.6 from source.

I think the problem is, once the process scheduled to install 0.4.6, even user chose not to install from source, it will try to install binary version even there is a same version binary package installed already. Then somehow this will cause problem.

Either don't try to install the same version binary, or fix the problem of installing same version binary again will fix this.

**Comment by jennybc** [comment]
You might find this issue helpful, for this case and just in general as a Windows user:

https://github.com/rstats-wtf/what-they-forgot/issues/62

**Comment by dracodoc** [comment]
Yes I knew I often need to restart R session for package loading/unloading errors. I did restart session before each command. With the commands I shown above, I just install rlang but didn't load it. I also restarted the R session right before running `devtools::install_github`, which is the first thing I do when I met package installation problems.

To verify it again, I just started from scratch again, still same result.

The issue is as I described, devtools will install rlang when option "CRAN only" is selected, even after user chose not to install source later.

Interestingly, using remotes::install_github don't have this problem, because there is no "update packages from CRAN" option, only have "whether to install source" question. So once user chose not to install source, it will not attempt to install binary version.

**Comment by dracodoc** [comment]
I think I knew why. With `remotes::install_github` it's the same, it also planned to install rlang, and go ahead to install rlang 0.4.5 binary again when I chose not to install source newer version. 

However rlang is not loaded so remotes can install it again without problem.

With devtools, rlang is loaded by devtools (even I restarted R session, didn't load devtools, only used `devtools::install_github`), so it cannot install rlang again.

I think I met this problem before. Whenever there is a rlang newer source version in windows, I met this problem with devtools::install_github. I have to install the source version to solve this. This is not a big problem for me, but our webapp was supposed to be used many users that not too familiar with R, they will not be able to handle this kind of problems (they probably cannot install Rtools in windows and install package from source too, which will bring more problems).

**Comment by jennybc** [comment]
rlang is used by devtools, so even though you don't load it, the use of `devtools::install_github()` does. So, yes, for the "rlang + Windows" combo, `remotes::install_github()` will be more robust to these DLL locking issues.

**Comment by dracodoc** [comment]
I changed the title to better reflect the issue. The problem now is
- if user have latest binary installed and chose not to install source version, should not try to install binary version again. This doesn't cause problem in normal cases, but is still not right.

The temporary solution is to ask user to use remotes instead, but I think the logic can be improved and solve this kind of problem all together. I will submit a issue in remotes since it should belong to remotes.
