### ISSUE TITLE
Error in loadNamespace: cli >= 2.0.2 is required

### ISSUE THREAD

**Issue by yzhang5158** [r-lib/devtools#2224]
I was trying to install a library from GitHub in R Studio and I encountered such an error:

`> devtools::install_github("haleyjeppson/ggmosaic")`
`Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘cli’ 2.0.0 is already loaded, but >= 2.0.2 is required`

I was wondering what this means and how I should solve this problem. Thanks!

**Comment by jimhester** [comment]
The easiest workaround is `install.packages("cli")`.

**Comment by alexmorenovi** [comment]
I also had that issue, I had to remove the cli package because it wasn¿t updating correctly, then I re-installed it and everything worked just fine.

**Comment by sandramacheri2498** [comment]
In my case I installed the "cli" package but I keep getting the same error. Advice?

**Comment by jennybc** [comment]
@sandramacheri2498 The entry-level advice is to make absolutely 100% sure that, after a confirmed successful re-installation of cli, that you also re-start R, making sure that it's a complete clean restart.

**Comment by AnotherDataGuy** [comment]
Just the same issue. 
I couldn't manage to update it. I was getting the warning: cannot remove prior installation of package ‘cli’).

So I first removed the package:
remove.packages("cli")

then installed it again:
install.packages("cli")

**Comment by KWigg4** [comment]
Thanks so much- uninstalling and reinstalling cli helped me after an hour of swearing :)

**Comment by omrctnr** [comment]
> Just the same issue. I couldn't manage to update it. I was getting the warning: cannot remove prior installation of package ‘cli’).
> 
> So I first removed the package: remove.packages("cli")
> 
> then installed it again: install.packages("cli")

It worked!
Thank you

**Comment by Bakazola99** [comment]
Thank you for this. I think the issue is after installing "cli" try to restart the R. it works well for me with that.

**Comment by treyhamilton** [comment]
Hi,

I have everything updated and installed 100% however, I was trying to use this to extract a file that I found and received the following output:

Please wait...
This depends on your internet connection speed and 'size' of content.

Error in str_match(css, el_re) :
lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/stringi/R/stringi.rdb' is corrupt
In addition: Warning messages:
1: In str_match(css, el_re) : restarting interrupted promise evaluation
2: In str_match(css, el_re) : internal error -3 in R_decompress1

**Comment by stuwrighthealthecon** [comment]
Just to add in case its useful but uninstalling and re-installing cli didn't work for me but then updating to latest version of RStudio seems to have fixed it

**Comment by chinedu2301** [comment]
remove cli and re-install it. That should help. remove.packages("cli") and afterwards install.packages("cli")

**Comment by idirdehmous** [comment]
remove cli  
reinstall it , if another package is loading it , be sure that you have loaded cli first
