### ISSUE TITLE
check support for _R_CHECK_*_ONLY_ env vars?

### ISSUE THREAD

**Issue by tdhock** [r-lib/devtools#2225]
https://cloud.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages says
```
On most systems, R CMD check can be run with 
only those packages declared in ‘Depends’ 
and ‘Imports’ by setting environment variable 
_R_CHECK_DEPENDS_ONLY_=true, 
whereas setting _R_CHECK_SUGGESTS_ONLY_=true
 also allows suggested packages, 
but not those in ‘Enhances’ nor those not mentioned
 in the DESCRIPTION file. It is 
recommended that a package is checked with 
each of these set, as well as with neither. 
```
so I was wondering if support for these options could be added to devtools::check?
I ask because devtools::check already supports the similar option:
```
force_suggests: Sets _R_CHECK_FORCE_SUGGESTS_. If FALSE (the
          default), check will proceed even if all suggested packages
          aren't found.
```

**Comment by jimhester** [comment]
You can supply additional environment variables to use during the check with the `env_vars` variable, e.g. `devtools::check(env_vars = c(_R_CHECK_DEPENDS_ONLY_="true"))`

I don't really want to go down the road of adding additional arguments for every environment variable available to tweak R CMD check, as there are [a lot](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#index-_005fR_005fCHECK_005fALL_005fNON_005fISO_005fC_005f) of them.

**Comment by tdhock** [comment]
ok thanks for the info, that is fine to only support a few of the env vars as arguments.

**Comment by samuel-rosa** [comment]
You will have to use:

     devtools::check(env_vars = c(`_R_CHECK_DEPENDS_ONLY_` = TRUE))
