### ISSUE TITLE
update_packages(): skipping n packages not available - how to make a package available?

### ISSUE THREAD

**Issue by jzadra** [r-lib/devtools#2230]
My team uses an internal package that is hosted on github in a public repo.  When i use `update_packages` either without arguments, or specifying our package, it reports that it is not available.

I've looked all over to try to figure out if there is something extra that has to be done to make a package "available" to `update_packages()`, but I"m not having any luck.  Can someone point me to such a resource or indicate what might be wrong?

**Comment by jimhester** [comment]
If it is installed via `devtools::install_github()` then it will update automatically via `update_packges()`.

If you install the package locally via `devtools::install()` it will not.

You will have to provide more information and a reproducible example in order to help you further.

**Comment by jzadra** [comment]
Got it. Thanks!
