### ISSUE TITLE
check() test request: https URL check now part of CRAN submission manual check

### ISSUE THREAD

**Issue by pnovack-gottshall** [r-lib/devtools#2232]
Hi,

Feature request for an additional check() in devtools. CRAN is now flagging URLs that don't begin https and rejecting packages with http submitted during manual check. Can you add a test in check() to search package docs for URL and flag those that aren't https?

Thanks,
Phil

**Comment by hadley** [comment]
Can you please provide more details?

**Comment by hadley** [comment]
In general, we're moving away from `devtools::release()`, and unfortunately can't provide automated verification of the manual checks that CRAN sometimes requires. Instead, you might want to file an issue with more details over at https://github.com/DavisVaughan/extrachecks.

**Comment by pnovack-gottshall** [comment]
Thanks, will do.
