### ISSUE TITLE
Give more detailed explanation of `args` argument to `devtools::check`

### ISSUE THREAD

**Issue by rorynolan** [r-lib/devtools#2233]
I find that `devtools::check(args = c("--no-examples", "--no-tests"))` works fine but devtools::check(args = "--no-examples --no-tests") does not work; instead it warns `Warning: unknown option ‘--no-tests --no-examples’` and carries on and performs the tests and examples. This is surprising behaviour, particularly for someone who is used to running `R CMD CHECK` from the command line. It would be good to make clear in the docs that the spaced approach will not work with `devtools::check()`.

I recently had a PR for this very reason accepted to the `rcmdcheck` package (https://github.com/r-lib/rcmdcheck/pull/125). Are you interested in such a PR for `devtools`? If so how would you like me to do it? Could just `@inheritParams rcmdcheck::rcmdcheck`?

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/devtools/commit/020c1d26f2b3c7ee926da94e0406cbb40985b573
