### ISSUE TITLE
`devtools::run_examples()` now running with warnings

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/devtools#2234]
Hi, I'm now seeing these warnings below, for any R packages, and on multiple machines. My main development machine is running R 4.0.1, devtools 2.3.0, pkgload 1.1.0.

```r
devtools::run_examples()
```

```
Warning messages:
1: `run_example(run=)` is deprecated, please use `run_example(run_dontrun=)` instead
2: `run_example(test=)` is deprecated, please use `run_example(run_donttest=)` instead
```

`devtools::check()` runs clean without warnings.

**Comment by jimhester** [comment]
Yes, it is already fixed in the devel version of devtools (https://github.com/r-lib/devtools/commit/b2136ff3a3ef67d1ce0af5d681a8b3dd8fd97e33), will be fixed in the next CRAN release

**Comment by mjsteinbaugh** [comment]
Awesome thanks @jimhester , I'll just run the latest version off GitHub for the time being
