### ISSUE TITLE
Developing 2 packages - Size difference

### ISSUE THREAD

**Issue by robertoromor** [r-lib/devtools#2236]
I am developing 2 different packages one is very basic less than 1k lines of code and 5-10 dependencies. The other one is more complex with more than 10k lines of code and 20 dependencies. Why  the package with 1k lines of code has more than 9.7gb and one with 10k lines of code 5.6gb? What am I doing wrong?

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

The difference must come from non-code related sources, e.g. data you have in the package directories.
