### ISSUE TITLE
Problem with install_github (maybe issues with environment variables?)

### ISSUE THREAD

**Issue by ThiagoRBM** [r-lib/devtools#2239]
Hello all,

Last week I was trying to solve a problem with python, with Path variables.
This week, apparently, I can't install packages on R via github. The error I get is the following:

Error: Failed to install 'AnomalyDetection' from GitHub:
  System command 'Rcmd.exe' failed, exit status: -1, stdout + stderr empty

All the packages I try to install return me this message. I'm not sure this is due to environment variable issue, but I think it can be.

Also, I tried upgrading R, from 3.6 to 4.0, but nothing changed.

Any help would be welcome!

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
