### ISSUE TITLE
Error with install_github() inserting "commit/" into URL rather than "src/"

### ISSUE THREAD

**Issue by Prometheus77** [r-lib/devtools#2242]
Trying to set up an R package in a private (corporate) Bitbucket repo for my teammates to use. The `install_bitbucket()` function works for other repos I've made, but not this one.

When I run:

`devtools::install_bitbucket("myorg/mypackage", auth_user = "myemail@mydomain.com", password = "mypassword")`

It returns the errror:

```
Downloading bitbucket repo myorg/mypackage@master
Error: Failed to install 'mypackage' from Bitbucket:
  cannot open URL 'https://api.bitbucket.org/2.0/repositories/myorg/mypackage/commit/master'
```

The actual URL for my package is `https://bitbucket.org/myorg/mypackage/src/master/`. I'm assuming the `api.bitbucket.org` bit isn't a problem, but the `commit/` probably is. Why is this occurring, and is there a way to override it?

**Comment by hadley** [comment]
Unfortunately none of the remotes developers (which is the source of this function) use bitbucket, so unless you're willing to dive into the source yourself (https://github.com/r-lib/remotes/blob/master/R/install-bitbucket.R) it's unlikely that we can be much help.
