### ISSUE TITLE
Prefer credentials package over GITHUB token env vars

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2243]

**Comment by hadley** [comment]
Or possibly just switch to using gh package.

**Comment by jimhester** [comment]
I don't really see a ton of benefit to this it over just using environment variables, if a malicious agent has enough permissions to see the environment variables of a process they basically already own that process.

Some packages, e.g. remotes won't really be able to use the credentials package, so users will have to have set the PAT as an environment variable at some point anyway.

It seems like a bunch of extra work for very minor convenience on the users part.

**Comment by hadley** [comment]
The main advantage is that the user can just set up git credentials interactively once, rather than having to also set up git credentials + mess with `.Renviron`. I think eliminates a potential pain point in the git setup process for relatively little cost.

(But I realise I was wrong in the title — we shouldn't prefer credentials; we should check them if the env var isn't set)
