### ISSUE TITLE
Custom repository incorrectly listed as 'CRAN' in `install_github()`

### ISSUE THREAD

**Issue by ms609** [r-lib/devtools#2244]
My CRAN package 'TreeDist' contains an `Additional_repositories:` entry in its `DESCRIPTION` file, pointing to a repository that I host on GitHub.

When a user installed 'TreeDist', using `install_github('ms609/TreeDist')`, they were prompted to update packages with:

```
1: All                                    
2: CRAN packages only                    
3: None                                  
4: ape       (5.3    -> 5.4       ) [CRAN]
5: phangorn  (2.5.5  -> 2.6.0.0   ) [CRAN]
6: TreeTools (1.0.0  -> 1.0.0.9000) [CRAN]
7: bit       (1.1-14 -> 1.1-15.2  ) [CRAN]
```

But the latest version of 'phangorn' and 'TreeTools' on CRAN was 2.5.5 and 1.0.0, which the user already had installed; the proposed updates (v2.6.0.0 & v1.0.0.9000) were hosted on my custom repository.

I would interpret this to suggest that the 'phangorn' and 'TreeTools' updates would be downloaded from CRAN.  This feels like a potential security risk: the user is not given the choice to decide whether or not they trust my personal repo.  Is it possible for the tag to reflect the true source of the linked files?

**Comment by jimhester** [comment]
CRAN here is any CRAN-like repository set in `options(repos)`.

It is not really possible to differentiate between them, and even if it was I would consider it out of scope for what remotes is trying to accomplish.

Additional_repositories is really meant for packages which are not available on CRAN, if your package is release on CRAN as well I would suggest removing that field from your package DESCRIPTION.
