### ISSUE TITLE
install_github() complains about lib argument if SHA1 has not changed.

### ISSUE THREAD

**Issue by rpruim** [r-lib/devtools#2245]
Here's the output.
```
Skipping install of 'ggformula' from a github remote, the SHA1 (cb354fb5) has not changed since last install.
  Use `force = TRUE` to force installation
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `lib`

Did you misspecify an argument? 
```

But if the package is not up to date, installation works (and `lib` is used).  This is not a big problem, but it is a bit confusing.

**Comment by jimhester** [comment]
There isn't really a way to address this.

You can set `options(devtools.ellipsis_action = rlang::signal)` to silence the warning if you wish.

**Comment by rpruim** [comment]
Thank. I'll probably just ignore the extra warning when it happens.
