### ISSUE TITLE
Error with install_github: "Could not find tools necessary to compile a package"

### ISSUE THREAD

**Issue by leahrosen** [r-lib/devtools#2247]
Hi,

When I try to install certain packages with `install_github`, I get the following error:
```
Error: Failed to install [package] from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```
However, when I run `pkgbuild::check_build_tools(debug = TRUE)` I get the following output:
```
> pkgbuild::check_build_tools(debug = TRUE)
Trying to compile a simple C file
Running \
  /nfs/research1/marioni/Leah/software/anaconda3/envs/scIB-R-integration/lib/R/bin/R \
  CMD SHLIB foo.c
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() :
  argument is of length zero
Calls: <Anonymous> -> .shlib_internal
Execution halted
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```
First I thought this issue was package-specific, but now I've had the issue with 2 packages (`MacoskoLab/liger` and `immunogenomics/harmony`).

I'm running R version 3.6.1 and would like to sick with that for compatibility reasons. I'm also happy to provide my sessionInfo, if that would help, but didn't want to clutter the question.

Any help would be much appreciated.

Thanks!

**Comment by jimhester** [comment]
Something is wrong with your anaconda environment. If you want to use that compiler toolchain you will have to use conda specific support venues.
