### ISSUE TITLE
Handy function to reset options to defaults

### ISSUE THREAD

**Issue by stevecondylios** [r-lib/devtools#2257]
Resetting options to their defaults can be a little cumbersome (I have just come from look around [here](https://stackoverflow.com/questions/15946953/how-to-set-r-to-default-options/63104681), and [here](https://stackoverflow.com/questions/36848785/how-do-i-reset-all-options-arguments-to-their-default-values))

It could be useful to have something easily available, perhaps:

```R
reset_options <- function() {
  default_opts <- callr::r(function(){options()})
  options(default_opts)
}
```
Note: there may already be easier/better ways of doing this. Apologies in advance if that's the case here

**Comment by jimhester** [comment]
You may want to consider using `callr::r_vanilla()` to do this, so that any options changed in your .Rprofile are not included.

But in general I don't think this function needs to be in devtools.

**Comment by jennybc** [comment]
Base R should arguably expose the (default) options in some programmatic way. I've also often wanted a way to see the options "in force" and understand which are R defaults vs., say, set via an `.Rprofile`. Basically something like `git config --list --show-origin`. You @stevecondylios might consider opening an issue here: https://github.com/HenrikBengtsson/Wishlist-for-R/issues

**Comment by hadley** [comment]
Also, you should be aware of [withr](http://withr.r-lib.org), which allows you to temporarily set options.
