### ISSUE TITLE
test() should support testing frameworks other than testthat

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2259]
We should keep the existing special case for testthat (since it gives nicer for the interactive case), but we should execute all other files in `tests/` in a new process.

Will also need to set an env var (e.g. `DEVTOOLS_TEST = true`) so that we can opt-out if needed.

cc @schloerke @yihui

**Comment by yihui** [comment]
FYI `Cmd + Shift + T` in RStudio IDE already does this when the package project does not use **devtools**, so you don't really need to wait for `R CMD check` (as you mentioned yesterday but I didn't have a chance to tell you).

**Comment by hadley** [comment]
In that case, and given that no one else has requested this, I'm going to close since it's unlikely to rise to the top of our priority list.
