### ISSUE TITLE
Be less aggressive about documenting in check()

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2263]
Not sure how to detect this, but when you’re doing a PR to someone else’s repo, it’s annoying that check documents and introduces a bunch of spurious changes. 

Maybe a reasonable heuristic is to only rebuild if roxygen version is the same, otherwise emit a very clear warning.

**Comment by jimhester** [comment]
I really think it would be better to not run `document()` by default in `check()` at all, but I know you disagree.

**Comment by hadley** [comment]
I think I agree that we shouldn’t have done this in the first place. But I’m concerned that if we change it now it’s going to cause a lot of unpleasant surprises for people so we need to figure out some compromise position.

**Comment by jimhester** [comment]
I think your idea of only rebuilding if the roxygen version matches is a good compromise.
