### ISSUE TITLE
check fails with "locked binding of ‘q’ cannot be changed"

### ISSUE THREAD

**Issue by ringprince** [r-lib/devtools#2265]
I can't run check().  The check itself does not run, but fails with ' locked binding of ‘q’ cannot be changed'.

This is with

- Linux (debian bullseye)
- R version 4.0.2
- devtools version 2.3.1.9000

This is the output, I see:

> Updating ggcorpairs documentation
> Loading ggcorpairs
> Registered S3 method overwritten by 'GGally':
>   method from   
>   +.gg   ggplot2
> Writing NAMESPACE
> Writing NAMESPACE
> ── Building ────────────────────────────────────────────────────── ggcorpairs ──
> Setting env vars:
> ● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
> ● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
> ● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
> ────────────────────────────────────────────────────────────────────────────────
> ✔  checking for file ‘/home/aleha/work/r-packages/ggcorpairs/DESCRIPTION’ (474ms)
> ─  preparing ‘ggcorpairs’:
> ✔  checking DESCRIPTION meta-information
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘ggcorpairs_0.1.tar.gz’
>    
> ── Checking ────────────────────────────────────────────────────── ggcorpairs ──
> Setting env vars:
> ● _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
> ● _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
> ● _R_CHECK_CRAN_INCOMING_           : FALSE
> ● _R_CHECK_FORCE_SUGGESTS_          : FALSE
> ● NOT_CRAN                          : true
> ── R CMD check ─────────────────────────────────────────────────────────────────
>    Error in assignInNamespace("q", function(save = "no", status = 0, runLast = TRUE) { : 
>      locked binding of ‘q’ cannot be changed
>    Calls: source -> withVisible -> eval -> eval -> assignInNamespace
>    Execution halted
> ── R CMD check results ───────────────────────────────────── ggcorpairs 0.1 ────
> Duration: 443ms
> 
> 0 errors ✔ | 0 warnings ✔ | 0 notes ✔

**Comment by jimhester** [comment]
I think this must be an issue in your package code.
