### ISSUE TITLE
Library not loading devtools

### ISSUE THREAD

**Issue by benduong1** [r-lib/devtools#2268]
I am trying to load devtools but when running library(devtools) I get the following error.

> library(devtools)
Error: package or namespace load failed for ‘devtools’:
 .onLoad failed in loadNamespace() for 'processx', details:
  call: namespaceExport(ns, exports)
  error: undefined exports: CleanupReporter, ps, ps_boot_time, ps_children, ps_cmdline, ps_connections, ps_cpu_count, ps_cpu_times, ps_create_time, ps_cwd, ps_environ, ps_environ_raw, ps_exe, ps_find_tree, ps_gids, ps_handle, ps_interrupt, ps_is_running, ps_is_supported, ps_kill, ps_kill_tree, ps_mark_tree, ps_memory_info, ps_name, ps_num_fds, ps_num_threads, ps_open_files, ps_os_type, ps_parent, ps_pid, ps_pids, ps_ppid, ps_resume, ps_send_signal, ps_status, ps_suspend, ps_terminal, ps_terminate, ps_uids, ps_username, ps_users, signals, with_process_cleanup
In addition: Warning messages:
1: package ‘devtools’ was built under R version 3.6.3 
2: S3 methods ‘as.character.ps_handle’, ‘format.ps_handle’, ‘print.ps_handle’, ‘print.with_process_cleanup’ were declared in NAMESPACE but not found

This is the version I am running. 
> version                   
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes  

Let me know if you need more information.

**Comment by jimhester** [comment]
Your processx installation seems to be broken, you will need to reinstall the processx package. Make sure you close all other R and RStudio instances, restart your R session with no loaded packages and then run `install.packages("processx")`.
