### ISSUE TITLE
dev_sitrep() has inconsistently formatted bullets

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2269]
<img width="472" alt="Screenshot 2020-08-24 at 1 00 56 PM" src="https://user-images.githubusercontent.com/4196/91079659-f5229580-e609-11ea-9261-b2f4fc030c34.png">

**Comment by jimhester** [comment]
I think this is intentional? The red ones are things that could be problems, the others are just informative.

**Comment by hadley** [comment]
They should at least use the same bullet character.

**Comment by jimhester** [comment]
So should we change `usethis::kv_line()` to use `ui_bullet()`, or write new variant of `ui_todo()` that uses the `*` as the bullet?

**Comment by hadley** [comment]
Seems reasonable to make `kv_line()` more consistent? (Although I'm not sure where else it's used)
