### ISSUE TITLE
devtools::install_github() error: trying to use CRAN without setting a mirror

### ISSUE THREAD

**Issue by jorvlan** [r-lib/devtools#2275]
Hi developers,

I have developed a R package and published it on GitHub (https://www.github.com/jorvlan/openvis)
The package is written in R version 4.0.0 on a macOS and on my mac, the package installs, loads, and works fine.
Now I am testing it on Windows and the following error is being raised:

```r
Error in contrib.url(repos, "source") : trying to use CRAN without setting a mirror
```

Full details:

```r
if (!require(devtools)){
  install.packages('devtools')
}
devtools::install_github('jorvlan/openvis')
```
```r
Downloading GitHub repo jorvlan/openvis@HEAD
The downloaded binary packages are in
	C:\Users\jorvlan\AppData\Local\Temp\RtmpGsN9w4\downloaded_packages
√  checking for file 'C:\Users\jorvlan\AppData\Local\Temp\RtmpGsN9w4\remotes1ad036f650ac\jorvlan-openvis-8eaaafc/DESCRIPTION' ...
-  preparing 'openvis': (475ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'openvis_0.1.0.tar.gz'

Installing packages into 'C:/Users/jorvlan/Documents/R/win-library/4.0/00LOCK-openvis/00new'
(as 'lib' is unspecified)
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Error: unable to load R code in package 'openvis'
Execution halted
ERROR: lazy loading failed for package 'openvis'
* removing 'C:/Users/jorvlan/Documents/R/win-library/4.0/openvis'
Error: Failed to install 'openvis' from GitHub:
```
Based on GitHub issues and issues on other platforms, I tried multiple things that were suggested there:

- Rstudio > Tools > Global Options > Packages > Primary CRAN repository (choosing a mirror).
- Try with `remotes::install_github()`
```r
- local({
      r <- getOption("repos");
      attr(r, "RStudio") <- TRUE
      r["CRAN"] <- "http://cran.us.r-project.org";
      options(repos=r)
    })
```
- set `~/.Rprofile` to `options(repos=structure(c(CRAN="YOUR FAVORITE MIRROR")))`

![devtools_sitrep](https://user-images.githubusercontent.com/46848177/92111100-13e41180-edec-11ea-8048-f2d4aaf815aa.PNG)

All options did not resolve my issue.
Thanks very much in advance.

**Comment by jimhester** [comment]
Did you try actually setting a CRAN mirror?

```r
options(repos = c(CRAN = "https://cloud.r-project.org"))
```

Will use the cloud mirror which automatically serves the files from a location near you.

**Comment by jorvlan** [comment]
```r
file.edit(".Rprofile") 
options(repos = c(CRAN = "https://cloud.r-project.org"))
```

That did the trick, amazing.

Thanks so much
