### ISSUE TITLE
Found the following (possibly) invalid URLs...

### ISSUE THREAD

**Issue by petermeissner** [r-lib/devtools#2276]
I am currently getting my package rejected again and again because the URLs used within vignettes and README.Rmd/md seem to trigger redirects: 

- redirect from HTTP to HTTPS
- redirect to www subdomain
- redirect to other subdomain
- redirect to folder
- ...

*example*

```
Found the following (possibly) invalid URLs:
     URL: https://foo (moved to
https://www.foo/)
       From: README.md
       Status: 200
       Message: OK
```

*Is {devtools} the right place to add a check if URLs work and if they trigger any kind of redirect which might than result in package reject and resubmit?*

So far I do not get those checks with local devtools (Win10) - old. 
And do not get them with Travis Ubuntu 16.04 - old, release, devel.

I do seem to get them sometimes with win builder devel but I do not seem to get them with win builder release.

*If {devtools} is the right place and somebody has an idea how to best tackle this I can spend some time working on a solution.*

**Comment by jimhester** [comment]
These checks are coming from `R CMD check`, which `devtools::check()` simply wraps. They are currently available only in R-devel as long as it is compiled with libcurl support _and_ the 'incoming' checks are enabled.

Assuming your R supports this then `devtools::check(remote = TRUE)` will include these checks. Note `remote = FALSE` is the default, and these remote checks are disabled by the default build script on travis for `language: r`.

To ensure you capture these before release the best practice is to use `devtools::check_win_devel()` to check with R devel on win builder before submitting to CRAN.

**Comment by petermeissner** [comment]
Thanks 👍 

The problem with `devtools::check_win_devel()` of cause is that it takes several minutes to get feedback. 

`devtools::check(remote = TRUE)` sounds like a viable solution - once R-devel has become R-release and I can just run it it locally.

Since it seems this will not and should not be solved in devtools, I will close this.
