### ISSUE TITLE
R crashes after calling load_all() 

### ISSUE THREAD

**Issue by dipterix** [r-lib/devtools#2277]
I'm writing a package containing `OpenMP` code. When I disable the OpenMP flag when compiling the code, everything works fine, but once I enable the flag, calling `load_all()` lead to segfaults.

To reproduce the error, follow the following steps:

1. Open/Download OpenMP enabled package. For example create R project from github, https://github.com/fstpackage/fstcore
2. Compile the package
3. Run some functions that uses OpenMP. For example
```r
.Call(fstcore:::`_fstcore_fststore`, tempfile(), data.frame(V1=1), 100L, TRUE)
```
4. Add a blank line in src/*.cpp (any file)
5. Run `devtools::load_all(recompile = TRUE)`

These five steps not only crash RStudio, but also R if ran in terminal.

I tried multiple packages that use OpenMP. None of them survives these steps.

**Comment by dipterix** [comment]
I put my session information below in case it's too long to be read.

## 1. System environment
`sessionInfo()` doesn't provide any useful information so I paste Makevars. I'm running R 4.0.2 under macOS Catalina 10.15.6. Compiler is llvm clang installed from `brewer`. (Macosx doesn't have OpenMP support by default)

(1) R User ~/.Makevars
```
CC=/usr/local/opt/llvm/bin/clang
CXX=/usr/local/opt/llvm/bin/clang++
CXX11=/usr/local/opt/llvm/bin/clang++
CXX14=/usr/local/opt/llvm/bin/clang++
CXX1X=/usr/local/opt/llvm/bin/clang++
LDFLAGS=-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
CXXFLAGS=-I/usr/local/opt/llvm/include
CPPFLAGS=-I/usr/local/opt/llvm/include

SHLIB_OPENMP_CFLAGS= -fopenmp
SHLIB_OPENMP_CXXFLAGS= -fopenmp
SHLIB_OPENMP_FCFLAGS= -fopenmp
SHLIB_OPENMP_FFLAGS= -fopenmp
```

(2) package Makevars

```
CXX_STD      = CXX11
PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
PKG_LIBS     = $(SHLIB_OPENMP_CXXFLAGS)
```

## 2. R console output
```r
> devtools::load_all()
Loading lazyarray

 *** caught segfault ***
address 0x111fc4070, cause 'memory not mapped'

Traceback:
 1: .Call(list(name = "processx_exec", address = <pointer: 0x7fee5be70520>,     dll = list(name = "processx", path = "/Users/dipterix/Library/R/4.0/library/processx/libs/processx.so",         dynamicLookup = FALSE, handle = <pointer: 0x7fee5be4b140>,         info = <pointer: 0x7fee60490480>), numParameters = 16L),     "/Library/Frameworks/R.framework/Resources/bin/R", c("/Library/Frameworks/R.framework/Resources/bin/R",     "CMD", "SHLIB", "foo.c"), NULL, "|", "2>&1", FALSE, list(        echo = FALSE), list(), NULL, FALSE, FALSE, <environment>,     TRUE, NULL, "", "PROCESSX_PS8ZWRMP0YCK_1599464579=YES")
```

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there?

Also see https://mac.r-project.org/openmp/ for more general setup of OpenMP with R on macOS.

**Comment by dipterix** [comment]
Hi, @jimhester , I reinstalled my library using CRAN guide https://mac.r-project.org/openmp/ . The problem still exists with `devtools`.

Also this is *not* a rstudio issue as I ran in terminal, it also crashes.
