### ISSUE TITLE
test() and check() give different results

### ISSUE THREAD

**Issue by Christoph999** [r-lib/devtools#2278]
This question has been asked [here](https://stackoverflow.com/q/63426395/5784831), but I can't figure out, what's going on: create a package and a test

```
test_that("test sort 1", {
  testthat_locale <- Sys.getlocale("LC_COLLATE")
  xx <- c("Schaffhausen", "Schwyz", "Seespital", "SRZ")
  invisible(Sys.setlocale("LC_COLLATE", locale))
  expect_equal(sort(xx), c("Schaffhausen", "Schwyz", "Seespital", "SRZ"))
  invisible(Sys.setlocale("LC_COLLATE", testthat_locale))
})
```

then

```
devtools::test()
# == Results ===
# OK:       1
# Failed:   0
# Warnings: 0
# Skipped:  0

devtools::check()
# ...
# 1 errors x | 1 warnings x | 1 note x
```

To me, that does not make sense. See also [here](https://stackoverflow.com/questions/63340367/how-to-change-lc-collate-c-globally-for-all-tests-in-testhat) and [here](https://stackoverflow.com/q/63336729/5784831) for background.

**Comment by jimhester** [comment]
R CMD check runs in the C locale, `test()` is running in your local locale.

**Comment by Christoph999** [comment]
@jimhester Ok, that is what I guessed. To improve my understanding: Where is that piece of code "hidden", which defines the collation in `check()`? I was not able to find that.

Appart from that: To me, this behaviour is really unexpected. Is it the intention to keep it this way? If yes: why?

Thanks for your support!

**Comment by jimhester** [comment]
`devtools::check()` is powered by the `rcmdcheck` package, which is a thin wrapper around `R CMD check`. The code for `R CMD check` to run tests is in the tools package, the particular code that sets the language for tests is at https://github.com/wch/r-source/blob/62b2f0a329c81b005e0eab232a3eef3e439f3441/src/library/tools/R/testing.R#L487-L491

**Comment by jimhester** [comment]
None of the code in `R CMD check` is anything that the devtools developers are responsible for or can realistically change.

**Comment by Christoph999** [comment]
Thanks a lot
