### ISSUE TITLE
Default arg for `devtools::install_github` `ref="master"` --> `ref="main"`

### ISSUE THREAD

**Issue by trashbirdecology** [r-lib/devtools#2280]
Recommend changing the default arg for `ref` in `devtools::install_github` from `ref="master"` to `ref="main"`. 

Although Github has [already taken measures](https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/) to redirect links containing master to main branches, it does not work for retrieving tarball.

**Comment by jimhester** [comment]
This has already been changed, please make sure you have the latest CRAN version of remotes (2.2.0) and devtools (2.3.2) installed.

**Comment by trashbirdecology** [comment]
Oh wowzers, thanks.
