### ISSUE TITLE
`devtools::check()` fails while `rcmdcheck()` succeeds running tests

### ISSUE THREAD

**Issue by statnmap** [r-lib/devtools#2281]
In the package [{checkhelper}](https://github.com/ThinkR-open/checkhelper), I read the outputs of the {rcmdcheck} package to list globalVariables.  
I added some unit tests to verify the outputs. When I run `devtools::check()`, the tests fail. Outputs of the {rcmdcheck} inside is apparently not run correctly and returns nothing. However, when I use `rcmdcheck::rcmdcheck()` it works perfectly.  
I tried to run the inside check in an external R session using `system()` but the result is the same. I do not see the difference between check and rcmdcheck that would explain this. 

To reproduce, you can try the "tests" branch here : https://github.com/ThinkR-open/checkhelper/tree/tests

This seems to depend on R versions as you can see that sometimes github-actions pass the tests, as there are set using {rcmdcheck}, but not always:
- Here with the inside checks directly in the testthat session: https://github.com/ThinkR-open/checkhelper/pull/9/checks?check_run_id=1159284127  
- Here with the inside checks in a separate R session using `system()`: https://github.com/ThinkR-open/checkhelper/runs/1159377508?check_suite_focus=true
 
_I personally use Ubuntu 20.04, with R 4.0.2. {devtools} 2.3.1.9000 and {rcmdcheck} 1.3.3_

**Comment by hadley** [comment]
Unfortunately we don't have the resources to deeply dive into these issues. `check()` does call `rcmdcheck::rcmdcheck()` so it must be something it does in the interim that causes the problem. I'd suggest working through the code line-by-line to figure out what the problem is.
