### ISSUE TITLE
Avoid rebuilding vignettes in devtools::release()

### ISSUE THREAD

**Issue by paul-buerkner** [r-lib/devtools#2284]
Some vignettes in some of my packages take very long time to build so I would prefer avoiding to rebuild them when running `devtools::release()` multiple times until CRAN accepts my new package version. Rather, I have prebuilt vignettes saved in `doc` through `devtools::build_vignettes()` that I would like to reuse for the release process. 

In the past I have tried to run `devtools::release(args = "--no-build-vignettes")` but it failed as the vignette index was not built correctly (or at all rather). 

Is it possible to add an argument to `devtools::release()` to reuse existing prebuilt vignettes while still making sure the vignette index (and whatever else might be required for vignettes to function correctly on CRAN) is built correctly?

Many thanks for your efforts on `devtools` and all the related packages! I don't know what I would do without them.

**Comment by jimhester** [comment]
It is bad practice to try and use pre-built vignettes. They should be built during `R CMD build`.

If they take a long time to build you can use the knitr cache to save the outputs, just exclude the cache directory from the built package.

**Comment by paul-buerkner** [comment]
Thank you! I will try this option.
