### ISSUE TITLE
option `porcelain` takes no value

### ISSUE THREAD

**Issue by corybrunson** [r-lib/devtools#2286]
Hi! I rely on this package for CRAN submissions and greatly appreciate it.

I had a new error arise that i don't think is due to a problem with my Git installation. It occurred during a `release()` of a new package, but i can reproduce it with a freshly initiated Git directory—though `reprex()` does not print the message. Here's the reprex:

``` r
library(devtools)
#> Warning: package 'devtools' was built under R version 4.0.2
#> Loading required package: usethis
#> Warning: package 'usethis' was built under R version 4.0.2
setwd(tempdir())
system2("git", "init")
print(devtools:::git_uncommitted())
#> Warning in system2("git", c("status", "--porcelain=v1"), stdout = TRUE): running
#> command ''git' status --porcelain=v1' had status 129
#> [1] FALSE
system2("rm", c("-r", ".git"))
```

<sup>Created on 2020-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And here's what i see by executing these lines in the Terminal:

```r
> setwd(tempdir())
> system2("git", "init")
Initialized empty Git repository in /private/var/folders/pg/fjg8r4fj5v33zqmwptf9mfg80000gn/T/Rtmp1NeQe7/.git/
> print(devtools:::git_uncommitted())
error: option `porcelain' takes no value
usage: git status [options] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns

[1] FALSE
Warning message:
In system2("git", c("status", "--porcelain=v1"), stdout = TRUE) :
  running command ''git' status --porcelain=v1' had status 129
> system2("rm", c("-r", ".git"))
```

I see from [git.R](https://github.com/r-lib/devtools/blob/master/R/git.R) that `git_uncommitted()` passes the `v1` flag to `porcelain`, though i don't know the background to this or the relevant version history.

Thank you for any assistance!

**Comment by jimhester** [comment]
What version of git are you using?

**Comment by corybrunson** [comment]
`git version 1.9.3 (Apple Git-50)`

**Comment by jimhester** [comment]
I think you need to upgrade your version of git, 1.9.3 is quite old, it was released sometime in 2014

**Comment by corybrunson** [comment]
Resolved—i had used homebrew to upgrade Git but had failed to notice that `PATH` had not been updated. Thank you!
