### ISSUE TITLE
devtools::install() conflicts with renv?

### ISSUE THREAD

**Issue by IanWorthington** [r-lib/devtools#2288]
If I understand correctly, `devtools::install()` should install a package from a project I'm working on into my local system(?) library, where it will be accessible for other projects to load using `library(...)`.

When I'm developing my package project with renv though `devtools::install()` seems to install to the project's renv library:

```
Running "C:/PROGRA~1/R/R-4.0.3/bin/x64/Rcmd.exe" INSTALL \
  "C:\Users\IanWo\AppData\Local\Temp\RtmpaoXfxI/ianwStocksLibrary_0.0.0.1000.tar.gz" \
  --install-tests 
* installing to library 'C:/Users/IanWo/My Code Projects/R Studio Projects/ianw-stockslibrary/renv/library/R-4.0/x86_64-w64-mingw32'
```

Is there anyway I can get `install()` to put it in the common library?

**Comment by jimhester** [comment]
`devtools::install() installs the package into your current library path, e.g. that given by `.libPaths()`. However renv changes your `.libPaths()`, so you would need to change to your normal library before calling `devtools::install()`. You can either call `.libPaths("my-path")` to set it or use `withr::with_libpaths("my-path", devtools::install("xyz"))` to temporarily change it for just the install.

**Comment by IanWorthington** [comment]
Thanks, Jim,  I shall look at that.

I'm being to wonder though if it makes sense to be using renv for package development.  If the dependencies file doesn't specify the version number of the imports, am I just creating a stick with which to beat myself?

What's considered best practice here, please?

**Comment by jimhester** [comment]
I generally do not think it is necessary to use renv for package development.
