### ISSUE TITLE
Relicensing devtools (2/2)

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2291]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/devtools/graphs/contributors). @adrtod, @amcdavid, @AmundsenJunior, @ashander, @ateucher, @az0, @bquast, @brentonk, @craigcitro, @daattali, @edwindj, @flying-sheep, @fmichonneau, @Geoff99, @hansharhoff, @HenrikBengtsson, @hmalmedal, would you permit us to re-license devtools with the MIT license? If so, please comment "I agree" below.

* [x] [@adrtod](https://github.com/r-lib/devtools/commits?author=adrtod)  
* [x] [@amcdavid](https://github.com/r-lib/devtools/commits?author=amcdavid)  
* [ ] [@AmundsenJunior](https://github.com/r-lib/devtools/commits?author=AmundsenJunior)  
* [x] [@ashander](https://github.com/r-lib/devtools/commits?author=ashander)  
* [x] [@ateucher](https://github.com/r-lib/devtools/commits?author=ateucher)  
* [x] [@az0](https://github.com/r-lib/devtools/commits?author=az0)  
* [x] [@bquast](https://github.com/r-lib/devtools/commits?author=bquast)  
* [x] [@brentonk](https://github.com/r-lib/devtools/commits?author=brentonk)  
* [x] [@craigcitro](https://github.com/r-lib/devtools/commits?author=craigcitro)  
* [x] [@daattali](https://github.com/r-lib/devtools/commits?author=daattali)  
* [x] [@edwindj](https://github.com/r-lib/devtools/commits?author=edwindj)  
* [x] [@flying-sheep](https://github.com/r-lib/devtools/commits?author=flying-sheep)  
* [x] [@fmichonneau](https://github.com/r-lib/devtools/commits?author=fmichonneau)  
* [x] [@Geoff99](https://github.com/r-lib/devtools/commits?author=Geoff99)  
* [x] [@hansharhoff](https://github.com/r-lib/devtools/commits?author=hansharhoff)  
* [x] [@HenrikBengtsson](https://github.com/r-lib/devtools/commits?author=HenrikBengtsson)  
* [x] [@hmalmedal](https://github.com/r-lib/devtools/commits?author=hmalmedal)

**Comment by az0** [comment]
I agree

**Comment by hmalmedal** [comment]
I agree

**Comment by ateucher** [comment]
I agree

**Comment by hansharhoff** [comment]
I agree

**Comment by bquast** [comment]
I agree

**Comment by ashander** [comment]
I agree

**Comment by adrtod** [comment]
I agree

**Comment by daattali** [comment]
I agree

**Comment by brentonk** [comment]
I agree

**Comment by craigcitro** [comment]
I agree

**Comment by amcdavid** [comment]
I agree

**Comment by edwindj** [comment]
I agree

Op vr 30 okt. 2020 15:16 schreef Hadley Wickham <notifications@github.com>:

**Comment by flying-sheep** [comment]
I agree

**Comment by Geoff99** [comment]
I agree

**Comment by flying-sheep** [comment]
I agree

**Comment by fmichonneau** [comment]
I agree

**Comment by HenrikBengtsson** [comment]
I agree

**Comment by hadley** [comment]
Thanks everyone — now closing to track final folks in #2326.
