### ISSUE TITLE
Relicensing devtools (1/2)

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2292]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/devtools/graphs/contributors). @ianmcook, @ijlyttle, @imanuelcostigan, @infotroph, @james-atkins, @jameslamb, @JBGruber, @jdblischak, @jiho, @jimvine, @jlburkhead, @jonthegeek, @juliangehring, @kalibera, @karl-forner-quartz-bio, @karthik, @Kevin-Jin, @kiendang, @kiwiroy, @kohske, @kornl, @lev-kuznetsov, @lindbrook, @lmullen, @maelle, @martinstuder, @mbjones, @mikemahoney218, @mikldk, @mnel, @muschellij2, @nbenn, @ncarchedi, @nparley, @onlymee, @Paxanator, @pkq, @plantarum, @rcannood, @renozao, @richfitz, @rmflight, @robertzk, @seankross, @StevenMMortimer, @t-gibson, @theGreatWhiteShark, @twolodzko, @WilDoane, @yoni, would you permit us to re-license devtools with the MIT license? If so, please comment "I agree" below.

* [x] [@ianmcook](https://github.com/r-lib/devtools/commits?author=ianmcook)  
* [x] [@ijlyttle](https://github.com/r-lib/devtools/commits?author=ijlyttle)  
* [x] [@imanuelcostigan](https://github.com/r-lib/devtools/commits?author=imanuelcostigan)  
* [x] [@infotroph](https://github.com/r-lib/devtools/commits?author=infotroph)  
* [x] [@james-atkins](https://github.com/r-lib/devtools/commits?author=james-atkins)  
* [x] [@jameslamb](https://github.com/r-lib/devtools/commits?author=jameslamb)  
* [x] [@JBGruber](https://github.com/r-lib/devtools/commits?author=JBGruber)  
* [x] [@jdblischak](https://github.com/r-lib/devtools/commits?author=jdblischak)  
* [x] [@jiho](https://github.com/r-lib/devtools/commits?author=jiho)  
* [x] [@jimvine](https://github.com/r-lib/devtools/commits?author=jimvine)  
* [x] [@jlburkhead](https://github.com/r-lib/devtools/commits?author=jlburkhead)  
* [x] [@jonthegeek](https://github.com/r-lib/devtools/commits?author=jonthegeek)  
* [x] [@juliangehring](https://github.com/r-lib/devtools/commits?author=juliangehring)  
* [x] [@kalibera](https://github.com/r-lib/devtools/commits?author=kalibera)  
* [ ] [@karl-forner-quartz-bio](https://github.com/r-lib/devtools/commits?author=karl-forner-quartz-bio)  
* [x] [@karthik](https://github.com/r-lib/devtools/commits?author=karthik)  
* [x] [@Kevin-Jin](https://github.com/r-lib/devtools/commits?author=Kevin-Jin)  
* [x] [@kiendang](https://github.com/r-lib/devtools/commits?author=kiendang)  
* [x] [@kiwiroy](https://github.com/r-lib/devtools/commits?author=kiwiroy)  
* [x] [@kohske](https://github.com/r-lib/devtools/commits?author=kohske)  
* [x] [@kornl](https://github.com/r-lib/devtools/commits?author=kornl)  
* [x] [@lev-kuznetsov](https://github.com/r-lib/devtools/commits?author=lev-kuznetsov)  
* [x] [@lindbrook](https://github.com/r-lib/devtools/commits?author=lindbrook)  
* [x] [@lmullen](https://github.com/r-lib/devtools/commits?author=lmullen)  
* [x] [@maelle](https://github.com/r-lib/devtools/commits?author=maelle)  
* [x] [@martinstuder](https://github.com/r-lib/devtools/commits?author=martinstuder)  
* [x] [@mbjones](https://github.com/r-lib/devtools/commits?author=mbjones)  
* [x] [@mikemahoney218](https://github.com/r-lib/devtools/commits?author=mikemahoney218)  
* [x] [@mikldk](https://github.com/r-lib/devtools/commits?author=mikldk)  
* [ ] [@mnel](https://github.com/r-lib/devtools/commits?author=mnel)  
* [x] [@muschellij2](https://github.com/r-lib/devtools/commits?author=muschellij2)  
* [x] [@nbenn](https://github.com/r-lib/devtools/commits?author=nbenn)  
* [ ] [@ncarchedi](https://github.com/r-lib/devtools/commits?author=ncarchedi)  
* [x] [@nparley](https://github.com/r-lib/devtools/commits?author=nparley)  
* [x] [@onlymee](https://github.com/r-lib/devtools/commits?author=onlymee)  
* [ ] [@Paxanator](https://github.com/r-lib/devtools/commits?author=Paxanator)  
* [x] [@pkq](https://github.com/r-lib/devtools/commits?author=pkq)  
* [x] [@plantarum](https://github.com/r-lib/devtools/commits?author=plantarum)  
* [x] [@rcannood](https://github.com/r-lib/devtools/commits?author=rcannood)  
* [x] [@renozao](https://github.com/r-lib/devtools/commits?author=renozao)  
* [x] [@richfitz](https://github.com/r-lib/devtools/commits?author=richfitz)  
* [x] [@rmflight](https://github.com/r-lib/devtools/commits?author=rmflight)  
* [x] [@robertzk](https://github.com/r-lib/devtools/commits?author=robertzk)  
* [x] [@seankross](https://github.com/r-lib/devtools/commits?author=seankross)  
* [x] [@StevenMMortimer](https://github.com/r-lib/devtools/commits?author=StevenMMortimer)  
* [x] [@t-gibson](https://github.com/r-lib/devtools/commits?author=t-gibson)  
* [x] [@theGreatWhiteShark](https://github.com/r-lib/devtools/commits?author=theGreatWhiteShark)  
* [x] [@twolodzko](https://github.com/r-lib/devtools/commits?author=twolodzko)  
* [x] [@WilDoane](https://github.com/r-lib/devtools/commits?author=WilDoane)  
* [ ] [@yoni](https://github.com/r-lib/devtools/commits?author=yoni)

**Comment by rmflight** [comment]
I agree

**Comment by ianmcook** [comment]
I agree

**Comment by jiho** [comment]
I agree

**Comment by jdblischak** [comment]
I agree

**Comment by jonthegeek** [comment]
I agree

**Comment by mikemahoney218** [comment]
I agree

**Comment by seankross** [comment]
I agree

**Comment by rcannood** [comment]
I agree

**Comment by kornl** [comment]
I agree

**Comment by plantarum** [comment]
I agree

**Comment by renozao** [comment]
I agree

**Comment by nparley** [comment]
I agree

**Comment by kiendang** [comment]
I agree

**Comment by Kevin-Jin** [comment]
I agree

**Comment by ijlyttle** [comment]
I agree

**Comment by kohske** [comment]
I agree

**Comment by WilDoane** [comment]
I agree

**Comment by infotroph** [comment]
I agree

**Comment by richfitz** [comment]
I agree

**Comment by lmullen** [comment]
I agree.

**Comment by jimvine** [comment]
I agree

**Comment by martinstuder** [comment]
I agree

**Comment by james-atkins** [comment]
I agree.

**Comment by robertzk** [comment]
I agree.

**Comment by muschellij2** [comment]
I agree

**Comment by mbjones** [comment]
I agree.

**Comment by jameslamb** [comment]
I agree

**Comment by twolodzko** [comment]
I agree.

Tymoteusz Wolodzko

**Comment by lindbrook** [comment]
I agree.

**Comment by theGreatWhiteShark** [comment]
I agree

**Comment by mikldk** [comment]
I agree

**Comment by kiwiroy** [comment]
I agree.

**Comment by jlburkhead** [comment]
I agree

**Comment by karthik** [comment]
I agree

**Comment by t-gibson** [comment]
I agree

**Comment by JBGruber** [comment]
I agree.

**Comment by maelle** [comment]
I agree

**Comment by imanuelcostigan** [comment]
I agree.

**Comment by StevenMMortimer** [comment]
I agree

**Comment by nbenn** [comment]
I agree.

**Comment by kalibera** [comment]
I agree with relicensing my own (and tiny) contribution to devtools. I don't speak for R Core here nor refer to any code incorporated from base R (DESCRIPTION lists R Core - "Some namespace and vignette code extracted from base R").

**Comment by hadley** [comment]
@kalibera we've already made a note that we need to remove that code in #2290 (the namespace code has already departed devtools)

**Comment by pkq** [comment]
I agree

**Comment by onlymee** [comment]
I agree.

**Comment by juliangehring** [comment]
I agree.

**Comment by lev-kuznetsov** [comment]
I agree

**Comment by onlymee** [comment]
I agree.

**Comment by hadley** [comment]
Thanks everyone — now closing to track final folks in #2326.
