### ISSUE TITLE
Error: package or namespace load failed for ‘devtools’

### ISSUE THREAD

**Issue by cedlfc44** [r-lib/devtools#2294]
Hi:
I try to install devtools but, i can t, then i get  a message.

install.packages("devtools")
library(devtools)

Error: package or namespace load failed for ‘devtools’:
 .onLoad failed in loadNamespace() for 'pkgload', details:
  call: NULL
  error: package ‘backports’ does not have a namespace
Además: Warning message:
package ‘devtools’ was built under R version 4.0.3

**Comment by jimhester** [comment]
It looks like your installation of backports failed. Close all your open R sessions, then start a new session without any packages loaded and then run `install.packages("backports"); install.packages("devtools")` to reinstall backports and devtools.

If you have further installation issues the best place to ask for help is <https://community.rstudio.com>.
