### ISSUE TITLE
install_github() needs to tickle gh to cache PAT in env var

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#2299]
I have now removed everything about my GitHub PAT from `.Renviron` and `.Rprofile`, trusting packages like gh and gert to discover the PAT in the Git credential store upon first need. Happily, they both cache the PAT in an env var for the duration of the R session.

The problem is that `devtools::install_github()` sort of assumes the PAT is ambiently available, yet does nothing to trigger its discovery and caching. Which leads to experiences like this:

```
> install_dev_deps()
Skipping 1 packages ahead of CRAN: pkgload
Error: HTTP error 403.
  API rate limit exceeded for 108.172.55.111. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2020-11-19 21:42:22 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
```

We need to do some combination of these things, here or in ?remotes?:

* Tickle gh to do its thing, perhaps with a `tryCatch()`d and silenced call to `gh::gh_token()`.
* Change the advice above to point people to <https://usethis.r-lib.org/articles/articles/git-credentials.html>

#2253 didn't completely close #2243 because I think devtools or remotes eventually hits GitHub w/o necessarily going through gh (am I right about that?)

cc @hadley

**Comment by jennybc** [comment]
Yeah, here is at least one example of hitting the GitHub API w/o routing through gh and, therefore, without pre-discovering the PAT:

https://github.com/r-lib/remotes/blob/c2013c25d905d73ca4326f2c5829165fea55f2ea/R/github.R#L28

Maybe this issue should be transferred to remotes.

**Comment by jennybc** [comment]
Even after using gh once successfully, devtools / remotes still can't find the PAT because gh / gitcreds now caches the PAT in an env var named `GITHUB_PAT_GITHUB_COM` cc @gaborcsardi

**Comment by gaborcsardi** [comment]
We'll put a minimal version of gitcreds into remotes, I think.

**Comment by jimhester** [comment]
remotes does not use gh at all. Mostly I think this is a misguided effort, so if you all want this you will have to do it.

**Comment by gaborcsardi** [comment]
@jimhester Could you pls elaborate why it is misguided?

**Comment by jimhester** [comment]
I don't think the minor security and ergonomic benefits warrant the effort involved. Adding a single line to `.Renviron` is not very onerous and still reasonably secure.

**Comment by gaborcsardi** [comment]
I think this is mostly about using the same credentials as git itself. And thereby supporting multiple hosts, users, repo-based config, custom auth, etc.

Most of the effort is already spent, and the rest is not that much. I.e. this was copying a file, and a three line change in pkgdepends: https://github.com/r-lib/pkgdepends/pull/219

**Comment by jennybc** [comment]
Yeah to further explain the motivation for refactoring PAT handling, it's to support GitHub Enterprise (i.e. GitHub.com is not the only GitHub host in the world). And once you decide to generalize that much, it's also nice to support username, because some people present themselves to, e.g., GitHub.com as userA from some repos and as userB from others. Git's credential store & helpers are already aware of these things.

I definitely want to change the troubleshooting advice I see in the original post here. Where should I do that?

**Comment by hadley** [comment]
@jennybc / @gaborcsardi could either of you propose a PR to do this?

**Comment by gaborcsardi** [comment]
I can do this, sure. 

Actually, for `install_github()` and co, it should be in remotes I think, and gh already does it, so is there anything to do in devtools?

**Comment by hadley** [comment]
I think the primary argument would be that it's easier to do in devtools because we can have dependencies more easily, and these functions are already shimmed out in devtools.

**Comment by gaborcsardi** [comment]
We actually can't easily do it in devtools, I think, because devtools is a bit far away from sending out the HTTP requests. 

E.g. when you install from Enterprise GH, or gitlab, and have a remote to github.com, then remotes needs to add the right tokens to the requests to the different servers. If you wanted to do this in devtools, then devtools would have to resolve the recursive dependencies first, to find the servers involved. Or remotes would need to call back to devtools to request the tokens, but that does not seem very nice, either. 

Also, many people use remotes now in their READMEs, so it would make sense to support it in remotes.

It is easy to add it to remotes, gitcreds is a standalone file now: https://github.com/r-lib/gitcreds/blob/a09b18866a5e0e175d976320a51d9023271faed6/R/git-auth.R

Standalone files are not great, so we can also make gitcreds an optional dependency in remotes. I think this code will not change too often, so I would slightly prefer embedding it.

**Comment by hadley** [comment]
Ok, makes sense. So let's close this issue and follow up in remotes?
