### ISSUE TITLE
Devtools not loading from library 

### ISSUE THREAD

**Issue by Chonto01** [r-lib/devtools#2302]
Hello, I am new to coding and I am taking some online classes to learn and they require me to use devtools. But when I download the package and try to load it this is what the console tells me 

The downloaded binary packages are in
	/var/folders/bz/qzpwnsy105bcjvty9rc83knr0000gn/T//RtmpiXy1b2/downloaded_packages
Error: package or namespace load failed for ‘devtools’: .onLoad failed in loadNamespace() for 'processx', details: call: loadNamespace(name) error: there is no package called ‘ps’

what can I do?

**Comment by jimhester** [comment]
It looks like your install of ps failed, you will need to install it again. Make sure you close all open R sessions, and with a completely _fresh_ session with no packages loaded run `install.packages("ps")`.
