### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub:

### ISSUE THREAD

**Issue by ttian627** [r-lib/devtools#2305]
I got the follow error with R3.6.0 and R4.0.2, how to solve it?

>devtools::install_github("davidaknowles/leafcutter/leafcutter")
Error: Failed to install 'unknown package' from GitHub:
  An unknown option was passed in to libcurl

> remotes::install_git("https://github.com/davidaknowles/leafcutter.git")
Downloading git repo https://github.com/davidaknowles/leafcutter.git
'/usr/bin/git' clone --depth 1 --no-hardlinks https://github.com/davidaknowles/leafcutter.git /tmp/RtmpdzfYwp/file299733ab1fb99
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 164 (delta 43), reused 57 (delta 10), pack-reused 0
Receiving objects: 100% (164/164), 4.49 MiB | 1.27 MiB/s, done.
Resolving deltas: 100% (43/43), done.
Error: Failed to install 'unknown package' from Git:
  Does not appear to be an R package (no DESCRIPTION)

**Comment by jimhester** [comment]
There seems to be something wrong with your installation of curl. The first usage works fine on my machine. If you do want to use use `install_git()` you will need to also use `subdir = "leafcutter"` as the R package is in a subdirectory.

This sort of question is a better fit for <https://community.rstudio.com>. If the above does not address the issue do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
