### ISSUE TITLE
install_github() fails with System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr empty

### ISSUE THREAD

**Issue by jhagenauer** [r-lib/devtools#2306]
I am trying to install the remotes package from github with:
    
    devtools::install_github("r-lib/remotes")

The output from RStudio is:

    Downloading GitHub repo r-lib/remotes@HEAD
    Error: Failed to install 'remotes' from GitHub:
      System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr empty

I am not able to track the error further down.
Here are my system informations:

    > sessionInfo()
    R version 4.0.1 (2020-06-06)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 17763)

    Matrix products: default

    locale:
    [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 
    LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] devtools_2.3.2 usethis_2.0.0 

    loaded via a namespace (and not attached):
     [1] rstudioapi_0.13   magrittr_2.0.1    rcmdcheck_1.3.3   pkgload_1.1.0     R6_2.5.0          rlang_0.4.9       fansi_0.4.1       
    tools_4.0.1       pkgbuild_1.2.0   
    [10] xopen_1.0.0       sessioninfo_1.1.1 cli_2.2.0         withr_2.3.0       ellipsis_0.3.1    remotes_2.2.0     assertthat_0.2.1  
    digest_0.6.27     rprojroot_2.0.2  
    [19] lifecycle_0.2.0   crayon_1.3.4      processx_3.4.5    purrr_0.3.4       callr_3.5.1       fs_1.5.0          ps_1.5.0          curl_4.3          
    testthat_3.0.1   
    [28] memoise_1.1.0     glue_1.4.2        compiler_4.0.1    desc_1.2.0        prettyunits_1.1.1
    > session_info()
    - Session info --------------------------------------------------------------------------------------------------------------------------- 
   ---------------------------
     setting  value                       
     version  R version 4.0.1 (2020-06-06)
     os       Windows 10 x64              
     system   x86_64, mingw32             
     ui       RStudio                     
     language (EN)                        
     collate  German_Germany.1252         
     ctype    German_Germany.1252         
     tz       Europe/Berlin               
     date     2020-12-30                  

    - Packages ------------------------------------------------------------------------------------------------------------------------------ 
   ----------------------------
     package     * version date       lib source        
     assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.3)
     callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
     cli           2.2.0   2020-11-20 [1] CRAN (R 4.0.3)
     crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.3)
     curl          4.3     2019-12-02 [1] CRAN (R 4.0.3)
     desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.3)
     devtools    * 2.3.2   2020-09-18 [1] CRAN (R 4.0.3)
     digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
     ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.3)
     fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.3)
     fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)
     glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)
     lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.3)
     magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
     memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.3)
     pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.3)
     pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.3)
     prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.3)
     processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.3)
     ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)
     purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)
     R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
     rcmdcheck     1.3.3   2019-05-07 [1] CRAN (R 4.0.3)
     remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
     rlang         0.4.9   2020-11-26 [1] CRAN (R 4.0.3)
     rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.3)
     rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)
     sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
     testthat      3.0.1   2020-12-17 [1] CRAN (R 4.0.3)
     usethis     * 2.0.0   2020-12-10 [1] CRAN (R 4.0.3)
     withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.3)
     xopen         1.0.0   2018-09-17 [1] CRAN (R 4.0.3)

    [1] C:/Users/HAGENAJ/R/win-library/4.0
    [2] C:/Program Files/R/R-4.0.1/library

    > find_rtools(T)
    Found in Rtools 4.0 installation folder
    [1] TRUE

My environment variables are:

    > Sys.getenv()['PATH']
    PATH                                              C:\Program Files\R\R-4.0.1\bin\x64;C:\Program Files\Amazon Corretto\jdk1.8.0_265\bin;C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_265\bin;C:\Program Files\ImageMagick-7.0.10-Q16;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\PuTTY;C:\Program Files\Git\cmd;C:\Program Files\Java\openjdk-13\bin;C:\Program Files(x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\R\R-4.0.1\bin;C:\Program Files\R\R-4.0.1\bin\x64;C:\rtools40\usr\bin;C:\Users\HAGENAJ\Anaconda3;C:\Users\HAGENAJ\Anaconda3\Library\mingw-64\bin;C:\Users\HAGENAJ\Anaconda3\Library\usr\bin;C:\Users\HAGENAJ\Anaconda3\Library\bin;C:\Users\HAGENAJ\Anaconda3\Scripts;C:\Users\HAGENAJ\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\HAGENAJ\AppData\Local\Programs\Python\Python39;C:\Users\HAGENAJ\AppData\Local\Microsoft\WindowsApps;C:\Users\HAGENAJ\AppData\Local\Programs\MiKTe 2.9\miktex\bin\x64;C:\Program Files (x86)\osmosis\bin

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
