### ISSUE TITLE
check() "no visible binding for global variable" errantly flags subset's subset arguments

### ISSUE THREAD

**Issue by SimonDedman** [r-lib/devtools#2307]
With apologies for the confusing titlename!

I think this might be a bug but I'm quite new to `check()`. I got a number of "no visible binding for global variable" notes, which I think were due to the syntax of `subset()`having its 'subset' argument look like a global variable. E.g.:

```
mydataframe$newColumn <- runif(100, 0, 1)
subset(mydataframe, newColumn > 0.5)
```

Would flag `newColumn` for this issue even though it's not a global variable. I presume this is due to the syntax checking algorithm `check()` uses but I'm massively guessing here.

Cheers!

**Comment by jimhester** [comment]
This is coming from `R CMD check`, which `devtools::check()` simply wraps, so not really an issue with devtools itself.

In any case you can avoid these warning by using `utils::globalVariables()` to mark the variables, and they won't be flagged by `R CMD check`.

**Comment by SimonDedman** [comment]
Thanks Jim. Following `data.table`'s [advice](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html#globals) I put these in the function call as `NULL`s; should I switch to the `utils` approach instead?

Also apologies for the followup question - a function of my naivety on the subject - am I not right in my original suspicion that these 'variables' being flagged at all is still an error though, even if in `R CMD check` & not `devtools::check`? Thanks again.

**Comment by jimhester** [comment]
It doesn't really matter which way you do it, either one will work fine.

Yes, this is a false positive, but there is not really any way to avoid it in the code for `R CMD check`, so I don't think anything could be changed by R core to improve the situation.

**Comment by SimonDedman** [comment]
Interesting. Ok, thanks again for the insights Jim - much appreciated.
