### ISSUE TITLE
Cannot install bootstraplib  (bslib) 

### ISSUE THREAD

**Issue by simranjeet063** [r-lib/devtools#2308]
Every time I try to install the bslib package, it fails and pop me with an error. 

![image](https://user-images.githubusercontent.com/25813127/104675762-f84e2780-574a-11eb-8c41-cb164dee9386.png)

Any suggestion on fixing this issue would be much appreciated.

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
