### ISSUE TITLE
Devtools package not installing on OSX (Catalina 10.15.7)

### ISSUE THREAD

**Issue by georgetye** [r-lib/devtools#2310]
> install.packages("devtools", dependencies = TRUE)
also installing the dependencies ‘gert’, ‘usethis’

  There are binary versions available but the source versions are
  later:
         binary source needs_compilation
usethis   1.4.0  2.0.0             FALSE
devtools 1.13.6  2.3.2             FALSE

Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘gert’
Do you want to attempt to install these from sources?
y/n: y
installing the source packages ‘gert’, ‘usethis’, ‘devtools’

trying URL 'https://cran.rstudio.com/src/contrib/gert_1.0.2.tar.gz'
Content type 'application/x-gzip' length 61324 bytes (59 KB)
==================================================
downloaded 59 KB

trying URL 'https://cran.rstudio.com/src/contrib/usethis_2.0.0.tar.gz'
Content type 'application/x-gzip' length 556740 bytes (543 KB)
==================================================
downloaded 543 KB

trying URL 'https://cran.rstudio.com/src/contrib/devtools_2.3.2.tar.gz'
Content type 'application/x-gzip' length 373387 bytes (364 KB)
==================================================
downloaded 364 KB

* installing *source* package ‘gert’ ...
** package ‘gert’ successfully unpacked and MD5 sums checked
Homebrew 2.7.1
Homebrew/homebrew-core (git revision 76779; last commit 2021-01-05)
Homebrew/homebrew-cask (git revision 3d3c93; last commit 2021-01-05)
Using PKG_CFLAGS=-I/usr/local/opt/libgit2/include
Using PKG_LIBS=-L/usr/local/opt/libgit2/lib -lgit2
----------------------------- ANTICONF -------------------------------
Configuration failed to find libgit2 library. Try installing:
 * brew: libgit2 (MacOS)
 * deb: libgit2-dev (Debian, Ubuntu, etc)
 * rpm: libgit2-devel (Fedora, CentOS, RHEL)
If libgit2 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libgit2.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: 'git2.h' file not found
#include <git2.h>
         ^~~~~~~~
1 error generated.
----------------------------------------------------------------------
ERROR: configuration failed for package ‘gert’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gert’
Warning in install.packages :
  installation of package ‘gert’ had non-zero exit status
ERROR: dependency ‘gert’ is not available for package ‘usethis’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/usethis’
Warning in install.packages :
  installation of package ‘usethis’ had non-zero exit status
ERROR: dependency ‘usethis’ is not available for package ‘devtools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/devtools’
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/1y/nycd21_d7h5_251qhqsrl4ch0000gn/T/RtmpB3kho2/downloaded_packages’

**Comment by jimhester** [comment]
This is an issue installing the gert package, not devtools. However the error tells you what the issue is.

```
Configuration failed to find libgit2 library. Try installing:
brew: libgit2 (MacOS)
```

Run `brew install libgit2` to install the libgit2 system dependency, then you can reinstall usethis and gert.
