### ISSUE TITLE
Error: 25:1: unexpected symbol

### ISSUE THREAD

**Issue by yancylau** [r-lib/devtools#2311]
**Hi, I tried to install packages from github with devtools on R4.0.3 (linux server, Red Hat), however it raised this error no matter which package it choose.  Your suggestions will be greatly appreciated.**

```
> devtools::install_github("devtools")
Error in parse_repo_spec(repo) :
  Invalid git repo specification: 'devtools'
> install_github("r-lib/devtools")
Downloading GitHub repo r-lib/devtools@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All
2: CRAN packages only
3: None
4: testthat (3.0.1 -> b19b5acc9...) [GitHub]
5: cli      (2.2.0 -> 2.3.0       ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:3
✔  checking for file ‘/tmp/Rtmpbd8j1G/remotesa23a207c5e8/r-lib-devtools-ef962e4/DESCRIPTION’ (460ms)
─  preparing ‘devtools’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘devtools_2.3.1.9000.tar.gz’

Error: 25:1: unexpected symbol
24:
25: options
    ^
Execution halted
Error: Failed to install 'devtools' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpbd8j1G/filea23a3fd773d4/devtools_2.3.1.9000.tar.gz’ had non-zero exit status
```

**Comment by jimhester** [comment]
I think this is likely unrelated to devtools. Verify that your .Rprofile does not have something wrong in it, either project level `.Rprofile` or user level `~/.Rprofile`

**Comment by yancylau** [comment]
Yeap. There is a extra characters in my ~/.Rprofile file. After removing that character it worked. Thanks Jim a lot.

**Comment by fontikar** [comment]
This was so helpful with my problem! I am currently building an R package and devtools::check() was not working in my RStudio console but the Build tab > Check was working smoothly. I checked I had some tect in my .Rprofile because I wanted to configure it last time I had it open but never finished. Deleting the text made devtools::check() console work! Thank you! (Took me weeks to find this answer!)
