### ISSUE TITLE
build_vignettes destroys .Rbuildignore

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/devtools#2312]
Invoking devtools::build_vignettes() gives, after a while, the following message:

✔ Adding '^doc$' to '.Rbuildignore'

In reality, my whole .Rbuildignore has been removed and replaced with one that just contains ^doc$

**Comment by jimhester** [comment]
devtools calls `usethis::use_directory()` to add the doc folder to `.Rbuildignore`. This function is used by many usethis functions and doesn't typically have this behavior, so if what you say happened it is very surprising.

Can you give any more details on what the contents of your `.Rbuildignore` were before, and possibly reproduce the behavior using `usethis::use_directory("doc", ignore = TRUE)`?

**Comment by stefanoborini** [comment]
@jimhester This is the diff of my .Rbuildignore

```
-Makefile
-^packrat/
-^\.Rprofile$
-\.keepdir
-\.RData
-requirements.txt
-dev-requirements.txt
-buildtools
-^.*\.Rproj$
-^\.Rproj\.user$
-docs
-.lintr
-.*\.tar\.gz$
-CHANGELOG\.md
-Jenkinsfile
-bootstrap-venv
-bootstrap.sh
-files
-invoke.yaml
-rip.lock
-rproject.toml
-tasks.py
-qs-buildtools
-.venv
-.envs
-.idea
+^doc$
```

I am using usethis 1.6.3

**Comment by stefanoborini** [comment]
@jimhester Ok, after I upgraded to the latest usethis, the problem does not occur anymore. I think we can close this at least because it's not a devtools issue. Thanks.

I'll investigate more if I can see it again, but honestly I think I'll just upgrade to 2.0.0 everywhere.
