### ISSUE TITLE
object 'is_R_CMD_check' not found

### ISSUE THREAD

**Issue by jorvlan** [r-lib/devtools#2313]
Hi,

I wanted to share an issue that I came across while updating my R-package.
I uploaded my package two months ago to GitHub and today, I wanted to check whether `devtools::check()` ran without problems.
However, I ran into the following issues:

1. When running `devtools::check()` the following error occured: 

```r
creating vignettes (14.9s) 
--- re-building ‘raincloudplots.Rmd’ using rmarkdown
object 'is_R_CMD_check' not found`
Error: Vignette re-building failed.
```

After reading up on some websites, I was able to resolve this error by changing the following in the Vignette YAML: 

```r
%\VignetteEngine{knitr::rmarkdown}
```
into

```r
%\VignetteEngine{rmarkdown::render}
```
Thereafter, the `devtools::check()` ran until the end with the following warning:

```r
checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘raincloudplots.Rmd’
```
My questions:

Why would I now have to change the YAML data, while `devtools::check()` ran perfectly two months ago?
Any suggestions on how to resolve the `inst/doc` warning? 

Both error and warning did not occur previously on the `devtools::check()` when I uploaded the package two months ago.

Many thanks.

**Comment by jimhester** [comment]
This issue tracker is really used for bugs in the devtools code, not general check questions.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
