### ISSUE TITLE
install.packages("devtools")  error

### ISSUE THREAD

**Issue by 1457634627** [r-lib/devtools#2316]
make: *** [/usr/lib64/R/etc/Makeconf:181: xml2_doc.o] Error 1
ERROR: compilation failed for package ‘xml2’
* removing ‘/usr/lib64/R/library/xml2’
ERROR: dependency ‘xml2’ is not available for package ‘roxygen2’
* removing ‘/usr/lib64/R/library/roxygen2’
ERROR: dependency ‘xml2’ is not available for package ‘rversions’
* removing ‘/usr/lib64/R/library/rversions’
ERROR: dependencies ‘roxygen2’, ‘rversions’ are not available for package ‘devtools’
* removing ‘/usr/lib64/R/library/devtools’

The downloaded source packages are in
	‘/tmp/RtmpTRE12X/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("devtools") :
  installation of package ‘xml2’ had non-zero exit status
2: In install.packages("devtools") :
  installation of package ‘roxygen2’ had non-zero exit status
3: In install.packages("devtools") :
  installation of package ‘rversions’ had non-zero exit status
4: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status

How can I solve this problem ？

**Comment by jimhester** [comment]
Figure out why xml2 failed, likely because `libxml2` was not installed on your system.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
