### ISSUE TITLE
Call latest testthat functions

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2320]
`devtools::test()` should call `test_local()` and `test_file()` should call `testthat::test_file()`

**Comment by jimhester** [comment]
They already do? https://github.com/r-lib/devtools/blob/f6b5935485146a014dd65277634031246d1a17fd/R/test.R#L36-L52

**Comment by jimhester** [comment]
But possibly not in the CRAN version

**Comment by hadley** [comment]
Doh, yeah. Do you think we could do a release soon? (including bump to require latest testthat)

**Comment by jimhester** [comment]
probably, I need to do a pkgdown release, so I could do devtools after that.

**Comment by hadley** [comment]
Closing this since I already did it 😬
