### ISSUE TITLE
Regular install packages fails because devtools not installed

### ISSUE THREAD

**Issue by ArnauC** [r-lib/devtools#2324]
Hi, I'm experiencing the following problem:

When I try to install any package (forcats in this example), at first, it seems to download the package just fine, but right after, I get the following error:

Error in library(package, character.only = TRUE, lib.loc = lib.loc) : 
  there is no package called ‘devtools’
Calls: <Anonymous> -> library
Ejecución interrumpida
Warning in install.packages :
  installation of package ‘forcats’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpzWbLHK/downloaded_packages’

![image](https://user-images.githubusercontent.com/10518683/108374106-e1469d80-7200-11eb-80e0-09fc0533c219.png)

Any suggestion about the cause of this behaviour?

**Comment by jimhester** [comment]
I would guess you have devtools in your `.RProfile`, but have not yet installed it, or something similar.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
