### ISSUE TITLE
Relicensing devtools (wrap up)

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#2326]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio contributors.
​
Due to the maximum number of users who can be tagged in a post on GitHub, there were two issues (#2290, #2291) used to track re-licensing for ggplot2. This issue combines the remaining contributors who have not yet responded.

@AmundsenJunior, @karl-forner-quartz-bio, @mnel, @ncarchedi, @Paxanator, @yoni, would you permit us to re-license devtools with the MIT license? If so, please comment "I agree" below.

* [ ] [@AmundsenJunior](https://github.com/r-lib/devtools/commits?author=AmundsenJunior)
* [x] [@karl-forner-quartz-bio](https://github.com/r-lib/devtools/commits?karl-forner-quartz-bio)
* [ ] [@mnel](https://github.com/r-lib/devtools/commits?author=mnel)
* [ ] [@ncarchedi](https://github.com/r-lib/devtools/commits?author=ncarchedi)
* [ ] [@Paxanator](https://github.com/r-lib/devtools/commits?author=Paxanator)
* [x] [@yoni](https://github.com/r-lib/devtools/commits?author=yoni)

**Comment by hadley** [comment]
@kforner I think this might be you?

**Comment by hadley** [comment]
Code contributed by @mnel no longer exists in devtools.

**Comment by hadley** [comment]
(Note to self — can't relicense until #2290 has been completed)

**Comment by yoni** [comment]
I agree

**Comment by kforner** [comment]
> @kforner I think this might be you?

Indeed. I agree.

**Comment by hadley** [comment]
Since folks haven't responed, I've carefully reviewed their contributions:

* @AmundsenJunior ran styler, extracted duplicated code into a function, and linked a blog post from the README
* @mnel changed one argument in a function call that is no longer included in devtools
* @ncarchedi changed a function that no longer is included in devtools
* @Paxanator adding a missing argument to a call

Since these contributions are small and mostly to code that no longer exists, I will proceed with re-licensing with lack of confirmation.
