### ISSUE TITLE
change wording of the check log ever so slighly

### ISSUE THREAD

**Issue by torbjorn** [r-lib/devtools#2329]
**Is your feature request related to a problem? Please describe.**

When running devtools::check() , it ends saying something like:

    See 
      '/home/user/.../00check.log'
    for details

Actually checking that files, there aren't really details there. It's just the same thing you see in your terminal (or RStudio window)

How about just:

    This output is stored in this log file:

or something.

I feel stupid pointing out this little thing.

It's just I'll be introducing this to absolute beginners in R package work, and adding excuses for all these small inaccuracies all the time eventually bugged me enough to actually feature request improvements here.

Also I admit I am procrastnating writing this.

It would be nice to convey the notion that message output means something, that it's worthwhile to actually read it and comprehend it, and that it holds accurate and relative information to what you are currently doing.

Too many times users approach me with:

them: "hey I got an error, what do I do now?"
me: "well what does it say?"
them: "it says this and that"
me: "well did you try fixing that?"
them: "no"
me: "..."

**Describe the solution you'd like**

See above

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jimhester** [comment]
There is unfortunately very little we can do about it, though I agree they are often not written clearly to new package developers.

This message and basically all the messages when you run `devtools::check()` are coming from `R CMD check` which is developed by the R core team, not anyone associated with the devtools package.
