### ISSUE TITLE
render readme automatically?

### ISSUE THREAD

**Issue by liutiming** [r-lib/devtools#2330]
https://github.com/r-lib/devtools/issues/2007

I wonder what is the status of this issue?

**Comment by jimhester** [comment]
I am not sure what you are asking for, `devtools::build_readme()` exists?

**Comment by jennybc** [comment]
Maybe this is about automation?

I think our group has decided that the inclusion of `devtools::build_readme()` in our release checklist is a solution we can live with. Here's an example (the check list looks different based on features of the package):

https://github.com/r-lib/gargle/issues/164

**Comment by liutiming** [comment]
Yes I was asking about automation. Thanks a lot!

(although it is a bit unexpected that usethis::use_readme_rmd()​will add checks to git hook so that the users are forced to run devtools::build_readme​ every time they change README.rmd. In these cases, an integrated solution will be helpful)
________________________________

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately, while I do think doing this automatically would be convenient in some cases I think there are too many cases where the code in the README.Rmd uses heavy dependencies or takes a long time to run, so I think it is ultimately better to leave things the way they are.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:

**Comment by liutiming** [comment]
Thanks for giving this some thought! Will do :D
