### ISSUE TITLE
devtools addins uses deprecated `test_file` instead of `test_active_file`

### ISSUE THREAD

**Issue by rundel** [r-lib/devtools#2339]
The 2.4.0 update has deprecated `test_file` in favor of `test_active_file` however the package's [addins.dcf](https://github.com/r-lib/devtools/blob/d0070ce0ed4c48a7986d81773ea89f7365e6d7b2/inst/rstudio/addins.dcf#L3) has not been updated and still uses `test_file` which results in a warning when used.

**Comment by jimhester** [comment]
Whoops, forgot about the addins, thanks, we will likely have to do a small release to fix this in the near future.

**Comment by hadley** [comment]
This will also require folks to re-set up their keyboard shortcuts, which is a bit of a bummer (but I don't see any way around it).
