### ISSUE TITLE
Building package with vignette deletes local files in inst

### ISSUE THREAD

**Issue by david-cortes** [r-lib/devtools#2342]
Migrated from here: https://github.com/rstudio/rstudio/issues/9230

**Steps to reproduce:**
* Make an R package project with vignettes (example to use: https://github.com/david-cortes/MatrixExtra).
* Create a sub-folder `inst/doc` and put some files there (e.g. a PDF or alike).
* Run `devtools::build()`

**Expected behavior:** should include the `inst/` files in the package.

**Actual behavior:** ***deletes*** the local files without warning and does not include them in the source build.

**Setup:** devtools 2.3.2.

This is BTW not an issue with R itself since `R CMD build` will not delete local files and will end up including the `inst` folder.

**Comment by jimhester** [comment]
This is the intended behavior, see https://github.com/r-lib/pkgbuild/issues/58 for discussion and suggested workarounds if you insist on using the workflow.
