### ISSUE TITLE
devtools (pkgload?) shims cause trouble in .onLoad

### ISSUE THREAD

**Issue by kevinushey** [r-lib/devtools#2343]
My package's `.onLoad()` looks like this:

```
.onLoad <- function(libname, pkgname) {
   
   # load tbb, tbbmalloc
   .tbbDllInfo       <<- loadTbbLibrary("tbb")
   .tbbMallocDllInfo <<- loadTbbLibrary("tbbmalloc")
   
   # load RcppParallel library
   library.dynam("RcppParallel", pkgname, libname)
   
}
```

When I try to call `devtools::document()`, I see:

```
> devtools::document()
ℹ Updating RcppParallel documentation
ℹ Loading RcppParallel
Error in library.dynam("RcppParallel", pkgname, libname) :
  shared object ‘RcppParallel.so’ not found
Calls: <Anonymous> ... <Anonymous> -> run_pkg_hook -> <Anonymous> -> library.dynam
Execution halted
```

And I believe this is because `.onLoad()` receives "shimmed" paths. If I `ls.str()` in my `.onLoad()`:

```
libname :  chr "/Users/kevin/r/pkg"
pkgname :  chr "RcppParallel"
```

I need to manually control the order in which shared libraries are loaded, hence the explicit usages of `dyn.load()` and `library.dynam()`.

What is the correct way out of this hole? How do I avoid the pkgload shims? Does pkgload need its own `library.dynam()` shim?

**Comment by kevinushey** [comment]
The path that the package was loaded from is also lost since the `.__NAMESPACE__.$path` was overwritten. Should that be preserved elsewhere?

**Comment by jimhester** [comment]
You will just have to not use pkgload or devtools if you want to do this. I don't think this use case is something we have the bandwidth to support.

**Comment by kevinushey** [comment]
Can there at least be an escape hatch, even if it's just documentation or something else? E.g. (if I understand correctly)

- Use `base::system.file()` if you want to avoid the `system.file()` shim;
- Temporarily disable dev mode in some way; e.g. via an option, so that the shims don't activate in certain contexts?

**Comment by jimhester** [comment]
I think using `base::system.file()` should work, can you double check that and if so we can add a note in `help("system.file", package = "pkgload")`

**Comment by kevinushey** [comment]
It looks like that doesn't work unfortunately, presumedly because the package's `.__NAMESPACE__.$path` was modified:

```
> devtools::load_all()
ℹ Loading RcppParallel
> system.file(package = "RcppParallel")
[1] "/Users/kevinushey/r/pkg/RcppParallel/inst"
> base::system.file(package = "RcppParallel")
[1] "/Users/kevinushey/r/pkg/RcppParallel"
> getNamespaceInfo("RcppParallel", "path")
[1] "/Users/kevinushey/r/pkg/RcppParallel"
> find.package("RcppParallel")
[1] "/Users/kevinushey/r/pkg/RcppParallel"
```
I unfortunately can't think of a clean solution to this though :-/ I agree this is niche enough that it's probably not worth extra work (I'm probably the only person using `devtools` trying to do this)

**Comment by kevinushey** [comment]
And (after some coffee this morning) I realize the right solution here is to install the TBB libraries during install to `../inst/lib`, rather than directly to the to-be-installed package directory. This way, local builds + installs are built in a way visible to devtools, and `R CMD INSTALL` will copy the inst folder after that happens anyhow.

**Comment by jimhester** [comment]
Great, glad you worked something out!
