### ISSUE TITLE
build_readme() does not find README in non interactive mode

### ISSUE THREAD

**Issue by ThierryO** [r-lib/devtools#2344]
One of my functions check if the README.Rmd is build when it exists. I test my function via a unit test. When I run the unit test interactively if works as expected. When I run `devtools::test()` it fails with ` Can't find a 'README.Rmd' or 'inst/README.Rmd' file.` (the [related line](https://github.com/r-lib/devtools/blob/96a54f5acdfa6b1f4ecff6f67bf3744e4953dd8e/R/build-readme.R#L57) in the devtools code).

I'm puzzled why this should happen as my code only runs `build_readme()` when the `README.Rmd` exists.

```
  if (file_test("-f", file.path(x$get_path, "README.Rmd"))) {
    status_before <- status(repo)
    build_readme(x$get_path, encoding = "UTF-8")
    doc_error <- c(
      doc_error,
      "`README.Rmd` need to be rendered. Run `devtools::build_readme()`"[
        !unchanged_repo(repo, status_before)
      ]
    )
  }
```

**Comment by jimhester** [comment]
Thanks for opening the issue.

This looks like a bug that was introduced in a recent revision, the `path` argument was not being correctly passed to `dir_ls()`. It should be fixed now, if you could test your code with the current master branch and confirm it is fixed that would be great.

**Comment by ThierryO** [comment]
I can confirm that the problem is solved. Thanks for the quick fix.
