### ISSUE TITLE
RStudio New Project wizard opens duplicate sessions

### ISSUE THREAD

**Issue by peymaneshghi** [r-lib/devtools#2346]
When using RStudio's New Project wizard to create "R package using devtools", it always opens the package in duplicate sessions.
Perhaps the dcf uses `create_package()`, which has `open = rlang::is_interactive()` argument and it causes new session gets opened.

**Comment by malcolmbarrett** [comment]
I've had the same issue with custom project templates, and `open` was indeed the cause. I've had to wrap a helper function that set `open  = FALSE`, then call that function in the project template DCF. However, it doesn't look like the "R package using devtools" template is in this package; is it in the IDE?

**Comment by malcolmbarrett** [comment]
Yeah, I think this is actually an issue created in the IDE, so you might want to file this over there: https://github.com/rstudio/rstudio/blob/0899d13386fd5e61ec847cc62a6eb252702a5ebc/src/cpp/session/modules/SessionProjectTemplate.cpp#L580

**Comment by peymaneshghi** [comment]
Thanks @malcolmbarrett 
Yes but the IDE is calling the `create()` from devtools. 
https://github.com/r-lib/devtools/blob/d4510b2030cfd4b3039d12b63884b503dcafe420/R/create.R#L9

I can't see how that could be fixed at the IDE without providing a wrapper function from devtools with `open = FALSE`?

**Comment by jimhester** [comment]
The only reason `devtools::create()` still exists is because the IDE uses it, so we could set `open = FALSE` as the default method in `devtools::create()`. I think most people will now use `create_package()` interactively.

**Comment by malcolmbarrett** [comment]
Oh, well that sure makes it easy
