### ISSUE TITLE
.check_Rd_contents is not in tools in 4.1.0

### ISSUE THREAD

**Issue by Alanocallaghan** [r-lib/devtools#2354]
This doesn't cause an error as far as I can tell but it presumably means check_man is not doing everything it ought to do. It is also somewhat unsightly.

See this toy package or just run check_man on any R package really. https://github.com/Alanocallaghan/testtools/runs/2684053323?check_suite_focus=true

**Comment by brownag** [comment]
I also have been running into this; it seems that on 4.1 `tools::checkRdContents()` needs to be called rather than `tools:::.check_Rd_contents()` 
https://github.com/r-lib/devtools/blob/2dbdfb06451cb7c5a0547f8a3e3c7332b4605cc1/R/check-doc.R#L29
