### ISSUE TITLE
Optional printing of stdout in devtools::build_manual().

### ISSUE THREAD

**Issue by arnejohannesholmin** [r-lib/devtools#2357]
Would it be an idea to make printing of msg$stdout optional in devtools::build_manual()? Messages like "Underfull \hbox ..." tend to fill up the console, and are anyhow returned from devtools::build_manual().

**Comment by hadley** [comment]
The problem is that we have no easy way to figure out whether a message to `stdout` is important or not, so I think we have to continue to defaulting to printing them all.
