### ISSUE TITLE
`Error: callr subprocess failed: Vignette re-building failed.` in build_vignettes()

### ISSUE THREAD

**Issue by matthiasgomolka** [r-lib/devtools#2360]
I observed that `build_vignettes()` fails with `Error: callr subprocess failed: Vignette re-building failed.`.

Simply knitting the vignette works normally. 

I also found out that `as.package()` which is called in the first line of `build_vignettes()` returns a UNC path in `pkg$path`. When I replace `pkg$path` with the respective "normal" / non-UNC path during debugging, the vignette builds as expected.

`getwd()`, `rstudioapi::getActiveProject()` and `here::here()` all return a "normal" / non-UNC path (if that is of any help).

Do you need any other information? Or am I doing something wrong?

Here is my `session_info()`:
```r
- Session info ------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language en                          
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2021-06-24                  

- Packages ----------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 cachem        1.0.4   2021-02-13 [1] CRAN (R 4.0.5)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.0.5)
 cli           2.5.0   2021-04-26 [1] CRAN (R 4.0.5)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
 desc          1.3.0   2021-03-05 [1] CRAN (R 4.0.5)
 devtools    * 2.4.1   2021-05-05 [1] CRAN (R 4.0.5)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.0.5)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.3)
 fastmap       1.0.1   2019-10-08 [1] CRAN (R 4.0.3)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)
 knitr         1.33    2021-04-24 [1] CRAN (R 4.0.5)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.5)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.0.5)
 pillar        1.6.1   2021-05-16 [1] CRAN (R 4.0.5)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.5)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.3)
 pkgload       1.2.1   2021-04-06 [1] CRAN (R 4.0.5)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.3)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.0.5)
 ps            1.4.0   2020-10-07 [1] CRAN (R 4.0.3)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
 remotes       2.3.0   2021-04-01 [1] CRAN (R 4.0.5)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.0.5)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.3)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
 testthat      3.0.2   2021-02-14 [1] CRAN (R 4.0.5)
 tibble        3.1.2   2021-05-16 [1] CRAN (R 4.0.5)
 tinytest    * 1.2.4   2020-12-17 [1] CRAN (R 4.0.3)
 usethis     * 2.0.1   2021-02-10 [1] CRAN (R 4.0.5)
 utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.3)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.0.5)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.5)
 xfun          0.24    2021-06-15 [1] CRAN (R 4.0.5)

[1] C:/Program Files/R/R4.0.2/library
```

**Comment by wfmueller29** [comment]
I am having this same issue

**Comment by mayer79** [comment]
Me as well...

**Comment by jennybc** [comment]
Note to self: consider if this is due to the adoption of fs and the move to `path_real()` here:

https://github.com/r-lib/devtools/commit/a4fe6113bd7ea06a1da90286b27f2626b4356b9a#diff-6cdf9383192f059643a614d3b5fa2237b4eb6e8a5ccf0d468a7d75057eb987b7

@wfmueller29 @mayer79 can you confirm you are also on Windows?

**Comment by mayer79** [comment]
Windows, here!

**Comment by wfmueller29** [comment]
I am on windows as well

**Comment by jennybc** [comment]
If anyone feels motivated to gather data, it would be interesting to know if `build_vignettes()` works for you if you install devtools 2.3.2, the last version before the switch to fs for file handling.

**Comment by paulnorthrop** [comment]
I had the same problem (on Windows).  I installed devtools 2.3.2, which gave a more specific error message to tell me that in my .Rmd YAML header I had tried to use a Citation Style Language (.csl) file that did not exist in my vignettes directory.  After I corrected my mistake my vignettes built without any problems.  Therefore, perhaps the only issue is how helpful the error message is when we, the users of devtools, mess things up?

**Comment by nspyrison** [comment]
Same and on Windows.  Installing devtools 2.3.2, showed red message text, allowing me to find the issue, (an error in a different vignette).

**Comment by mayer79** [comment]
@jcubic: maybe you can try to update pandoc - sometimes this magically solves such issues.

**Comment by jcubic** [comment]
@mayer79 I needed to install texlive-extra. But the library gives no clue what was the error, unless I've downgraded the library.

**Comment by ColauttiLab** [comment]
I had a similar issue on Windows it but worked after I quit and re-ran in Admin mode

**Comment by hadley** [comment]
You should be able to resolve the vast majority of these problems by running `build_vignettes(quiet = FALSE)`, which we're likely to make the default in the next version.

But I think the root of the problem is that no one on the tidyverse team uses this function so no one noticed any problems with it. Could folks on the thread comment why they use this function?

**Comment by jcubic** [comment]
If I remember correctly, I've used that function to generate pdf files with documentation that I've uploaded to Google Drive.

**Comment by matthiasgomolka** [comment]
I use this function to manually create complete binaries of packages. 

I do this because we don't have a CI/CD pipeline for internal R packages at work.

**Comment by hadley** [comment]
@matthiasgomolka why don't you use `build()` for that?

**Comment by matthiasgomolka** [comment]
I observed that the vignettes are somehow not included in the windows binary if I simply hit the Build button in RStudio. Is `devtools::build()` doing something else than the Build Button?

**Comment by hadley** [comment]
@matthiasgomolka yes.
