### ISSUE TITLE
add function to check if package names are single quoted

### ISSUE THREAD

**Issue by jensharbers** [r-lib/devtools#2362]
**Is your feature request related to a problem? Please describe.**
The CRAN policy states that the user should single quote package names in the title as well in the description section of the DESCRIPTION file. See [Checklist for CRAN submissions](https://cran.r-project.org/web/packages/submission_checklist.html)

'Put non-English usage, including names of other packages and external software, in single quotes. Example: 'OpenSSL'. '

**Describe the solution you'd like**
```

# Alert User to remind CRAN policy for package mentioning

pcks <- utils::available.packages() # get all packages in CRAN
package_names <- base::rownames(pcks) # extract just the package names


# sample string from a Description file
# can be also a Title or the Description section itself.
# for real usage, one has to find a way to read both section from DESCRIPTION file as a string. One per section.
s <- "I use the 'ggplot2' package for plotting awesome plots.
      I also use 'tidyverse' a lot." 

s <- gsub(".,;\"?!", "",s)
s <- base::unlist(base::strsplit(s," ")) 
findings <- base::intersect(s,package_names)

if (base::length(findings) > 0 ){
base::stop(base::paste("change:",
            paste0(findings," --> ","'",findings,"' ")))
}
# prints no error, as the packages are referred correctly with single quotes.

s <- "I use the ggplot2 package for plotting awesome plots.
      I also use tidyverse a lot" 

s <- gsub(".,;\"?!", "",s)
s <- base::unlist(base::strsplit(s," ")) 
findings <- base::intersect(s,package_names)

if (base::length(findings) > 0 ){
base::stop(base::paste("change:",
            paste0(findings," --> ","'",findings,"' ")))
}
```

The basic idea is to retive the known package names and map those with each word of the DESCRIPTION file.
it should return the names of the packages that are not single quoted. Also double quoted packages should be printed as error, as it is different to single quotes.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, tweaking the human written parts of the DESCRIPTION is out of scope for devtools.. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
