### ISSUE TITLE
Convert uses of `stop()` to use `cli::cli_abort()`

### ISSUE THREAD

**Issue by jimhester** [r-lib/devtools#2364]

**Comment by jimhester** [comment]
It looks like there are some [other uses of stop](https://github.com/r-lib/devtools/search?q=stop) we need to clean up as well, so I will leave this open for now.

**Comment by jennybc** [comment]
Oh right, of course! Oops.

**Comment by hadley** [comment]
I'm working on this, as part of a more general messaging cleanup:

* `stop()`
* `rlang::abort()`
* `warning()`
* `rlang::warn()
* `message()
* `rlang::inform()`
* `cli_alert_*()`

I'll also look into making some kind of lintr to make sure we don't accidentally reintroduce.

**Comment by jennybc** [comment]
In terms of linting, here's a workflow in usethis to prevent base R file system functions from creeping back in: https://github.com/r-lib/usethis/blob/main/.github/workflows/lint-undesirable-functions.yaml.

**Comment by hadley** [comment]
Moving to a separate issue since this is about to get closed.
