### ISSUE TITLE
Problem including a large matrix when using devtools install

### ISSUE THREAD

**Issue by p-carter** [r-lib/devtools#2366]
I'm trying to use devtools install with a package that I am developing. I do the following after starting R:

library("devtools")                              
library("roxygen2")                               
setwd("./")                                       
install("myPackage")

But I get the error:

*** moving datasets to lazyload DB
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  : 
  long vectors not supported yet: connections.c:5984
ERROR: lazydata failed for package ‘myPackage’
* removing ‘/home/phil/R/x86_64-pc-linux-gnu-library/3.6/myPackage’
* restoring previous ‘/home/phil/R/x86_64-pc-linux-gnu-library/3.6/myPackage’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout & stderr were printed

I think this is caused by a recent addition of a large matrix in the package's data/ directory stored as a  .RData file. If I remove that file, devtools install works fine again. I can load the matrix inside R, although it's big (matrix is 45000x24717).

I found that I can get around this by splitting the matrix into 3 parts to make the vectors/matrices smaller, but I'd still like to know if there is a way that I can use just one file.

I've looked at the devtools install documentation, but I didn't see anything like a parameter that I can set.

When I searched for a solution, I saw some answers for similar problems where cache.lazy = FALSE was recommended for lazyLoadDBinsertVariable.

I tried posting on the Google group for rdevtools but I didn't get a reply.

Thanks very much in advance.

**Comment by jimhester** [comment]
LazyData datasets have a limit of 2 GB when serialized.

> Lazy-loading is not supported for very large datasets (those which when serialized exceed 2GB, the limit for the format on 32-bit platforms).

From https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages

This is R limitation, not a devtools specific issue.

**Comment by p-carter** [comment]
Thanks for your comment. It's not 2GB - it's about 79Mb; but the matrix has large dimensions (45000x24717), I think it's probably related to that i.e. exceeding the vector length. I wonder though if there's a work around e.g. parameter that I can set?

**Comment by hadley** [comment]
I'm closing this since it seems like an R issue, rather than a devtools one.
