### ISSUE TITLE
Add a function to install archive packages

### ISSUE THREAD

**Issue by earnaud** [r-lib/devtools#2367]
Upon upgrading R to 4.0, one of my packages got obsolete (namely {ArgumentCheck}) and has been removed from CRAN repo. However, its archived versions still work efficiently. I then wanted to get a way to install it back. I then used the following function to get it installed:

```
install.archive <- function(url) {
  stopifnot(!missing(url))
  stopifnot(is.character(url) && grepl("^https?://cran.r-project.org/src/contrib/Archive", url))
  
  pkgFile <- paste0(tempdir(), gsub("^https?://.*/", "", url))
  download.file(url, pkgFile)
  
  devtools::install_local(pkgFile, dependencies = TRUE, upgrade = "never")
  
  unlink(pkgFile)
}
```

Clearly, this is more a script than a robust solution, but I believe a `install.archive()` function to allow the user to get older version would easily would be helpful. Also, letting a `version` argument could be useful to catch older versions.

**Comment by jimhester** [comment]
You can do this with `install_version()`, e.g. 

`devtools::install_version("ArgumentCheck", "0.10.2")`
