### ISSUE TITLE
revdep does not support Bioconductor repositories beyond the software one

### ISSUE THREAD

**Issue by lcolladotor** [r-lib/devtools#2368]
**Is your feature request related to a problem? Please describe.**

When working with Bioconductor packages, `revdep()` only extracts the information from the Bioconductor software packages. However, there are more types: annotation, experiment data, workflows, and books. So those dependencies are missed. See

```R
> devtools::revdep("SpatialExperiment", recursive = TRUE, bioconductor = TRUE)
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org/

[1] "ExperimentSubset" "mistyR"
```

which misses several packages:

<img width="649" alt="Screen Shot 2021-08-06 at 3 14 02 PM" src="https://user-images.githubusercontent.com/2288213/128560614-822daab7-0e0b-414c-aa73-266b80a136cd.png">

**Describe the solution you'd like**

I wrote the following code going by what `devtools` already does. I can modify it and submit it as a PR if you think that's ok.

```R
packages_all <- function() {
    repos <- BiocManager::repositories()
    views <- paste(repos[grepl("BioC", names(repos))], "VIEWS", sep = "/")
    views <- views[!grepl("books", views)]
    
    all_pkgs <- c(lapply(views, devtools:::bioc_packages), list("CRAN" = devtools:::cran_packages()))

    Reduce(function(...) merge(..., all = TRUE), all_pkgs)
    
}

revdep_all <- function(pkg, dependencies = c("Depends", "Imports", "Suggests",
    "LinkingTo"), recursive = FALSE, ignore = NULL, bioconductor = FALSE)
{
    if (missing(pkg))
        pkg <- as.package(".")$package
    all <- if (bioconductor)
        packages_all()
    else devtools:::cran_packages()
    deps <- tools::dependsOnPkgs(pkg, dependencies, recursive,
        installed = all)
    deps <- setdiff(deps, ignore)
    devtools:::sort_ci(deps)
}
 ```

The end result is this one:

```R
> revdep_all("SpatialExperiment", recursive = TRUE, bioconductor = TRUE)
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org/

[1] "BayesSpace"            "ExperimentSubset"      "miloR"
[4] "mistyR"                "MouseGastrulationData" "SingleCellMultiModal"
[7] "spatialLIBD"           "STexampleData"         "TENxVisiumData"
```

**Describe alternatives you've considered**

In my `packages_all()` code there's a little detail that "books" is a new Bioconductor repository and it doesn't have the `VIEWS` that others do have. Another option would be to use `tryCatch()` and test all the `views` instead of dropping `books`.

**Additional context**

I'm trying to list at https://github.com/lmweber/OSTA-book all the software related to `SpatialExperiment` that readers might want to check out.

Thanks!

**Comment by lcolladotor** [comment]
R version details:

```R
> R.version.string
[1] "R version 4.1.0 (2021-05-18)"
> packageVersion("devtools")
[1] ‘2.4.2’
> packageVersion("BiocManager")
[1] ‘1.30.16’
> BiocManager::repositories()
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org/

                                                BioCsoft
           "https://bioconductor.org/packages/3.14/bioc"
                                                 BioCann
"https://bioconductor.org/packages/3.14/data/annotation"
                                                 BioCexp
"https://bioconductor.org/packages/3.14/data/experiment"
                                           BioCworkflows
      "https://bioconductor.org/packages/3.14/workflows"
                                               BioCbooks
          "https://bioconductor.org/packages/3.14/books"
                                                    CRAN
                          "https://cloud.r-project.org/"
```

**Comment by lcolladotor** [comment]
Oops, just saw this https://twitter.com/hadleywickham/status/1423763753594761225?s=20. Please enjoy your well deserved rest!!!! =)

**Comment by jimhester** [comment]
In some sense this omission is intentional. We use `revdep()` to determine which packages we run reverse dependencies for, and these other Bioconductor repository types are often too large for us to make it worth our while to check them. They also typically have only a small amount of R code that could possibly break if dependencies change.

**Comment by lcolladotor** [comment]
Ok, that's fair. Thanks for the reply Jim. 

I do have an experiment data package on Bioconductor with lots of code, `spatialLIBD`, which is an exemption to the general trend that you described. Regardless though, for the purposes of https://github.com/lmweber/OSTA-book/commit/376498872494eee2302358d2a240e553430772fe we wanted to find an automatic way to list all packages related to `SpatialExperiment`. The above code, outside of a package, already works for that purpose.

If we/I want to make it easier for others to run code like this, would it be best if I added this version to `biocthis` as say `biocthis::bioc_revdep()`? It would have a couple of `:::` calls though. Or would suggest doing a PR with a logical argument like `bioc_all` that defaults to `FALSE` on `revdep()`, such that the current use of `revdep()` doesn't change, but it does support the use case I'm presenting.

Best,
Leo

**Comment by jimhester** [comment]
Yeah I think putting it in `biocthis` seems like a good solution. What unexported functions would need to be exported in devtools?

**Comment by lcolladotor** [comment]
Hi Jim,

I can live with the unexported functions, though well, if you ever change them I'll notice once the daily Bioconductor build report lets me know. 

The list is at https://github.com/r-lib/devtools/issues/2368#issue-962987313, so that would be:

* `devtools:::bioc_packages`
* `devtools:::cran_packages`
* `devtools:::sort_ci`

Best,
Leo

**Comment by mlane3** [comment]
For my state partners and the CDC, I would also like to second nomination for 'biothis'.

**Comment by hadley** [comment]
We no longer use `revdep()` to power our own reverse dependency checks, so it's unlikely we'll change it in the future. I'd encourage you to create your own function that provides the list of reverse dependencies that's most useful for you.
