### ISSUE TITLE
Suggestion: check size of tarball/add to list of Qs before release

### ISSUE THREAD

**Issue by higgi13425** [r-lib/devtools#2369]
**Problem:**
Submitted a data package > 5 MB to CRAN

**Possible solution:**
It would be nice (especially for beginners) to have a built-in check of tarball size, and a friendly note if > 5 MB that 1. this is too big for CRAN, and 2. you might want to edit your .Rbuildignore file to exclude some files, especially files for web documentation, pkgdown, etc.

It would also be nice to add this to the list of Q before release, if detected

**Describe alternatives you've considered**
1. Knowing the 5MB limit
2. Checking tarball size manually

**Admittedly**
this is not a huge deal, but would be friendly and helpful, and avoid CRAN rejections.

**Comment by jimhester** [comment]
The size limit is included in the standard checks in `R CMD check` which is run by `devtools::check()`.

https://r-pkgs.org/r-cmd-check.html#package-structure

**Comment by hadley** [comment]
`submit_cran()` also prints the size of the tarball, so I think we're already doing enough here.
