### ISSUE TITLE
Suggestion: function to build \describe and \items section of oxygen file from a dataset

### ISSUE THREAD

**Issue by higgi13425** [r-lib/devtools#2370]
**Problem**
While it is relatively easy to write an R script to generate a .Rd documentation file for a small dataset with few variables, it is quite painful for a dataset with hundreds of variables, especially when many variables have nonintuitive names, like gene names.

**Possible solution**
A devtools function that would take a dataset as an argument, and build (with glue?) the 
\describe section of the R script to generate and .Rd file
with all of the \items, data type, levels (if factor), range (if numeric), and a spot for a descriptive name (which would have to be hand-edited)

**Describe alternatives you've considered**
Spending a long time hand-editing these and hunting for typos, missing braces, mismatched variable names, etc.

**Additional context**
It is not essential, but it would be nice and friendly.

**Comment by jimhester** [comment]
Thanks for opening the issue!

I don't think we will add something like this to devtools, however there exist packages to do some of this already, e.g.

``` r
#install.packages("sinew")
sinew::makeOxygen(mtcars)
#> #' @title DATASET_TITLE
#> #' @description DATASET_DESCRIPTION
#> #' @format A data frame with 32 rows and 11 variables:
#> #' \describe{
#> #'   \item{\code{mpg}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{cyl}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{disp}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{hp}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{drat}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{wt}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{qsec}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{vs}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{am}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{gear}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{carb}}{double COLUMN_DESCRIPTION} 
#> #'}
#> #' @details DETAILS
#> "mtcars"
```

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by higgi13425** [comment]
thanks - did not know about {sinew} !    On Tuesday, August 17, 2021, 02:31:56 PM EDT, Jim Hester ***@***.***> wrote:  
 
 


Thanks for opening the issue!

I don't think we will add something like this to devtools, however there exist packages to do some of this already, e.g.
#install.packages("sinew")
sinew::makeOxygen(mtcars)
#> #' @title DATASET_TITLE
#> #' @description DATASET_DESCRIPTION
#> #' @format A data frame with 32 rows and 11 variables:
#> #' \describe{
#> #'   \item{\code{mpg}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{cyl}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{disp}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{hp}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{drat}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{wt}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{qsec}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{vs}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{am}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{gear}}{double COLUMN_DESCRIPTION}
#> #'   \item{\code{carb}}{double COLUMN_DESCRIPTION} 
#> #'}
#> #' @details DETAILS
#> "mtcars"
Created on 2021-08-17 by the reprex package (v2.0.0)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
