### ISSUE TITLE
Suggestion: a function to detect which variables are mismatched when Check fails for a data package because code variables names do not match docs

### ISSUE THREAD

**Issue by higgi13425** [r-lib/devtools#2371]
**Problem**
When variable names in a dataset do not **exactly** match the documentation file, it is relatively easy find the difference in a small dataset with few variables. However, it is quite painful when you have a dataset with hundreds of variables, especially when many variables have similar names, or nonintuitive names, like gene names.

**Suggested solution**
a function that would compare the dataset variables and the documentation variables, and display the mismatches

**Describe alternatives you've considered**
pasting the check output into 2 word documents, one for docs and one for code, and running Compare Documents. This is a hacky workaround, but it works. Just far from elegant. But a lot better than hand-inspecting hundreds of non-adjacent pairs of variable names.

**Additional context**
This is a bit of an edge case. But I do think more folks have large datasets with many variables nowadays.

**Comment by jimhester** [comment]
I think `R CMD check` already does this automatically?
