### ISSUE TITLE
get true namespace exports

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/devtools#2373]
Because {devtools} hacks the namespace system, `getNamespaceExports()` returns all unexported objects too if `devtools::load_all()` was used.

I'm designing a function to help package development and I'd like to access the list of true exports of the currently developed package.

The following gets me close, except it doesn't include the variables created by `.onLoad()` (and I don't know how to get those)  :  

```
get_namespace_exports <- function(ns) {
  current_pkg <- sub("^Package: (.*)$", "\\1", readLines("DESCRIPTION")[[1]])
  if(is.environment(ns)) ns <- sub("^namespace:", "", environmentName(ns))
  if(ns != current_pkg) return(getNamespaceExports(ns))
  ns_lines <- readLines("NAMESPACE")
  pattern <- "^export\\((.*)\\)$"
  sub(pattern, "\\1", ns_lines)[grepl(pattern, ns_lines)]
}
```

Would it make sense to have such a function in {devtools} ?

**Comment by jimhester** [comment]
You could call `getNamespaceExports(pkgload::load_all(export_all = FALSE))`

**Comment by moodymudskipper** [comment]
Thanks. This code fails as `load_all()` doesn't return a namespace, but maybe you meant the following ?

```
pkgload::load_all(export_all = FALSE)
getNamespaceExports(my.package)
```

If so, it does give me what I want, but I'd like to still have access to unexported functions, I can wrap those in a function but it is slow and seems overkill ?

```
pkgload::load_all(export_all = FALSE, quiet = TRUE)
getNamespaceExports(my.package)
pkgload::load_all(export_all = TRUE, quiet = TRUE)
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
