### ISSUE TITLE
`check_mac_devel()`

### ISSUE THREAD

**Issue by jimhester** [r-lib/devtools#2375]
Like `check_win_devel()` but on CRAN's new m1 macOS builder (https://mac.r-project.org/macbuilder/submit.html)

**Comment by hadley** [comment]
Including support for additional custom dependencies. There is a private API we might be able to use.

**Comment by jimhester** [comment]
The custom dependencies stuff is documented at https://github.com/R-macos/recipes. But I don't think that part it is something we can really automate. We can certainly include a link in the documentation to that repo however.

**Comment by jimhester** [comment]
Oh I see, there is also support for custom R dependencies apart from the system dependencies I referenced above.
