### ISSUE TITLE
devtools::document() fails namespace imports with files which contain no code

### ISSUE THREAD

**Issue by JSzitas** [r-lib/devtools#2378]
Hi! 

I have a problem with `devtools::document()` where it fails to record imports from files which contain no code. I set up a minimal reproducible example over at https://github.com/JSzitas/autodepFailExample. 

In short, as long as any code is present in the file, `devtools::document()` seems to record the imports from the `@importFrom` tags as anticipated (regardless of whether they are used in the code). This would be what I would anticipate would happen. However, if you have a file which contains nothing but `@importFrom` tags (or, I presume, other tags and/or documentation), the imports specified there will not be recorded in the `NAMESPACE` file when running `devtools::document()`.

This led to a bit of confusion for me and I have no idea whether this is intended behavior, so I figured I would ask. 

Thank you for the awesome package!

**Comment by jimhester** [comment]
This is expected, use `NULL` below the import in these cases.

```r
#' @importFrom foo bar
NULL
```
