### ISSUE TITLE
quit and restart R.app (on MacOS) after each make

### ISSUE THREAD

**Issue by tbates** [r-lib/devtools#2380]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to quit and restart R.app (on MacOS) after each make.

**Describe the solution you'd like**
it would be great if devtools had a `restart= T/F` parameter allowing the user to automate build, quit, and execute a delayed call like this (would need tweaking):

```R
system("sleep 2; open -a R.app")
quit()
```

**Describe alternatives you've considered**
manually watching for make to complete, executing quit, opening R... 10 times a session :-)

**Additional context**
This was not necessary a couple of years ago as builds typically left the package  reloaded correctly. So loving the library/corruption problem would be the ideal solution with this as a workaround..

**Comment by hadley** [comment]
The point of `devtools::load_all()` is to avoid restarting R after each compile. Have you tried using that?

**Comment by tbates** [comment]
That does the trick: thank you Hadley - I had not seen `load_all` before + assumed build would do this rather than leave the help database etc. non-operable.

t
