### ISSUE TITLE
how to generate function lists in a pks?

### ISSUE THREAD

**Issue by DawnEve** [r-lib/devtools#2389]
I add one function and annotation, and `build()`.
The function can be called correctly, and F1 on the fucntion works.

But `help(package='Gxx') #URL '/help/library/Gxx/html/00Index.html' not found`
When using `help(package='ggplot2')`, it is a function list in this pkg, but mine is empty.
So, how to generate function list in a pkg?

**Comment by jennybc** [comment]
This issue doesn't appear to be a bug report or a specific feature request for devtools, so it's more suitable for [RStudio Community](https://community.rstudio.com).

But it sounds like you might only be building the package ("Building converts a package source directory into a single bundled file.") rather than **installing** the package.

https://r-pkgs.org/package-structure-state.html

**Comment by DawnEve** [comment]
> This issue doesn't appear to be a bug report or a specific feature request for devtools, so it's more suitable for [RStudio Community](https://community.rstudio.com).
> 
> But it sounds like you might only be building the package ("Building converts a package source directory into a single bundled file.") rather than **installing** the package.
> 
> https://r-pkgs.org/package-structure-state.html

No, I do this without Rstudio, under R command line, And I both build my pkg and install my pkg, but there are no function list page after usuing `build` function in devtools.

**Comment by DawnEve** [comment]
A simple example:
```

=> R
> library('devtools')
> create('~/data/my_R_pkg/somePkg')
> setwd('~/data/my_R_pkg/somePkg')
> dir()
# [1] "DESCRIPTION" "NAMESPACE"   "R"


=> shell
$ cd ~/data/my_R_pkg/somePkg
$ vim R/add.R
#' Add 2 numbers
#'
#' @param num1 a number
#' @param num2 another number
#'
#' @return a number
#' @export
#'
#' @examples
#' my_add(2, 3)
#'
my_add <- function(num1, num2){
	num1+num2
}

# no change to DESCRIPTION.
$ cat DESCRIPTION 
Package: somePkg
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person("First", "Last", , "first.last@example.com", role = c("aut", "cre"),
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
    license
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2



=>R
> devtools::document()
> build()
# [1] "/home/wangjl/data/my_R_pkg/somePkg_0.0.0.9000.tar.gz"

> install.packages("~/data/my_R_pkg/somePkg_0.0.0.9000.tar.gz", repos = NULL, type = "source")
# * DONE (somePkg)

> library("somePkg")
> my_add(2,3)
[1] 5

> help(package='somePkg')
Information on package ‘somePkg’
Nothing below, no function list, no description 



> help(package='ggplot2')
              Information on package ‘ggplot2’

Description:

Package:                ggplot2
Version:                3.3.5
Title:                  Create Elegant Data Visualisations Using the
                        Grammar of Graphics
...
Index:

+.gg                    Add components to a plot
CoordSf                 Visualise sf objects
aes                     Construct aesthetic mappings
```
