### ISSUE TITLE
copy vignettes to inst/doc after calling document?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/devtools#2394]
This is related to https://github.com/rstudio/rstudio/issues/1766.

In RStudio, the default package workflow involves installing the package without building vignettes, which implies that calls to `vignette()` will fail to find your package's vignettes (unless, of course, you run `devtools::load_all()` before your attempt).

However, it's possible for the RStudio install-without-build to work with vignettes if those vignettes are copied to `inst/doc` first. We could do this in RStudio, but it might be reasonable to do this in `devtools` as well.

In this world, the assumption is that the package author only places their vignettes in the `vignettes/` directory, and the `inst/doc/` directory is managed entirely by `devtools`. So, `devtools::document()` would:

1. Remove any old files within `inst/doc/`,
2. Generate documentation + vignettes with `roxygen2` as normal (if the `vignette` roclet is active),
3. Copy the generated vignettes to `inst/doc/`, so they're visible on a later install.

A later call to `R CMD INSTALL` would use the versions of those vignettes copied to `inst/doc/`; if the package author later was preparing a release for CRAN, those older vignettes would be automatically overwritten during build. This implies no extra gunk in `.Rbuildignore` or `.Rinstignore` is required, which is nice.

Let me know if this feels in scope; if not, we'll probably consider a similar strategy in RStudio proper.

**Comment by jennybc** [comment]
My first reaction is that no, we probably don't want to do this in devtools, but I'll be interested to hear if @hadley and @gaborcsardi have opinions.

I seem to mostly live in a state where I have no built vignettes lying around for packages I'm working on. If I just want to consult an existing vignette, I go to the pkgdown site. If I'm tinkering with a vignette, I knit it locally. I also seem to work mostly on packages that use articles heavily, much more than goes-to-CRAN vignettes. Even for other people's packages, that have no pkgdown site, I barely ever read local vignettes. I guess I just read the PDF on CRAN.

So it seems my vignette-related workflows are very, very different from, e.g., what I absorb from those commenting in https://github.com/rstudio/rstudio/issues/1766.

**Comment by hadley** [comment]
Yeah, I'm pretty sure we don't want to do that here. We probably do need to think about our overall vignette management strategy, but the current strategy at least works for us without problems.
