### ISSUE TITLE
Suggestion: Ability to use built packages with check_win_*  and check_mac_release

### ISSUE THREAD

**Issue by waternumbers** [r-lib/devtools#2398]
It seems that these functions appear to build then submit the package. It would be nice if they could recognise built packages (*.tar.gz) and submit these rather then rebuilding from source.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
