### ISSUE TITLE
Images in Rd pages not displayed during development (img src mismatch with tmp file path + resources not copied)

### ISSUE THREAD

**Issue by tbates** [r-lib/devtools#2399]
Thank you for the ever improving goodness of devtools!
During development, in the browser the generated file path for a Rd file  will be e.g.
> file:///private/var/folders/66/wrbb/T/Rtmp/Rtxt.html

Paths to images in that Rd file, however, are unchanged (e.g. `<img src="../help/figures/example.png">`) and the `help` and `figures` folders aren't copied in.

So, the image display fails because the folder containing the generated page doesn't contain the `figures` folder and the address is not re-written to match the throw-away url.

Not a massive problem, but would be nice if images displayed during development.

<img width="930" alt="missing image 2021-12-31 at 00 14 39" src="https://user-images.githubusercontent.com/736156/147795881-130349be-7013-4738-9ee9-9bf32eed5b78.png">

**Comment by tbates** [comment]
fyi also, `\doi{}` links in Rd files are not expanded in the browser build of help files, instead appearing like this `\Sexpr[results=rd,stage=build]{tools:::Rd_expr_doi("10.1001/archpsyc.65.8.897")}.`

e.g.

> De Moor, M. H., Boomsma, D. I., Stubbe, J. H., Willemsen, G., & de Geus, E. J. (2008). Testing causality in the association between regular exercise and symptoms of anxiety and depression. Archives of General Psychiatry, 65(8), 897-905. \Sexpr[results=rd,stage=build]{tools:::Rd_expr_doi("10.1001/archpsyc.65.8.897")}.

again, minor, but perhaps worth fixing.

**Comment by hadley** [comment]
I'm pretty sure we've looked into this in the past, and it would be very expensive to fix. Fortunately you can just build and install the whole package.
