### ISSUE TITLE
Could `@noRd` create build ignored help files for developers ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/devtools#2400]
This might be an roxygen2 issue but I think devtools is needed. 

When working on a big package it would be useful to view the doc of the functions tagged with noRd as the standard documentation.

We can use `@keywords internal` but then the doc is available to all users of the package, it would be good to keep it only for developers to discourage use of internal functions by users, and because it might be of lower quality than what we want to share to the public.

If we stored the `@noRd` generated files in a build ignored folder we could make `?` in devtools_shims look up the doc there too.

As an additional benefit it might be used to create pages not attached to functions, containing guidelines to developers or explain the code structure, this would make cross references convenient and we could consult those right from the gui.

We might also have a new dedicated tag for this feature

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by moodymudskipper** [comment]
I've implemented the idea in {devtag}, so we can use "@dev" for unexpected functions where we would use "@export" for exported ones.

https://github.com/moodymudskipper/devtag
