### ISSUE TITLE
`install` always recompiles the C/C++ code

### ISSUE THREAD

**Issue by stla** [r-lib/devtools#2403]
Hello,

  When I do a package including C code or using **Rcpp**, and when I click *"Install and restart"* in RStudio, the C/C++ code is not recompiled if it has not changed. But with `devtools::install` it is always recompiled. Is it possible to prevent that? That would be nice.

**Comment by jennybc** [comment]
It sounds like you might want to set `build = FALSE`?

```
build

if `TRUE` `pkgbuild::build()`s the package first: this ensures that the installation is completely clean, and prevents any binary artefacts (like .o, .so) from appearing in your local package directory, but is considerably slower, because every compile has to start from scratch.
```

https://devtools.r-lib.org/reference/install.html

**Comment by stla** [comment]
I believe I already tried this option, and that didn't change anything. But OK, will try again to be sure.

**Comment by stla** [comment]
I confirm my belief: `build = FALSE` does not solve the problem.

**Comment by jennybc** [comment]
I'm not able to reproduce this. That is, I can call `devtools::install()` in a package with C/C++ below `src/` and, if nothing's changed, the existing `.o`/.`so` files are being used, i.e. I'm not seeing recompilation. So I can't agree that `install()` unconditionally recompiles everything.

Chances are there's something specific about about your context (your package, your settings, etc.) that is tickling some difference between the way devtools and RStudio are forming the call to `R CMD INSTALL` (note: that RStudio has been known to display a certain command in the build pane, but then be executing something *slightly* different).

If you can provide exact steps to reproduce, you can open a new issue.
