### ISSUE TITLE
`devtools::install` always recompiles C/C++

### ISSUE THREAD

**Issue by stla** [r-lib/devtools#2405]
[Obeying to @jennybc](https://github.com/r-lib/devtools/issues/2403#issuecomment-1013764866), I provide here the exact steps which yield to my problem. I'm using R-4.1.2 on Windows 10.

- Make a package containing C code or C++ using **Rcpp**.
- Install it with the button "Install and restart" in RStudio. This compiles the C/C++ code, but if you don't change it and press again the button, this does not run the compilation.
- So don't change anything to your C/C++ code. Open a terminal a Windows, run R (by typing "R") from the package directory, and once R is opened, type `devtools::install(args = "--no-multiarch", build = FALSE)`. Then this runs the C/C++ compilation, even though the C/C++ code has not changed.

**Comment by jennybc** [comment]
Can you point to a package with source on GitHub where you see this?

When I do this with readxl, I see no recompilation:

```
> devtools::install(args = "--no-multiarch", build = FALSE)
Running /Library/Frameworks/R.framework/Resources/bin/R CMD INSTALL \
  /Users/jenny/rrr/readxl --install-tests --no-multiarch
* installing to library ‘/Users/jenny/Library/R/x86_64/4.1/library’
* installing *source* package ‘readxl’ ...
** using staged installation
** libs
make: Nothing to be done for `all'.
installing to /Users/jenny/Library/R/x86_64/4.1/library/00LOCK-readxl/00new/readxl/libs
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (readxl)
```

**Comment by stla** [comment]
Yes, this happens for my package [RCGAL](https://github.com/stla/RCGAL). I advertise you the compilation is slloooowwww.

**Comment by hadley** [comment]
Thanks for filing this issue! I think it's due to the interaction between `devtools::install()` and RStudio's "build and reload", and unfortunately it seems unlikely to be worth the time to run down exactly what's causing the problem. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by stla** [comment]
Hi,

  Now I'm using `devtools::install(quick = TRUE)` and I don't get this problem.
