### ISSUE TITLE
Difference between devtools::check() and devtools::test() regarding usage of test data

### ISSUE THREAD

**Issue by MxNl** [r-lib/devtools#2412]
Hello,

in my currently developed package I want to use data (several .tif files) for unit testing with testthat.
I read in [R Packages](https://r-pkgs.org/data.html#other-data) that the recommended solution is to put it into the tests directory.
Additionally, I read this thread on [Stackoverflow](https://stackoverflow.com/questions/32328802/where-should-i-put-data-for-automated-tests-with-testthat).
I put it in 
- tests/testdata. Later I also tried it in 
- inst/testdata and 
- inst/extdata. 

In one of my testfiles I test a function that gets the directory where the test data lives as argument. I provided this directory using 
- "tests/testdata"
- system.file("tests/testdata", package = "my-package")
- here::here("tests/testdata")

When running the test using devtools::test() everything is fine but when running devtools::check() or using control + shift + E this directory is not found. After printing the root directory during testing it seems that the directory "test" doesn't exist.
I didn't expect this to be an edge case, but from the usual web research it seems like it.

I would really appreciate any hint. Thanks a lot!

**Comment by MxNl** [comment]
I have now posted it also here: https://community.rstudio.com/t/difference-between-devtools-check-and-devtools-test-regarding-usage-of-test-data/130561
I will close this issue, if it gets answered in RStudio community.

**Comment by jennybc** [comment]
I believe [`testthat::test_path()`](https://testthat.r-lib.org/reference/test_path.html) is the solution you seek.

**Comment by jennybc** [comment]
This GitHub search is rich in examples of how people use it:

https://github.com/search?q=test_path+path%3Atests+org%3Acran

**Comment by MxNl** [comment]
> I believe [`testthat::test_path()`](https://testthat.r-lib.org/reference/test_path.html) is the solution you seek.

Thanks a lot!!! I'll try it out. It would be great to have an example of that in the R Packages book. After an average web search I didn't come across that function. According to the lack of solutions in relevant questions on SO, others have difficulties to find it, too. But thanks a lot so far! Greetings from Berlin!

**Comment by jennybc** [comment]
The testing chapter has not been revised yet for the 2nd edition but will be.

**Comment by KrishyV** [comment]
In my case, the contents of `inst/testdata` was moved to a folder `Package.Rcheck/Package/test-data/` when running `devtools::check()`. This difference in working directory broke the absolute path to the test data. I did a pattern match with `grepl ` to handle this case. Not elegant but it worked.

**Comment by MxNl** [comment]
> In my case, the contents of `inst/testdata` was moved to a folder `Package.Rcheck/Package/test-data/` when running `devtools::check()`. This difference in working directory broke the absolute path to the test data. I did a pattern match with `grepl ` to handle this case. Not elegant but it worked.

Ok, but why not using jennybc's solution. It's easy and works. Data in subfolder of tests/testthat and then refer to it with `testthat::test_path()`.
