### ISSUE TITLE
devtools::install changes .libPaths()

### ISSUE THREAD

**Issue by LukasTang** [r-lib/devtools#2421]
Hi, we just upgraded to R 4.1.3 (from 3.5.1), we change our library path through RProfile.Site to a custom path, but when I try to install custom packages, it crashes and the library paths change, how can this be?

![image](https://user-images.githubusercontent.com/49587161/166635121-b21a1713-d669-4fab-a12a-1f6c6a9eadf0.jpeg)

**Comment by jennybc** [comment]
It's almost impossible to troubleshoot based on a photo of your screen.

But I see "downloaded length 0 != reported length 213003" which suggests that the zip ball did not download, which would is a good candidate for the main problem here.
