### ISSUE TITLE
Updates needed for the cheatsheet

### ISSUE THREAD

**Issue by jennybc** [r-lib/devtools#2443]
Thanks to @averiperny the package development cheatsheet got a much-needed update in June/July 2022. Hopefully we'll test drive it in workshops at rstudio::conf(2022).

However, we fully expect that it needs a few more refinements. This issue is the designated place to collect any reports of typos or suggestions for improvement.

The revised cheatsheet is already appearing in the devtools README / pkgdown site.

All related assets live in the dedicated cheatsheet repo:

https://github.com/rstudio/cheatsheets/blob/main/keynotes/package-development.key

https://github.com/rstudio/cheatsheets/blob/main/package-development.pdf

https://github.com/rstudio/cheatsheets/blob/main/pngs/package-development.png

https://github.com/rstudio/cheatsheets/blob/main/pngs/thumbnails/package-development-thumbs.png

**Comment by jennybc** [comment]
The PDF may lack a "bleed area". Or maybe this is just a "feature" of all our cheatsheets?

https://github.com/rstudio/cheatsheets/issues/258

**Comment by jennybc** [comment]
> Getting Started
> Once per machine:
> • Get set up with `use_r_profile()`

`use_r_profile()` should be replaced with `use_devtools()`

**Comment by gui-salome** [comment]
The `create_package` function does not exist, should be replace by `create`:
<img width="510" alt="Screen Shot 2022-09-09 at 4 31 52 PM" src="https://user-images.githubusercontent.com/68299186/189438210-4adec8ad-58e3-446a-b1b4-3c1ac8574272.png">

**Comment by jennybc** [comment]
@gui-salome No, it's more the other way around. `devtools::create()` is now just a thin wrapper for `usethis::create_package()`. And anyone who attaches devtools with `library(devtools)` will have usethis attached as well.

**Comment by jennybc** [comment]
I think this is done (?) so I'm closing.
