### ISSUE TITLE
Local installation of devtools

### ISSUE THREAD

**Issue by jcabrerazuniga** [r-lib/devtools#2462]
I tried installing devtools on a shared Centos 7 server:

> install.packages("devtools")
Installing package into ‘/home/jcabrerazuniga/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
Error in install.packages("devtools") : 
  unable to create temporary directory ‘/tmp/Rtmpey9yAc/downloaded_packages’
In addition: Warning message:
In dir.create(tmpd) :
  cannot create dir '/tmp/Rtmpey9yAc/downloaded_packages', reason 'No such file or directory'

As I can see the installation tries to use a tmp folder that my account has no access to. Could it be possible to use a tmp file within the user's folder to do the installation?

**Comment by jennybc** [comment]
This issue doesn't appear to be a bug report or a specific feature request, so it's more suitable for [RStudio Community](https://community.rstudio.com).

**Comment by jcabrerazuniga** [comment]
Possibly you are right, but that permissions issue will be a problem on Linux systems. If the user of R does not have admin privileges then this problem will stop that user from installing devtools.

Thanks
Jose
________________________________

**Comment by jennybc** [comment]
I don't see how this is specific to devtools, though. Nor how it could be fixed in devtools.

**Comment by jcabrerazuniga** [comment]
This is for Dev-tools installation process and this, normally, is developer's responsibility. I tried a local installation and the problem appeared. I had to contact the admin to make that tmp folder accessible from my account as typically this folder is for admins only. As your installation process could access my local folder, why not the installation process could use a tmp folder created within the local user account. Just a suggestion.

Thanks
________________________________
