### ISSUE TITLE
Can't install packages on localized Windows

### ISSUE THREAD

**Issue by olehenrikogaard11** [r-lib/devtools#2468]
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Ole Henrik �gaard/OneDrive - Norges Handelsh�yskole/Dokumenter": Systemet finner ikke angitt bane
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Ole Henrik �gaard/OneDrive - Norges Handelsh�yskole/Dokumenter": Systemet finner ikke angitt bane
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Ole Henrik �gaard/OneDrive - Norges Handelsh�yskole/Dokumenter": Systemet finner ikke angitt bane
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) : path[1]="C:/Users/Ole Henrik �gaard/OneDrive - Norges Handelsh�yskole/Dokumenter": Systemet finner ikke angitt bane

I get this warning message when starting Rstudio. 

Does anyone have a solution? It seems like the program cant read the letter "Ø".

**Comment by jennybc** [comment]
> I get this warning message when starting Rstudio

Can you help me reconcile this description with the issue title?

> Can't install packages on localized Windows

Are you seeing this when RStudio starts or when you try to install packages? What is the connection to the devtools package?

**Comment by jennybc** [comment]
This thread went stale.
