### ISSUE TITLE
devtools ubuntu 22.04 dependency error

### ISSUE THREAD

**Issue by cinnetcrash** [r-lib/devtools#2472]
I had some problems with ubuntu 22.04 and R when installing devtools.
The solution was installing some library from command line.

sudo apt -y install libfontconfig1-dev libharfbuzz-dev install libtiff-dev

**Comment by hadley** [comment]
You can use `pak:pkg_system_requirements()` to get the full set of requirements if you're installing from source, e.g.

``` r
writeLines(pak::pkg_system_requirements("devtools", "ubuntu", "20.04"))
#> apt-get install -y libfreetype6-dev
#> apt-get install -y libfribidi-dev
#> apt-get install -y libharfbuzz-dev
#> apt-get install -y git
#> apt-get install -y libxml2-dev
#> apt-get install -y make
#> apt-get install -y libfontconfig1-dev
#> apt-get install -y libicu-dev
#> apt-get install -y pandoc
#> apt-get install -y zlib1g-dev
#> apt-get install -y libssl-dev
#> apt-get install -y libjpeg-dev
#> apt-get install -y libpng-dev
#> apt-get install -y libtiff-dev
#> apt-get install -y libgit2-dev
#> apt-get install -y libcurl4-openssl-dev
```

<sup>Created on 2022-10-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by tomstamour** [comment]
Thanks, this worked for me as well!
