### ISSUE TITLE
Require shiny as a dependency, since it seems to be required

### ISSUE THREAD

**Issue by ernstki** [r-lib/devtools#2484]
Hi all, hope you're well.

**Is your feature request related to a problem? Please describe.**

Unfortunately, I haven't been able to reproduce this deterministically—suggestions welcome—but shiny _sometimes_ turns out to be an implicit dependency of devtools.

I had a coworker repeatedly and unsuccessfully trying to install devtools so she could `devtools::install_github` a package of ours, and what it boiled down to was the error message `there is no package called ‘shiny’` which is _very_ easily overlooked among the other console messages when installing devtools in a fresh R environment.

I'm aware of the nuance here (the complicated web of dependencies among DT, crosstalk, shiny, and devtools), and I've already read through #2112, #2133, and related issues.

**Describe the solution you'd like**

If the dependency chain can't be disentangled cleanly, and one of the dependencies of devtools is going to need to resolve shiny _anyway_, resulting in hard-to-spot failure messages during initial installation, please make shiny an explicit dependency of devtools.

**Describe alternatives you've considered**

I've considered updating our package's README to say something like "if you receive the error `there is no package called ‘shiny’`, then install shiny, but _our_ package doesn't require shiny, and this seems like something devtools should be handling on its own.

**Additional context**

Thanks for your consideration!

**Comment by jennybc** [comment]
At the time I write this, devtools appears to require shiny via its dependence on miniUI.

```
> pak::pkg_deps_explain("devtools", "shiny")
devtools -> miniUI -> shiny        
```

I don't have the bandwidth to analyze that particular dependency situation atm. But I can say two things to possibly move this along in the meantime:

* devtools is conceived primarily as a package development suite and that's the priority. So we will tend to choose "batteries included" for that persona over minimalism. If all your colleague wants to do is install a package from GitHub and they aren't engaged in any other package dev tasks, they could consider using `remotes::install_github()` or (what I would do) `pak::pak()`.
* devtools `Imports` miniUI and miniUI `Imports` shiny, so if package installation is going normally, the installation of shiny (or any such dependency) should "just happen". So it feels like there must be more to the story.

**Comment by ernstki** [comment]
@jennybc Thanks for pointing out some alternatives, which I was not aware of. I assume `devtools::install_github` was chosen by the original package author just due to [its featuring prominently](https://github.com/hadley/r-pkgs/search?q=devtools) in the available reference materials, for the reasons you point out.

I agree, it seems like shiny being installed as a dependency should "just happen," that was what felt weird about it. I _did_ attempt to replicate on multiple workstations, on all three OSes, but I wasn't as scientific about it as I could've been (_e.g._, I did not start with a factory-fresh `library` directory each time). But if I can manage to nail it down, I'll report back.
