### ISSUE TITLE
Any way to tell `install_local()` to ignore Remotes packages? Or to use the `repos` even for Remotes?

### ISSUE THREAD

**Issue by daattali** [r-lib/devtools#2493]
(I realize this may be a strange question)

I want to use `install_local()` to install a private package. This package does generally on some github-hosted packages, so it contains a `Remotes` section in the `DESCRIPTION`. However, in one case, I would like to install the package without access to github. I do have all the latest versions of these github packages available in a CRAN-like repository, but I can't get install_local() to look there. It keeps failing because it tries to reach github. I essentially want either to ignore the `Remotes` section, or to be able to specify that the Remotes should really be looking in the same repository as the other packages.

**Comment by jennybc** [comment]
I think @gaborcsardi will have the best answer to this. I'm not super optimistic, because it feels like a pretty fundamental property of `Remotes` that the specification of a given package *also* specifies where to install it from.

**Comment by gaborcsardi** [comment]
If you only use proper repositories, then you don't need devtools, you can install packages with the standard base R tools, they will ignore `Remotes`.

**Comment by daattali** [comment]
The exact same command doesn't seem to work with `install.packages()`.

The following devtools command works:

```r
devtools::install_local("relative/path/to/pkg.tar.gz", repos = "file:///absolute/path/to/lib", type = "source", upgrade = "always")
```

Yet the exact same command with `install.packages()` doesn't. 

I would understand if you don't want to explicitly support this feature, but was wondering if you can think of a workaround with your knowledge of how devtools works. If not, you can close.

**Comment by gaborcsardi** [comment]
I don't think this is possible with devtools.
