### ISSUE TITLE
Check checks for bashisms

### ISSUE THREAD

**Issue by pachadotdev** [r-lib/devtools#2496]
Hi!

I got a few warnings about possible bashism in my `configure` file when I run `devtools::check()`.

According to this answer on SO https://stackoverflow.com/a/75391226/3720258, the check could be wrong.

It would be good that an expert gives a look at it.

**Comment by hadley** [comment]
This is just forwarding the error from `R CMD check`, so unfortunately there's nothing devtools can do about it.
