### ISSUE TITLE
Command line argument "--install-tests"  is passed to `R CMD INSTALL`  by default

### ISSUE THREAD

**Issue by cgiachalis** [r-lib/devtools#2515]
Is it intentional in devtools::install()? The only way to ignore "--install-tests" is to set `keep_source = TRUE`.  Thanks.

```r
    opts <- c(
      if (keep_source) "--with-keep.source",
      "--install-tests"
    )
    if (quick) {
      opts <- c(opts, "--no-docs", "--no-multiarch", "--no-demo")
    }
    opts <- c(opts, args)
```
https://github.com/r-lib/devtools/blob/daca0cf04413a9d251b3e55f80091afa07a60ab2/R/install.R#LL71C1-L78C26

**Comment by jennybc** [comment]
It's been this way for a very long time and I can't find any related issues or discussion. So I'm going to say, yes, this is intentional and has stood the test of time.
