### ISSUE TITLE
Loading devtools should not cause shiny to be loaded

### ISSUE THREAD

**Issue by wch** [r-lib/devtools#2523]
Currently, loading devtools causes shiny to be loaded, but it shouldn't. This is because devtools imports miniUI, which imports shiny.

Searching the code for `miniUI`, I see only this (and the corresponding entry in NAMESPACE):

```
#' @importFrom miniUI miniPage
```

Searching for `miniPage`, I see no other uses of it. So I think miniUI can be removed as a dependency, and I think this will make it so shiny will no longer be needed at all by devtools.

**Comment by jennybc** [comment]
Closing in favor of #2524
