### ISSUE TITLE
submit_cran returns Error in if (new_url$query$submit == "1") { : argument is of length zero

### ISSUE THREAD

**Issue by DavZim** [r-lib/devtools#2527]
I am trying to submit my RITCH package to CRAN using devtools v 2.4.5 but I run into the following error.
Note that the RITCH package had been archived and this is submit to cran supposed to fix the issues.

```
> packageVersion("devtools")
[1] ‘2.4.5’


> devtools::submit_cran()
Is your email address david_j_zimmermann@hotmail.com?

1: No
2: No way
3: Of course

Auswahl: 3
✔  checking for file 'C:\Users\david\Nextcloud\Github\RITCH/DESCRIPTION'
─  preparing 'RITCH': (2.2s)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (834ms)
─  checking for empty or unneeded directories
─  building 'RITCH_0.1.20.tar.gz'
   
── Submitting ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Path C:\Users\david\AppData\Local\Temp\RtmpmyC4m5/RITCH_0.1.20.tar.gz
ℹ File size: 424.6 Kb

Ready to submit RITCH (0.1.20) to CRAN?

1: Uhhhh... Maybe?
2: Not yet
3: Yes

Auswahl: 3
ℹ Uploading package & comments
ℹ Confirming submission
Error in if (new_url$query$submit == "1") { : argument is of length zero
```

**Comment by jennybc** [comment]
CRAN is down right now (as in experiencing a breakage of some sort), so I assume this results from this very weird situation.

**Comment by aronatkins** [comment]
Manual upload sends the uploader back to the web form, which gains an additional message in the page body:

> Unpacking failed. Please make sure the tar.gz was created with R CMD build. If so, then contact cran-sysadmin@r-project.org.

There is no error HTTP response or other feedback.

Per https://cran.r-project.org:

> CRAN submissions are currently partly not possible due to some infrastructure issues. Please so NOT conact us if you see "Unpacking failed. Please make sure the tar.gz was created with R CMD build....". CRAN sysadmins will work on it once they are available.
> In addition, processing the CRAN incoming queue of packages (CRAN pretest) is currently delayed by 2 days.

**Comment by fritzbayer** [comment]
Same issue here

**Comment by ginberg** [comment]
Same issue here

**Comment by ahjota** [comment]
I was able to submit a new version of the `datarobot` package using devtools 2.4.5 on Sat Jul 15. Got the submission email, and the confirmation workflow on the CRAN page appeared to work as well.

Here's hoping the "incoming queue of packages" has been cleared...

**Comment by adriancorrendo** [comment]
I'm facing the same issue when trying to submit my package update:

> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

devtools_2.4.5

> devtools::submit_cran()
Is your email address acorrend@uoguelph.ca?

1: Not yet
2: No
3: Definitely

Selection: 3
── R CMD build ───────────────────────────────────────
✔  checking for file ‘/Users/acorrend/Documents/GitHub/metrica/DESCRIPTION’ ...
─  preparing ‘metrica’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (6.3s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘metrica_2.1.0.tar.gz’
   
── Submitting ────────────────────────────────────────
ℹ Path
  /var/folders/rp/cvjg6h156k93q027hhv33ydw0000gn/T//RtmpHgX95l/metrica_2.1.0.tar.gz
ℹ File size: 2 Mb

Ready to submit metrica (2.1.0) to CRAN?

1: Yup
2: Nope
3: I forget

Selection: 1
ℹ Uploading package & comments
ℹ Confirming submission
Error in if (new_url$query$submit == "1") { : argument is of length zero
