### ISSUE TITLE
More Date conversions/formats

### ISSUE THREAD

**Issue by K-eL** [r-lib/devtools#2538]
I'm working with dates, and would be very helpful if I could get all date formats from the source date/datetime.
I.e. where it currently shows the ISO date on Timestamp Converter, it would show ISO, Short Date, Long Date, UTC, etc.. like below:
"2015-03-25T10:00:00.000Z"
"2015-03-25T12:00:00.00+02:00"
"Thu Mar 25 2015 12:00:00 GMT+0200 (Central European Summer Time)"
"2015-03-25"
"25/03/2015"
"03/25/2015"
"Mar 25 2015"
"25 Mar 2015"

**Comment by jennybc** [comment]
Can you help me understand how this relates to the devtools package?

**Comment by K-eL** [comment]
lol, nevermind, this is the wrong repo.. sorry! :)
