### ISSUE TITLE
`release` causes me a problem if 'foghorn' package is installed

### ISSUE THREAD

**Issue by stla** [r-lib/devtools#2546]
- **Is your feature request related to a problem? Please describe.**
I'm always frustrated when I do `devtools::release` and it fails with the error message:

> Erreur dans ie_get_proxy_for_url(test_url) : 
>  ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT

This occurs with my R-4.3.2 version, but with R-4.3.1 it works, there's no error. I know this error is generated by the 'curl' package but I investigated and I think the issue is related to the 'foghorn' package: it is installed in my R-4.3.2 version but not in my R-4.3.1 version. This is the only difference I found.

- **Describe the solution you'd like**
An option to not use 'foghorn' maybe. 

- **Describe alternatives you've considered**
I use R-4.3.1 to release.

- **Additional context**
Maybe I rather should investigate what happens with 'foghorn' and fill an issue to the 'foghorn' repo?..
And I know this problem is specific to my laptop, which is the one from my former job.

**Comment by jennybc** [comment]
> Maybe I rather should investigate what happens with 'foghorn' and fill an issue to the 'foghorn' repo?..

Since this is the first/only report of trouble, I'm going to choose this option for now 😄
