### ISSUE TITLE
Documentation unclear on the `pkg` parameter

### ISSUE THREAD

**Issue by telenskyt** [r-lib/devtools#2584]
The `?document` (also `build_manual` and perhaps others) says about the `pkg` parameter

> pkg - The package to use, can be a file path to the package or a package object. See as.package() for more information.

But what is "file path to the package"? What does "file path" mean? Shouldn't it be "directory" rather than file? Isn't it a path to the package **directory**, rather than some file? "File" suggests a path to the file in which the package is packed... The documentation of `as.package()` is not much clearer.

Could you please make the documentation clear and specific? This is quite confusing.

**Comment by jennybc** [comment]
I believe "file path" to be a generally understood term that encompasses the path to a file or a folder.

> A path (or filepath, file path, pathname, or similar) is a [string](https://en.wikipedia.org/wiki/String_(computer_science)) of [characters](https://en.wikipedia.org/wiki/Character_(computing)) used to uniquely identify a location in a [directory structure](https://en.wikipedia.org/wiki/Directory_structure).

https://en.wikipedia.org/wiki/Path_(computing)

devtools has been on CRAN since 2011 and is widely used by R package developers, so this doesn't appear to be a source of widespread confusion.

**Comment by telenskyt** [comment]
File is a file, not a directory. I still don't know what should I supply to the pkg parameter!

Issue closed? So instead of spending like 2 minutes improving and clarifying the documentation, you just wipe it off the table. Nice.
