### ISSUE TITLE
namespace does not delete old information when @importFrom changes

### ISSUE THREAD

**Issue by dougmitarotonda** [r-lib/devtools#407]
Suppose I maintain two packages, call them `foo` and `bar`. `bar` exports a function `baz` and `foo` imports it in the help.R file using `@importFrom`, i.e., in foo/R/help.R there is a line `@importFrom bar baz`. When I `document` the namespace file is correctly created so it has `importFrom(bar,baz)`.

Now suppose, I change the name of `baz` to `bash` in the `bar` package. I update foo/R/help.R to `@importFrom bar bash`. When I `document` though, the namespace correctly adds `importFrom(bar,bash)` but it does not delete `importFrom(bar,baz)` so I get errors when running `install`. 

I am using the `clean = TRUE` argument thinking that would clean this as well, but it seems like that only goes to the man files. Am I missing something here? Or is this a bug?

Thanks!

**Comment by amtf1019** [comment]
delete the namespace file and do load_all() and then do devtools::docuement(). It should do the work.
