### ISSUE TITLE
Error in fetch(key) : lazy-load database '�' is corrupt

### ISSUE THREAD

**Issue by lucacerone** [r-lib/devtools#419]
The documentation is not reloaded properly when changes are made.

For example:

```
library(devtools)
dev_mode()
document("mypackage")
install("mypackage")
?some_function # shows the documentation correctly

# I keep working and make modifications to the documentation of "some_function".
# I want to update the documentation and the package so I issue:

detach("package:mypackage", unload = TRUE)
document("mypackage")
install("mypackage")
?some_function
```

Now the documentation shows 

```
"Error in fetch(key) : lazy-load database '�' is corrupt"
```

However if I restart my R session the documentation is visualized correctly.

**Comment by kendonB** [comment]
If anyone cares, I also have this problem.

**Comment by WilliamKinaan** [comment]
This problem is making me crazy, yet no solution

**Comment by hadley** [comment]
Either just use `load_all()` or use Build & Reload (in Rstudio, other IDEs may have something similar)

**Comment by danielecook** [comment]
I get this error message constantly - any idea why this is happening so I can try to avoid it?

**Comment by jimhester** [comment]
@danielecook Are you using the latest version of devtools? Can you provide your `devtools::session_info()`. Also in order to figure out the cause you need to provide the full error message including traceback.
