### ISSUE TITLE
"Missing" R-Tools in Windows

### ISSUE THREAD

**Issue by dmenne** [r-lib/devtools#426]
One one Windows computer, the R-tools where reported missing even if they where there for sure. 

```
install_path <- dirname(dirname(ls_path))
install_path2 <- dirname(dirname(dirname(gcc_path)))
if (install_path2 != install_path) 
  return(NULL)
```

install_path: D:/Rtools
install_path2: d:/Rtools

These paths (note the D: and d:) are equivalent under Windows, but the test fails. Maybe

http://www.boost.org/doc/libs/1_53_0/libs/filesystem/doc/reference.html#equivalent

**Comment by woodhaha** [comment]
Thanks @hadley @dmenne 
I have tried many times intalling the pkg "devtools" from GitHub on my windows10(x+64),and finally successed.
Fllowing the steps
1. Upgrade the java devlopment enviroment on my win10 ( http://www.oracle.com/technetwork/java/javase/downloads/index.html) install "Java SE 8u131"(Java Platform, Standard Edition)
and then configuring the developing enviroment on java control panel, setting the java runtime for related Apps 
2. Install "Rtools34" in （Path C:\Rtools）,then select components(R toolset,Cygwin DLLs, R3.3.x+64 bit toolchain,Extras to build 64bit R）

3. Install “cygwin setup-x86_64” comfiguring the linux devlopment enviroment 

4. Install "basic-miktex-2.9.6236-x64"

5. Restart your windows system, then in RStudio configuring Rtools developing enviroment by using the function: 
normalizePath("C:/Rtools/bin")
and lastly using 
devtools::build_github_devtools() ## to install the Github devtools pkg"devtools_1.12.0.9000.zip"#
