### ISSUE TITLE
Avoid Travis-CI time out from tests

### ISSUE THREAD

**Issue by philchalmers** [r-lib/devtools#481]
Hi Hadley,

I was wondering if it's possible to add an argument to the `check()` function which would allow a more verbose output for running tests with `testthat`. The reason is that Travis-CI will time out after a few minutes if there is no output being flushed to their console, so to avoid that I've usually just set up the `R CMD check` and `testthat` tests separately with a Makefile so that everything is printed on a continuous basis (e.g., https://travis-ci.org/philchalmers/mirt). In this way I have up to an hour of automated tests that can be run rather than just a few minutes. However, passing something like `check(package, verbose = TRUE)` would be a little more convenient and save from using a Makefile. Thanks for your time.

**Comment by jackwasey** [comment]
http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received
