### ISSUE TITLE
devtools::build_github_devtools() installation error on Windows

### ISSUE THREAD

**Issue by cjyang90** [r-lib/devtools#497]
Hi, I have the following issue with running devtools::build_github_devtools() on Windows. The commands in https://github.com/hadley/devtools works fine for Mac. Do I need to install anything extra to get the devtools updated?

![devtools](https://cloud.githubusercontent.com/assets/7917160/3306838/777b356e-f665-11e3-9ce7-ecbad6286a9d.png)

**Comment by uptownfunk** [comment]
I also can't build the dev version of devtools, and I get the same error. I have dplyr 0.4.3
