### ISSUE TITLE
use_vignettes() should .gitignore inst/doc

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#584]
(because it shouldn't be checked in)

**Comment by jtr13** [comment]
Why? Isn't it more efficient to have the built vignettes on Github rather than use build_vignettes = TRUE w/ install_github()? More discussion here: [https://github.com/STAT545-UBC/Discussion/issues/68](https://github.com/STAT545-UBC/Discussion/issues/68)

**Comment by hadley** [comment]
Because it causes problems with R CMD check - I'm reasonably certain that saving built vignettes in `inst/doc` is the wrong approach

**Comment by jtr13** [comment]
I'll trust your instincts.  So, to confirm, the right approach is to instruct users on Github to add build_vignettes = TRUE? Surprising this is rarely done, AFAIK.

**Comment by hadley** [comment]
We'll fix this in devtools eventually - see https://github.com/hadley/devtools/issues/1578

**Comment by jtr13** [comment]
Got it, thanks.
