### ISSUE TITLE
Rmarkdown vignettes not building the vignette INDEX file

### ISSUE THREAD

**Issue by jimhester** [r-lib/devtools#587]
I am trying to use an Rmarkdown vignette created using `use_vignettes()` and I encountered the ire of the esteemed Prof. Ripley upon package submission because my vignettes did not have a built index. `Package has a VignetteBuilder field but no prebuilt vignette index.` However I am not sure how to create this INDEX.

``` r
build_vignettes()
# NULL
```

I think this is not working because docs has no value

``` r
tools::pkgVignettes(dir = '.')
# $docs
# character(0)
# 
# $names
# character(0)
# 
# $engines
# character(0)
# 
# $patterns
# character(0)
# 
# $dir
# [1] "/Users/james.hester/Dropbox/projects/gmailr/vignettes"
# 
# $pkgdir
# [1] "/Users/james.hester/Dropbox/projects/gmailr"
# 
# $msg
# character(0)
# 
# attr(,"class")
# [1] "pkgVignettes"
```

Trying to call `tools::buildVignettes()` directly also fails

``` r
tools::buildVignettes(dir = '.', tangle=TRUE)
# Warning message:
# In tools::buildVignettes(dir = "..", tangle = TRUE) :
#   Files named as vignettes but with no recognized vignette engine:
#    ‘vignettes/sending_messages.Rmd’
# (Is a VignetteBuilder field missing?)
```

I can get the vignette to build by manually running `rmarkdown::render()` on the file, but that does not build the vignette INDEX file.

FYI the package I am having issues with is https://github.com/jimhester/gmailr
#### Session Info

```
Session info--------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 3.1.1 (2014-07-10)
 system   x86_64, darwin13.3.0
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       America/New_York

Packages------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source
 devtools   * 1.5.0.9001 2014-09-18 Github (hadley/devtools@69c99fa)
 evaluate     0.5.5      2014-04-29 CRAN (R 3.1.1)
 formatR      1.0        2014-08-25 CRAN (R 3.1.1)
 httr         0.5        2014-09-02 CRAN (R 3.1.1)
 knitr        1.6        2014-05-25 CRAN (R 3.1.1)
 RCurl        1.95.4.3   2014-07-29 CRAN (R 3.1.1)
 rstudioapi   0.1        2014-03-27 CRAN (R 3.1.1)
 setwidth   * 1.0.3      2013-01-16 CRAN (R 3.1.1)
 stringr      0.6.2      2012-12-06 CRAN (R 3.1.1)
```

**Comment by gennaro-tedesco** [comment]
Hi all,

I am having the exact same issue as reported above, being unable to build the vignette index despite having the correct `%\VignetteIndexEntry{<my vignette title>} `. 

Running 
```
> build_vignettes()
NULL
```
returns a NULL value, nevertheless the vignette itself builds fine and there is no other warning of sort. 

Is there any other particular trick that can conflict with creating the vignette index?

**Comment by gunhanb** [comment]
Hi gennaro,
I have exactly same problem, build_vignettes() returns NULL. And I searched a lot, but could not find any solution. 
When I use .Rnw file with knitr, it works. For this reason, I will use .Rnw (instead of .Rmd).

**Comment by muschellij2** [comment]
Getting `NULL` from `build_vignettes` can also happen when `VignetteBuilder` is not specified in the DESCRIPTION correctly. 

This is because `build_vignettes` uses `tools::pkgVignettes` which uses `tools::pkgVignettes` which calls
```
    buildPkgs <- loadVignetteBuilder(dir, mustwork = FALSE)
    engineList <- vignetteEngine(package = buildPkgs)
```
and if you have not specified `VignetteBuilder` then `loadVignetteBuilder` doesn't recognize `knitr` or `rmarkdown` and will simply return `utils` and that's why a `Rnw` works (since `utils::Sweave` is found).

You should be able to add
```
VignetteBuilder: knitr
```
to the DESCRIPTION and should be fine.
