### ISSUE TITLE
Package description must be title case

### ISSUE THREAD

**Issue by bpbond** [r-lib/devtools#621]
Package `Title` field in `DESCRIPTION` file must be title case, and while CRAN checks this, devtools does not. E.g. "This is Title Case" passes CRAN, but "This is not title case" does not (at least, doesn't pass Uwe Ligges).

Not sure if this is devtools's responsibility, or that of R CMD check, but wanted to note it.

**Comment by sanmai-NL** [comment]
It's a bit anglocentric to require this. But it is currently possible to convert titles to title case using `tools::toTitleCase`. Have you automated this check and/or and fix yet?

**Comment by bpbond** [comment]
See discussion above, in particular @barryrowlingson 's comment. No, it's not automated.
