### ISSUE TITLE
install_github fails "Error in function (type, msg, asError = TRUE)  : <not set>"

### ISSUE THREAD

**Issue by sthesing** [r-lib/devtools#650]
The devtools::install_github function fails on any package I try. I thought this might be the same issue as #638 , however the error message is different:

```
> install_github("hadley/devtools")
Downloading github repo hadley/devtools@master
Error in function (type, msg, asError = TRUE)  : <not set>
```

It doesn't seem to be the unzip-Issue:

```
> getOption("unzip")
[1] "/usr/bin/unzip"
```

I'm on 64bit Ubuntu.

**Comment by charles-plessy** [comment]
Hello, just for the record, we corrected the Debian package `r-cran-rcurl` in all Debian distribution `unstable`, `testing`, and more recently `stable` (Jessie 8.2). Sorry for the problem, and thanks for using Debian ! The correction eventually made it in Ubuntu `wily` as well.
