### ISSUE TITLE
Install github should add git hash

### ISSUE THREAD

**Issue by hadley** [r-lib/devtools#70]
Somewhere in description or version.

**Comment by piccolbo** [comment]
Hi,
actually there is an old branch, feature/install-github-sha1 or some such, with one commit by @jjallaire  that implements this. It seems to work. +1 for this feature. Carefully incrementing version number doesn't work, who increments version number for each commit? I know better fairy tales.

**Comment by jjallaire** [comment]
Yes, this was merged into master some time ago.

**Comment by piccolbo** [comment]
Sorry I should have tried instead

**Comment by josiekre** [comment]
I don't understand the post-close comment above. I see that install_github() adds fields to the Description file, but is it possible to have the version number look like '0.9.0-68-gc235a93' (See @wch comment above using `git describe --tags`)?

**Comment by gaborcsardi** [comment]
@josiekre that's not a valid R package version number, unfortunately. It can only contain numbers separated by dots or dashes.

**Comment by josiekre** [comment]
@gaborcsardi That is a bummer. Thanks for the clarification. I use this kind of versioning in Python, and man is it helpful!

**Comment by rmflight** [comment]
I think this was part of my motivation to get the git-SHA included in the extra package tags even when installing from *local*, and then get it to show up when using `devtools::session_info`, it's not **officially** part of the version number, but you can get the information and document it as part of an analysis. That was [this pull request](https://github.com/hadley/devtools/pull/1027). I haven't checked in a while, but I think that is still the behavior ....
